### ISSUE TITLE
Disable `requestAnimationFrame` in khafile.js

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#1002]
Debugging draw calls by stepping through JavaScript line by line in the debugger is much easier when `requestAnimationFrame` has been disabled in favor of a `setInterval` loop, because then draws are displayed instantly as you step through the code.

With `requestAnimationFrame` enabled, stepping through each line won't visually update the canvas, because that's handled asynchronously, and the program is paused for debugging.

Would it make sense to add an option to disable `requestAnimationFrame` in the khafile.js file?

**Comment by sh-dave** [comment]
Hm, sounds to me like something to better handle manually while debugging. Just set `requestAnimationFrame = null` [here](https://github.com/Kode/Kha/blob/ebafec87c6422e949489931d2493edf84947f814/Backends/HTML5/kha/SystemImpl.hx#L423) should do the trick easy enough? I'm not convinced that requires an actual implementation.

**Comment by Joncom** [comment]
Fair point
