### ISSUE TITLE
Khafile misses unicode define

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#1004]
khafile should have `project.addDefine('hxcpp_smart_strings');` by default for correct haxe std work in hxcpp.
There also is problem with charAt/charCodeAt and maybe other string methods with non-english strings, `trace("Н".charAt(0), "Н".charCodeAt(0));` should give `Н, 1053` for cpp targets, same as on js.

**Comment by RblSb** [comment]
Hm, after full recompilation with `hxcpp_smart_strings` define in khafile, string methods works now.
@OlegAntipov can you test it? (related to http://forum.kode.tech/topic/266)

**Comment by OlegAntipov** [comment]
> Hm, after full recompilation with `hxcpp_smart_strings` define in khafile, string methods works now.
> @OlegAntipov can you test it? (related to http://forum.kode.tech/topic/266)

Yes, it seems that adding this define solves the problem! Cool, thanks! I have tried it on android-native target only, but I think everything should also work under iOS.
