### ISSUE TITLE
Graphics2 throws "End before you begin" error after updating Kha

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#1011]
After updating to the latest version of Kha today, I started getting this error when I run my game compiled to the HTML5 target:

> End before you begin

![Screen Shot 2019-03-10 at 6 10 53 PM](https://user-images.githubusercontent.com/1667179/54084167-e1289c80-435f-11e9-8278-a788c53f5c68.png)

I think I basically understand the error. It's saying that you should always call `g2.begin` first, followed by `g2.end`, and don't forget to do either one.

However, I'm not sure why I'm getting this error, because I believe the only place in my game where either of these gets called, is in my `render` function, which quite simply calls them in the correct order already.

```haxe
public static function render(framebuffers: Array<Framebuffer>): Void {
  var g = backbuffer.g2;

  // clear and draw to our backbuffer
  g.begin(false);
  g.color = Color.Black;
  g.fillRect(0, 0, backbuffer.width, backbuffer.height);
  g.color = Color.White;
  if(impact.Global.game != null) {
    impact.Global.game.draw();
  } else if(impact.Global.loader != null) {
    impact.Global.loader.draw();
  }
  g.end();

  // draw our backbuffer onto the active framebuffer
  var framebuffer = framebuffers[0];
  framebuffer.g2.begin();
  Scaler.scale(backbuffer, framebuffer, System.screenRotation);
  framebuffer.g2.end();
}
```

Viewing a couple functions up the call-stack, we see `g2.begin` getting called in my `render` function.

![Screen Shot 2019-03-10 at 6 15 47 PM](https://user-images.githubusercontent.com/1667179/54084230-b723aa00-4360-11e9-9869-8af1f30e130f.png)

Looks like typical usage `g2` usage to me.

Am I doing something wrong?

**Comment by RobDangerous** [comment]
Well, that's so much easier for you to figure out than it is for me.

**Comment by Joncom** [comment]
Hmm, something different starting happening after refreshing. Going to re-document this after playing around a bit...
