### ISSUE TITLE
Android native build stopped working

### ISSUE THREAD

**Issue by Dimous** [Kode/Kha#1018]
| Name | Version |
|---|---|
| Windows | 10 |
| NDK | r15c |
| Kha | 1a71a4e5061338d849413b185f44fef32d661172 |
| Android + Device | 5.1, Samsung SM-J320F |
| | 4.4, Samsung GT-N7100 |

Sample code:

<details>

khafile.js
```js
const project = new Project("demo");
project.addDefine("actuate_manual_time");
project.addDefine("actuate_manual_update");
project.addParameter("-dce full");
project.addAssets("Assets/**");
project.addSources("Sources");
project.addLibrary("actuate");
resolve(project);
```
Main.hx
```haxe
package;

import kha.Window;
import kha.System;

class Main {
	public static function main() {
		System.start(new SystemOptions(), function (window: Window): Void new Project());
	}
}
```
Project.hx
```haxe
package;

import kha.Color;
import kha.System;
import kha.Scheduler;
import kha.Framebuffer;
import kha.graphics2.Graphics;

import motion.Actuate;
import motion.easing.Bounce;
import motion.actuators.SimpleActuator;

final class Square {
	public var x: Float = 0;
	public var y: Float = 0;
	public var width: Float = 25;
	public var height: Float = 25;
	
	public function new() {}
}

final class Project {
	private final square: Square;

	public function new() {
		this.square = new Square();
		
		System.notifyOnFrames(this.render);
		SimpleActuator.getTime = Scheduler.time;		
		Scheduler.addTimeTask(function (): Void SimpleActuator.stage_onEnterFrame(#if kha_html5 0.0 #end), 0, 1 / 60);
		Actuate.tween(this.square, 5, {x: System.windowWidth() - this.square.width, y: System.windowHeight() - this.square.height}).ease(Bounce.easeOut).repeat();
	}

	private function render(framebuffers: Array<Framebuffer>): Void {
		final graphics: Graphics = framebuffers[0].g2;

		graphics.begin();
		graphics.color = Color.White;
		graphics.fillRect(this.square.x, this.square.y, this.square.width, this.square.height);
		graphics.end();
	}
}
```

</details>

When I try to compile with VSCode `Android (native, full build)` task, it fails: https://gist.github.com/Dimous/81323b18fe6865518d787619a67301f9

But when I run `Android (full build)` then import in Android Studio, it goes how it should. It opens up an app, but it is blank and nothing special in the logcat.

Logcat:
https://gist.github.com/Dimous/e50c1b209d2239adc94a69e7b9e743c5

Windows and HTML5 targets are working. A bunch of commits ago it was working on my  Android devices.

---
I also tried to compile Armory sample with `android-native-hl preset` and mobile render path. It showed a black screen and crashed:
https://gist.github.com/Dimous/1075f53cb1fcc2fd32a4195ade7b2bf5

Windows and HTML5 targets are working.

| Name | Version |
|---|---|
| Armory | 2.80, git a83a1bc873d295be3653f9569a2a4e959f48a058 |
| Kha | e7c27fb76f8f672699a13ce9637259be2004e06e |
| Iron | git 5943af4cd16db6a80d49ef56adc0980dcedca54b |

**Comment by RobDangerous** [comment]
I can not reproduce that error, is your Android stuff up to date?

PS: The `Android (full build)` situation was already reported and this is not the right place for Armory sample situations.

**Comment by Dimous** [comment]
I believe it is. I'll recheck. Ok, thanks!

**Comment by RobDangerous** [comment]
But please report back, even if an Android SDK update resolves it.
