### ISSUE TITLE
[BUG?] macOS build both regular & openGL errors with Kore/AtomicImpl.h not found

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#1025]
with the current git kha, but also has been a problem for quite a few commits.

with a simple setup for the project & exporting to both the regular macOS & macOS openGL versions, an error of `Kore/AtomicImpl.h file not found`

im assuming that the regular macOS build is for Metal. makes sense if so

<img width="1156" alt="Screen Shot 2019-04-03 at 19 21 12" src="https://user-images.githubusercontent.com/11299322/55503223-2af66100-5646-11e9-9ed3-d782739be0b1.png">
<img width="272" alt="Screen Shot 2019-04-03 at 19 23 38" src="https://user-images.githubusercontent.com/11299322/55503233-2df15180-5646-11e9-874c-d8baa998388a.png">

**Comment by RobDangerous** [comment]
It's not true, you updated khacpp beyond what Kha points to, actual correctly checked out git Kha still works fine (by the way, I fixed the git instructions in the wiki a while back). But I'll make it works with the latest khacpp soonish.

**Comment by lewislepton** [comment]
wow. never realised I had even touched khacpp or updated it
