### ISSUE TITLE
[BUG?] macOS Mojave build has weird glitches with native applications

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#1026]
using the current kha git repo with the latest [mojave 10.14] of macOS brings in some really weird glitches & window problems when running a debug & release build in Xcode [10.2].

everything works fine. but has this strange glitch. at some other points, when only jumping or hitting into certain things that can either delete or kill, brings in this glitch.

on the previous macOS Yosemite it seemed fine & no window glitches.

this build is using the standard macOS build in vscode, not the OpenGL build. I've not tried yet with the OpenGL, but will & say if there's glitches or not with a native application

https://www.dropbox.com/s/0zlvt27yl4xikef/windowErrors.mp4?dl=0

**Comment by lewislepton** [comment]
ok - on a quick check. it seems that OpenGL was completely fine. no glitches.

as said, the previous Yosemite build were using the standard macOS build & not the openGL build & were fine. but on Mojave, brings a glitch. But OpenGL is fine

**Comment by RobDangerous** [comment]
Can you reproduce those glitchy glitches with the standard samples?

**Comment by lewislepton** [comment]
ill give a check

**Comment by RobDangerous** [comment]
Maybe fixed, nobody knows.
