### ISSUE TITLE
vector class inconsistency

### ISSUE THREAD

**Issue by sh-dave** [Kode/Kha#1027]
I just noticed that `normalize` is the only mutating operation in the vector classes. To make the api more consistent, my suggestion would be something along the lines of:

```haxe
class VectorX {
    ...
    @:deprecated("normalize() will be deprecated soon, use the immutable normalized() instead")
    @:extern public inline function normalize(): Void {
        ...
    }

    @:extern public inline function normalized() : VectorX {
        var v = new VectorX(x, y, ...);
        v.length = 1;
        return v;
    }

// inline now (should be done regardless of the api change as that is just plain faster)
    private inline function get_length(): Float {
        return Math.sqrt(x * x + y * y);
    }

// inline now (should be done regardless of the api change IMO)
    private inline function set_length(length: Float): Float {
        var currentLength = get_length();
        if (currentLength == 0) return 0;
            var mul = length / currentLength;
            x *= mul;
            y *= mul;
            return length;
	}
    }
}
```

**Comment by RobDangerous** [comment]
Yes, let's normalize normalize. I vote against the length inlining though, all targets but the flash target can take care of that automatically when no inline constructors are involved and I think nobody uses that target anymore.

**Comment by sh-dave** [comment]
Hm, not so sure about the inlining.

This will be generated without inlining the getter/setter, you think this will be optimized at runtime in JS?
```javascript
var kha_math_Vector2 = function(x,y) {
	if(y == null) {
		y = 0;
	}
	if(x == null) {
		x = 0;
	}
	this.x = x;
	this.y = y;
};
$hxClasses["kha.math.Vector2"] = kha_math_Vector2;
kha_math_Vector2.__name__ = "kha.math.Vector2";
kha_math_Vector2.prototype = {
	get_length: function() {
		return Math.sqrt(this.x * this.x + this.y * this.y);
	}
	,set_length: function(length) {
		var currentLength = this.get_length();
		if(currentLength == 0) {
			return 0;
		}
		var mul = length / currentLength;
		this.x *= mul;
		this.y *= mul;
		return length;
	}
	,__class__: kha_math_Vector2
};

// at the call site

v = ...;

var _this_x = Math.random();
var _this_y = Math.random();
var v1 = new kha_math_Vector2(_this_x,_this_y);
v1.set_length(1);
var vtmp = v1;
v.x = vtmp.x;
v.y = vtmp.y;
```

And this is with inlining the `length` getter/setter.

```javascript
// no kha_math_Vector2 and prototype stuff anymore

// at the call site

v = ...;

var _this_x = Math.random();
var _this_y = Math.random();
var vtmp_x = _this_x;
var vtmp_y = _this_y;
var currentLength = Math.sqrt(vtmp_x * vtmp_x + vtmp_y * vtmp_y);
if(currentLength != 0) {
	var mul = 1 / currentLength;
	vtmp_x *= mul;
	vtmp_y *= mul;
}
v.x = vtmp_x;
v.y = vtmp_y;

```

**Comment by sh-dave** [comment]
Or wait, maybe i have a better idea?

```haxe
class VectorX {
        // always inline the getter (would result in slighty faster debug builds as well)
	private inline function get_length(): Float {
		return Math.sqrt(x * x + y * y);
	}

        // keep the setter as is (when you manually call vec.length = something)
	private function set_length(length: Float): Float {
		var currentLength = get_length();
		if (currentLength == 0) return 0;
		var mul = length / currentLength;
		x *= mul;
		y *= mul;
		return length;
	}

        // use the new haxe4 call site inline feature
	@:extern public inline function normalized(): VectorX {
		var v = new Vector2(x, y, ...);
		#if haxe4 inline #end v.set_length(1);
		return v;
	}
}
```

This get's rid of the `kha_math_Vector2` from the comment above.

**Comment by RobDangerous** [comment]
Yes, JavaScript can do optimizations like that automatically, see for example https://v8.dev/blog/disabling-escape-analysis. I'm not sure there are any situations where "inline" (or really any optimization Haxe can do) can benefit current versions of V8 or SpiderMonkey but some tests about that would be very interesting. Inline constructors however are super important for C++ because Haxe makes zero attempts to automatically remove allocations and C++ itself does not know what a garbage collected allocation is. If just calling a non-inlined function opts Haxe out of using an inline constructors we should therefore inline the hell out of everything that has an inline constructor. But why does inlining get_length help when you call set_length, do you have any idea about that?

**Comment by sh-dave** [comment]
Well `set_length` calls `get_length` internally, and when `get_length` is not inlined it's trying to call the `get_length` function and therefore requires the whole class declaration i guess.

Try it online [here](http://try-haxe.mrcdk.com/#7Dc53). (You might have to set `options tab/haxe version` to one of the latest development releases, so the call site inline in `set_length` works).

**Comment by sh-dave** [comment]
PR was merged so this can be closed
