### ISSUE TITLE
Inconsistent opacity behavior

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#1028]
I'm seeing inconsistent behaving between the WebGL and Canvas implementations.

Is `opacity` supposed to be a value between 0 and 1?

http://api.kha.tech/kha/graphics2/Graphics.html#set_opacity

Setting opacity to any number >= 1 will draw images normally on Canvas.

However, the image will become bright, white, and washed out as the number exceeds 1 on WebGL.

Should this value be clamped to produce consistent behavior?

**Comment by RobDangerous** [comment]
Yes, it has to be between 0 and 1, everything else is undefined behavior. That's ok I think and certainly very common, I don't want to force-clamp it.

**Comment by RblSb** [comment]
Supposed to be. >= 1 is unspecified, also more bright seems like cool feature.

**Comment by RobDangerous** [comment]
The whole point of g2 is canvas compatibility - and canvas doesn't do that.
