### ISSUE TITLE
There is no `g2.popTranslation` function

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#1029]
There is a `g2.pushTransformation` and `g2.popTransformation` function. And there is a `g2.pushTranslation` function, however, there is no `g2.popTranslation` function. Is `g2.popTransformation` used to undo changes made with `pushTranslation`?

**Comment by sh-dave** [comment]
Yes exactly, it just pops the last pushed transformation (custom transformation, translation, rotation).

**Comment by Joncom** [comment]
Thanks @sh-dave
