### ISSUE TITLE
Is it possible to fill a bezier curve path?

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#1030]
In the [GraphicsExtension](http://api.kha.tech/kha/graphics2/GraphicsExtension.html) class, I see a polygon can be filled using [fillPolygon](http://api.kha.tech/kha/graphics2/GraphicsExtension.html#fillPolygon). This can be used for drawing arbitrarily shaped objects. This functionality basically replicates Canvas's "beginPath", "moveTo", "lineTo", "closePath", "fill" logic.

However, I want some parts of the shape to be bezier curves. Normally, this could be done with Canvas's "toBezierCurve" function. But I'm not noticing anything comparable in the `GraphicsExtension` class. I do see [drawCubicBezier](http://api.kha.tech/kha/graphics2/GraphicsExtension.html#drawCubicBezier) and [drawCubicBezierPath](http://api.kha.tech/kha/graphics2/GraphicsExtension.html#drawCubicBezierPath), but these appear to be for drawing a line/stroke, not filling in a shape.

Is it possible to fill a path containing a mixture of lines and bezier curves with the current Kha API?

**Comment by Joncom** [comment]
Just thinking out loud here.. This guy suggests that one way to fill bezier curves would be to break them up into small line segments, and then fill with an ordinary `fillPolygon` method. https://computergraphics.stackexchange.com/a/1899/10496

**Comment by sh-dave** [comment]
I guess you could take the `drawBezier` code and instead of drawing lines, create an array of of vertices you can use in `fillPolygon`.

**Comment by RobDangerous** [comment]
Out of scope for Kha.
