### ISSUE TITLE
Draw on Image problem on windows and android-native

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#104]
If I create a image on game.init(), and draw on it, it won't render on game.render() until I draw on it again at least one more time after the init() function. This not happen on html5, but is happening on windows and android native.

The color in the image.g2.begin works, but everything that is drawn isn't showing.

example:

To make this code work I'm using the variable firstTime to draw again one more time in the update function. If I remove the "if (firstTime)" block in update (or entire update function), the image won't be rendered in the render function.

```
class Empty extends Game 
{
    var img:Image;
    var firstTime = true;

    public function new() 
    {
        super("Empty", false);
    }

    override public function init():Void 
    {
        super.init();

        img = Image.createRenderTarget(100, 100);
        renderImg();
    }

    function renderImg()
    {
        img.g2.begin(true, Color.Blue);
        img.g2.color = Color.Red;
        img.g2.drawLine(0, 0, img.width, img.height, 10);
        img.g2.drawLine(img.width, 0, 0, img.height, 10);
        img.g2.end();
    }

    override public function update():Void 
    {
        if (firstTime)
        {
            renderImg();
            firstTime = false;
        }
    }

    override public function render(frame:Framebuffer):Void 
    {
        frame.g2.begin(true, Color.White);
        frame.g2.drawImage(img, 270, 190);
        frame.g2.end();
    }
}
```

**Comment by RafaelOliveira** [comment]
This is happening too if I draw a Image inside another Image.

**Comment by RobDangerous** [comment]
Seems to be fixed.
