### ISSUE TITLE
Cannot build dx9 on windows

### ISSUE THREAD

**Issue by CptPotato** [Kode/Kha#1042]
When trying to build the Visual Studio solution for the Windows DirectX9 target the build fails with several errors in `Kore\Backends\Graphics4\Direct3D9\Sources\Kore\Direct3D9.cpp` as well as `...\*Impl.cpp`. It's mostly due to missing namespaces, methods and variables.

Building for the OpenGL or DirectX12 target works. I'm using the latest Kha from git, Haxe 4.0.0-rc.2 and Visual Studio 2019 Community.

**Comment by RobDangerous** [comment]
Not sure whether I want to continue to work on D3D9 myself but I'll gladly take pull requests.
Usual disclaimer: Your Haxe installation is ignored by Kha.

**Comment by CptPotato** [comment]
Thanks for the clarification. I might look into it when I have time but I also think dx9 is somewhat outdated enough to drop it in favor of newer APIs. I just noticed that it did not compile when trying out different build targets.

Also, great work on this project. I'm impressed by how much Kha offers and how (for the most part) effortless compiling for a specific platform is.

**Comment by RobDangerous** [comment]
Thanks, good to hear.

**Comment by RobDangerous** [comment]
D3D9 compiles again.
