### ISSUE TITLE
Keyboard events not firing at all in HTML5

### ISSUE THREAD

**Issue by tienery** [Kode/Kha#1050]
Hello.

I have been trying to figure out an issue with Keyboard events on the HTML5 target using the latest version of Kha and can't figure out why none of the key events are firing. I double checked in debug if listeners were being added, and they were:

![image](https://user-images.githubusercontent.com/2475112/58076168-771f4580-7ba1-11e9-812a-17015b74416a.png)

I then tried a simple trace call in my internal `KEY_EVENT_UP` event:

![image](https://user-images.githubusercontent.com/2475112/58076281-bbaae100-7ba1-11e9-9e0a-61adad42252d.png)

But it wasn't firing no matter what I pressed.

I took a look behind-the-scenes to see if I could see anything obvious that might have caused the issue, any changes that have occurred before I updated to the latest version to get Zui working, but couldn't.

I just don't understand what's going on. Is anything revolving the Keyboard now broken until further notice on the HTML5 target? I do have an old version of Kode Studio, but I wouldn't have thought updating that would make a difference.

**Comment by sh-dave** [comment]
> Is anything revolving the Keyboard now broken until further notice on the HTML5 target?

No, the problem usually sits behind the keyboard.

Build and tested with latest Kha (1ccb97687662c67654e74b391f9e54dfc31240d8).

![Screenshot_2019-05-21_10-17-02](https://user-images.githubusercontent.com/13007175/58079668-cf5e4380-7bb1-11e9-8ad4-51fa9f4bf1bf.png)

**Comment by tienery** [comment]
So, I changed to `System.start` in my underlying code and hasn't made a difference.

Also, these changes will still work on Haxe 3.4.7, correct? I'm reluctant to update to the latest Haxe until all my tools are up-to-date.

I've also changed the code on initialisation:

```haxe
System.start({ title: "P&M Business", width: 1600, height: 900 }, function (_) {
	Assets.loadEverything(function()
	{
		kha.input.Keyboard.get().notify(
			function(key) { trace(key); },
			function(key) { trace(key); },
			function(char) { trace(char); }
		);

		//Scene.init();

		//System.notifyOnFrames(render);
	});
});
```

Still no output or results... I'll switch to the RC version of Haxe and see if that improves.

**Comment by sh-dave** [comment]
> So, I changed to System.start in my underlying code and hasn't made a difference.

 Yes, that won't make a difference.

> Also, these changes will still work on Haxe 3.4.7, correct? I'm reluctant to update to the latest Haxe until all my tools are up-to-date.

If you are using latest Kha, it already uses haxe `4.0.0-rc.1`. Whatever you install on your system doesn't matter. If you don't override it, Kha will use it's bundled haxe version in `Kha/Tools/haxe`.

Are you by any chance using a custom `index.html` file (or have an old generated one in your `build/html5` folder)? If you do, make sure you have a `tabIndex="-1"` attribute on it, see [here](https://github.com/Kode/khamake/blob/d150dc038231a70a229620154d9f6ce482389a7f/Data/html5/index.html#L8). Otherwise it might be possible (depending on the browser) that you won't get proper keyboard events.

**Comment by tienery** [comment]
Ah, yes. The `tabIndex` change worked. I did try deleting the entire build folder and rebuilt from scratch but didn't work! The template file being used didn't have `tabIndex` in there... I may not have updated all the submodules.

But it is now working, so thank you. Hopefully now I can try Zui and find out if that works...

**Comment by sh-dave** [comment]
Ok great.

> The template file being used didn't have tabIndex in there... I may not have updated all the submodules.

Then your Kha is on a very very old commit indeed, as that was changed months ago. See the wiki on how to properly update your git clone.

**Comment by RblSb** [comment]
`tabIndex` thing is my old bad, when i move autofocus to html file instead of calling it in kha.js and html5-debug target was broken.
