### ISSUE TITLE
JSON parse won't work in osx build

### ISSUE THREAD

**Issue by LucasMW** [Kode/Kha#1053]
It won't correctly trace in Mac OS build, despite tracing the variables correctly in html5 debug build (default debug in Kode Studio).  It pauses or lead to weird untraceable crashes.

This is a simple example:
http://kodegarden.org/#7e4d5a91c4fb6494a33568af687dfe9594c26765

I seek help.

**Comment by sh-dave** [comment]
The json look like it's unrelated, does it work in build without Kha?
The more likely problem is your empty render function. Try to add at least a g2.begin() / g2.end() call in it.

**Comment by LucasMW** [comment]
I've had a bigger project with a render function which would crash when the json was being processed. (Namely the `Json.parse()` function; every trace before would print and every trace after wouldn't) It had render and update functions being used. 
I believe there really is a problem.
This was just a small project to demonstrate that.

**Comment by RobDangerous** [comment]
Please open and start it in Xcode, that'll get us some more info to work with.

**Comment by LucasMW** [comment]
The expected log would be something like
Main.hx:36: BTC, 7593.73741140298
(This is the debug HTML5 result)

The small project which I have linked to you would not log my trace lines and would 'freeze'.

> 2019-05-23 09:11:05.750181-0300 SimpleApi[53593:10632588] [DYMTLInitPlatform] platform initialization successful
> 2019-05-23 09:11:05.800861-0300 SimpleApi[53593:10632586] [default] Unable to load Info.plist exceptions (eGPUOverrides)
> Starting Kore
> 2019-05-23 09:11:05.820177-0300 SimpleApi[53593:10632561] Metal GPU Frame Capture Enabled
> 2019-05-23 09:11:05.820533-0300 SimpleApi[53593:10632561] Metal API Validation Enabled
> Starting application
> deviceBufferSize = 4096
> 
> mSampleRate = 48000
> 
> mFormatFlags = 00000009
> 
> mBytesPerPacket = 8
> 
> mFramesPerPacket = 1
> 
> mChannelsPerFrame = 2
> 
> mBytesPerFrame = 8
> 
> mBitsPerChannel = 32
(Freezes)

Then, when the window close button was pressed it would give the following error:

> Application stopped
> libc++abi.dylib: terminating with uncaught exception of type Dynamic
> (lldb) 

<img width="1119" alt="Screen Shot 2019-05-23 at 9 06 18 AM" src="https://user-images.githubusercontent.com/8429832/58251881-36f3ca80-7d3b-11e9-9b7c-54486cdf16c8.png">

**Comment by LucasMW** [comment]
The larger project would crash without freezing or requiring any user action. It would show a very similar error message. (Crashes in the `throw inDynamic;` line)

**Comment by RobDangerous** [comment]
The "throw inDynamic" is not the crash, that's the error handler. Go up the stack to your main function please.

**Comment by RobDangerous** [comment]
Uhm, also move your code inside the start callback please, you are running code before Kha is initialized.

**Comment by LucasMW** [comment]
I don't know exactly  what do you mean by "your main function" but here are these prints from the same earlier crash:

<img width="1101" alt="Screen Shot 2019-05-23 at 9 25 45 AM" src="https://user-images.githubusercontent.com/8429832/58253142-2133d480-7d3e-11e9-8500-bab24bd75c60.png">
<img width="1120" alt="Screen Shot 2019-05-23 at 9 35 52 AM" src="https://user-images.githubusercontent.com/8429832/58253175-36a8fe80-7d3e-11e9-8679-58a8d7e535f7.png">
(It's virtually the same error the bigger project gets)

I will move the code inside the start callback and report back any changes

**Comment by LucasMW** [comment]
Moved to here:
<img width="668" alt="Screen Shot 2019-05-23 at 9 40 25 AM" src="https://user-images.githubusercontent.com/8429832/58253439-d8305000-7d3e-11e9-86bb-4254bb9fbc8d.png">
Now it does not require user action to crash;
It crashes on its own
<img width="1110" alt="Screen Shot 2019-05-23 at 9 43 38 AM" src="https://user-images.githubusercontent.com/8429832/58253635-44ab4f00-7d3f-11e9-828f-d24f5e09095c.png">
<img width="1257" alt="Screen Shot 2019-05-23 at 9 44 39 AM" src="https://user-images.githubusercontent.com/8429832/58253713-69072b80-7d3f-11e9-9b8e-92720a62170d.png">

**Comment by sh-dave** [comment]
Can you just do a `trace(obj);` and see if that explodes as well? Maybe you try to access invalid fields in `obj`.

**Comment by RobDangerous** [comment]
You found the main function ;) Did you ever test whether anything at all works? Like, does an empty program run?

**Comment by LucasMW** [comment]
@RobDangerous 
Programs from lewis lepton course repository would run without problems.
@sh-dave  All my tests pointed out a problem in `Json.parse()` function in the osx build;
Note that this works in the HTML5 build. So the field is not invalid.
When traced, obj would be printed like I expected a json object would. (I can perform again, if you insist)
It appears that `Json.parse()` is parsing incorrectly on osx build.

**Comment by LucasMW** [comment]
@sh-dave 
<img width="601" alt="Screen Shot 2019-05-23 at 9 57 11 AM" src="https://user-images.githubusercontent.com/8429832/58254458-29d9da00-7d41-11e9-8ea0-c04d7ca241ce.png">

Full log in file
[log.txt](https://github.com/Kode/Kha/files/3212219/log.txt)

<img width="1415" alt="Screen Shot 2019-05-23 at 9 59 33 AM" src="https://user-images.githubusercontent.com/8429832/58254619-83420900-7d41-11e9-8140-fdee2f0887c7.png">

**Comment by sh-dave** [comment]
I think it explodes b/c `obj.data` is an object, not an array (look at the traces), but you're accessing it like an array with `data[1]`. Use Reflect.field() in that case.

```haxe
trace(Reflect.get(obj.data, '1').symbol);
```

**Comment by LucasMW** [comment]
Thanks very much! It worked. However, I still doesn't know why it was working in HTML5 back then. I will read more about `Reflect`

**Comment by RobDangerous** [comment]
That's because JavaScript is very resistant to wrong types.

**Comment by tienery** [comment]
Well, JavaScript is not a typed language which makes it difficult to debug sometimes. But that's why we use Haxe ;)

**Comment by sh-dave** [comment]
Just FYI, when dealing with json, i ususally use [tink_json](https://github.com/haxetink/tink_json). This will pull in quite some dependencies, but being able to just typedef something and have the parser validate it, makes for a much better development experience IMO.
