### ISSUE TITLE
iOS -g opengl System.stop doesn't work

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#1054]

**Comment by RobDangerous** [comment]
Does it work with Metal? That would surprise me.

**Comment by RblSb** [comment]
Will test later. Probably not, the only difference is [shutdownMetalCompute](https://github.com/Kode/Kinc/blob/7f23fce9e8a32ba7e5d3be0fad15a537d2fd2bcc/Backends/Graphics5/Metal/Sources/Kore/ComputeImpl.mm#L64) call.

**Comment by RobDangerous** [comment]
OK, follow-up question - does that even make sense on iOS? Normally iOS programs are not stopped manually but follow that iOS activation/deactivation flow.

**Comment by RblSb** [comment]
Oh, probably not https://stackoverflow.com/a/2980740
Will just hide exit button in ios version then.
