### ISSUE TITLE
MacOS Mojave build error: Khamake not building project

### ISSUE THREAD

**Issue by darmie** [Kode/Kha#1059]
![Screenshot 2019-06-09 at 02 13 42](https://user-images.githubusercontent.com/848002/59153856-4d4c9680-8a5c-11e9-90b9-0a35439532a2.png)

Khamake isn't building project on OSX 

My Khafile.js is like this
```js
let project = new Project('Project');
project.addSources('Sources');
project.addSources('../Meerkat/src');
project.addLibrary('linc_yoga');
resolve(project);
```

**Comment by RobDangerous** [comment]
That usually means that an earlier build step failed. What's the output of your khamake call?

**Comment by darmie** [comment]
```
...
The following build commands failed:
        CompileC /Users/damilare/Documents/projects/Sample/build/osx-build/build/myproject.build/Debug/myproject.build/Objects-normal/x86_64/main-697e830fc8722d1fa51f5e3bf774296d8b68158e7cebfbc1b4e1a93caee989e2.o /Users/damilare/Documents/projects/Sample/kha/Backends/Kore/main.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Compilation failed.
```

**Comment by RobDangerous** [comment]
It normally does. Please paste in the complete khamake output.

**Comment by darmie** [comment]
The output is too long, so I pasted it in a gist.
https://gist.github.com/darmie/ccb7ebf7b8fab1697af61d9ef810df2e

**Comment by RobDangerous** [comment]
You're getting a warning about that yoga lib. Try without it.

**Comment by darmie** [comment]
Okay. It worked without the Yoga library. 
So just figured that Kha has its own convention for third party libraries.

**Comment by RobDangerous** [comment]
It also supports haxelib libraries in the normal way but apparently it has some problem with that yoga lib. Will have to have a closer look at that.

**Comment by darmie** [comment]
I actually wrote the Yoga library bindings. It's available at https://github.com/darmie/linc_yoga

**Comment by RobDangerous** [comment]
Ah, it includes some C++. Sorry but for that to work you will need to change it into a Kha subproject - the way Kha builds C++ projects is entirely different compared to what hxcpp normally does.

**Comment by darmie** [comment]
I see. Working on a Korefile.

**Comment by darmie** [comment]
Resolved.
