### ISSUE TITLE
Problem adding Library

### ISSUE THREAD

**Issue by UnknownGuy1** [Kode/Kha#1061]
Hi, my problem is that I can't access any files in the Library.

addLibrary('mylib');      // in the khafile.js
in the library folder i have the "haxelib.json" with the name and the classpath,
but when I try to import a file (for example) from the Main.hx (" import mylib.File ")
it says : "[diagnostics] Type not found : mylib.File "

I did it exactly like Lewis Lepton for his raccoon engine, but it throws this error at me

**Comment by RobDangerous** [comment]
"diagnostics" messages only concern code completion, you have to restart your IDE after adding a library to fix it. What happens when you try to compile the project?

PS: I don't know what Lewis does for his raccoon engine, if this can't be resolved easily I'll need you to provide a sample project.

**Comment by UnknownGuy1** [comment]
Yea when I compile it than it works, so that's good, but I cant get rid of the diagnostics (even if I restart KodeStudio)

**Comment by RobDangerous** [comment]
ok, so purely a diagnostics problem. If you want to, give it a try in vscode with the Kha extension pack, which uses a much newer version of vshaxe. Otherwise I'm afraid you'll have to wait until I get to updating Kode Studio. Would still be interested in a sample project to test it myself though.

**Comment by UnknownGuy1** [comment]
OK, where do I share my project? Do I just attach it here?

**Comment by RobDangerous** [comment]
For example, any way you want.

**Comment by UnknownGuy1** [comment]
[Engine.zip](https://github.com/Kode/Kha/files/3269620/Engine.zip)
Ok so here it is

**Comment by RobDangerous** [comment]
Thanks.
