### ISSUE TITLE
[android-native] drawString is broken

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#1075]
Draws nothing.

**Comment by juakob** [comment]
Using android version(4.4.4) uses opengl es 2 and its running in a ouya
https://github.com/Kode/Kinc/blob/master/Backends/Graphics4/OpenGL/Sources/Kore/TextureImpl.c#L460
the texture created by g2, to render text throws an error after that line. I change GL_FLOAT to GL_UNSIGNED_BYTE as a fast hack
Not sure if we need a function like convertType(format) or just use GL_UNSIGNED_BYTE

**Comment by RblSb** [comment]
Maybe `convertType(format)` check is requred? From Kore:
https://github.com/Kode/Kinc/blob/ae8b88f443cd7ad76731bc931eb23e1efaf42c34/Backends/Graphics4/OpenGL/Sources/Kore/TextureImpl.cpp#L442-L447

**Comment by RobDangerous** [comment]
Hey, I merged that pull request. Is this fixed?

**Comment by RblSb** [comment]
I dont think you merged that pull request. Will create and test that pull request today.

**Comment by RobDangerous** [comment]
Ah, yes I merged https://github.com/Kode/Kinc/pull/409 but that was another ES 2 problem.
