### ISSUE TITLE
GC deadlock on linux and android-native

### ISSUE THREAD

**Issue by sh-dave** [Kode/Kha#1085]
The app just freezes after a couple of minutes running, and it seems related to the GC running 4 parallel threads that deadlock randomly. That only seems to happen with the new kinc based Mutex/Semaphore implementations on linux and android-native.

a workaround is to use the old non-kinc threadcode, see here: https://gist.github.com/sh-dave/57f9cdee216ae836b017596e9550b723

**Comment by RobDangerous** [comment]
@sh-dave I think you had some test code for me but I forgot where it is. Can you dig that up again?

**Comment by sh-dave** [comment]
It was possible to trigger this when you set a breakpoint somewhere in the cpp/h files. Can you find it in the chatlog? It guess it's older than what khalog.kode.tech lets me see currently, as the 2 mentions of `breakpoint` aren't related to that.

**Comment by RobDangerous** [comment]
Will temporarily increase the chatlog size when I'm home. I think I have a fix, but need to verify it...

**Comment by RobDangerous** [comment]
Got it, your repro-hint was:
"not sure if it's exactly the same issue,  but an easy to reproduce way is if you set a breakpoint in  HxSemaphore::Wait(). if it breaks and you click continue, it deadlocks.  this doesn't happen when i rename the `#if defined(KORE)` to `KORExxx`  and therefore use the HxSemaphore hugh implemented."

**Comment by RobDangerous** [comment]
Oh no, I tried in SuperJumpmanLand on macOS and it never Waits.

**Comment by sh-dave** [comment]
Then go nuts allocating moar stuff to trigger it! :smiley: 
I seem to have lost my sample code, but i'll try to recreate another one.

**Comment by RobDangerous** [comment]
I will allocate all the things tonight. Feeling dirty already.

**Comment by sh-dave** [comment]
Here is a simple project i can reproduce the issue with. Launch the `c++ linux debug` config and then activate the breakpoint (as mentioned in a comment above) after all GC threads have started. Sometimes the breakpoint will be hit and then you can actually continue, but for me it will eventually deadlock after a random number of hits (usually 0 - 10).

[kha-issue-1085.zip](https://github.com/Kode/Kha/files/3495674/kha-issue-1085.zip)

**Comment by RobDangerous** [comment]
That sounds very helpful, thanks!

**Comment by RobDangerous** [comment]
Arrr, it doesn't hang on macOS even though it uses the exact same code for all threading things. Now I'll actually have to boot Linux.

**Comment by RobDangerous** [comment]
Good news: I could reproduce it in Linux 😃
Bad news: When it hangs, it also hange the IDE 😒

**Comment by RobDangerous** [comment]
Don't think I could reproduce it after all, IDE and program just hang immediately when I hit a breakpoint. Anyway, I basically copied in my PS4 event code which works fine in even the most dire of situations, please give that a try.

**Comment by sh-dave** [comment]
What IDE are you running? Seems i can break/continue just fine in vscode with the c++ extension. Will check out the PS4 code tomorrow.

**Comment by RobDangerous** [comment]
Normally Clion but I have to renew my license so I ended up using Code::Blocks.

**Comment by sh-dave** [comment]
I can't reproduce the deadlock with the breakpoint anymore :tada: , but i'll let my app running for a while now and see if that triggers the original deadlock i encountered.

@OlegAntipov (i hope that it's you from IRC 2 months back) can you test your android-native build with this fix as well?

**Comment by sh-dave** [comment]
The app is running for an hour now without going khaputt (used to deadlock within 15min), so i think that PS4 code fixed it.

**Comment by OlegAntipov** [comment]
> @OlegAntipov (i hope that it's you from IRC 2 months back) can you test your android-native build with this fix as well?

Yeah, I'll try it tonight!

**Comment by RobDangerous** [comment]
Uh, exciting!

**Comment by OlegAntipov** [comment]
I tested the latest version of Kha this morning on android-native target, and there are no crashes. It seems that the problem with the deadlock is resolved!

**Comment by RobDangerous** [comment]
Exquisite!
