### ISSUE TITLE
Graphics2 rendering errors on iOS

### ISSUE THREAD

**Issue by hamaluik** [Kode/Kha#1087]
G2 rendering is broken on iOS using latest Kha. Created a demo project to showcase the issue: https://github.com/hamaluik/kha-texture-demo

Expected output (screenshot taken on html5):

![](https://raw.githubusercontent.com/hamaluik/kha-texture-demo/master/expected-html5.png)

Actual output on a iPhone 7+:

![](https://raw.githubusercontent.com/hamaluik/kha-texture-demo/master/ios.png)

I get a similar warping /distortion effect when just trying to draw a filled rect using:

```haxe
fb.g2.begin(true, 0xff424242);
fb.g2.color = 0xff00ff00;
fb.g2.fillRect(0, 0, 256, 256);
fb.g2.end();
```

**Comment by RblSb** [comment]
Probably related to https://github.com/Kode/Kinc/pull/403 & https://github.com/Kode/Kinc/pull/404

**Comment by hamaluik** [comment]
Unfortunately those fixes haven't changed anything. Still getting the issue.

**Comment by RobDangerous** [comment]
Oh, then I think I know what it is. Randomly changing matrix transpose at https://github.com/Kode/Kinc/blob/master/Backends/Graphics5/Metal/Sources/Kore/ConstantBuffer5Impl.mm#L9 should fix it. Digging out the Mac tonight.

**Comment by RobDangerous** [comment]
Fixed. But beware of https://github.com/Kode/Kha/issues/1085 - the last remaining critical issue of the Kinc upgrade I'm currently aware of.
