### ISSUE TITLE
Testing Kha support for input text

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#110]
I was testing input text in Kha, for future implementations of UI libs, and I'd like to show what I found.

In windows apps Game.keyDown is receiving specific characters from my keyboard (brazilian portuguese), which is very good, like ç. But it isn't recognizing characters that need a combination of keys, like accents. It is showing "~a" instead of "ã".

Html5 isn't mapping my keyboard in Game.keyDown, but I found that if I map the keypress event on canvas, like in:

```
private function roomLoaded():Void
{
    var canvas = js.Browser.document.getElementById('khanvas');
    canvas.onkeypress = keyPress;
}

function keyPress(event:KeyboardEvent)
{
    event.stopPropagation();

    var char = String.fromCharCode(event.which);
    js.Browser.console.log(char);

    // text will be drawn on screen
    text += char;
}
```

I can receive all characters from my keyboard, including characters from non-latin idioms, like hebrew (if I change my keyboard layout on windows). They are printed in the console, as shown in the function. Now a problem in both windows and html5, is that g2.drawString isn't printing this non-latin characters, only the latin ones. I'm using a Arial font, and Arial has support for hebrew, but the characters are not printed.

I was thinking, maybe Game.keyDown isn't very suited for input text, so we could have a event that map to keyPress on html5, and in windows (and other targets) it could resolve things like characters that need a combination of keys, like accents.

I now this can be harder than I think, but this is just a starting point.

**Comment by luboslenco** [comment]
It works, even in Safari!

**Comment by RobDangerous** [comment]
The ~a thing convinced me that I'll have to change the api for text input.
Printing non-latin characters is a bigger problem though. Kha uses bitmap font rendering, so I can't just put them all in as that would be bigmap rendering, so will likely require some sort of configuration.

**Comment by RafaelOliveira** [comment]
Maybe a specific api just for text input?

**Comment by RobDangerous** [comment]
Yes, I think so. Would also make a lot of sense for the software keyboards on iOS/Android.

**Comment by RobDangerous** [comment]
I adjusted the keyboard API slightly. There's a new keyPress callback and keyUp/Down provide keycodes only.
