### ISSUE TITLE
[khacpp] Zero is not equal to zero

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#1104]
Spooky? Works fine on hxcpp git.
```haxe
package;

class Main {

	static function main():Void {
		#if kha
		kha.System.start({title: "Empty", width: 800, height: 600}, init);
		#else
		init(null);
		#end
	}

	static function init(_):Void {
		final main = new Main();
	}

	var items:Array<{id:Int}>;

	function new() {
		items = haxe.Json.parse('[{"id": 0}]');
		final item = getBoxItem();
		trace(items[0].id, item.id);
		trace(items[0].id == item.id); // false
	}

	function getBoxItem():Null<{id:Int}> {
		if (Std.random(1) == 0) return {id: 0};
		return null;
	}

}
```

**Comment by OlegAntipov** [comment]
I already raise issue about this https://github.com/Kode/khacpp/issues/8.

Need to merge this commit to khacpp https://github.com/HaxeFoundation/hxcpp/commit/8f4396940a8d580b35bc10a9557c0c35581a2900

**Comment by RblSb** [comment]
Ah, i thinking this is only about `<=` and even thinking Robert merged that already. Good thing that nothing broken in fork specifically.

**Comment by OlegAntipov** [comment]
I'm not sure, but I think this piece of code affects any comparisons, not only <=

**Comment by RblSb** [comment]
Checked hxcpp commit before fix, this is it, yep. For history: https://github.com/HaxeFoundation/hxcpp/issues/822

**Comment by RobDangerous** [comment]
That reminds me of https://github.com/Kode/khacpp/commit/dd8875507402c50c89059565b469f06584a7d1a5. Anyway, will merge some things after #1085 is fixed.

**Comment by RobDangerous** [comment]
Merged all the things, should be fixed.
