### ISSUE TITLE
[macOS] High CPU usage with hidden window

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#1110]
On opengl kinc_g4_swap_buffers>[swapBuffersMac](https://github.com/Kode/Kinc/blob/master/Backends/System/macOS/Sources/Kore/System.mm#L103) still called when app is hidden or on another virtual window, and probably starts ignoring redraw interval (same as in https://github.com/glfw/glfw/issues/680?).
Not sure about metal, doesn't work currently, there is `Kinc/Graphics` includes in some places.

**Comment by RobDangerous** [comment]
You mean includes?

**Comment by RblSb** [comment]
Yep, fixed

**Comment by RobDangerous** [comment]
So you actually set your macOS to case-sensitive? Very courageous. I'll fix those tonight, then we can have a look at Metal (opengl on Mac is nowadays very low-prio for me).
