### ISSUE TITLE
Android Virtual Keyboard doesn't trigger key press callback

### ISSUE THREAD

**Issue by Huyston** [Kode/Kha#1138]
Hi!

I'm using the following code to get keyboard events:
```haxe
Keyboard.get().notify(onKeyDown,onKeyUp,onKeyPress);
```

This works in the browser. However, on Android, the virtual keyboard is not triggering those callbacks if I press a lowercase letter. If I press an uppercase letter, the shift key triggers the callback. Backspace and Return (Enter) triggers the callback too.

**Comment by Huyston** [comment]
The keyPress event is not defined for Android.
The event comes from [here](https://github.com/Kode/Kha/blob/bd4e647cfd98b28b7702a1b56f0d3c5cc281d914/Backends/Android/tech/kode/kha/KhaRenderer.hx) and then to [here] (https://github.com/Kode/Kha/blob/bd4e647cfd98b28b7702a1b56f0d3c5cc281d914/Backends/Android/kha/SystemImpl.hx).

To fix this issue, just call keyboard.sendPressEvent if the keyDown is triggered and is a char.

**Comment by RblSb** [comment]
https://github.com/Kode/Kha/issues/687

**Comment by Huyston** [comment]
Merge fix issue. Closing.
