### ISSUE TITLE
[android-n] AudioChannel.position not implemented

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#1141]

**Comment by RobDangerous** [comment]
That is not true, I see it right here: https://github.com/Kode/Kha/blob/master/Sources/kha/audio2/AudioChannel.hx#L69

**Comment by RblSb** [comment]
Well, `channel.position` always return zero for me. Works for html5 target.

**Comment by RobDangerous** [comment]
Sample project please. HTML5 in desktop browsers and Android-native use the same code for that.

**Comment by RblSb** [comment]
Ok. I thought it uses this code: https://github.com/Kode/Kha/blob/master/Backends/Kore/kha/audio2/StreamChannel.hx#L80

**Comment by RobDangerous** [comment]
Ah, you're talking about a StreamChannel. That's different. Still the same for all native targets though and also looks like there is an implementation.
