### ISSUE TITLE
GL Error 1282

### ISSUE THREAD

**Issue by DarthVernus** [Kode/Kha#1144]
10/22 21:05:33: Launching 'app' on ZTE ZTE BLADE A5 PRO.
$ adb shell am start -n "tech.kode.kore/tech.kode.kore.KoreActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Connected to process 17990 on device 'zte-zte_blade_a5_pro-900501921622'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/art: Late-enabling -Xcheck:jni
V/Activity: calling onCraete for activity: tech.kode.kore
W/ContextImpl: Failed to ensure directory: /storage/sdcard0/Android/obb/tech.kode.kore
W/ContextImpl: Failed to ensure directory: /storage/sdcard0/Android/data/tech.kode.kore/files
V/threaded_app: Creating: 0xadc48d40
V/threaded_app: Config: mcc=0 mnc=0 lang=ru cnt=RU orien=1 touch=3 dens=240 keys=1 nav=1 keysHid=3 navHid=0 sdk=21 size=2 long=2 modetype=1 modenight=1
I/: JNIHelper has not been initialized. Call init() to initialize the helper
V/threaded_app: Start: 0xadc48d40
V/threaded_app: activityState=10
V/threaded_app: Resume: 0xadc48d40
V/threaded_app: activityState=11
V/Activity: calling onResume for activity: tech.kode.kore
V/threaded_app: InputQueueCreated: 0xadc48d40 -- 0xadc39d40
V/threaded_app: APP_CMD_INPUT_CHANGED
    Attaching input queue to looper
V/threaded_app: NativeWindowCreated: 0xadc48d40 -- 0xb0248f08
V/threaded_app: APP_CMD_INIT_WINDOW
V/threaded_app: WindowFocusChanged: 0xadc48d40 -- 1
I/Kinc: Starting KoreHL
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 392
W/Kinc: Uniform projectionMatrix not found.
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 410
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 392
W/Kinc: Uniform projectionMatrix not found.
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 410
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 392
W/Kinc: Uniform projectionMatrix not found.
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 410
W/libOpenSLES: class OutputMix interface 0 requested but unavailable MPH=43
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 392
W/Kinc: Uniform projectionMatrix not found.
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 410
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
E/Kinc: GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209
    GL Error 1282 D:\SOFT\DEV\Armory3d\ArmorySDK\Kha\Kinc\Backends\Graphics4\OpenGL\Sources\Kore\PipelineStateImpl.c 209

**Comment by RobDangerous** [comment]
"Uniform projectionMatrix not found" <- doesn't seem to be a Kha issue. If you still think it is, please provide a minimal sample project.
