### ISSUE TITLE
Rendering area has offset on top when device has soft keys

### ISSUE THREAD

**Issue by Huyston** [Kode/Kha#1159]
There are some devices that uses virtual buttons (they draw the buttons on the screen, instead of using physical buttons).

For those devices, the returned touch position is summed with the virtual button height, causing a mismatch between the finger position and touch coordinate.

Disabling the virtual buttons fixes the touch position.

Disclaimer: Tested only on Android devices (LG G3 and Samsung S8).

**Comment by RobDangerous** [comment]
Can you fix it? I don't have a device like that.

**Comment by Huyston** [comment]
I'm trying to figure it out.

**Comment by Huyston** [comment]
I think the issue is that we call MotionEvent getX instead of getRawX. getX can return relative positions.

Source: https://developer.android.com/reference/android/view/MotionEvent

**Comment by RobDangerous** [comment]
OK, please give it a try.

**Comment by Huyston** [comment]
Changing that doesn't fix.

**Comment by potatoelixir** [comment]
I have multiple devices I can test this on; I'll see if I can test/check the issue out. Assuming no progress has been made by OP since last comment?

**Comment by Huyston** [comment]
Didn't figure it out yet. Tested on Xiaomi Redmi Note 6, which has soft buttons, but the issue is not present.

**Comment by Huyston** [comment]
There is a black area on top of the devices with this problem, which corresponds with the soft keys height.

System.windowHeight returns a value which is not the actual display height. The viewport 0,0 coordinate is not at the right position. Thus, the coordinate of the touch and the drawing mismatch.

So the problem is not actually the touch coordinate which is wrong, is that the drawing coordinates are wrong for those devices.

**Comment by Huyston** [comment]
Issue is reproducible on the emulator, using Google Pixel 2 API 29 Android 10.

**Comment by potatoelixir** [comment]
Possibly related:
https://stackoverflow.com/questions/29398929/how-get-height-of-the-status-bar-and-soft-key-buttons-bar/29400243
https://stackoverflow.com/questions/6936986/wrong-dimensions-returned-from-display-and-displaymetrics-in-android-3-2/8622079

**Comment by potatoelixir** [comment]
`System.windowHeight` is calculated by code in line 74 of https://github.com/Kode/Kha/blob/master/Backends/Android/kha/Window.hx if I'm not mistaken, and it looks correct D: DisplayMetrics are supposed to take into account status bars, soft menus, etc.

**Comment by Huyston** [comment]
windowHeight is correct, as it returns the "usable height". However, the y coordinate 0 doesn't match with the top of the "usable area". So kha is drawing behind the soft keys, while ignoring the top. So where does kha finds this 0,0 coordinate? We should take a look there.

**Comment by potatoelixir** [comment]
Possibly related:
https://stackoverflow.com/questions/27856603/lollipop-draw-behind-statusbar-with-its-color-set-to-transparent

**Comment by potatoelixir** [comment]
Kha's primary application is, I'd say, games and other types of interactive media. With these on Android (at least the machines I've used: LG V20, LG AKA, Samsung Galaxy Note...), the soft menu usually hides itself automatically, and whatever is being drawn ignores the soft menu (draws behind it). This is what I would expect for Kha to do, though you seem to be trying to draw only in the area of the screen excluding soft menus and status bars?

**Comment by potatoelixir** [comment]
`tech.code.kha.KhaView` extends `GLSurfaceView` which extends `View` which has a `setY()` method that we could use? Sorry for keep commenting "maybe this? maybe that?" but I am unable to test right now so this is the only way I'm able to help D:

**Comment by Huyston** [comment]
Kha's default is to use the fullscreen mode. Therefore, it should draw on the entire screen. But that's not what it is doing for some devices. It draws behind the soft keys, which is ok for that mode, but it doesn't draw at the top of the screen. There is a black area bellow the status bar.
So, the goal for me is to draw on the entire screen when using the fullscreen mode (default).

**Comment by potatoelixir** [comment]
Ok, gotchu. Apparently `setY()` behaves incorrectly sometimes? https://stackoverflow.com/questions/16782705/android-setx-and-sety-behaving-weird
Maybe `setTranslationY()`...

**Comment by Huyston** [comment]
> tech.code.kha.KhaView extends GLSurfaceView which extends View which has a setY() method that we could use?

Will have a look at that when I can. I'm actually very new to Kha, so anything is helpful for me :)

**Comment by Huyston** [comment]
setTranslationY can be used as a workaround, but I think we need to initialize in the right position. Another problem is discovering how many pixels we have to translate.
I'm trying to find the view or renderer parameter that defines the 0,0 coordinate.

**Comment by Huyston** [comment]
After some digging, I found that the view size is right. The problem is on the renderer gl instructions.

**Comment by Huyston** [comment]
Ok, I found the line that causes this problem. Backends/Android/kha/android/Graphics.hx:113.
The error comes from kha.System.windowsHeight being the wrong.

**Comment by potatoelixir** [comment]
Nice work! So are your changes PR-ready yet, or does it still need a bit more work?

**Comment by Huyston** [comment]
I'm testing to see if it breaks something.

**Comment by RobDangerous** [comment]
Oh, so everybody but me was talking about the Android-backend instead of the Android-Native-backend?

**Comment by Huyston** [comment]
Will refer as Non-Native Android backend in the future to avoid that :)
Closing as the merge fix this issue.
