### ISSUE TITLE
Vector operation force you to make allocation

### ISSUE THREAD

**Issue by wighawag** [Kode/Kha#116]
In Vector4.hx for example several function contain a "new Vector4()" that create an array of float. 

A better API like the one used by  http://glmatrix.net/ can be used so the user can make the decision to allocate or not. This is done by passing the result as a parameter instead of getting as the return only

I started to port this library to haxe and you can see for example how matrix transformation does not do any allocation : https://github.com/wighawag/kit/blob/master/src/glmat/Vec4.hx#L44

**Comment by RobDangerous** [comment]
The matrices and vectors used by Kha in g2 don't do any allocations either, just have to adjust the remaining classes accordingly. Not really necessary to make the api hard to use like that when you have inline constructors.

**Comment by wighawag** [comment]
It might be an haxe issue but currently the generated js and cpp do allocation on every call to new Matrix4(), same for Vector4...
Do you have that too ?

**Comment by RobDangerous** [comment]
Regular Haxe 3.2 or Haxe version included in Kha? Because the latter had some inlining fixes.

**Comment by wighawag** [comment]
both

**Comment by RobDangerous** [comment]
I did a quick test with Vector4 and git Kha and it was perfectly inlined.

	private function test(): Float {
		var vec = new kha.math.Vector4(3, 4, 5, 6);
		var vec2 = vec.add(new kha.math.Vector4(7, 8, 9, 0));
		return vec2.x;
	}

is compiled to

	test: function() {
		var vec_x = 3;
		var vec_y = 4;
		var vec_z = 5;
		var vec_w = 6;
		var vec_x1 = 7;
		var vec_y1 = 8;
		var vec_z1 = 9;
		var vec_w1 = 0;
		var vec2_x = vec_x + vec_x1;
		var vec2_y = vec_y + vec_y1;
		var vec2_z = vec_z + vec_z1;
		var vec2_w = vec_w + vec_w1;
		return vec2_x;
	}

Can you show me the code that isn't inlined?

**Comment by wighawag** [comment]
oh, I was using Empty but for some reason I was not on the latest Kha.

Still with the latest Kha I have the following:

```haxe
var m = Matrix4.identity();
var v = new Vector4(0,1,2,0);
var out = m.multvec(v);
```

I get the following js
```js
        var m__00 = 1;
	var m__10 = 0;
	var m__20 = 0;
	var m__30 = 0;
	var m__01 = 0;
	var m__11 = 1;
	var m__21 = 0;
	var m__31 = 0;
	var m__02 = 0;
	var m__12 = 0;
	var m__22 = 1;
	var m__32 = 0;
	var m__03 = 0;
	var m__13 = 0;
	var m__23 = 0;
	var m__33 = 1;
	var v_x = 0;
	var v_y = 1;
	var v_z = 2;
	var v_w = 0;
	var out;
	var product = new kha_math_Vector4();
	product.x = m__00 * v_x + m__10 * v_y + m__20 * v_z + m__30 * v_w;
	product.y = m__01 * v_x + m__11 * v_y + m__21 * v_z + m__31 * v_w;
	product.z = m__02 * v_x + m__12 * v_y + m__22 * v_z + m__32 * v_w;
	product.w = m__03 * v_x + m__13 * v_y + m__23 * v_z + m__33 * v_w;
	out = product;
```

Also as soon as the matrix/vector is stored as a member variable it needs to be an instance of the generated js matrix/vector class

**Comment by RobDangerous** [comment]
There are lots of situations that currently force the Haxe compiler to do allocations even when a proper inlining constructor is supplied. Some of those might be relatively easy to fix in the compiler (member variables might be one of those) and it might therefore make sense to open an issue in the official Haxe project. Other situations are really hard to handle, for example variables which are returned from a functions which isn't inlined - I suspect that's what happens to your out variable?
inlining constructors help in some situations. When they don't help, you will have to resort to classic strategies to avoid allocations in GC languages as you described above. That said, Kha itself should never allocate a Vector or a Matrix and I'll soon be done enforcing this.

**Comment by wighawag** [comment]
The out was just a local variable and it was not returned. So I guess this is an issue with the haxe compiler.
For these reasons, I think it would be better to have an allocation-less api but if you do not plan to make one, I ll probably create a wrapper that does it.
Thanks

**Comment by RobDangerous** [comment]
I prefer to fix the compiler.
Can reproduce the problem in your function, will see what can be done about it...
And about member variables - don't see how another api could help there right now, but always open for suggestions.

**Comment by wighawag** [comment]
I agree that it will be great if the compiler could be improved to inline member variable and other use case. 
In the mean time, for member variable, the idea is to use something similar to what I described above : you pass the matrix to be modified as a parameter to the function. Basically functions never call "new"
It might be less than ideal API but at least you can be sure there is no instantiation.

**Comment by RobDangerous** [comment]
Still don't see how that can help. The allocation happens when you create the matrix for the member variable, not when you call the function, right?

**Comment by wighawag** [comment]
I was referring to further allocation, I do not mind the first allocation of the member variable as it can be done in the constructor of the enclosing class whose instantiation I control. 

see:

```haxe
class Test{
  var m : Matrix4;
  public function new(){
    m = Matrix4.identity();
  }

  public function update(){
   m = Matrix4.orthogonalProjection(...
 }
}
```

in the update function a new allocation is made.

**Comment by RobDangerous** [comment]
Ah, understood. OK, good argument, will add the allocation avoidance api.

**Comment by wighawag** [comment]
Should we reopen this issue as the allocation avoidance api has not been implemented yet ?
