### ISSUE TITLE
Seg fault on linux with multithreading using workers

### ISSUE THREAD

**Issue by mundusnine** [Kode/Kha#1160]
Using the most recent Kha git
OS: Debian 10
Example project:
[project.zip](https://github.com/Kode/Kha/files/3881505/project.zip)
 When testing with the project just press D once on the keyboard and wait. 
```
Active debugger config: GDB/CDB debugger:Default
Building to ensure sources are up-to-date
Selecting target: 
Debug
Adding source dir: /home/jsnadeau/Documents/tests/multithreaded-kha/build/linux-build/
Adding source dir: /home/jsnadeau/
Adding file: /home/jsnadeau/Documents/tests/multithreaded-kha/build/linux-build/bin/Debug/New-Project
Changing directory to: /home/jsnadeau/Documents/tests/multithreaded-kha/build/linux
Set variable: LD_LIBRARY_PATH=.:
Starting debugger: /usr/bin/gdb -nx -fullname -quiet  -args /home/jsnadeau/Documents/tests/multithreaded-kha/build/linux-build/bin/Debug/New-Project
done
Registered new type: wxString
Registered new type: STL String
Registered new type: STL Vector
Setting breakpoints
Debugger name and version: GNU gdb (Debian 8.2.1-2+b1) 8.2.1
Child process PID: 9598
At /home/jsnadeau/Kha/Backends/Kore/khacpp/src/hx/gc/Immix.cpp:1855
Continuing...
No stack.
Program terminated with signal SIGSEGV, Segmentation fault.
Debugger finished with status 0

```

**Comment by sh-dave** [comment]
Does it happen with `--slowgc` as well?

**Comment by RobDangerous** [comment]
That sample is way too complicated for me. Can you try with something simple instead? There's a lot that can go wrong with threads in Haxe, in particular and as I only recently learned myself the garbage collector can crash when you access an object from multiple threads without using a mutex. I can't tell whether that is happening here.

**Comment by mundusnine** [comment]
> That sample is way too complicated for me. Can you try with something simple instead? There's a lot that can go wrong with threads in Haxe, in particular and as I only recently learned myself the garbage collector can crash when you access an object from multiple threads without using a mutex. I can't tell whether that is happening here.

Ok I will try to simplify the usecase. I will also try what dave proposed. Will report back when it's done.

**Comment by mundusnine** [comment]
So here it is; I couldn't find the define or the command that dave talked about. Issue still happens on simplified version. It always fails on the same line in Immix.cpp.

[simple-project.zip](https://github.com/Kode/Kha/files/3882137/simple-project.zip)

**Comment by mundusnine** [comment]
The issue seems to have been caused by https://github.com/HaxeFoundation/hxcpp/issues/872. When I git pulled most recent changes to khacpp it fixed the issue.

**Comment by RobDangerous** [comment]
Yay
