### ISSUE TITLE
`Direct fetching of that commit failed`

### ISSUE THREAD

**Issue by hamaluik** [Kode/Kha#1164]
I frequently get issues when using Kha as a submodule, with the message `Direct fetching of that commit failed`. Here's a sample from a checkout a few minutes ago:

```
Submodule 'games/libs/Kha' (https://github.com/Kode/Kha.git) registered for path 'games/libs/Kha'
Cloning into '/root/project/games/libs/Kha'...
Submodule path 'games/libs/Kha': checked out '91400b060fafc3e5b856e299d01ed543963ff06a'
Submodule 'Backends/Kore/khacpp' (https://github.com/Kode/khacpp.git) registered for path 'games/libs/Kha/Backends/Kore/khacpp'
Submodule 'Kinc' (https://github.com/Kode/Kinc.git) registered for path 'games/libs/Kha/Kinc'
Submodule 'Tools/haxe' (https://github.com/Kode/haxe_bin.git) registered for path 'games/libs/Kha/Tools/haxe'
Submodule 'Tools/khamake' (https://github.com/Kode/khamake.git) registered for path 'games/libs/Kha/Tools/khamake'
Submodule 'Tools/kravur' (https://github.com/Kode/kravur_bin.git) registered for path 'games/libs/Kha/Tools/kravur'
Submodule 'Tools/lame' (https://github.com/Kode/lame_bin.git) registered for path 'games/libs/Kha/Tools/lame'
Submodule 'Tools/oggenc' (https://github.com/Kode/oggenc_bin.git) registered for path 'games/libs/Kha/Tools/oggenc'
Cloning into '/root/project/games/libs/Kha/Backends/Kore/khacpp'...
Cloning into '/root/project/games/libs/Kha/Kinc'...
Cloning into '/root/project/games/libs/Kha/Tools/haxe'...
Cloning into '/root/project/games/libs/Kha/Tools/khamake'...
Cloning into '/root/project/games/libs/Kha/Tools/kravur'...
Cloning into '/root/project/games/libs/Kha/Tools/lame'...
Cloning into '/root/project/games/libs/Kha/Tools/oggenc'...
Submodule path 'games/libs/Kha/Backends/Kore/khacpp': checked out 'fa0a4d4cc74fab80e8eab27992e2d6a29b226ed2'
Submodule path 'games/libs/Kha/Kinc': checked out '48cc599a4c61861164ece52bb5e63001995a86a8'
Submodule 'Tools/kincmake' (https://github.com/Kode/kincmake.git) registered for path 'games/libs/Kha/Kinc/Tools/kincmake'
Submodule 'Tools/kraffiti' (https://github.com/Kode/kraffiti_bin.git) registered for path 'games/libs/Kha/Kinc/Tools/kraffiti'
Submodule 'Tools/krafix' (https://github.com/Kode/krafix_bin.git) registered for path 'games/libs/Kha/Kinc/Tools/krafix'
Cloning into '/root/project/games/libs/Kha/Kinc/Tools/kincmake'...
Cloning into '/root/project/games/libs/Kha/Kinc/Tools/kraffiti'...
Cloning into '/root/project/games/libs/Kha/Kinc/Tools/krafix'...
Submodule path 'games/libs/Kha/Kinc/Tools/kincmake': checked out '18e8761cd49b0ab46650bc2870efffba59634362'
Submodule path 'games/libs/Kha/Kinc/Tools/kraffiti': checked out '1a589c357b7716b6643d318eca937d81902e778a'
error: no such remote ref 5a2dc7d376bf5aef638a6d4561d0d2094ed74a75
Fetched in submodule path 'games/libs/Kha/Kinc/Tools/krafix', but it did not contain 5a2dc7d376bf5aef638a6d4561d0d2094ed74a75. Direct fetching of that commit failed.
Submodule path 'games/libs/Kha/Tools/haxe': checked out 'de31b2cc440bcd91942d7fae966507ea44176c8e'
Submodule path 'games/libs/Kha/Tools/khamake': checked out '37938d557cc9aa5ba742ffc33b58694eabc1ed17'
Submodule path 'games/libs/Kha/Tools/kravur': checked out '224bfe99eebe2fa7d30659ca8f0fc435f312d66d'
Submodule path 'games/libs/Kha/Tools/lame': checked out '7e10dc2dd39444a97444a6b07635a7786b227bcb'
Submodule path 'games/libs/Kha/Tools/oggenc': checked out 'dcb7978e77c5154ecfd2c3931c0aae1ce68c5fee'
Failed to recurse into submodule path 'games/libs/Kha/Kinc'
Failed to recurse into submodule path 'games/libs/Kha'
Exited with code 1
```

This has been happening for a while now, and it seems like there isn't really a pattern to it. One day it will be fine, another it will break all my CI and my coworkers freak out and I have to go in and tinker with the submodules to get it working again.

I believe the issue could be related to development work that pushes the `Kha` repo before pushing changes in the upstream repos, but I'm not sure of this as I don't know your process for syncing those (ref: https://www.deployhq.com/support/common-repository-errors/direct-fetching-of-commit-failed).

**Comment by RobDangerous** [comment]
The issue is that GitHub handles shallow submodules purely. Basically only the latest commit works directly. I thought I found a silly workaround by pushing a tag for each commit and that seemed to work for me yesterday but judging from your log that isn't reliable either. I don't know what to do about it yet but meanwhile a git submodule sync call should help.

**Comment by RobDangerous** [comment]
Just did a `git clone --recursive https://github.com/Kode/Kha.git` and that worked though. Are you sure that log was from right now?

**Comment by hamaluik** [comment]
The log was from ~4 hours ago now, run on CircleCI. I just re-ran the job, and it failed again on CircleCI's server. When I download the repo and check it out locally though it worked just fine.

CircleCI on the left, local on the right:
![https://imgur.com/r0qaklz](https://i.imgur.com/r0qaklz.png)

When I cloned it locally at work ~3 hours ago I failed to pull it (don't have a log for this) so it's not strictly  limited to CircleCI. (When I remote in and clone right now, it clones just fine).

I wonder if there's some weird caching going on somewhere?

**Comment by RobDangerous** [comment]
Maybe. Can you see which commands CircleCI executes exactly?

**Comment by hamaluik** [comment]
The checkout code step (which runs successfully) runs these commands:

```
#!/bin/sh
set -e

# Workaround old docker images with incorrect $HOME
# check https://github.com/docker/docker/issues/2968 for details
if [ "${HOME}" = "/" ]
then
  export HOME=$(getent passwd $(id -un) | cut -d: -f6)
fi

mkdir -p ~/.ssh

echo 'github.com ssh-rsa **REDACTED**
bitbucket.org ssh-rsa **REDACTED**
' >> ~/.ssh/known_hosts

(umask 077; touch ~/.ssh/id_rsa)
chmod 0600 ~/.ssh/id_rsa
(cat <<EOF > ~/.ssh/id_rsa
$CHECKOUT_KEY
EOF
)

# use git+ssh instead of https
git config --global url."ssh://git@bitbucket.org".insteadOf "https://bitbucket.org" || true
git config --global gc.auto 0 || true

if [ -e /root/project/.git ]
then
  cd /root/project
    git remote set-url origin "$CIRCLE_REPOSITORY_URL" || true
else
  mkdir -p /root/project
    cd /root/project
    git clone "$CIRCLE_REPOSITORY_URL" .
fi

if [ -n "$CIRCLE_TAG" ]
then
  git fetch --force origin "refs/tags/${CIRCLE_TAG}"
else
  git fetch --force origin "develop:remotes/origin/develop"
fi

if [ -n "$CIRCLE_TAG" ]
then
  git reset --hard "$CIRCLE_SHA1"
  git checkout -q "$CIRCLE_TAG"
elif [ -n "$CIRCLE_BRANCH" ]
then
  git reset --hard "$CIRCLE_SHA1"
  git checkout -q -B "$CIRCLE_BRANCH"
fi

git reset --hard "$CIRCLE_SHA1"
```

The step that fails (checking out submodules) runs:

```
#!/bin/bash -eo pipefail
git submodule update --init --recursive
```

**Comment by RobDangerous** [comment]
Did this fix itself in the meantime? And if it didn't, would it be ok for you if I changed things to use git lfs instead of shallow submodules?

**Comment by sh-dave** [comment]
I have the same issue but only with specific git versions (2.11 on my debian). A workaround is to

```
cd Kha/Kinc/Tools/krafix
git pull --unshallow
```

Other git versions i tried (2.7, 2.14) work fine.

**Comment by hamaluik** [comment]
Seems to be working right now on my machine (though I'm not confident saying it's 100% fixed because the issue only happens some of the time, not all the time).

On my end I'm totally fine with LFS—we use it for all of our assets, I would just be worried about breaking things for others (though you could certainly argue that if you're competent enough to use git submodules you should be competent enough to use git lfs).

@sh-dave Thanks for that! I run git 2.24 on my development machine, but my build container is definitely using 2.11.. I'll get that sorted / use that command and see if that sorts it out.

**Comment by RobDangerous** [comment]
ok, please tell me if it breaks again. If so I'll probably switch to git lfs which seems to be the lesser evil.

**Comment by matkoniecz** [comment]
It happened again on trying `git clone --recursive https://github.com/Kha-Samples/Empty.git` from https://github.com/Kode/Kha/wiki/Examples

Full log at https://gist.github.com/matkoniecz/1ac00e45fa70c123cc2488eecb284ab8

```
Submodule path 'Kha/Kinc/Tools/krafix': checked out '5a2dc7d376bf5aef638a6d4561d0d2094ed74a75'
error: Server does not allow request for unadvertised object de31b2cc440bcd91942d7fae966507ea44176c8e
Fetched in submodule path 'Kha/Tools/haxe', but it did not contain de31b2cc440bcd91942d7fae966507ea44176c8e. Direct fetching of that commit failed.
Failed to recurse into submodule path 'Kha'
```

**Comment by RobDangerous** [comment]
Empty was still pointing to an older Kha revision. I just changed that, please give it another try.

**Comment by matkoniecz** [comment]
Now it worked, thanks.

**Comment by hamaluik** [comment]
Just chiming in to say that I haven’t experienced this once since updating the git version in my build image. Since Kha + git updates seem to have also fixed this for others, I think this issue can probably be closed and resolved.

Thanks everyone!

**Comment by RobDangerous** [comment]
Let's hope for the best. Thanks for the info!
