### ISSUE TITLE
crash on windows when no audio devices present

### ISSUE THREAD

**Issue by romamik** [Kode/Kha#1175]
When I have no audio devices enabled in windows control panel, empty kha application crashes
at `WASAPI.winrt.cpp:192` in `kinc_a2_init()`, because `deviceEnumerator->GetDefaultAudioEndpoint` set `null` to `device`.
https://user-images.githubusercontent.com/3735734/73246248-33182200-41bf-11ea-8ab5-81dc8d06a3da.png

**Comment by RobDangerous** [comment]
We don't talk about that... because talking requires an audio device.
