### ISSUE TITLE
Incompatibility for platforms using CompareMode

### ISSUE THREAD

**Issue by trsh** [Kode/Kha#1176]
**Example**: 
[dxp.zip](https://github.com/Kode/Kha/files/4129396/dxp.zip)

**System**: Windows 10, GTX 750 TI (up to date drivers)

**Test IDE**: VSCode with Kha ext. Krom path and kha path set to newest from git

**Reproduction steps**:
Build with HTML5 in VS: Red something visible (WebGL?)
Build with Krom in VS: Red something **not** visible (DX?)

-----------------------------------------------------------------------------

**Other system**: OSX

**Test IDE**: VSCode with Kha ext. Krom path and kha path set to newest from git

**Reproduction steps**:
Build with HTML5 in VS: Red something visible (WebGL?)
Build with Krom in VS: Red something visible (Metal?)

**Comment by RobDangerous** [comment]
Please describe what you are actually talking about, I don't want to download some random zip archive.

**Comment by trsh** [comment]
@RobDangerous 

a) The topic kind of explains what I'm talking about? 
b) CompareMode has different effects on different platforms (or broken on some), what shouldn't be so?
c) This is nor random zip, but an reproduction example. Small Kha prohect
d) Why while asking for details, u actually close the issue before getting answers?
