### ISSUE TITLE
`kha.audio2.Audio.stream` (on HTML5) throws an exception for uncompressed sounds

### ISSUE THREAD

**Issue by hamaluik** [Kode/Kha#1178]
I'm fiddling with audio in one of my projects (a racing game), and want to eventually get to dynamically adjusting pitch (or at least, audio channel playback speed) but I can't seem to get `audio2` to work at all. The current problem I'm running headfirst into is that if I call:

```haxe
var channel = kha.audio2.Audio.stream(Assets.sounds.idle, true);
```

(on HTML5, the assets have all been loaded), an exception is thrown:

```
Audio.hx:93 Uncaught TypeError: Cannot read property 'b' of null
    at Function.kha_audio2_Audio.stream (Audio.hx:93)
    at Function.kha_audio2_Audio1.stream (Audio1.hx:171)
    at new processors_audio_EngineSounds (EngineSounds.hx:25)
    at Function.Game.initialize (Game.hx:67)
    at Function.Loader.onDone (Main.hx:9)
    at Loader.hx:22
    at onLoaded (Assets.hx:133)
    at uncompressInner (WebAudioSound.hx:107)
```

[The line it's referencing is](https://github.com/Kode/Kha/blob/master/Backends/HTML5/kha/audio2/Audio.hx#L93):

```haxe
var blob = new js.html.Blob([sound.compressedData.getData()], {type: "audio/mp4"});
```

And the problem is that the sound's `compressedData` is `null` (printing the `Sound` to the console reveals):

```javascript
{
    sampleRate: 44100,
    channels: 2,
    length: 5.0639909297052155,
    compressedData: null,
    uncompressedData: Float32Array(446644),
}
```

I fiddled around with changing the sound in `Audio.hx` to load a blob from the
uncompressed data, but that just took me to more errors.

I think this is either a bug (according to git this code hasn't been touched in 4
years), or I'm approaching audio all wrong (which would very well be possible).

The asset I'm trying to load is a `.wav` file, and the line that triggers this is:

```haxe
idleChannel = Audio.stream(Assets.sounds.get("idle"), true);
```

**Comment by sh-dave** [comment]
If you `kha.Assets.loadEverything()`, sounds will be uncompressed by default. So check the params and provide a custom uncompress filter that just returns `false`.

https://github.com/Kode/Kha/blob/679f19fd415a3ef5f6914338514956976b31ba00/Sources/kha/Assets.hx#L89

**Comment by RobDangerous** [comment]
That is expected, stream is for directly playing compressed sounds without uncompressing them. Wavs are uncompressed. When you load a sound by default it gets uncompressed (you can provide a filter to the loadEverything function to avoid it). Try the play function instead. Also have a look at audio2.Audio1 for some sample code, including some code to change the pitch.

**Comment by RobDangerous** [comment]
Oh no, super fast Dave was super fast.

**Comment by hamaluik** [comment]
Ahh, thanks guys! One of these days I'll get around to working on a more cohesive API documentation PR..
