### ISSUE TITLE
[Java/Android] compile failure when passing constant to inline function expecting FastFloat

### ISSUE THREAD

**Issue by AlexRamallo** [Kode/Kha#1179]
The following code:
```
import kha.Color;
import kha.FastFloat;

class Main {

	static inline function test(x:FastFloat):FastFloat{
		return Color.White.A * x;
	}

	static function main(){
		var a = test(1.0);
		trace(a);
	}
	
}
```

Results in the following error when compiling in Android Studio:
`error: incompatible types: possible lossy conversion from double to float`

The generated code looks like this:

```
	public static float test(float x)
	{
		//line 28 "x/Sources/Main.hx"
		return ( ( (( ((int) (-1) ) >>> 24 )) * ((float) (0.00392156862745098) ) ) * x );
	}
	
	
	public static void main()
	{
		//line 32 "x/Sources/Main.hx"
		float a = ( ( (( ((int) (-1) ) >>> 24 )) * ((float) (0.00392156862745098) ) ) * 1.0 );
		//line 33 "x/Sources/Main.hx"
		haxe.Log.trace.__hx_invoke2_o(((double) (a) ), haxe.lang.Runtime.undefined, 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (33) )) )}));
	}
```

The workaround is simply to not inline `test`, or just specify the type of the parameter like `test((1.0:FastFloat))`. The C++ target generates similar code, but it compiles fine because C++ allows the implicit cast.

I don't know if this is a Kha problem or a Haxe problem. Even though it's easy to workaround, I can imagine a lot of debugging headache if you encounter this Java error while your code compiles perfectly fine on the other targets.

**Comment by RobDangerous** [comment]
That's a Haxe issue, FastFloat is just a typedef for Single. Please report it there and link this issue.

**Comment by sh-dave** [comment]
I think thats the same issue @RblSb encountered a while ago with the matrix classes IIRC?

**Comment by RobDangerous** [comment]
Oh, you might be right! Super fast Dave on it again.

**Comment by RblSb** [comment]
@sh-dave i think this is different case, but maybe can be related, yeah.
https://github.com/HaxeFoundation/haxe/issues/8220

**Comment by RobDangerous** [comment]
Ah and also that one's already fixed.
