### ISSUE TITLE
Detect window resize for all kha targets

### ISSUE THREAD

**Issue by ianharrigan** [Kode/Kha#1182]
Is there a way, using the standard kha apis, to detect if the "window" has resized, so that would mean:

* the canvas in a web app has resized (via browser resize, or external js resizing it)
* main window on windows get resized by the user
* application gets resized due to an orientation change on mobiles

Ive had a look round the api and nothing jumped out at me, i asked in the discord and it was suggested that every frame i could check if the window had changed its dimensions and could do whatever i wanted when it had - but before i went that route i wanted to make sure that was indeed the best / only way to go about this.

Cheers,
Ian

**Comment by sh-dave** [comment]
There is `kha.Window.notifyOnResize()`, but i'm not sure if it's implemented yet.

**Comment by ianharrigan** [comment]
Thanks for that! Ill check it out and see how supported / implemented it is.

Thanks again!

**Comment by RobDangerous** [comment]
PS: Please use the forum or irc for questions. GitHub is for bugs and discord... man, I still wished I could just get that channel closed, it's less then unhelpful.

**Comment by ianharrigan** [comment]
Fair enough - noted.
