### ISSUE TITLE
Color mixup in krom (macOS)

### ISSUE THREAD

**Issue by BlackGoku36** [Kode/Kha#1185]
| Color used to draw | Color actually displayed in krom|
|---------------------|--------------------------------|
|red                           | blue|
|blue                         | red|
|yellow                      | cyan|
|green                       | green |
|Orange                    | Sky blue|
|etc.                        |etc.|

Same sample code from here: https://github.com/Kode/Kha/issues/1184
`img.g1.setPixel(Std.int(mouse.x+y), Std.int(mouse.y+x), kha.Color.Red);`

**Comment by RobDangerous** [comment]
There's an incomplete pull request for that, add your info there please: #1161
