### ISSUE TITLE
[HTML5] Mouse wheel default action is always prevented

### ISSUE THREAD

**Issue by Sanva** [Kode/Kha#1186]
This looks like the opposite of #733.

Here, the use case would be to have a regular web document using some kind of advanced component that is developed with Kha. The problem is that the user would not be able to scroll the page [1] using the mouse wheel without issues, since it would work only if the mouse is not hovering the Kha canvas — so, to make matters worst, to a regular user it would be like the page randomly fails to scroll.

I'm thinking about opening a pull request implementing something like `Keyboard.disableSystemInterventions` but for mouse wheel and surface touch down events. Would it be something desirable to have?

[1] In mobile devices it is worst, preventing user from scrolling in any way if the browser has the Kha application occupying all visible space.

**Comment by RobDangerous** [comment]
Yes, I'd very much like to see that pull-request.
