### ISSUE TITLE
Out of date API documentation at api.kha.tech

### ISSUE THREAD

**Issue by ZanaDev** [Kode/Kha#1189]
Looks to be 2 years out of date, and it seems several features have been deprecated and added in the mean time. 

Regenerate it?

**Comment by RobDangerous** [comment]
Hey, it's not that easy, I had to fix an hxsl macro to make the Haxe compiler spit out the documentation xml again. But it is done.

**Comment by ZanaDev** [comment]
Sorry about the difficulty, but thank you, it's very appreciated.
