### ISSUE TITLE
Issue with drawRect() on HTML5 target

### ISSUE THREAD

**Issue by maxfish** [Kode/Kha#1195]
Hi,
I'm aware of all the previous discussions about the lack of support for HiDPI screens, and even if I think this might be related to that, this could be a slightly different issue.

The short description is: drawRect() doesn't draw correctly when targeting HTML5.
<img width="693" alt="Screenshot 2020-04-26 at 17 10 23" src="https://user-images.githubusercontent.com/1917764/80311593-d8538e00-87e0-11ea-9b7d-8116262a09cb.png">

The issue can be reproduced using **MacOS** (Catalina) and resizing the window. A video of the issue in action is [here](https://youtu.be/sQr4nLR3_Fg)

The minimal app to reproduce the issue is [here](https://gist.github.com/maxfish/2f2f2e2d1f630c240b308ad3008322d1).

**Comment by RobDangerous** [comment]
This is working as intended, see #80.
