### ISSUE TITLE
How to set Kha/Kode to use latest Haxe?

### ISSUE THREAD

**Issue by darmie** [Kode/Kha#1200]
Kode studio indicates that I am using Haxe `4.0.0-rc.1` , which I think is outdated, because I have some dependencies that uses `haxe.macro.FunctionKind` but I keep getting an error like this `Type not found : FunctionKind`

I suspect that I need to update the Haxe version which Kha supports, How can I do that without breaking Kha?

**Comment by RobDangerous** [comment]
Hi! Sorry but please use the forum or irc for asking questions, the issue tracker is exclusively used for tracking issues.

**Comment by darmie** [comment]
@RobDangerous just did
