### ISSUE TITLE
kha.netsync.Network class missing in android build project

### ISSUE THREAD

**Issue by abisxir** [Kode/Kha#1201]
Kha version 16.1.2
The default project with no additional code, created in Kode studio, when builds for android, the java file for Network class missing.
As I see Session class uses this class:
kha.netsync.Network

**Comment by RobDangerous** [comment]
Sorry but the netsync package shouldn't be used yet and I'm not sure I'll even provide it for Java Android. Also pretty sure you're not using Kha 16.1.2 because that version didn't even have the netsync package.

**Comment by abisxir** [comment]
Humm, definitely I use kha version 16.1.2, additionally checked from directory structure of haxelib, but why did you close the issue? I am not familiar with kha community guidelines but closing an issue without any solution is so disappointing. I will fix this by commenting some lines to see what else I will face with an empty project.

**Comment by RobDangerous** [comment]
Because netsync is a non-finished feature so it does not yet make sense to submit bugs for it. Also please don't use the haxelib version ever - actually don't understand at all what you're doing there, please read the docs for how to use Kha, it's so disappointing when people use Kha without reading the docs.

**Comment by abisxir** [comment]
You are right about the version, the version is 18.11.3 but not about the unfinished features, because it is kind of partially merged there. Why I have to see something unfinished in the generated code of the official installation? 

The reason of a bug is not the solution for that. When you close a bug without any mark you will lose the track, so maybe this bug will last long and will appear also in the next release. By the way the issue went to a wrong direction so I skip the details and will find a solution for myself there.
And thanks for the hint for the version check.

**Comment by RobDangerous** [comment]
You are not helpful. You still haven't even read the documentation and play around with a version from 2018. Please go and try some other project.

**Comment by abisxir** [comment]
Yes sir, I was waiting for your orders to avoid the project.

For the other people facing this issue, the last available release of Kode studio uses and older version of Kha. To update Kha, there is not an easy way like updating extension so you should clone Kha somewhere else and change the Kha path inside KodeStudio settings.

So it is a KodeStudio bug not a Kha bug.

Now I understand why such a great project has less users, it was my first interaction and I feel I will not touch it again. The guy here comments in a very bad way that leads you to nowhere, not helpful but very irritating and confusing. I was doubting that what I have not read, because I just started the from official website:

http://kha.tech/getstarted

But what he mentioned that you did not read the docs was here:

https://github.com/Kode/Kha/wiki/Getting-Started

**Comment by RobDangerous** [comment]
Yay, bye.
