### ISSUE TITLE
Krom trace message length

### ISSUE THREAD

**Issue by tong** [Kode/Kha#1214]
https://github.com/Kode/Kha/blob/edb480bbaa327700951b6978edaeeb7a4cb36078/Backends/Krom/kha/SystemImpl.hx#L138
Is there any reason why the trace messages are limited to a length of 512?  
It's not enough in some cases.

**Comment by RobDangerous** [comment]
Yes, multiple reasons - buffer and packet sizes. But it's all fixed now.
