### ISSUE TITLE
Rendertarget draws after 374 images, does not draw after 375.

### ISSUE THREAD

**Issue by 5Mixer** [Kode/Kha#1222]
Render texture fails to draw after 375 calls to `drawImage`, however succeeds after 374.

See testcase reproducing issue [here](https://github.com/5Mixer/KhaRendertextureTestCase).

When `repeats=375`
![image](https://user-images.githubusercontent.com/8501694/86789015-2cfd6a00-c0aa-11ea-8b4c-959f18b232e0.png)
When `repeats=374`
![image](https://user-images.githubusercontent.com/8501694/86789078-3f77a380-c0aa-11ea-88fe-9e6aa3cf149a.png)

Building on Linux from Kode for HTML5 export.

**Comment by 5Mixer** [comment]
This is because the buffer used for g2 on Graphics4 is set to a constant of 1500 vertices, see https://github.com/Kode/Kha/blob/e96800502b192f0d8b1a51a3aa092f85f7389915/Sources/kha/graphics4/Graphics2.hx#L118, which is equivalent to 375 quads.

This behavior feels buggy, and could probably be resolved through flushing the buffer when it is full.

**Comment by RobDangerous** [comment]
Ah, that's where the number comes from. Shouldn't cause a glitch though, the buffer is flushed when it's full. Sorry, I was a little busy with the CrossCode release but I'll get to it during the weekend.
