### ISSUE TITLE
[Android-Native] Compiling for specific architecture broken

### ISSUE THREAD

**Issue by highco** [Kode/Kha#1229]
When creating an android-native build using:

`kha/make android-native --compile --arch arm7`

instead of compiling for the specified architecture (arm7), kha compiles for all architectures (arm7, arm8, x86, x86_64). This increases the compile time as well as the size of the final apk roughly by a factor of 4.

**Comment by RobDangerous** [comment]
Can not reproduce this. Tried it on Windows with latest Kha with your exact build line (but starting with node Kha/make instead of kha/make of course) and it worked correctly. The same can also be seen in the GitHub action which runs on some Linux VM.
Feel free to provide more info but I suspect a user error. Maybe your Kha is very old.

**Comment by highco** [comment]
After some fiddling around, I got it to work by deleting my build folder. Possibly because some of the files in this folder where created by an old version of Kha. Thanks for looking into it!

**Comment by highco** [comment]
@RobDangerous Thank you for looking into it! After some testing and fiddling around, I found that you need to create a debug build to reproduce the bug. Use these commands to reproduce the bug with a clean, new project:
```
Kha/make --init
Kha/make android-native --debug --compile --arch arm7
```

**Comment by RobDangerous** [comment]
Hu, that's strange, --debug does little to nothing for native targets.

**Comment by skylerparr** [comment]
Is there a way to pass the `-debug` flag to the `cpp` targets? It would be nice to print stack traces to help debug issues. I've tried adding to my `khafile.js`
```
project.addParameter('--debug')
```
and
```
project.addParameter('-debug')
```
The project builds and runs, but I'm not getting any stack traces. Is there a more `Kha` way of doing this?

**Comment by RobDangerous** [comment]
That's left to the target system IDE unless you use Linux makefiles. Is that also about Android?

**Comment by skylerparr** [comment]
I'm confused why this is up to the makefiles or ide. Shouldn't we be able
to pass this param straight to haxe during haxe code generation?

**Comment by RobDangerous** [comment]
Now I'm confused. You can pass Haxe's debug parameter directly using addParameter but with cpp you're normally getting stack traces by using a debugger and compiling in debug mode (C++ debug mode that is, has nothing to do with Haxe).

**Comment by skylerparr** [comment]
I tried adding `project.addParameter('-debug')` to the `khafile.js` and I'm still getting empty haxe stack traces when calling `haxe.CallStack.callStack()` which is what I'm interested in.

**Comment by RobDangerous** [comment]
Ah! I know nothing about that but I guess it's unrelated to Haxe's debug parameter then.

**Comment by skylerparr** [comment]
It's a compilation flag you pass to the haxe compiler https://haxe.org/manual/compiler-usage-flags.html

**Comment by RobDangerous** [comment]
I know about -debug. But I know nothing about haxe.CallStack.callStack.

**Comment by skylerparr** [comment]
You're right. I dug into it and the -debug flag is being passed to the hxml file. On a vanilla haxe project, when building with the `debug` flag for the cpp target, a binary with a `-Debug` suffix is added to the output and the stack traces can be printed. So it must be something that is setup whenever the vanilla hxcpp target is compiling a project.
