### ISSUE TITLE
Matrix transformation not working in WebGL

### ISSUE THREAD

**Issue by varomix** [Kode/Kha#125]
I'm following [Lubos tutorials](http://luboslenco.com/kha3d/#matrices)
and I noticed that the matrix transformation wasn't happening, it wasn't until I tested building a linux version that I noticed the code was actually working, just not in WebGL

![trianglemvp](https://cloud.githubusercontent.com/assets/728059/9075504/d437c83c-3ad2-11e5-8023-e9b88cb963f4.jpg)

not sure what the issue might be.

hope this helps

**Comment by varomix** [comment]
Not sure if this is related to that but I get strange results compiling most of Lubos examples,
here's the monkey 
![monkey](https://cloud.githubusercontent.com/assets/728059/9101923/25c2f3d4-3baa-11e5-8ee8-e3401dbcefc5.png)

that looks weird, same result on Linux and html5

thanks

**Comment by RobDangerous** [comment]
haxelib Kha, right? There was a change in the Matrix class that I think happened after the haxelib release. Next haxelib release is just a few days away though...

**Comment by luboslenco** [comment]
If you cant wait, these changes to Matrix4 should fix it: https://github.com/KTXSoftware/Kha/commit/797170ba9ec6c3d263770cd80f752c0d2b61577c

**Comment by varomix** [comment]
yeah is the haxelib version,
cool glad to see that is been fixed

thanks guys
