### ISSUE TITLE
[HTML5] Timetasks update less frequently on framerates above 60

### ISSUE THREAD

**Issue by zshoals** [Kode/Kha#1266]
**Describe the bug**
Timetasks appear to be updating less frequently (and also less consistently) when framerates are over 60 on HTML5. More generally, I believe this behavior will occur on any target which does not properly retrieve the monitor's refresh rate (in HTML5's case it's set to 60 by default), while the user's monitor is actually displaying 120/144/240 etc. frames per second.

For my system, which has a 120hz monitor, Windows builds do not have the same issue and appear to run at the appropriate speed regardless of the framerate. I know that Kha gets the correct frequency for this backend.

This issue was introduced with this commit: https://github.com/Kode/Kha/commit/574ce9bbccc68d590413db4eda6a999a7b8a7de7

**To Reproduce**
Using a graphical benchmark project makes it visually apparent almost instantly: https://github.com/Kode/ParrotMark works as an example. Adding enough parrots to drop the framerate from 120 to 60 results in a speed increase for all parrots bouncing around.

Steps to reproduce the behavior generally:
1. Have a 120hz monitor (you know, just have one).
2. Add a timetask that updates something at 1/60th intervals.
3. Build for HTML5 or HTML5-debug.
4. If you have some sort of visual output, observe updates occurring more frequently as you take some sort of action to reduce the framerate. 

You can probably (not totally certain but it's sensible) replicate the same situation on a 60hz monitor by doing the following:
1. Have a 60hz monitor.
2. Set get_frequency in Display.hx under the HTML5 backend to 30.
3. Do everything from step 3 in the above section.

**Expected behavior**
Timetasks run at the appropriately set update interval regardless of the framerate (within reason).

**Screenshots**
I'll add a video if you need it but that'll take me quite a bit of effort. Let me know if you absolutely need one though and I'll make it happen.

**Execution Environment:**
- Host system (where you compile your code): Windows 7
- Target system (where you run your code): HTML5 
- IDE used (if any): VSCode
- Kha revision: 1b0435fc
- Kha build output (Using Kha...): Using Kha (1b0435fc) from C:\HaxeLibraries\Kha (No errors in this section, standard shader and asset output)

**Additional context**
I'm absolutely terrible with time related stuff so I may be misdiagnosing the exact issue. However, there's definitely some sort of timetask issue that's been introduced with the recent frame scheduling improvements. Sorry if I end up off base with what's going on.

Manually setting get_frequency in Display.hx on HTML5 to 120 appears to correct the issue for me with my 120hz monitor, but is obviously not really a solution.

**Comment by juakob** [comment]
Don't know if its the best example because the movement from the parrots is frame/step/update dependent, for what I can see from the code (https://github.com/Kode/ParrotMark/blob/86bb6c68d0af2af69eb7f631ffd0bf42a4d94527/Sources/parrots/Parrots.hx#L46)  But I dont have a 120hz monitor and I couldnt notice that issue. 
try taking into account the time

var now=Scheduler.time();
var deltaTime=now-lastTime;
lastTime=now;
 for ...

parrot.x += parrot.speedX*deltaTime;
parrot.y += parrot.speedY*deltaTime;
parrot.speedY += gravity*deltaTime;

plus you need to change the valuse to pixels per second (multiply by  around 100)

**Comment by RobDangerous** [comment]
No worries, I do have a 120 Hz monitor. If this is a bug, it will be fixed pronto.

**Comment by zshoals** [comment]
The value that you get from Scheduler.time() seems correct. However, the Scheduler.realTime() value ends up incorrect and I guess this is what's actually used for timetask pacing.

I overcomplicated the original issue and should have made a more minimal example. I blame lack of sleep for this. Using this code results in two different values for Scheduler.realTime() after these frame scheduling improvements on my 120hz system: 

```hx
package;

import kha.Assets;
import kha.Framebuffer;
import kha.Scheduler;
import kha.System;

class Main {
	static var lastTime:Float = 0;

	static function update(): Void {
		trace(Scheduler.realTime() - lastTime);
		lastTime = Scheduler.realTime();
	}

	public static function main() {
		System.start({title: "Project", width: 1024, height: 768}, function (_) {
			Assets.loadEverything(function () {
				Scheduler.addTimeTask(function () { update(); }, 0, 1 / 60);
			});
		});
	}
}
```

On commit https://github.com/Kode/Kha/commit/1b0435fc2fbd466cb2b89753bc92adae34ee4a4e with get_frequency set to 60: 

```
Main.hx:12: 0.02479999999923166
Log.hx:66
Main.hx:12: 0.02479999999923166
Log.hx:66
Main.hx:12: 0.02479999999923166
Log.hx:66
Main.hx:12: 0.02479999999923166
Log.hx:66
Main.hx:12: 0.02489999998942949
Log.hx:66
Main.hx:12: 0.02470000000903383
```

On commit https://github.com/Kode/Kha/commit/1b0435fc2fbd466cb2b89753bc92adae34ee4a4e (the same commit as above) with get_frequency set to 120:

```
Main.hx:12: 0.016199999998207204
Log.hx:66
Main.hx:12: 0.01639999999315478
Log.hx:66
Main.hx:12: 0.01720000000204891
Log.hx:66
Main.hx:12: 0.016400000007706694
Log.hx:66
Main.hx:12: 0.015899999998509884
Log.hx:66
Main.hx:12: 0.016400000007706694
Log.hx:66
Main.hx:12: 0.016499999997904524
```

On commit 039aec6bc78d0d83fdd97fbb5afee201ebc3197a, pre-frame scheduling improvements, with get_frequency set to 60:
```
Main.hx:12: 0.016700000007404014
Log.hx:66
Main.hx:12: 0.015899999998509884
Log.hx:66
Main.hx:12: 0.01680000001215376
Log.hx:66
Main.hx:12: 0.0166999999928521
Log.hx:66
Main.hx:12: 0.01609999999345746
Log.hx:66
Main.hx:12: 0.01630000000295695
Log.hx:66
Main.hx:12: 0.016599999988102354
Log.hx:66
```

This example doesn't show that these values correct themselves as you approach the refresh rate but hopefully it makes it more obvious that there's an issue here.

**Comment by RobDangerous** [comment]
Well, that's normal - realTime is the actual real time as measured at the exact point in time you call that function. The html5 target currently doesn't know that it runs faster than 60 times per second so it will catch up every second frame and therefore the realTime values become strange. But realTime should explicitly not be used in conjunction with time tasks, they are based on smoothed time values aka Scheduler.time.
Looks like there's no actual Scheduler bug here after all apart from it missing the required monitor information it needs to smooth frame timing appropriately.

**Comment by zshoals** [comment]
See https://github.com/Kode/Kha/issues/1277
