### ISSUE TITLE
[html5] glBufferSubData reduces performance in Safari

### ISSUE THREAD

**Issue by sh-dave** [Kode/Kha#1269]
**Describe the bug**

After commit  https://github.com/Kode/Kha/commit/bb7176220496c78e95d86c8cf44959c5d900138f our app runs like :shit: on Safari Mobile. Every build before the mentioned commit does run fine.

**Execution Environment:**
- Host system (where you compile your code):
  - Debian 10
- Target system (where you run your code):
  - HTML build running in
    - Safari on iPad (5. Generation) (iOS 14.2)
    - Safari on iPhone 6s (iOS 13.3.1)

**Comment by sh-dave** [comment]
from IRC about parrot mark

> the normal 10k parrots run fine with reverted commit (5-10 ms per frame) and choppy with latest kha (wildly fluctuating 10-20ms)

**Comment by RblSb** [comment]
I see similar 40% frame time increase on macOS Safari for g2. Chrome/Firefox actually works better with current change.
Maybe using `bufferData` in `if (webkit)` can be a solution?

**Comment by RobDangerous** [comment]
Directly inside the backend? Silly but if it works, let's do it.
