### ISSUE TITLE
Short2Norm/Short4Norm fail on OpenGL Linux

### ISSUE THREAD

**Issue by 5Mixer** [Kode/Kha#1275]
**Describe the bug**
Short2Norm/Short4Norm seem to fail with OpenGL/Linux. Renderdoc reports all data as 0. Test case works (and shows rotating texture) with HTML5. Renderdoc VBO Data:
![image](https://user-images.githubusercontent.com/8501694/102209763-5eb21100-3f25-11eb-853c-9f68d6b2142e.png)

**To Reproduce**
Run test case https://github.com/5Mixer/ShortNormVertexDataBug

**Expected behavior**
Standard Short2Norm/Short4Norm behaviour - pass 2 or 4 two byte Shorts for each entry in the vertex structure.

**Screenshots**
HTML5 expected result:
![image](https://user-images.githubusercontent.com/8501694/102207602-720fad00-3f22-11eb-9819-4c26da06fc45.png)

**Execution Environment:**
- Host system: Arch Linux
- Kha revision: Fails with both eb60ed53 and latest 1891555b
- Kha build output (Using Kha...):
```
Using Kha (1891555b) from /home/mixer/tools/latest/Kha
Creating Kha project.
Exporting asset 1 of 1 (parrot.png).
Compiling shader 1 of 2 (texture.frag.glsl).
Compiling shader 2 of 2 (texture.vert.glsl).
Compiling shader 1 of 9 (clear.comp.glsl).
Compiling shader 2 of 9 (painter-colored.frag.glsl).
Compiling shader 3 of 9 (painter-colored.vert.glsl).
Compiling shader 4 of 9 (painter-image.frag.glsl).
Compiling shader 5 of 9 (painter-image.vert.glsl).
Compiling shader 6 of 9 (painter-text.frag.glsl).
Compiling shader 7 of 9 (painter-text.vert.glsl).
Compiling shader 8 of 9 (painter-video.frag.glsl).
Compiling shader 9 of 9 (painter-video.vert.glsl).
kincfile found.
Creating Linux project files.
Compiling...
```

**Comment by Sanva** [comment]
It doesn't work on Android either.

**Comment by Sanva** [comment]
OK, I think I've found the problem — expect something soon.
