### ISSUE TITLE
loadSoundFromPath fails on native when loading a large wav file

### ISSUE THREAD

**Issue by mundusnine** [Kode/Kha#1294]
**Describe the bug**
Calling loadSoundFromPath with a wav file yields:
![](https://media.discordapp.net/attachments/757530769315856425/812399017567715358/unknown.png?width=594&height=462)

The length of the file being loaded is 3min 35 sec

**Update**:
After some tests wav files seem to work if they are small. I will add a small wav and a big wav in repro repo. A note that loading an ogg file on native yields other errors. An ogg file was also shared for testing.

**To Reproduce**
1 - Build for windows native(default): https://github.com/mundusnine/bug-4-rob
2 - Debug in visual studio

**Expected behavior**
Loads the sound

**Screenshots**

**Execution Environment:**
- Host system (where you compile your code): Windows
- Target system (where you run your code): Windows(default)
- IDE used (if any): Visual Studio
- Kha revision: `Using Kha (f7e22b05) from d:\repos\bug-4-rob\Kha`
- Kha build output (Using Kha...):
- Application output (if it runs): `Unknown error`

**Additional context**

**Comment by RobDangerous** [comment]
So it was a 24 bit wav file. Hint for next time though - search the code for "Unknown error" and set a breakpoint.
