### ISSUE TITLE
[MacOS] dce=full does not compile

### ISSUE THREAD

**Issue by tyrondis** [Kode/Kha#1297]
**Describe the bug**
When setting `dce` (Dead Code Elimination) to `full`, my project does not compile for MacOS.

**To Reproduce**
1. Create a new Kha project
2. Add `project.addParameter('-dce full');` to `khafile.js`
3. Build for MacOS
4. Compiling fails with error message (see below)

**Expected behavior**
Compilation should work fine.

**Screenshots**
n.a

**Execution Environment:**
- Host system (where you compile your code): macOS Big Sur 11.2.1
- Target system (where you run your code): macOS Big Sur 11.2.1
- IDE used (if any): VS Code
- Kha revision: 5107d3f
- Kha build output (Using Kha...): see below
- Application output (if it runs): n/a

**Additional context**
Compile error:

```
osx-build/Sources/src/kha/Video.cpp:47:2: error: excess elements in struct initializer
        ( void (::hx::Object::*)())&::kha::Video_obj::unload,
```

**Comment by RobDangerous** [comment]
Fixed.
