### ISSUE TITLE
[Metal] Blurry shapes

### ISSUE THREAD

**Issue by tyrondis** [Kode/Kha#1298]
**Describe the bug**
When choosing Metal as a graphics backend, shapes are rendered with blurry outlines. They look sharp with OpenGL.

**To Reproduce**
1. Render a simple shape (`g2.fillRect()`)
2. Launch Kha make with metal `./Kha/make.sh -g metal osx --run`
3. Observe blurriness

**Expected behavior**
Shapes should be rendered the same way as they do with OpenGL.

**Screenshots**
n/a

**Execution Environment:**
- Host system (where you compile your code): macOS Big Sur 11.2.1
- Target system (where you run your code): macOS Big Sur 11.2.1
- IDE used (if any): VS Code
- Kha revision: 5107d3f
- Kha build output (Using Kha...): n/a
- Application output (if it runs): n/a

**Additional context**
I tried playing around with `imageScaleQuality()`, but it doesn't seem to have an effect on Metal.

**Comment by RobDangerous** [comment]
source code please, is some render target involved there? If so, this is a duplicate of https://github.com/Kode/Kha/issues/977 and if not I do not yet know what's going on.

**Comment by tyrondis** [comment]
@RobDangerous seems indeed to be a duplicate, I'm going to close this issue.
