### ISSUE TITLE
Audio and size issues。

### ISSUE THREAD

**Issue by smallcoderofme** [Kode/Kha#1342]
**1. I know that kha should automatically convert the audio from wav to ogg and mp4, but I only have ogg here, not mp4.Where did I go wrong?
2. There is also this canvas size, I set 1024x768, but it seems to be the default 800x600. code:(System.start({title: "Hello World", width: 1024, height: 768}, function(){}）**

"C:\Users\Administrator\Desktop\Empty\HelloWorld>node ../Kha/make html5
Using Kha (e26ec9f5) from C:\Users\Administrator\Desktop\Empty\Kha
Creating Kha project.
Exporting asset 1 of 3 (bullet.png).
Exporting asset 2 of 3 (playerShip.png).
Exporting asset 3 of 3 (sound.wav).
(node:8404) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or dir
ectory, stat 'C:\Users\Administrator\Desktop\Empty\HelloWorld\build\html5\sound.
mp4'
(node:8404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:8404) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code."

**Comment by RobDangerous** [comment]
mp4s can only be created when you provide the --ffmpeg option - otherwise it can only create ogg files because we do not bundle software that contains patent-problems. I don't know though why it nontheless tries to access an mp4 file - but before we check that or whatever you mean with canvas-size, please update your version of Kha. You are using a version from 1.5 years ago.

**Comment by smallcoderofme** [comment]
OK, thank you for your answer
