### ISSUE TITLE
Device independent pixels

### ISSUE THREAD

**Issue by trsh** [Kode/Kha#136]
Problem:

Multiple devices can have very different DPI and screen resolutions, and drawing, for ex., a 100px line can look huge on a small screen and to tiny to see on a large screen. In reality, mostly, we want to the the game the same on all screens.

Solution: 

Work with a unit called DIP (Device independent pixels), which takes DPI and screen size into account and calculates the real pixels.

Technically: 

Calculate the largest side (width or height) and assume it equal to 100 DIP.  Now, for ex., 50 DIP = 400 real pixels on 800px wide screen and 50 DIP = 800px for 1600px wide screen. So final real pixels given for drawing will create same feeling on all devices.

Implementation:

1) As we either use or don't use DIP, there could be a settings on turning it on or off. Then somewhere in the core it's taken into account and real pixels are given for drawing.

2) Programmer use a static function line.x = DIP(0.20);

3) Something more cooler I can't think of, because I'm not very knowing in KHA.

**Comment by RafaelOliveira** [comment]
There is a Scaler class the scales the game to all sizes. drawing with DPI would be good in vector game where you wouldn't use the Scaler, but in a game with just images, you have the same efect with the Scaler. I think Kha could expose the DPI of each platform, so we can load hd images for higher DPI, but for drawing using DPI, this can be in a extern lib.

**Comment by RobDangerous** [comment]
We have System.screenDpi() now which I think is sufficient.
