### ISSUE TITLE
kha/SystemImpl.hx:372: Could not initialize WebGL 2, falling back to WebGL

### ISSUE THREAD

**Issue by TechComet** [Kode/Kha#1374]
### Hi,

this problem when build from `code-insiders` but it's work when `play` from blender
```
kha/SystemImpl.hx:372: Could not initialize WebGL 2, falling back to WebGL.
kha/graphics4/PipelineState.hx:89: Error: Could not compile shader:
ERROR: unsupported shader version
```

**Comment by RobDangerous** [comment]
I don't know what code-insiders is and I don't do anything with Blender. Also we have issue-templates here, please use them.

**Comment by TechComet** [comment]
code-insiders

https://code.visualstudio.com/insiders
