### ISSUE TITLE
Full Screen fails to work

### ISSUE THREAD

**Issue by jrdoughty** [Kode/Kha#1378]
Unable to get full screen to work by both adding Window to the start function as:
`window: {
  windowFeatures: FeatureMinimizable,
  mode: kha.WindowMode.Fullscreen
}`

or running `Window.get(0).mode = WindowMode.Fullscreen` which yields `Uncaught TypeError: fullscreen error`

fails in both html5 and windows builds

Using VS Code on Windows 10 and Windows 11
https://github.com/jrdoughty/GitGold is the repo I'm experimenting within, but it requires other libraries, in particular my fork of echoes

**Comment by RobDangerous** [comment]
Please use the Bug report issue template when reporting a bug.
