### ISSUE TITLE
Reuse ide completion server for faster builds 

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#1391]
I think we can read `vshaxe.displayPort` in Kha vscode extension and pass it to `khamake` binary as some argument.
Then, if `build/project-target.hxml` is not changed and completion target equals compilation target, use incremental compilation instead of basic compilation.
As example, using generated `hxml` task instead of `khamake` compiles basic Kha project in `0.01s` instead of `1.7s` for me in html5. 

Also some hack to reproduce this if someone interested:
- Compile with khamake for html5 first
- Add this to `.vscode/settings.json`
```
"haxe.configurations": [
	["--cwd build", "project-html5.hxml"]
]
```
- Add this task to `.vscode/tasks.json`
```
{
  "type": "haxe",
  "args": "active configuration",
  "group": {
    "kind": "build",
    "isDefault": true
  }
},
```
- Change Completion provider from Kha to Haxe and build with this task.
- If you also launch some live-reload server, you should get instant workflow for this target

**Comment by sh-dave** [comment]
Run khamake with the `--watch` argument?

**Comment by RblSb** [comment]
Thanks, there is v2 setup, `tasks.json`:
```json
{
      "type": "shell",
      "command": "node ${command:kha.findKha}/make html5 --watch",
      "isBackground": true,
      "problemMatcher": {
        "pattern": [
          {
            "regexp": ".",
            "file": 1,
            "location": 2,
            "message": 3
          }
        ],
        "background": {
          "activeOnStart": true,
          "beginsPattern": "Haxe compilation...",
          "endsPattern": "Haxe compile end."
        }
      },
      "group": {
				"kind": "build",
				"isDefault": true
			},
      "label": "HTML5-watch"
    },
```
Lets keep this open and add some watched setups to vscode in future, i think.

**Comment by 1226085293** [comment]
> 认为我们可以读取它作为一些参数我们可以读取而不是`vshaxe.displayPort`传递给`khamake`K 文件。 然后，如果并`build/project-target.hxml`完成目标编译器的目标，使用编译器我不是基本编译器。 例如，生成`hxml`的任务而不是在 html5 中`khamake`编译基本的 Kha 项目`0.01s`而不是`1.7s`对我来说。
> 
> 如果有，还有一些可能会出现这个：
> 
> * 先用khamake编译html5
> * 添加到`.vscode/settings.json`
> 
> ```
> "haxe.configurations": [
> 	["--cwd build", "project-html5.hxml"]
> ]
> ```
> 
> * 任务任务添加到`.vscode/tasks.json`
> 
> ```
> {
>   "type": "haxe",
>   "args": "active configuration",
>   "group": {
>     "kind": "build",
>     "isDefault": true
>   }
> },
> ```
> 
> * 将完成从 Kha 更改为 Haxe 提供程序并使用此任务进行制造。
> * 如果您还启动了一些重载服务器，您应该获得此目标的即时工作流

Additional launch.json configuration
```
{
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}/build/html5/",
      "cleanUp": "onlyTab",
      "preLaunchTask": {
        "type": "haxe",
        "args": "active configuration"
      }
    }
  ],
  "compounds": []
}
```

**Comment by RblSb** [comment]
```json
		{
			"name": "HTML5-watch",
			"request": "launch",
			"type": "pwa-node",
			"program": "${command:kha.findKha}/make",
			"args": [
				"html5",
				"--watch",
				"--server",
				"--port",
				"4200",
				"--livereload"
			],
			"killBehavior": "polite"
		},
```
