### ISSUE TITLE
gl_FrontFacing yields different results on HTML5 and D3D11-Krom

### ISSUE THREAD

**Issue by MoritzBrueckner** [Kode/Kha#1405]
**Describe the bug**
When using `gl_FrontFacing` in a shader and the cull mode is set to `None`, its result differs between the html5 target and the Krom target using D3D11. In the attached example project, a blue sqare is drawn in case `gl_FrontFacing` is true (this happens on Krom) and a red square is drawn in the opposite case (happens on html5).

I noticed that front- and back-facing is set differently based on the cull mode in the backend sources for those targets (permalinks for [d3d11](https://github.com/Kode/Kinc/blob/648f6fb93e5412eac249b42148ea5da41c31866d/Backends/Graphics4/Direct3D11/Sources/kinc/backend/graphics4/pipeline.c.h#L11-L23), [OpenGL](https://github.com/Kode/Kinc/blob/648f6fb93e5412eac249b42148ea5da41c31866d/Backends/Graphics4/OpenGL/Sources/kinc/backend/graphics4/pipeline.c.h#L332-L349) and [html5](https://github.com/Kode/Kha/blob/0296e6d576332eacafa923a9de2b6354a39a2f9b/Backends/HTML5/kha/js/graphics4/Graphics.hx#L474-L485)), is this because of a different default winding order? Maybe this is related to this issue?

**To Reproduce**
Example project: [FrontFaceTest.zip](https://github.com/Kode/Kha/files/8218782/FrontFaceTest.zip)

Run the attached project. On vanilla Krom the drawn geometry is incorrect (not a rect but some line-like thingy), but you can still see the blue color. When using Armorcore, the geometry is correct and you see the blue color.

**Expected behavior**
Both targets should show the same color.

**Screenshots**
Krom:
![Krom screnshot](https://user-images.githubusercontent.com/17685000/157554001-28b2df0b-0892-4248-b913-69719f29dff6.png)

HTML5:
![grafik](https://user-images.githubusercontent.com/17685000/157554122-0f4533fc-44ad-42b7-8a82-1ae87c87b4dd.png)

The different positions of the rectangle are due to different timings when doing the screenshots, the example project is based on https://github.com/Kha-Samples/Shader-G2/ where the rectangle moves.

**Execution Environment:**
- Host system (where you compile your code): Windows 10
- Target system (where you run your code): Windows 10
- IDE used (if any): VS Codium
- Kha revision: 4c9bc0bba509c409ad503cd8e56d79c8b10bf5cd
- Kinc revision: a0f14bcbc4056f7af0248ccbce5218b0fe003a06
- Using latest Kode/Krom and Armorcore binaries
- Kha build output (Using Kha...):
  ```
  Using Kha (4c9bc0bb, M Kinc, M Tools/khamake) from [...]\Kha
  Creating Kha project.
  Compiling shader 1 of 1 (frontface_test.frag.glsl).
  Compiling shader 1 of 8 (painter-colored.frag.glsl).
  Compiling shader 2 of 8 (painter-colored.vert.glsl).
  Compiling shader 3 of 8 (painter-image.frag.glsl).
  Compiling shader 4 of 8 (painter-image.vert.glsl).
  Compiling shader 5 of 8 (painter-text.frag.glsl).
  Compiling shader 6 of 8 (painter-text.vert.glsl).
  Compiling shader 7 of 8 (painter-video.frag.glsl).
  Compiling shader 8 of 8 (painter-video.vert.glsl).
  Done.
   ```
  Kinc shows up as modified because Kha's Kinc version doesn't yet point to the latest master, the Khamake version has html5 devtools enabled upon startup. Other than that there are no changes.

**Additional context**
Original issue: https://github.com/armory3d/armory/issues/2371

**Comment by RobDangerous** [comment]
Maybe fixed in the latest Kinc-revision.

PS: To test OpenGL/Direct3D11 differences, just compile directly for OpenGL and Direct3D 11 - no need for Krom detours, that just makes it more complicated for everyone.

**Comment by RobDangerous** [comment]
Checked with your sample in Kha with Direct3D11 and a new Krom build that's actually largely unrelated to the version of Krom you are using is triggered.

**Comment by MoritzBrueckner** [comment]
Can confirm that it's fixed now, thanks a lot!
