### ISSUE TITLE
WAV sound is null with loadSoundFromPath on the linux target 

### ISSUE THREAD

**Issue by MasterIO02** [Kode/Kha#1426]
**Describe the bug**
When loading a WAV audio file with loadSoundFromPath on the linux target, the sound is null but on linux-hl the sound plays correctly. The sound loads and plays fine when it's in an Assets folder loaded in the khafile on the linux and linux-hl target.

**To Reproduce**
1. Run [this](https://github.com/Kode/Kha/files/9259380/sound-test.zip) Kha project with the linux target (change the path accordingly to where the project is located on the system)
2. See audio being null and the app crashing

**Expected behavior**
The sound is not null and the app doesn't segfault.

**Execution Environment:**
- Kha revision: dd216e8b

**Comment by MasterIO02** [comment]
The same problem occurs with loadImageFromPath, so I assume it should also occur with all the Assets.load from path functions.

**Comment by RobDangerous** [comment]
The error is in your code after all, loadSoundFromPath is asynchronous so the callback wasn't necessarily called when you start to use the sound-variable. The HL-implementation is still blocking so that's why it always works there.

**Comment by MasterIO02** [comment]
Well, that should be stated somewhere. When something works on a specific target but not the other I can't think of anything else than a bug.

**Comment by RobDangerous** [comment]
Then better not start with graphics-programming 🙃 Anyway, I think the function-signature makes it very clear already but feel free to send a pull-request that adds a comment.
