### ISSUE TITLE
macOS build fails on Apple Silicon (M1) due to linking issues

### ISSUE THREAD

**Issue by Makoren** [Kode/Kha#1432]
**Describe the bug**
Any Kha project fails to build in Xcode.

**To Reproduce**
1. Open an empty folder in Visual Studio Code and generate a new project using the `Kha: Init Project` command.
2. Press Cmd + Shift + B and select the `Kha: Build for macOS` task.
3. When the build finishes, go to the `osx-build` folder that was generated and open `New-Project.xcodeproject` in Xcode.
4. Build the project. There should be an error similar to the one in the attached screenshot.

**Expected behavior**
The build should succeed.

**Screenshots**
![Screen Shot 2022-09-04 at 5 19 47 pm](https://user-images.githubusercontent.com/37968413/188302226-542fcf48-3aa3-4083-b6e3-d1a0a6955870.png)

![Screen Shot 2022-09-04 at 5 28 48 pm](https://user-images.githubusercontent.com/37968413/188302513-3b2f845b-57a2-42f0-ac21-6e2c64f72cfe.png)

**Execution Environment:**
- Host system (where you compile your code): macOS Monterey version 12.5.1, Apple M1 processor
- Target system (where you run your code): macOS Monterey version 12.5.1, Apple M1 processor
- IDE used (if any): Visual Studio Code, Xcode
- Kha revision: 22.8.0
- Kha build output (Using Kha...): See attached screenshot.
- Application output (if it runs): N/A

**Additional context**
Both the Apple Silicon and Rosetta builds will fail due to the same error. The Apple Silicon build fails due to undefined symbols for the arm64 architecture, and the Rosetta build fails due to undefined symbols for the x86_64 architecture.

**Comment by RobDangerous** [comment]
I followed your steps exactly (even also used an M1 Mac) but couldn't reproduce the error and the GitHub CI also disagrees with you. Are you sure you created a new project and didn't just test that with some old project which still had some outdated object files lying around that confused the compiler?

**Comment by Makoren** [comment]
I just followed my own steps again, and it succeeded at building this time somehow... But I still hit an assert before a window could open. Here's the log from the report navigator:
```
Starting Kinc
2022-09-04 21:59:23.246842+1000 New Project[63309:1279453] Metal GPU Frame Capture Enabled
2022-09-04 21:59:23.247004+1000 New Project[63309:1279453] Metal API Validation Enabled
2022-09-04 21:59:23.268188+1000 New Project[63309:1279453] fopen failed for data file: errno = 2 (No such file or directory)
2022-09-04 21:59:23.268221+1000 New Project[63309:1279453] Errors found! Invalidating cache...
2022-09-04 21:59:23.488270+1000 New Project[63309:1279453] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x60000196a4e0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
deviceBufferSize = 4096

mSampleRate = 48000

mFormatFlags = 00000009

mBytesPerPacket = 8

mFramesPerPacket = 1

mChannelsPerFrame = 2

mBytesPerFrame = 8

mBitsPerChannel = 32

Starting application
validateRenderPassDescriptor:991: failed assertion `RenderPass Descriptor Validation
Either set rendertargets in RenderPassDescriptor or set renderTargetWidth and renderTargetHeight.
no sampleCount for color and raster available, either set defaultColorSampleCount or set defaultRasterSampleCount or set appropriate attachments
'
validateRenderPassDescriptor:991: failed assertion `RenderPass Descriptor Validation
Either set rendertargets in RenderPassDescriptor or set renderTargetWidth and renderTargetHeight.
no sampleCount for color and raster available, either set defaultColorSampleCount or set defaultRasterSampleCount or set appropriate attachments
'
```

**Comment by RobDangerous** [comment]
That has already been fixed, please update Kha.
