### ISSUE TITLE
VSync-like behaviour even tho it is off, but only when the App Window is focused

### ISSUE THREAD

**Issue by Simonrazer** [Kode/Kha#1434]
**Describe the bug**
Framerate of the application is limited to 60 FPS even though Vsync is off, but only if the app's Window is focused.

**To Reproduce**
Turn off VSync in your Project
Focus and Unfocus the Window
Observe the difference in FPS, it should be >60 when unfocused.

**Expected behavior**
There not to be a difference and the FPS to always be unlocked when VSync is off.

**Screenshots**
![image](https://user-images.githubusercontent.com/30187223/190917306-46af8cb3-303a-4bd8-9835-34cfa495da00.png)
High FPS numbers: Window not in focus
Low: Window in focus

**Execution Environment:**
- Host system (where you compile your code): Win 10
- Target system (where you run your code): Win 10 Krom
- IDE used (if any): VS Code
- Kha revision: https://github.com/armory3d/Kha

Minimal example:

[Main.zip](https://github.com/Kode/Kha/files/9594399/Main.zip)

**Comment by RobDangerous** [comment]
That's not the behavior I am seeing. Please don't open issues in my repositories that haven't been checked with my versions of Kha and Krom.

**Comment by Simonrazer** [comment]
That's a shame. I switched to your beautiful version of Kha/Krom, and it just as non-functional.

**Comment by RobDangerous** [comment]
So why not create an issue about that?
