### ISSUE TITLE
Kha compute shader shaderstoragebuffer compiling error

### ISSUE THREAD

**Issue by Ron5s** [Kode/Kha#1452]
When I try to build (OpenGL full build) the Kha compute shader sample in VSCode I get the following error:

Severity Code Description Project File Line  Suppression State
Error    C2039    'ShaderStorageBuffer': is not a member of 'Kore' (compiling source file Sources\src__boot__.cpp)    ComputeShader    C:\Users\Ron\Desktop\ComputeShader-master\build\windows-build\Sources\include\hxinc\kha\compute\ShaderStorageBuffer.h

**Comment by RobDangerous** [comment]
Fixed.

**Comment by Ron5s** [comment]
Thank you for fixing this so quickly.
