### ISSUE TITLE
Windows PCRE Errors

### ISSUE THREAD

**Issue by bojjenclon** [Kode/Kha#1464]
**Describe the bug**
When including certain libraries that contain regular expressions, building for Windows results in a PCRE error on run.
Examples of libraries that have thrown errors:

* https://github.com/flashultra/uuid
* https://github.com/deepnight/deepnightLibs

**To Reproduce**
1. Create a project that references one of the above libraries
2. Build for Windows
3. Run the executable
5. See error popup

**Expected behavior**
The regular expressions in question don't even seem to be referencing any unicode characters so they shouldn't cause an error.

**Screenshots**
![image](https://github.com/Kode/Kha/assets/1127397/47a473e3-7a33-40a0-b3ab-bf37c72ecae8)

**Execution Environment:**
- Host system (where you compile your code): Windows 10
- Target system (where you run your code): Windows 10
- IDE used (if any): Sublime Text 4
- Kha revision: https://github.com/Kode/Kha/commit/c932f56af3b3ca94356c98b2c7f82dbaadcaeb18
- Application output (if it runs): Error shown above

**Additional context**
This error doesn't occur when running on the HTML5 build, only on native targets. Likely due to PCRE being compiled into the CPP targets (I assume, I'm not super well versed on how its added).

**Comment by RobDangerous** [comment]
Please have a quick look at the existing issues before submitting a new one. The issue that was on the very top of the list when you submitted this one (#1461) already describes the same problem.

**Comment by bojjenclon** [comment]
I did look I just didn't realize it was the same case, as that dealt with specific strings whereas my error was showing a failed regex compilation. The error shown in the linked Issue is also different. So sorry if it's the same root cause but it was a case of "I'm not experienced enough in the error to know," not a case of not checking. :/

**Comment by RobDangerous** [comment]
It also has pcre in the title. But ok then, no worries.
