### ISSUE TITLE
Compute shaders.

### ISSUE THREAD

**Issue by e2002e** [Kode/Kha#1483]
Hello, do the compute shaders still work ?
I cannot get armory3d to write data to a 3D image.
It used to work like 4 years ago, I found a code sample for compute shaders that points to a commit of Kha (4e14edf) that does run but all my materials are shadeless.
Any help appreciated.

**Comment by RobDangerous** [comment]
I haven't heard about anything being wrong with compute shaders in Kha. Please don't open issues to ask questions.
