### ISSUE TITLE
Native Library headerCode file not found

### ISSUE THREAD

**Issue by ClintFlames** [Kode/Kha#1485]
**Describe the bug**
When compiling project with Native Library getting compilation error:
```error
../Sources/include/hxinc/SMain.h:12:10: fatal error: test.h: No such file or directory
   12 | #include <test.h>
      |          ^~~~~~~~
compilation aborted
```

**To Reproduce**
1. F1 > Kha: Init Project
2. Commands
```bash
$ git init
$ git submodule add https://github.com/Kode/Kha
$ cd ./Kha
$ ./get_dlc
$ cd ../Libraries
$ git clone https://github.com/Kha-Samples/NativeLibrary
```

2. Renaming NativeLibrary/Sources/Main.hx to SMain (both file and class).
2. Add line to Main.hx main function
```haxe
@:privateAccess trace(SMain.nativeAdd(1, 2));
```
3. Add line to khafile.js before `resolve(project);`
```haxe
project.addLibrary('NativeLibrary')
```
**Expected behavior**
Expected trace 3.

**Screenshots**
-

**Execution Environment:**
- Host system (where you compile your code): Endeavour OS (Arch Linux)
- Target system (where you run your code): Endeavour OS (Arch Linux)
- IDE used (if any): VSCode
- Kha revision: 1cd008c5
- Kha build output (Using Kha...): 
[kha_build_output.txt](https://github.com/Kode/Kha/files/13924526/kha_build_output.txt)
- Application output (if it runs): -

**Additional context**
Also i created repository with steps done https://github.com/ClintFlames/Ancnew

**Comment by RobDangerous** [comment]
"NativeLibrary" is not a library itself, it is a sample of how to integrate a native library.

**Comment by ClintFlames** [comment]
Yes, that's understandable. But isn't this a error with the "NativeLibrary" itself. test.h exists, but the compiler says it does not exist. And I just don't understand why.

**Comment by RobDangerous** [comment]
The reason it doesn't find the file is because the way you do it the C sources are not integrated into the project at all, it only adds the Haxe files. Just because a file exists somewhere on your filesystem doesn't mean a compiler will find it.

**Comment by ClintFlames** [comment]
"test.h" i was talking about is in `NativeLibrary/VeryNative/src`. Looks like [kincfile.js](https://github.com/Kha-Samples/NativeLibrary/blob/main/VeryNative/kincfile.js) is reffering to all files in `src`, so it should detect test.h too, but for some reason it doesn't.

**Comment by RobDangerous** [comment]
And it does. But as I said before, you are just adding the Haxe files, you do not use kincfile.js. Locking this, all the information you need is here already.
