### ISSUE TITLE
[HTML5] Canvas has fixed size in the browser and its scale is proportional to the windows initial size

### ISSUE THREAD

**Issue by moisesjpelaez** [Kode/Kha#1492]
**Describe the bug**
I have been using [Armory3D](https://github.com/armory3d/armory) to create a test demo, when I build the project in my main monitor it looks proportionally smaller in a web browser, since it's pixel ratio is 1.25. Another thing is that the canvas doesn't adjust according to the browser's window size, the canvas keeps a fixed size when I go full-screen or resize the browser's view.

**Expected behavior**
The canvas should have the browser's window size and resize accordingly.

**Screenshots**
Current normal size:
![image](https://github.com/Kode/Kha/assets/24682046/29b9c1d4-8340-4cb5-ac98-9b3e3c045f47)

Current full-screen size:
![image](https://github.com/Kode/Kha/assets/24682046/0e8aa36d-f3e9-4004-bfd0-a60f59d37322)

Expected normal size:
![image](https://github.com/Kode/Kha/assets/24682046/ee83ec8f-963b-440e-a5cc-b5b182a3c305)

Expected full-screen size:
![image](https://github.com/Kode/Kha/assets/24682046/0a4e0a18-0268-48a0-aa55-6db08b28c924)

**Execution Environment:**
Using Armory3D 2024.02

**Additional context**
This an [issue](https://github.com/armory3d/armory/issues/2515) related to what I'm saying, I believe this is the [commit](https://github.com/Kode/Kha/commit/a0db16de6e05e8da213a7fcb5545174efb34543c) causing it since I already fixed it manually by modifying `SystemImpl.hx`.

**Comment by RblSb** [comment]
There is example in wiki how to override html5 resizing behavior:
https://github.com/Kode/Kha/wiki/HTML5#full-page-canvas

**Comment by moisesjpelaez** [comment]
Yeah, I have seen it but doesn't `project.addDefine('kha_html5_disable_automatic_size_adjust');` mean that it should disable the default html5 automatic size adjust? (which is the one I'm reporting)

Or a better question would be, why make the current automatic size adjust the default behavior?

**Comment by RobDangerous** [comment]
Kha doesn't handle canvas-resizing because a canvas element is usually embedded into a website that also does other things so Kha can't possibly know what to do.

**Comment by moisesjpelaez** [comment]
> Kha doesn't handle canvas-resizing because a canvas element is usually embedded into a website that also does other things so Kha can't possibly know what to do.

I'm not sure I'm understand this answer and I'm wondering why the issue has been closed. The intended behavior shouldn't be to set the canvas size automatically in `SystemImpl.hx`? (which isn't doing it as expected)

I see that by modifying it as I mention [here](https://github.com/armory3d/armory/issues/2515#issuecomment-2028415334) really solves the current issue without needing to override the canvas resizing behavior manually.
