### ISSUE TITLE
Take kfx out of service

### ISSUE THREAD

**Issue by RobDangerous** [Kode/Kha#156]
- Implement AGAL support directly in krafix
- Fix all remaining problems people currently have with krafix (please list them right here)

**Comment by RobDangerous** [comment]
* Float constants in glsl have to be fixed, see KTXSoftware/krafix_tests@e647c6d773841a76349e810fb4efcf7f850519e2

**Comment by RobDangerous** [comment]
* gl_fragCoord should be supported

**Comment by peteshand** [comment]
Hey, cheers for the update. does this resolve the issue listed at: mesh.vert.agal #1?

**Comment by RobDangerous** [comment]
At some point it will. Direct SPIR-V to AGAL is almost working now and register allocations properly prefer lower values. But baseline profile is very restrictive and I might have to work on optimizations for a while to make it fit.
