### ISSUE TITLE
persisting draw even after not being called (at least on windows dx9)

### ISSUE THREAD

**Issue by wighawag** [Kode/Kha#169]
g2 seems to keep drawing itself after it is not called though the frame.g2 api.
This is shown with the use of viewport, 
I created a sample project to show the issue : https://github.com/wighawag/g2_persist
on html5 it works fine.
on windows using directx9 the issue is shown. the bar is not deleted, it even flicker. do not know why

**Comment by wighawag** [comment]
It actually affect g4 and I think this is related to the difference between dx9 and webgl. dx9 use viewport parameter to define the area affected by clear while webgl do not (always clear the full canvas).

Still there should be no flicker if the viewport is set after clear call.

Any idea?

Note: I updated the repo to show the issue on g4

**Comment by wighawag** [comment]
by setting the viewport to 0,0,frame.width,frame.height before clear and setting the viewport as wished afterward make it work.

Could this be fixed so the behaviour is same on all target ?
Maybe by making dx9 set viewport to frame on every frame. if this has no performance impact?

**Comment by wighawag** [comment]
Also why does the drawing appear again if not cleared the second time ?

**Comment by wighawag** [comment]
Actually the way to make it consistent would be set the viewport on clear for dx9 and reset to its value before. But maybe there is another way ?

**Comment by RobDangerous** [comment]
Can not reproduce, guess it was fixed at some point.
