### ISSUE TITLE
ability to change resolution and resize window on all target

### ISSUE THREAD

**Issue by wighawag** [Kode/Kha#173]
it would be great to be able to change resolution at runtime on all target where it is meaningfull
It would also be grate to be able to set the window as resizable and upon resizing the resolution would change accordingly

**Comment by dmitryhryppa** [comment]
Yep, that's will be super useful :+1:

**Comment by jefvel** [comment]
Windows native can now change resolution, so that's a step forward in this issue I guess. Could take a look at linux native later.

**Comment by Jumblemuddle** [comment]
Didn't realize this wasn't implemented yet.
Related: https://github.com/KTXSoftware/Kha/issues/400

**Comment by wildfireheart** [comment]
^ this. For me, this is a deal breaker and reason, why I cannot use Kha yet. I mean proper full screen and window resizing, at least on Windows and Mac. I'd look into it myself, but I never looked through Kha source before, so I'm not yet brave enough to try to change anything there.

**Comment by RobDangerous** [comment]
Fixed.
