### ISSUE TITLE
thx.core cannot be used a library (haxelib) 

### ISSUE THREAD

**Issue by wighawag** [Kode/Kha#185]
I can use haxelib by specifying the lib in the libraries field in project.kha but "thx.core" fails with "Warning, could not find library thx.core." even though it is present when executing "haxelib list"
I suppose this is due to thx.core having a dot ?

**Comment by RobDangerous** [comment]
On my system, haxelib renames it to thx,core (comma instead of point), I would guess the same happens for you?

**Comment by wighawag** [comment]
You are right, it does the same on my system (windows 7)

**Comment by TiZ-EX1** [comment]
I think you're on the wrong issue tracker, bud... [Here's thx.core's issue tracker.](https://github.com/fponticelli/thx.core/issues)

**Comment by RobDangerous** [comment]
I don't consider it to be a thx issue. Will change khamake to replace dots with commas the same way haxelib does.

**Comment by TiZ-EX1** [comment]
Oh, so the problem is using thx.core in conjunction with Kha? My bad.

**Comment by RobDangerous** [comment]
This was fixed a while ago.
