### ISSUE TITLE
Memory leak in JS when using DYNAMIC_DRAW indicies.

### ISSUE THREAD

**Issue by praleks** [Kode/Kha#189]
There is a bug in chrome witch produce memory leak when calling new Uint16Array(data).
This code is used in IndexBuffer.unlock, and when it called every frame - memory leaking.
Maybe there way to do one Uint16Array without renewing like in VertexBuffer Float32Array is made?

**Comment by RobDangerous** [comment]
How do you know it's leaking? Garbage collection only kicks in periodically. There is a general problem in Chrome - when you create too much garbage it can't keep up with it. Do you really just call that once per frame?
