### ISSUE TITLE
Duplicate asset id issue

### ISSUE THREAD

**Issue by sh-dave** [Kode/Kha#192]
Hi Robert,

i noticed you changed a lot about the asset loading (kha.Assets.xxx instead of the old kha.Loader class). A problem i'm know facing is the use of duplicate asset ids. In my Assets folder i have f.ex:

```
maps/classic/001.map
maps/ext01/001.map
```

will both generate a `_001_map` blob entry. Maybe you should add the relative path for the id as well, like `maps_classic_001_map`?

**Comment by RobDangerous** [comment]
Ah, this one was fixed at some point.
