### ISSUE TITLE
Stretching when rendering 3d into an image in opengl

### ISSUE THREAD

**Issue by AoE-Maniac** [Kode/Kha#208]
When rendering a 3d scene into an image and then drawing it fullscreen it is somewhat streteched in opengl@windows, in webgl it works.

See [example.zip](https://github.com/KTXSoftware/Kha/files/82615/example.zip), interesting stuff begins at line 200 in empty. When running press space to toggle between using the intermediate image and directly rendering into the frame. For the html5 target there is no difference, in opengl there is.

**Comment by RobDangerous** [comment]
Looks like this has been fixed.
