### ISSUE TITLE
Font-Names  ( very minor issue )

### ISSUE THREAD

**Issue by Justinfront** [Kode/Kha#217]
**_Font-Names  ( very minor issue )**_
Maybe this is not worth the effort to improve but if anyone else has same issue then it's atleast documented as an issue source.

Kha asset exporter does not halt and warn on unacceptable font names but fails during compile without clarifying the reason in a way that users may easily misunderstand. For example you may want to use Lato-Regular and add it to be rendered in your Render Loop:

``` haxe
    g2.font = Assets.fonts.Lato-Regular;
    g2.fontSize = 20;
    g2.drawString( 'Lato-Regular', 100, 30 );
```

But that creates an error which is not that obvious.

``` console
Creating Kha project.
Exporting asset 1 of 2 (Lato-Regular.ttf).
Exporting asset 2 of 2 (ball.png).
Assets done.
Haxe stderr: ../Sources/GraphicsKha.hx:397: characters 18-35 : kha.FontList has no field Lato
../Sources/GraphicsKha.hx:397: characters 36-43 : Unknown identifier : Regular
../Sources/GraphicsKha.hx:397: characters 8-43 : Int should be kha.Font
```

Would be ideal if the issue was flagged durring the export phase with a comment along the lines of 

```
Creating Kha project.
Exporting asset 1 of 2 (Lato-Regular.ttf).
WARNING: Lato-Regular.ttf is not a suitable font name for code access, 
suggest renaming your font to Lato_Regular.ttf
do you wish to continue y/n
```

**Comment by Justinfront** [comment]
obviously I should have realized straight away that Assets.fonts.Lato-Regular would not work but easy to not think about that when trying to follow an example you found online and extract the relevant parts for your particular use.

**Comment by RobDangerous** [comment]
But the thing is, it does work. Names like that are automatically changed (should be Lato_Regular, but you can look that up in build/whatever-resources/files.json).

**Comment by Justinfront** [comment]
ah ok I don't have completion on textmate does it autocomplete then?  But I manually just changed the name.  But this thread now documents how it does works :)

**Comment by RobDangerous** [comment]
Sorry for the late answer. Yes, it autocompletes.
