### ISSUE TITLE
[REQUEST] allow editable company signature within kha

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#254]
this is when exporting kha items. so if i export/build a iOS application. it automatically gives the company signature 'com.ktxsoftawre.APPLICATIONNAME'

there should be or could be something with the khafile.js or something similar that can override. because you cant edit on xcode once it set.

**Comment by RobDangerous** [comment]
You can edit that in Xcode. It's the plist file in Kha/Kore/Backends/{iOS|OSX}. But I agree, it should be an option in the khafile.

**Comment by lewislepton** [comment]
cool spot ;)

**Comment by lewislepton** [comment]
aye. i know about the dit part. thats fine. but i guess it more for new users etc. plus a more accesible way for people to edit ;)

**Comment by RobDangerous** [comment]
This exists nowadays via the targetOptions.
