### ISSUE TITLE
Support to include assets in libraries

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#256]
I think this was a feature in project.kha. There is a section in the wiki that talk about this
https://github.com/KTXSoftware/Kha/wiki/Libraries
I was thinking in add "this feature existed in the project.kha and will be ported to the khafile.js"

**Comment by RobDangerous** [comment]
Done, see https://github.com/Kode/Kha/wiki/khafile.js#add-a-subproject
