### ISSUE TITLE
Importing kha.Assets breaks haxe.Unserializer on flash?

### ISSUE THREAD

**Issue by sh-dave** [Kode/Kha#264]
Hi Robert,

i have something very strange going on ...

``` haxe
class Main {
    public static function main() {
        var us = haxe.Unserializer.run("oy9:testFloaty17:989.9044586345553y10:testStringy20:some%20test%20stringy7:testInty3:602g");
        trace(us);
    }
}
```

... works. But when i do

``` haxe
import kha.Assets;
```

the deserialization of testFloat's value (string "989.9044586345553") crashes the `haxe/std/haxe/Unserializer.hx`

``` haxe

function unserializeObject() {
...
var v = unserialize(); // crash here
...
}
```

with

```
[Fault] exception, information=TypeError: Error #1034: Type Coercion failed: cannot convert "989.9044586345553" to kha.Image.
```

when i comment out `kha.Assets.hx`

``` haxe
public static function loadImage(name: String, done: Image -> Void ): Void {
...
        // Reflect.setField(images, name, image);
...
}
```

it fails with 

```
[Fault] exception, information=TypeError: Error #1034: Type Coercion failed: cannot convert "989.9044586345553" to kha.Blob.
```

Commenting out that continues to Sound, Font, Video. And after that the Unserializer works again. 

(I'm actually trying out kha.StorageFile, but that doesn't load anything back on flash, and this seems to be the problem)

**Comment by RobDangerous** [comment]
Can not reproduce, does this still happen for you?

**Comment by sh-dave** [comment]
nope, seems to be working now :+1:
