### ISSUE TITLE
CJK IME Support

### ISSUE THREAD

**Issue by buckle2000** [Kode/Kha#317]
please support input method editor.
just need to pass input event to OS if ime is on.

**Comment by RobDangerous** [comment]
No experience at all with ime on my side. What OS do you need it for most? Would start with that so you can test it.

**Comment by buckle2000** [comment]
Windows. may I ask that what backend do kha use when targeting c++ platforms? sdl?

**Comment by RobDangerous** [comment]
Nooo, that is a little insulting. C++ backends are here: https://github.com/KTXSoftware/Kore/tree/master/Backends (Kore is Kha's sister project for C++ based projects, can also be used on its own)

**Comment by RafaelOliveira** [comment]
I think what needs to be implemented for this is utf8. Because IME is just a way to enter a letter that isn't available in the keyboard. Like japonese letters. With utf8 Kha will recognize the letter that is being passed.

**Comment by buckle2000** [comment]
@RafaelOliveira You are wrong. CJK have special IMEs.

**Comment by RobDangerous** [comment]
I have actually no idea whether this is working now. Maybe. Please reopen with some hints if it doesn't work.
