### ISSUE TITLE
Fresh & Empty HTML5 build not executing

### ISSUE THREAD

**Issue by echorebel** [Kode/Kha#324]
I was just trying out kha for the first time.
According docs i just run `haxelib run kha html5` on my empty project template.
I get html5 output and serve it.
Chrome 51 outputs: `kha.js:15408 Uncaught TypeError: Illegal invocation`.
Firefox 39 more detailed: `kha.js:15408:2 TypeError: 'bufferData' called on an object that does not implement interface WebGLRenderingContext.`

I tried to change background color on backbuffer.g2 to see if it's still running but without success.

Some1 has a clue or hint what's going wrong?

**Comment by RobDangerous** [comment]
Haven't seen that before. What version of Haxe do you use? Can you send me the contents of the build/html5 directory?

**Comment by echorebel** [comment]
Haxe 3.3.0, html5 folder attached:
[html5.zip](https://github.com/KTXSoftware/Kha/files/329421/html5.zip)

**Comment by DimuDesigns** [comment]
I'm having the same issue. Here's a screenshot from Chrome's developer console that shows the line of code in kha,js that generated the error:

![error](https://cloud.githubusercontent.com/assets/10224023/16359265/928af538-3afb-11e6-89cd-3d9cf22a91d2.png)

**Comment by RobDangerous** [comment]
Also on Haxe 3.3 rc1 (actual Haxe 3.3 doesn't exist yet)?

**Comment by DimuDesigns** [comment]
Yes. I also noticed that in kha.js when retrieving the webgl context the code uses "experimental-webgl". I believe that has been deprecated in favor of just plain "webgl".

**Comment by RobDangerous** [comment]
Probably, but experimental-webgl was around for so long, it will work forever.
Haxe 3.3 rc1 seems to be the problem here. Will fix this when the actual Haxe 3.3 is out. Meanwhile please use Haxe 3.2.1 or the git version of Kha which already uses a fairly recent version of Haxe (see https://github.com/KTXSoftware/Kha/wiki/Getting-Started for how to do that).

**Comment by RobDangerous** [comment]
Not sure I'll get back to the haxelib version so closing this.
