### ISSUE TITLE
Better anti-aliasing in the windows target (default graphics render)

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#335]
Below is a screenshot of the html5 and windows target. On each screen, the left text is being rendered using a BitmapText lib, and the right text is using the Kha text render. You can see that the html5 target has a slightly better render anti-aliasing than windows. This is not specific to the font render, because the BitmapText lib is just rendering the letters from a image. This is not a problem in big images, but for small things like text the result isn't good.

I'm rendering directly in the framebuffer with ImageScaleQuality.High, and using g2.begin(true, Color.White).

I was trying to create a simple rss reader when I noted this. I could use electron but I don't like the minimum size of 30mb.

(click to see better)
![screen-test](https://cloud.githubusercontent.com/assets/69374/16572961/f4a6508c-4244-11e6-80b9-ab0fbca1e624.png)

Link to download the project
https://www.dropbox.com/s/3wuqcexbuzaq97n/AATest.zip?dl=0

**Comment by dstrekelj** [comment]
I'm drawing strings to a backbuffer that is later scaled, which is causing a similar issue for smaller font sizes.

HTML5:
![](https://thumbs.gfycat.com/GlaringFlamboyantAsianlion-size_restricted.gif)

Windows:
![](https://thumbs.gfycat.com/JampackedMelodicAfricanpiedkingfisher-size_restricted.gif)

**Comment by RobDangerous** [comment]
Is this still the case? Can not reproduce.

**Comment by RafaelOliveira** [comment]
No, it's better now, thanks. HTML5 and Windows are equal now.
