### ISSUE TITLE
define sys_android instead of sys_android_native

### ISSUE THREAD

**Issue by romamik** [Kode/Kha#363]
When compiling to android-native target get sys_android defined instead of sys_android_native.

**Comment by luboslenco** [comment]
Any reasoning behind this? 'sys_android_native' define is actually a feature, makes it easy to tell them apart. Plus you can easily catch both (sys_android  || sys_android_native).

**Comment by RobDangerous** [comment]
Hmm, things will get a little convoluted when HL gets in the game. I'd prefer to only define sys_android and add sys_native or sys_hl when appropriate - that ok?

**Comment by luboslenco** [comment]
Anything that gives ability to easily tell them apart is fine by me. I guess I could just use 'cpp' define.

**Comment by romamik** [comment]
As for me I would like to have defines that match parameter of khamake.

**Comment by luboslenco** [comment]
Is that not the current situation?
node Kha/make android-native -> sys_android_native
node Kha/make android -> sys_android

Or did something change after big merge?

**Comment by romamik** [comment]
No. And that is what this issue is about. Currently (I think after updating kha to latest version) in android-native I get sys_android. 
(Sorry if my message was not clear enough)

**Comment by romamik** [comment]
And yes, if you will add sys_native it will be ok. But in any case we need to distinguish between different targets.

**Comment by RobDangerous** [comment]
Thought about it and I'll got the sys_native route because I want to support things like node Kha/make windows-steam and whatever else will come up.

**Comment by RobDangerous** [comment]
We have new defines (sys_* is now deprecated). kha_android is defined for every Android target but there's also kha_android_java and kha_android_cpp and kha_android_hl.

**Comment by sh-dave** [comment]
I guess the wiki should be updated with this new info as well: https://github.com/Kode/Kha/wiki/System-defines

**Comment by RobDangerous** [comment]
Done, thanks.

**Comment by sh-dave** [comment]
Wow, that was fast, maybe even mention it here: https://github.com/Kode/Kha/wiki/Breaking-Changes ?

**Comment by RobDangerous** [comment]
Aye!
