### ISSUE TITLE
Working with vim (vaxe)

### ISSUE THREAD

**Issue by Jumblemuddle** [Kode/Kha#365]
Has anyone had luck setting up kha to work with vaxe?

**Comment by RobDangerous** [comment]
Never tried. Also not a Vi guy. What does vaxe need to do its job?
(btw there is also a forum and a chat, don't think the issues are monitored by a lot of people)

**Comment by Jumblemuddle** [comment]
I'm not really sure. I also asked over on the vaxe GitHub issues, and @OvermindDL1 seemed to have experience with both.
https://github.com/jdonaldson/vaxe/issues/96#issuecomment-238698784
The use of node does seem a bit strange.
I'm thinking I may lean towards something like [heaps](https://github.com/ncannasse/heaps) for the sake of simplicity and compatibility with vaxe. While it would be cool, I don't really need all of Kha's platforms.

**Comment by RobDangerous** [comment]
Ah, yes, I know Mr Overmind from http://forum.kode.tech/topic/100/linux-builds

**Comment by RafaelOliveira** [comment]
When you create a project, khamake creates a hxml file for each platform, inside the build folder. 
e.g. for html5 you have build/project-html5.hxml
And I'm seeing here that vaxe supports hxml files.

**Comment by jdonaldson** [comment]
I'll talk about this more on the vaxe issue.  I don't think anything needs to change on the kha side at the moment.

**Comment by Jumblemuddle** [comment]
Alright, I managed to get stuff working, though there's definitely things that can be improved.

I created a `build.hxml` file in the root of my project.
```
-cp Sources
-cp Kha/Sources
-cp Libraries/zui/Sources
-cp Kha/Backends/HTML5
```

For the most part this caused things to work, though the asset's macros started running into issues, so I had to create an `empty-resources` folder in the root of my project (with all the contents of html5-resources).
This seems to be due to the `Kha/Sources/kha/internal/AssetsBuilder.hx$findResources()` function.
Can anyone on the Kha side think of an easy solution to make it use the `html5-resources` folder in `build`?

**Comment by RobDangerous** [comment]
Any reason you don't use the hxml file in the build folder?

**Comment by Jumblemuddle** [comment]
Was running into `Compiler error: Error: Display file was not found in class path`, so I manually made on for vaxe.

**Comment by RobDangerous** [comment]
The hxml files in build should be run from within build, might that be the problem? Concrete problem with your build file seems to be that -js is missing in your build.hxml (the defines are also missing).

**Comment by Jumblemuddle** [comment]
That makes sense. I suppose starting vim from within the build folder would probably solve the issue.
This hxml file isn't actually meant to be run, it's just for vaxe's sake.

**Comment by RobDangerous** [comment]
You could also grab the file from build and adjust the paths.

**Comment by OvermindDL1** [comment]
@Jumblemuddle Once you get it all working and set up would love a git repo or gist of the scaffolding.  :-)

**Comment by Jumblemuddle** [comment]
@OvermindDL1 Seems to be fairly simple; I could try to get something together if you'd like though.
Main things are:
- hxml file (perhaps vaxe could automatically search in the build folder for hxml files then run the `haxe --display` from within there?)
- empty-resources folder (I've just symlinked build/html5-resources to empty-resources in the root folder for now. Hopefully one of the Kha guys can think of a nicer soulution)

**Comment by RobDangerous** [comment]
Did adding the -js parameter not resolve the resources problem?

**Comment by Jumblemuddle** [comment]
Well, that did make it look at the right folder (html5-resources) though it thinks it's in the build folder.
Starting vim from within the build folder results in vaxe not finding a valid hxml file. (Even with only one in the folder) Not really sure what's going on.

**Comment by RobDangerous** [comment]
Closing this because I don't think I can help. Sorry.

**Comment by sh-dave** [comment]
I don't use vaxe, so not sure whats all involved, but maybe try with this build.hxml file in root.
It just sets the current directory to /build and calls the khamake generated one.

```haxe
--cwd build
project-html5.hxml
```

**Comment by nonameentername** [comment]
Thanks @sh-dave I got it working with the above `build.hxml` file.
