### ISSUE TITLE
Linux build, framebuffer dimensions not resizing

### ISSUE THREAD

**Issue by Jumblemuddle** [Kode/Kha#400]
On linux, the dimensions of the framebuffer don't seem to be resizing at all.

**Comment by Jumblemuddle** [comment]
Did a little digging into Kore: [System.cpp#L268](https://github.com/KTXSoftware/Kore/blob/f6dc66c81d08c105beb1cd5ed3fd505471a9473a/Backends/Linux/Sources/Kore/System.cpp#L268)
I'm not seeing anywhere where the windowimpl::windows[id]'s width would be updated. Seems like it's just set when created then never updated.
In Html's [SystemImpl.hx](https://github.com/KTXSoftware/Kha/blob/master/Backends/HTML5/kha/SystemImpl.hx#L106) on the other hand, it directly points to the canvas element, which will of course always have the current width. (I'm manually updating the canvas size to be the browser window size - it would normally be static, of course)

**Comment by Jumblemuddle** [comment]
Can't seem to get System.changeResolution to work either.

**Comment by RobDangerous** [comment]
All fixed I think.
