### ISSUE TITLE
[Request] Method to set a Matrix3 uniform in g4

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#408]
For now there is only a method to set a Matrix4.

**Comment by romamik** [comment]
Youc can easily convert matrix3 to matrix4:

		var m4:FastMatrix4 = new FastMatrix4(
			m3._00, m3._10, 0, m3._20,
			m3._01, m3._11, 0, m3._21,
			0, 0, 1, 0,
			m3._02, m3._12, 0, m3._22
		);

**Comment by RafaelOliveira** [comment]
I have a shader that converts a matrix4 to a matrix3 and do some calculations, I was trying to do this conversion outside of the shader and send only the matrix3, but there is only a method to send matrix4 in g4:
function setMatrix(location: ConstantLocation, value: FastMatrix4): Void;
The problem is not converting to matrix4, because the matrix4 is already available (it is the source matrix).
