### ISSUE TITLE
WebGL | Texture in vertex shader causes issues.

### ISSUE THREAD

**Issue by jefvel** [Kode/Kha#418]
Something causes errors when trying to read textures in the vertex shaders.
To replicate, just add a sampler2D to a vertex shader, and try to read from it:

```
uniform sampler2D texture;
void kore() {
    vec2 uv = vec2(0.5);
    vec4 thing = texture2D(texture, uv);
    gl_Position = thing;
}
```

It seems to compile into something like this:

```
...
vec4 thing = texture2DLodEXT(texture, uv, 0.0);
...
```

If I change this to a normal texture2D, I get errors with mixed up precisions on uniforms that are used in multiple shaders, like this:

Vertex shader:

```
uniform float time;
```

Fragment shader:

```
...
precision mediump float;
...
uniform highp float time;
```

The shaders work once I rewrite all the precision definitions.

**Comment by jefvel** [comment]
Here's a repo for reproducing the error.

https://github.com/jefvel/khame/tree/aad6bded99cd44116fbab4cc82e94df72e1d40d0

**Comment by jefvel** [comment]
Krom also has trouble with vertex shader textures. Getting this error during compilation: 
    
    test.vert.hlsl(2,19-25): error X3000: syntax error: unexpected token 'texture'

**Comment by RobDangerous** [comment]
Should now work for WebGL, please give it a try.

**Comment by RobDangerous** [comment]
Also implemented support in Direct3D11. Closing...
