### ISSUE TITLE
[HTML5] System.windowWidth() / windowHeight() values depend on call order

### ISSUE THREAD

**Issue by dstrekelj** [Kode/Kha#421]
**What did I want to do?**

I wanted to get the window dimensions after the system has initialised and store them for later.

**What did I do?**

I used `System.windowWidth()` and `System.windowHeight()` in the `Systeim.init()` callback argument.

**What did I expect to happen?**

I expected to get window dimensions, which are 800x600 by default.

**What actually did happen?**

I got that the window dimensions were 300x150, which is a totally unexpected and somewhat odd value. Further experimentation led me to finding out that I can get the expected window dimensions if I request window width and height after assets have been loaded.

**How can I reproduce?**

Latest KodeStudio (at the time of writing) on Windows 10 64-bit. Run the code below in KodeStudio's debugger.

``` haxe
import kha.Assets;
import kha.System;

class Main {
    static function main() {
        System.init({}, function () {
            // This returns "300, 150" in my case
            trace(System.windowWidth(), System.windowHeight());

            Assets.loadEverything(function () {
                // This returns "800, 600", which is correct (and default)
                trace(System.windowWidth(), System.windowHeight());
            });
        });
    }
}
```

**Comment by RafaelOliveira** [comment]
related: https://github.com/KTXSoftware/KodeStudio/issues/16

**Comment by Devination** [comment]
I had this same issue a few days ago although I didn't have any assets to load. Every time I hit F5 in KodeStudio I would get the wrong window dimensions.

What ended up 'fixing' it for me was making a release build for HTML5. The release build reported the correct dimensions. Then the next time I hit F5 in KodeStudio (and all future times), it also reported the correct dimensions. ¯\_(ツ)_/¯

Has anyone else been able to 'fix' it the way I did? I'm running Windows 7 64-bit with the latest KodeStudio.

**Comment by dstrekelj** [comment]
When this was brought up on IRC, @RobDangerous' response was:

> When you call windowWidth in init you're in sync with canvas creation. Maybe a setTimeout(0) would fix it.

I haven't looked into fixing it myself because I got caught up in other things (and I sort of resolved it, as stated in the issue report). Not sure how a release build would affect debugging like that, but then again, I'm not that knowledgeable about KodeStudio's inner workings.

**Comment by RobDangerous** [comment]
windowWidth/Height just returns canvas.width/height which seems to work unreliably in Electron at startup time. The setTimeout thing is the fix I'll likely integrate.

**Comment by dstrekelj** [comment]
Just to keep track of things, I've upgraded to the latest Kha and the "fix" mentioned above doesn't work anymore.

**Comment by dstrekelj** [comment]
Actually, this might not be related to the Kha version, as much as the fix not being a reliable one.

**Comment by RobDangerous** [comment]
Hmm, ugly. Have to check if there is some JS event I can wait for.

**Comment by OvermindDL1** [comment]
Setting a timeout of 0 will only cause it to wait for a single poll of the browser messaging queue, which is usually a minimum of 4ms, sometimes more.

A better thing to wait for might actually be the 'load' event, not for the page but for the specific element that you want to attach to.  That 'should' not be called until the element is entirely loaded, although you may still want to wait one render cycle after before doing things to it, via 'requestAnimationFrame' (or just setTimeout of about 30ms or more (30ms is 'usually' fine) on old browsers that do not have rAF), to make sure the DOM renderer has fully parsed the element (and its sizing) after it has been loaded.

So yes, in order, if not already loaded then wait until the 'load' event for the canvas is run, once that is run (or it is already loaded) then call requestAnimationFrame to wait for one DOM processing and render cycle to make sure the sizes are set up properly, then hope that the DOM does not do anything else weird, but that 'should' work...

Yes javascript and the DOM sucks.

**Comment by anissen** [comment]
This issue is... still an issue :/

**Comment by RobDangerous** [comment]
:/ Clever pull requests for this one are very welcome.

**Comment by anissen** [comment]
I don't suppose using the height and width arguments from `System.init` as defaults (until the proper ones can be acquired) would suffice?

**Comment by RobDangerous** [comment]
Maybe. Did some stuff, needs testing.

**Comment by romamik** [comment]
I've got some problems with current implementation. I have some custom html structure: script is in iframe and canvas is in parent document. And at least in this case canvas.onload is not fired (or may be fired before we set our handler) and thus SystemImpl.loaded is always false. 
BTW 300x150 - is default canvas size.

**Comment by romamik** [comment]
So I tried this. In debug-html5\index.html changed canvas element like this:

    <canvas id="khanvas" width="0" height="0"></canvas>

And now canvas width/height report 0 before app is initialized. So it's possible to change windowWidth()/windowHeight() like this:

    return (khanvas.width == 0 && options.width != null) ? options.width : khanvas.width;

But width/height will be reported wrong when canvas size is actually 0.

**Comment by RobDangerous** [comment]
Good enough for me, thanks.
