### ISSUE TITLE
Multiple g2 scissor rects not working properly for renderTargets

### ISSUE THREAD

**Issue by sh-dave** [Kode/Kha#424]
https://github.com/sh-dave/kha-issues/tree/master/g2-scissors

Something is wrong when i use multiple scissor rects on renderTargets.
In the provided sample, the colored rects seem to flipped upside down.

Framebuffer: red upper left, green upper right, blue full bottom, parrot center
Rendertarget: blue full top, red lower left, green lower right, parrot center

Tried in KS (latest + bundled Kha), linux (latest Kha)

**Comment by ianharrigan** [comment]
To add to the above, using latest kha and html5 and the following app:

```haxe
        var g = framebuffer.g2;
        g.begin(true, _backgroudColor);

        
        g.color = Color.Red;
        g.fillRect(0, 0, 50, 50);
        
        g.color = Color.Green;
        g.fillRect(50, 0, 50, 50);
        
        g.color = Color.Blue;
        g.fillRect(0, 50, 50, 50);
        
        g.color = Color.Yellow;
        g.fillRect(50, 50, 50, 50);
        
        
        
        g.scissor(100, 0, 25, 25);
        g.color = Color.Red;
        g.fillRect(100, 0, 50, 50);
        //g.disableScissor();
        g.scissor(0, 0, 0, 0);
        
        g.color = Color.Green;
        g.fillRect(150, 0, 50, 50);
        
        g.color = Color.Blue;
        g.fillRect(100, 50, 50, 50);
        
        g.color = Color.Yellow;
        g.fillRect(150, 50, 50, 50);
        
        
        
        g.end();
```

I get the following: 

![image](https://cloud.githubusercontent.com/assets/3024242/20581087/efbc5c0e-b1d6-11e6-9eb2-6856812a44bc.png)

Without the scissor, i get:

![image](https://cloud.githubusercontent.com/assets/3024242/20581096/f8bde228-b1d6-11e6-9a8b-3268e012c76f.png)

So it seems like the `disableScissor` call is having no effect.

**Comment by RafaelOliveira** [comment]
Checked this now, I'm using only one scissor in a render target, but the image is being cut in the wrong position in the y axis.
my test: https://www.dropbox.com/s/rr3875scvbbyr8s/TestBugScissor.zip?dl=0

**Comment by ianharrigan** [comment]
what about html?

**Comment by RafaelOliveira** [comment]
http://sudoestegames.com/play/bugscissor/

backbuffer.g2.scissor(20, 20, 300, 300);
I'm using this command, the cut starts in 20,20, but seeing in the page above, its actually cutting in a position with the wrong y. Using scissor directly in the framebuffer is ok.

```
package;

import kha.Image;
import kha.Assets;
import kha.Framebuffer;
import kha.Scheduler;
import kha.System;
import kha.Scaler;

class Project 
{
    var backbuffer:Image;

	public function new() 
    {
        Assets.loadEverything(assetsLoaded);		
	}
    
    function assetsLoaded():Void
    {
        backbuffer = Image.createRenderTarget(800, 600);

        System.notifyOnRender(render);
		Scheduler.addTimeTask(update, 0, 1 / 60);
    }

	function update():Void 
    {
		
	}

	function render(framebuffer:Framebuffer):Void 
    {
        backbuffer.g2.begin(true);

        backbuffer.g2.scissor(20, 20, 300, 300);
        
        backbuffer.g2.drawImage(Assets.images.bg, 0, 0);
        backbuffer.g2.drawImage(Assets.images.tree, 50, 50);
        backbuffer.g2.drawImage(Assets.images.tree, 450, 50);

        backbuffer.g2.disableScissor();
        
        backbuffer.g2.end();        

        framebuffer.g2.begin();
		Scaler.scale(backbuffer, framebuffer, System.screenRotation);
		framebuffer.g2.end();
	}
}
```

**Comment by RobDangerous** [comment]
@ianharrigan I think the only problem with disabling scissoring is that you call scissor(0, 0, 0, 0), isn't it? Everything else is fixed and thanks for the parrot.

**Comment by ianharrigan** [comment]
Initial test with HaxeUI and git Kha shows nothing at all, not even without a clip rect, probably something wrong in HaxeUI / my test app, ill investigate later tonight once its working and get back to you.

Thanks for the update though! 

Ian

**Comment by ianharrigan** [comment]
I get the same thing still: 

![image](https://cloud.githubusercontent.com/assets/3024242/24903653/50f2460c-1eae-11e7-8869-190d09638c2f.png)

@RobDangerous - im not quite sure i follow with "scissor(0, 0, 0, 0)", are you saying i should call that? Currently i just call disableScissor

**Comment by ianharrigan** [comment]
Might help if i uncomment the scissor code in haxeui-kha... ;)

![image](https://cloud.githubusercontent.com/assets/3024242/24903770/afec7010-1eae-11e7-96e5-8e647bc5e68f.png)

All working fine for me

**Comment by RobDangerous** [comment]
So we're done here?

**Comment by ianharrigan** [comment]
It is for me, yes, but i didnt open the issue, so cant speak for everyone. But for my part, yes, works just as it used to.

Thanks!

Ian
