### ISSUE TITLE
Mouse move jumps on touch

### ISSUE THREAD

**Issue by jefvel** [Kode/Kha#442]
The first time you touch the screen, dx and dy will be equal to x and y in the mouseMove listener function. Should this be handled in kha, so that during the first touch dx and dy will be set to 0, or is it up to the user to do this?

**Comment by RobDangerous** [comment]
Should be handled by Kha I guess. But what system are we talking about?

**Comment by jefvel** [comment]
I'm using html5. Debugging in Kode studio and browser, Windows 10.

**Comment by RobDangerous** [comment]
Are you talking about actual touch events in Win10?

**Comment by jefvel** [comment]
Yeah, should be I think. Using a touch screen, but the same thing happens on android.

**Comment by RobDangerous** [comment]
Ah, that's helpful as I don't have a win touch device. OK, will try to fix...

**Comment by jefvel** [comment]
I fixed it locally by doing something like this:

onmousedown() {
 firstDown = true;
}
onmousemove(dx, dy) {
 if(firstDown) {dx = 0; dy = 0;}
firstDown = false;
}
mouseup() {
firstDown = false;
}

it works quite nice.
