### ISSUE TITLE
dx, dy discrepancy 

### ISSUE THREAD

**Issue by jefvel** [Kode/Kha#453]
There's an issue with the dx and dy values on mouse move in Chrome and Edge, http://i.imgur.com/s4xLNWY.gifv

However, it works properly in Electron and Firefox, 
http://i.imgur.com/vTk6MN6.gifv

The issue seems to be with when the screen size is not set to 100% in the display settings in Windows. When it's set to 100% it works the same way in chrome as in electron.

**Comment by RobDangerous** [comment]
Hey, I think this is fixed.
