### ISSUE TITLE
Expose more properties of the Displays from Kore

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#471]
The properties that are listed here:

https://github.com/Kode/Kore/blob/master/Backends/Windows/Sources/Kore/Display.h
https://github.com/Kode/Kore/blob/master/Backends/Linux/Sources/Kore/Display.h

like the position of the display and is if primary.

**Comment by sh-dave** [comment]
@RafaelOliveira this can be closed now i guess?
