### ISSUE TITLE
[HTML5] Game is "accelerating" when the browser is switched to another tab

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#472]
If I switch to another tab, stay some time there, and then switch back, the game will play accelerated like it was stopped and now was trying catching up the frames that wasn't played when the tab was not visible. The same happen in KodeStudio if the window is minimized for some time.

The code is simple and is below:

https://www.dropbox.com/s/y6v3jik910872r2/TestSpeed.zip?dl=0

```haxe
package;

import kha.Framebuffer;
import kha.Scheduler;
import kha.System;

class Project 
{
	var x:Float;	

	public function new()
	{
		x = 0;		

		System.notifyOnRender(render);
		Scheduler.addTimeTask(update, 0, 1 / 60);
	}

	function update(): Void 
	{
		x += 1;
		if (x > 640)
			x = 0;
	}

	function render(framebuffer:Framebuffer):Void 
	{
		var g2 = framebuffer.g2;

		g2.begin(true, kha.Color.Black);
		g2.color = kha.Color.Red;
		g2.fillRect(x, 100, 100, 100);
		g2.end();
	}
}
```

**Comment by RobDangerous** [comment]
Thought we fixed that. Are you on the latest revision?

**Comment by RobDangerous** [comment]
Minutes before is totally sufficient. Will have a close look at that tomorrow.

**Comment by RobDangerous** [comment]
Works as expected for me, it makes up for 0.5 seconds max (you can tweek this value here: https://github.com/Kode/Kha/blob/master/Sources/kha/Scheduler.hx#L61) which I think is OK. Is that the same you are seeing? We had a bug before where it tried to make up for the complete time it was inactive.

**Comment by RafaelOliveira** [comment]
I recorded a video. This was after leave the browser on another tab for some time. The strange thing is, for what I remember this wasn't happening before even on 0.5 sec, so this was introduced to fix another thing?

https://www.youtube.com/watch?v=nlUAQCyVcjI

**Comment by RobDangerous** [comment]
The 0.5 seconds speedup always happened, it's part of Kha's frame pacing system. But I can't reproduce what happens in your video. What browser is this? Can you upload your test project?

**Comment by RafaelOliveira** [comment]
Google chrome in Windows 10, version 55.0.2883.87 m
There is nothing special in the code, is the same as in the first post.

https://www.dropbox.com/s/y6v3jik910872r2/TestSpeed.zip?dl=0

**Comment by RafaelOliveira** [comment]
http://sudoestegames.com/play/test-speed/

**Comment by OvermindDL1** [comment]
> http://sudoestegames.com/play/test-speed/

Huh, fascinating...  I confirm in Chrome, Firefox, and Edge.  Just open the link, switch tab in the same window for a minute, then switch back and it goes into hyperspeed for a few seconds until it catches up....

**Comment by RafaelOliveira** [comment]
Also in chrome for android if I minimize the browser

**Comment by RafaelOliveira** [comment]
@OvermindDL1 can you download the code and test in your machine?

**Comment by OvermindDL1** [comment]
> @OvermindDL1 can you download the code and test in your machine?

Not currently, I'm at work and was just catching up on my Github notifications.  :-)

If you need further testing then feel free to poke me tonight and I might be able to.  But without looking at the Kha code for how it registers those I am wondering if it is getting hit by the browser throttling a message to only handle 1 a second then catches all of them up later.  This should not happen if `requestAnimationFrame` was being used though I'd think, but without checking the code I cannot confirm...

**Comment by RobDangerous** [comment]
No worries, can now reproduce the problem...

**Comment by OvermindDL1** [comment]
Cool, I did take a quick look just now, in Javascript in the `kha_Scheduler.executeFrame` function the `while(kha_Scheduler.timeTasks.length > 0) {` loop seems to be calling the users 'update' function a *LOT*, apparently has an unbounded delta that it keeps counting up to until it catches up...

**Comment by RobDangerous** [comment]
Accidentally deleted a line when I fixed something else this week and used a project which was too resource demanding for testing so it didn't show up.

**Comment by RafaelOliveira** [comment]
Its working know, thanks.
