### ISSUE TITLE
[HTML5] audio1.AudioChannel.finished is not working in Chrome for Android

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#473]
In both Desktop and mobile when call AudioChannel.finished they check if the position of the audio is in the end, but the function AudioChannel.stop() in desktop puts the position in the end and in mobile it puts the position at 0, so in mobile AudioChannel.finished returns a wrong value.

**Comment by RobDangerous** [comment]
Same story, please test.

**Comment by RafaelOliveira** [comment]
Tested and is working too, thanks!
