### ISSUE TITLE
[HTML5] audio1.AudioChannel.play() is not working after AudioChannel.stop() in Desktop

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#474]
Calling AudioChannel.play() after AudioChannel.stop() works on Chrome for Android, but not in Chrome for Desktop.

**Comment by RobDangerous** [comment]
Speculative fix, please test (don't want to turn audio on right now).

**Comment by RafaelOliveira** [comment]
Tested and it's working, thanks!
