### ISSUE TITLE
[HTML5] audio1.Audio in Chrome for Android fails to play a different audio file after the first

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#476]
The first time I play a audio on a mobile browser (Chrome) is ok, I saw that internally Kha uses the function catchUp() to play the sound in the first touch. After that the file that was played will play always, but if I try to play another audio file, the audio fail and Chrome notify on console:

"Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.".

So, it seems all audio files needs to be played inside a user gesture, at least once. I was thinking if could be possible to "unlock" all audio files inside the catchUp() function, but only play actually the sound that was requested, the others files would be something like, play and then stop. 

Another problem would be that for this the sound system would need to maintain a list of all the audio files that was loaded but wasn't played for the first time, to unlock them in the next touch.

Something to note, I researched how Phase does this, it uses two systems, the "AudioTag" (that is probably the AudioElement), and WebAudio api. And in chrome for android the sound started to play without touch, but I dont know exactly if this works ok in all browsers or need adjustments (the WebAudio). There is even code for different versions of ios in the phaser code https://github.com/photonstorm/phaser/blob/v2.6.2/src/sound/SoundManager.js#L283 (but I dont know what sound system this is referring).

I'm not used to write much in english, so I hope the text isn't confuse!

**Comment by RafaelOliveira** [comment]
Another idea that would mitigate this (but not resolve), would be "Audio Sprites". The dev would put all the audio inside one file, then Kha would have a function like audio.playPeriod(start:Float, duration:Int, loop:Bool). So all the audio would be loaded in the first touch, but this would be a suggestion of what to do on mobile.

**Comment by RobDangerous** [comment]
I think none of that will work probably so the plan is to build a third audio backend specifically for mobile, based on WebAudio, automatically started on the first user gesture but using WebAudio on a higher level than the current WebAudio backend (e.g. not mixing audio in software) for better performance.

**Comment by RobDangerous** [comment]
And it's done. For iOS support make sure to use ffmpeg when running khamake.

**Comment by RafaelOliveira** [comment]
Thanks, in android now it start to play even without the first touch and I noticed the audio in loop now play without pauses (before there was some miliseconds after start again).

**Comment by wighawag** [comment]
@RobDangerous What do you mean by " For iOS support make sure to use ffmpeg when running khamake." ?

Is it for iOS browsers ?

What happen if we do not use ffmpeg? an error on build ?

**Comment by RafaelOliveira** [comment]
This change is for html5 in mobile browsers, the code is different for desktop browsers, because mobile browsers has some limitations. The ffmpeg is because ios doesnt support ogg, so Kha generate the file that is supported (maybe mp4 with aac, but I doesnt have a iphone to test).

**Comment by wighawag** [comment]
ok, so maybe Khamake should output a warning when ffmpeg is not used

**Comment by RobDangerous** [comment]
Software fallback is coming soon.
