### ISSUE TITLE
Windows shader compiler error

### ISSUE THREAD

**Issue by IMFUZZ** [Kode/Kha#487]
```shell
Gunther@DESKTOP-7VBSKF0 C:\Repos\kha_experimentation
> make
Creating Kha project.
Exporting asset 1 of 1 (crate.png).
Compiling shader 1 of 8 (painter-colored.vert.glsl).
Shader compiler error.
```
Created a project using Kode studio a couple of days ago. Compiled it on windows target and ran it using the HTML5 debugger but since yesterday (16/01/17) it stopped compiling to other platform than HTML5. Tried compiling the project on another machine/creating another projet but still nothing.

Tried to compile on windows 10,
still haven't tried compiling on linux, will try soon.

**Comment by RobDangerous** [comment]
What is your exact khamake call? What is "make"?

**Comment by IMFUZZ** [comment]
The make is the make.bat from the root directory of Kha. The command written here is not exactly correct, it should be something like make --compile I guess. Either way, I get the same error when compiling using Kode Studio with the path to the same Kha directory.

**Comment by IMFUZZ** [comment]
I was able to compile the project on Linux but I would get a black screen when running the application. The terminal did not show any particular message.

**Comment by RobDangerous** [comment]
Can you upload the project or ideally a smaller version of the project which also exhibits those problems?

**Comment by IMFUZZ** [comment]
Sure, my project is here https://github.com/IMFUZZ/kha_experimentation, it's quite small actually. Thanks a lot for your time. Not having a "working" project is the only thing keeping me from jumping head first into kha!

**Comment by RobDangerous** [comment]
Finally tried it but can not reproduce the problem. Is this still happening?
