### ISSUE TITLE
Instancing is broken

### ISSUE THREAD

**Issue by dmitryhryppa** [Kode/Kha#490]
I think something broken with instancing. 
I got just a yellow screen with that example: 
https://github.com/AoE-Maniac/Kha-InstancedExample

Tested on windows, with GL and D3D9 targets.

**Comment by luboslenco** [comment]
Looks like the depth is not cleared.

Try changing 
https://github.com/AoE-Maniac/Kha-InstancedExample/blob/master/Sources/InstancedExample.hx#L174

to

`g.clear(Color.fromFloats(1, 0.75, 0, 1), 1.0);`

**Comment by dmitryhryppa** [comment]
Yeah, that's helped, thanks :D
But still have some strange behaviour on D3D9 target.

So, when I run it on D3D9 - it goes very-very slow and sometimes it's freezing my OS. But everything goes ok with GL.
