### ISSUE TITLE
D3D11 blank window

### ISSUE THREAD

**Issue by dmitryhryppa** [Kode/Kha#492]
Hey ;)
Here is I have a small example. 
It's working fine on GL and D3D9 targets, but not working on D3D11 target.
I got just a blank screen. 

Windows 10 / gtx970

https://www.dropbox.com/s/jvatgck7eid2wme/d3d11_issue.zip?dl=0

**Comment by dmitryhryppa** [comment]
Looks like the same:
https://github.com/Kode/Kore/issues/137

**Comment by RobDangerous** [comment]
Yes, try to adjust the depth clear value.

**Comment by dmitryhryppa** [comment]
I think I found something interesting
If you will draw everything directly into **framebuffer** - you will get a blank window
But if you will draw into **rendertarget** - it will work. But without depth.
Even if you have **DepthStencilFormat.DepthAutoStencilAuto** setting and **depthWrite = true**;

**Comment by RobDangerous** [comment]
All fixed.
