### ISSUE TITLE
Error compiling in Linux

### ISSUE THREAD

**Issue by gabdab** [Kode/Kha#498]
git clone --recursive https://github.com/Kha-Samples/TPlayer.git --depth=1
node Kha/make html5
node Kha/make flash
node Kha/make linux

[SyntaxError: Unexpected token =]

**Comment by RobDangerous** [comment]
Sorry, your version of node.js is outdated.

**Comment by gabdab** [comment]
downloaded from : https://nodejs.org/en/download/
now working for html5
But android : { Error: ENOENT: no such file or directory, stat '/home/gabriele/hd2/Lavoro/Lavoro_1/haxe/kha-examples-master/TPlayer/Kha/Tools/khamake/out/Exporters/Data/android/build.gradle'
