### ISSUE TITLE
Android not compiling

### ISSUE THREAD

**Issue by gabdab** [Kode/Kha#499]
{ Error: ENOENT: no such file or directory, stat '/home/gabriele/hd2/Lavoro/Lavoro_1/haxe/kha-examples-master/TPlayer/Kha/Tools/khamake/out/Exporters/Data/android/build.gradle'

**Comment by RobDangerous** [comment]
That looks like an earlier bug, is your Kha up to date? See https://github.com/Kode/Kha/wiki/Getting-Started at the bottom.

**Comment by gabdab** [comment]
Doing a plain haxelib install kha seems a route to avoid .
Following [(https://github.com/Kode/Kha/wiki/Getting-Started)] lines do work flawlessly .
I still need to install gradle and compile , but android project is created fine .

**Comment by RobDangerous** [comment]
Aye, please avoid the haxelib version, it's totally outdated (and I can't update before the next official Haxe release without causing chaos).
