### ISSUE TITLE
Support for glsl arrays and struct

### ISSUE THREAD

**Issue by wighawag** [Kode/Kha#500]
Currently the shader compiler do not complain on arrays and struct but the parser do not differentiate them (at least in the files.json output) and there is no g4 method to set them

**Comment by wighawag** [comment]
I guess setting them works using "<array>[<index>].<struct member>" , right ?

it would be nice if kha api supported arrays, struct and arrays of struct directly via haxe types.

For my use case, khage will take care of that but I would need krafix to output proper type and access name so that I can generate the correct code

Currently for array it give out the type of the array elements and does not specify it is an array of that type

and for an array of struct it gives ```"type": "unknownarray"```

**Comment by dmitryhryppa** [comment]
I'm currently using arrays of struct like that:

shader part:
```
struct LightStruct {
    vec3 position;
    vec3 color;
    float power;
    float radius;
};

const int maxLights = 32;
uniform LightStruct lights[maxLights ];
```

haxe part:
```
//get array of struct item property:
pipeline.getConstantLocation("lights[" + i + "].radius");
```

**Comment by wighawag** [comment]
That's what I thought, thanks for letting me know. I still need khamake/krafix to output the proper types in files.json  so khage can know how to deal with them.
