### ISSUE TITLE
android-native on Linux

### ISSUE THREAD

**Issue by gabdab** [Kode/Kha#502]
I've been using Ndk for a while in cocos2d-x and haxeflixel ..
Should I export some sort of environment variable ?
I am unaware of Ndk download option in android sdk manager .

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> NDK not configured. 
  Download it with SDK manager.)
```

**Comment by RafaelOliveira** [comment]
You can download the lastest version of the NDK from the android site. When you create a android-native project and open in android studio, it will ask you about the path of the NDK.
To create a android-native project, in Kode Studio press F1 -> Compile Kha Project -> Android (native)

**Comment by RobDangerous** [comment]
Kha creates standard Android Studio/Gradle projects which can be loaded and build in Android Studio (which has an option to download the ndk) or build on the command line using Gradle. I'm not sure if cocos/flixel already use gradle based projects, maybe they still use earlier Android build systems and things behave differently for that reason. Any Android Gradle docs should help you out with the necessary env vars.

**Comment by gabdab** [comment]
Flixel uses lime compile system .
Cocos2d-x is based off CMake .
Still trying to grasp android studio workings ..

**Comment by RobDangerous** [comment]
But what do lime and/or cmake use? Both are just meta-buildsystems themselves.

**Comment by gabdab** [comment]
Ndk for Android ..

**Comment by RobDangerous** [comment]
You can't just use that directly, Android is sadly a little more complex.

**Comment by RobDangerous** [comment]
Nothing left to do here I guess. If somebody disagrees, please reopen.
