### ISSUE TITLE
html5 | full window canvas broken

### ISSUE THREAD

**Issue by JeriXNet** [Kode/Kha#503]
I've updated my kha submodule recursively today and got my html5 build broken.
`System.windowWidth()` and `System.windowHeight()` as well as `framebuffer.width` and `framebuffer.height` now returning dimensions from `System.init()` and not from actual html calculated canvas dimensions as before.
I'm using this html template:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>title</title>
    <style>html, body { width:100%; height:100%; margin:0; }</style>
</head>
<body>
    <canvas id="khanvas" style="width:100%; height:100%; display:block;"></canvas>
    <!-- <div id="haxe:trace" style="display: none;"></div> -->
    <script src="kha.js"></script>
</body>
</html>

```

**Comment by JeriXNet** [comment]
It's working as expected with these changes:
Kha/Backends/HTML5/kha/SystemImpl.hx:298
this
```js
		canvas.onload = function () {
			loaded = true;
		};
```
changed to this
```js
			loaded = true;
```

**Comment by romamik** [comment]
This is caused by things i wrote about here: https://github.com/Kode/Kha/issues/421#issuecomment-276647674

**Comment by RobDangerous** [comment]
Reverted the non-working onload mumbojumbo.
