### ISSUE TITLE
windows | haxe resources compilation error

### ISSUE THREAD

**Issue by JeriXNet** [Kode/Kha#504]
I'm trying to use embedded haxe resources like this:
```js
let project = new Project('Empty');
project.addSources('Sources');
project.addParameter('-resource ../filename1.ext');
project.addParameter('-resource ../filename2.ext');
resolve(project);
````
It's working with html5 js and failing with windows on cpp compilation:
```
node Kha/make --run
```
```
"c:\KhaEmpty\build\windows-build\Empty.vcxproj" (default target) (1) ->
(ClCompile target) ->
 c:\khaempty\build\windows-build\sources\src\resources\__res_0.cpp(7837): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "hxcpp.h"' to your source? [c:\KhaEmpty\build\windows-build\Empty.vcxproj]
 c:\khaempty\build\windows-build\sources\src\resources\__res_1.cpp(19012): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "hxcpp.h"' to your source? [c:\KhaEmpty\build\windows-build\Empty.vcxproj]
```

**Comment by JeriXNet** [comment]
Could you please give me any feedback on this issue?
I'm not that experienced with cpp compilation so I can't understand the real problem.
So I really need resource embedding in my project and I don't want to implement hacky and dirty workarounds...

**Comment by RobDangerous** [comment]
Cross compiled Haxe files are compiled using precompiled headers to speed things up - doesn't work with resource files though because Haxe doesn't put #include hxcpp.h on top of those files (which makes sense because they don't include anything at all). I now exclude them from using precompiled headers.

**Comment by JeriXNet** [comment]
oh, thanks!
when you are going to update khamake in Kha so I can check it's working?

**Comment by RobDangerous** [comment]
Just git pull khamake inside of Kha manually.

**Comment by JeriXNet** [comment]
it's working now, thanks!

**Comment by RafaelOliveira** [comment]
@ianharrigan is this what haxeui was needing to compile to Windows?

**Comment by ianharrigan** [comment]
Yes. That looks promising. I'm in the UK till next Thursday, but I'll check when I get back.
