### ISSUE TITLE
[BUG] latest update has damaged things

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#505]
on just doing the latest update
https://github.com/Kode/Kha/tree/929d73e8c918e0b26791b0896c45c7e414265680

its now shit the bed on running in KS, here are screen shots showing errors

this pops up right away when opening KS
<img width="1292" alt="screen shot 2017-02-01 at 13 36 28" src="https://cloud.githubusercontent.com/assets/11299322/22508852/bc302aa8-e883-11e6-88ec-4cc7ab3c4919.png">

this is when you try to run anything
<img width="699" alt="screen shot 2017-02-01 at 13 36 58" src="https://cloud.githubusercontent.com/assets/11299322/22508857/bf658f4c-e883-11e6-90d7-d041a26bff1f.png">

**Comment by romamik** [comment]
This is caused by things i wrote about here: https://github.com/Kode/Kha/issues/421#issuecomment-276647674

**Comment by RobDangerous** [comment]
No, this is caused by Haxe 3.4 linking dynamically to libpcre.

**Comment by romamik** [comment]
I've posted to wrong issue. I've deleted wrong post and made new one: https://github.com/Kode/Kha/issues/503#issuecomment-276703624

**Comment by RobDangerous** [comment]
For reference: https://groups.google.com/forum/#!topic/haxelang/ltw4Eiv6xsQ
