### ISSUE TITLE
Shader output different between HTML5/OpenGL and Directx9

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#507]
I have a fragment shader that the output in HTML5/OpenGL is different from the default graphics in Windows (Directx9).

There is a simple animation with the time, but I coded the project to have the same uniforms like in the default code in this page: http://editor.thebookofshaders.com (I removed the mouse for this test). I could had removed the animation, but I want to show that the output in html5/opengl is the same as in the page.
There is some colors changing in opengl, but in Direct there is only one color changing from blue to black.

Also, Directx is showing this in the console:
Could not find texture tex.

(but I'm using the painter_colored_vert)

html5/opengl in the left and directx in the right
![test_shader](https://cloud.githubusercontent.com/assets/69374/22561911/8879c640-e961-11e6-986d-b9081f94c28a.png)

project:
https://www.dropbox.com/s/1w2ben75koqn1pj/TestShader.zip?dl=0

```haxe
package;

import kha.Color;
import kha.Framebuffer;
import kha.Scheduler;
import kha.System;
import kha.Shaders;
import kha.math.FastVector2;
import kha.graphics4.PipelineState;
import kha.graphics4.BlendingFactor;
import kha.graphics4.VertexData;
import kha.graphics4.VertexStructure;
import kha.graphics4.ConstantLocation;

class Project 
{
	var pipeline:PipelineState;

	var width:Float;
	var height:Float;
	var resolution:FastVector2;
	
	var resolutionID:ConstantLocation;
	var timeID:ConstantLocation;

	public function new():Void
	{
		setupShader();

		width = System.windowWidth();
		height = System.windowHeight();
		resolution = new FastVector2(width, height);		

		System.notifyOnRender(render);
		Scheduler.addTimeTask(update, 0, 1 / 60);
	}	

	function setupShader():Void
	{
		pipeline = new PipelineState();
		pipeline.vertexShader = Shaders.painter_colored_vert;
		pipeline.fragmentShader = Shaders.shader_frag;

		var structure = new VertexStructure();
		structure.add("vertexPosition", VertexData.Float3);		
		structure.add("vertexColor", VertexData.Float4);

		pipeline.inputLayout = [structure];

		pipeline.blendSource = BlendingFactor.SourceAlpha;
		pipeline.blendDestination = BlendingFactor.InverseSourceAlpha;
		pipeline.alphaBlendSource = BlendingFactor.SourceAlpha;
		pipeline.alphaBlendDestination = BlendingFactor.InverseSourceAlpha;		

		pipeline.compile();

		resolutionID = pipeline.getConstantLocation('u_resolution');		
		timeID = pipeline.getConstantLocation('u_time');
	}

	function update(): Void 
	{
		
	}

	function render(framebuffer:Framebuffer):Void
	{
		framebuffer.g2.begin(true, Color.White);
		
		framebuffer.g2.pipeline = pipeline;
		framebuffer.g4.setVector2(resolutionID, resolution);		
		framebuffer.g4.setFloat(timeID, Scheduler.time());

		framebuffer.g2.fillRect(0, 0, width, height);
		framebuffer.g2.end();
	}
}
```

```glsl
#ifdef GL_ES
precision mediump float;
#endif

uniform vec2 u_resolution;
uniform float u_time;

void main() {
    vec2 st = gl_FragCoord.xy/u_resolution.xy;
    st.x *= u_resolution.x/u_resolution.y;

    vec3 color = vec3(0.0);
    color = vec3(st.x,st.y,abs(sin(u_time)));

    gl_FragColor = vec4(color,1.0);
}
```

**Comment by dmitryhryppa** [comment]
I think that's because of gl_FragCoord. Because there is no similar thing in HLSL. 
But I may be wrong.

**Comment by wighawag** [comment]
yes that would not work.

What you can use instead of fragCoord is to have a new vertex shader that do the same thing as painter_colored_vert but pass the vertexPosition as a varying to the fragment shader. This will be your fragCoord.

**Comment by RafaelOliveira** [comment]
yeah @dmitryhryppa @wighawag you are right. I passed the vertexPosition from the vertexShader as fragCoord, and that worked. The colors are now upside down, but are equal in both directx and opengl, so I only need to mader other adjustments to the code.
The message "Could not find texture tex." is still showing in the console with directx, so its seems to be a different problem, but its not affecting the app.
