### ISSUE TITLE
All I get is enigmatic "Haxe compiler error." 

### ISSUE THREAD

**Issue by b005t3r** [Kode/Kha#509]
This is all I get when trying to build an empty project that I just created with:
```node /usr/local/lib/haxelib/kha/git/make --init```

```
node /usr/local/lib/haxelib/kha/git/make html5
Creating Kha project.
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Haxe compiler error.
```

When I try to run it with Kode Studio, with the github version of kha set, I get a similarly enigmatic output:

```
Using Kha from /usr/local/lib/haxelib/kha/git
Creating Kha project.
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Launch canceled.
```

That's it :)

PS. I'm on Mac OS X El Capitan 10.11.6 if that matters.

**Comment by RobDangerous** [comment]
Please avoid mixing the haxelib version and the git version. Don't think that's the issue here though. Is that some older version of macOS?

**Comment by b005t3r** [comment]
Wow, that was fast. It's Mac OS X El Capitan 10.11.6 if that matters.

> Please avoid mixing the haxelib version and the git version.

What do you mean? I downloaded kha using haxelib, I'm not supposed to do that? I was following Lewis Lepton's tutorial (which is a bit outdated currently).

BTW, is there something like a stable kha version I should maybe use? Something not too outdated, but stable enough to use?

**Comment by RobDangerous** [comment]
Ya, you're not supposed to use the haxelib version, it's super outdated and the git version doesn't mix with it. Will try to get old macOS running again later today. The git version is usually stable.

**Comment by b005t3r** [comment]
OK, I thought haxelib can keep different versions of a given lib at the same time - currently kha version in haxelib is set to 'git', it has a separate subdirectory and all. Is that going to cause problems in the future? :)

BTW, I'm usign haxe 3.4.0 and haxelib 3.3.0 (for some reason versions are not the same?).

**Comment by b005t3r** [comment]
PS. Looks like it is possible to store different versions of a given lib using haxelib:

```
ls -l /usr/local/lib/haxelib/kha/
total 0
drwxr-xr-x  18 root  wheel  612 Feb  4 17:26 16,1,2
drwxr-xr-x  22 root  wheel  748 Feb  4 11:23 git
```

**Comment by RobDangerous** [comment]
Not sure that works in all situations, it was never meant to be used like that. Sure doesn't work if you try to use the haxelib kha commands. Haxe and haxelib versions do not matter if you use Git Kha (uses its own embedded version of Haxe).

**Comment by b005t3r** [comment]
All right, understood. Anything I can do to help you find and solver the problem? Is there a way to turn a more verbose mode in kha make, to give you any details?

**Comment by RobDangerous** [comment]
I think I already know what to do. Just have to get the Mac...

**Comment by b005t3r** [comment]
All right. Just to be sure I downloaded Kha from github the classic way and tried to build the project and got the same result.

Also node.js version I have installed is 6.9.5.

**Comment by RobDangerous** [comment]
Seems to be trickier than I thought. For reference, this is the problem: https://groups.google.com/forum/#!topic/haxelang/ltw4Eiv6xsQ
If there's no fix by tomorrow I'll revert the macOS version to 3.4rc2 until there is one.

**Comment by b005t3r** [comment]
Ah, I see, it's the problem with the haxe itself. So which version of haxe do you use with kha? The one included with the github version does in fact crush:
```
~/Documents/haxe/kha/Kha/Tools/haxe/haxe-osx 
Illegal instruction: 4
```

**Comment by RobDangerous** [comment]
It's a slightly customized version of 3.4. You can drop in a regular Haxe 3.4 and most things will work.

**Comment by RobDangerous** [comment]
I temporarily replaced it with the official Haxe 3.4 macOS binary - does that work for you?

**Comment by b005t3r** [comment]
Yes, it looks like it works now - I'm able to launch ```~/Documents/haxe/kha/Kha/Tools/haxe/haxe-osx``` and Kode Studio with this directory set up works as well.

**Comment by Turboconnard** [comment]
Hi, I think i have the same issue on linux...

git clone --recursive https://github.com/KTXSoftware/Empty.git
node Kha/make html5   
`Creating Kha project.
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Compiling code.
Haxe compiler error.
`
node 7, ubuntu 14 :/

**Comment by RafaelOliveira** [comment]
@Turboconnard the kha version in the Empty project is 7 months old. You can update it with
git submodule foreach --recursive git pull origin master
See here https://github.com/Kode/Kha/wiki/Getting-Started

**Comment by Turboconnard** [comment]
yep, you were right, HTML5 compiles, g++ is compiling... and everythings looks fine !
Thanks @RafaelOliveira !

**Comment by RobDangerous** [comment]
All done here I think, macOS binary is compiled on 10.10 from now on.

**Comment by b005t3r** [comment]
Hey, and it didn't even take that long! 😄
