### ISSUE TITLE
Can't draw an image

### ISSUE THREAD

**Issue by MrSylar59** [Kode/Kha#510]
Hi, I've been trying to simply draw an image with Kha for about an hour now and I just can't figure this out... I was watching Lewis Lepton's tutorials on youtube but I don't know why, this isn't working at all.

class Project {
	public var image:Image;

	public function new() {
		System.notifyOnRender(render);
		Scheduler.addTimeTask(update, 0, 1 / 60);

		image = Assets.images.PixelMeComputer;
	}

	function render(framebuffer: Framebuffer): Void {	
		framebuffer.g2.begin();
		framebuffer.g2.drawImage(image, 30, 30);
		framebuffer.g2.end();
	}
}

This code give me the following error: "Cannot read property 'get_width' of null"
If you have any clue to this problem, I'd be very happy!

**Comment by RobDangerous** [comment]
The error is actually quite descriptive - your image is null because you didn't load it. You can load all assets at once by calling Assets.loadEverything - and make sure not to use the image because that functions callback was called.
