### ISSUE TITLE
[Request] Intellij IDEA support

### ISSUE THREAD

**Issue by b005t3r** [Kode/Kha#511]
I noticed that the best IDE out there is not supported. I tried using Kode Studio and as it might be OK for learning, it's nowhere near IDEA when it comes to creating a real project - it has very poor autocompletion, it doesn't import classes automatically, there's no refactoring options, etc. I can't see myself working as efficiently with it as I do with IDEA.

So, is it possible to develop things using kha in IDEA (with debugging)?

**Comment by sh-dave** [comment]
Even though 'best' is very subjective, when you run khamake it should already create IDEA project folders in 'build/projectname-target-intellij'. Did you try to open one?

**Comment by RobDangerous** [comment]
Aye, IDEA is supported for years. I don't use it personally though because I really don't like it so you might run into issues. The exporter is located here in case you want to change something: https://github.com/Kode/khamake/blob/master/src/HaxeProject.ts

**Comment by b005t3r** [comment]
Yeah, after posting the bug I managed to open one of the projects, but it couldn't find kha classes. Also, if I change something in the project will it get overwritten if I call khamake again? And is it possible to debug using IDEA (and which target is debuggable)?

I have a lot of questions about that, but what I was able to find in the Wiki does not answer those questions, so I'm asking here :)

**Comment by RobDangerous** [comment]
Never managed to get debugging in IDEA to work myself - but that's not a Kha problem, that's completely up to the IDEA plugin and I'm not even sure that one's still in active development. I think it's supposed to support Flash debugging.
The project will get overwritten, yes. If you need something in the project file to be different, please edit HaxeProject.ts accordingly.

PS: There's a forum for questions: http://forum.kode.tech
