### ISSUE TITLE
Doesn't understand how Image.at() works

### ISSUE THREAD

**Issue by MrBramard** [Kode/Kha#520]
Hey,
I'm working on a little game and I am trying to create a tilemap based on an image where each pixel's color represent a tile.
To do that, I'm trying to read the kha.Color of each pixel of my image using Image.at(x,y) but it doesn't work the way I was expecting it to work.
Here's my code :

`	public function load_from_image(image:Image)
	{
		map = new Array<Array<Tile_type>>();
		var array:Array<Tile_type>;

		for(i in 0...image.height)
		{
			array = new Array<Tile_type>(); 
			for(j in 0...image.width)
			{

				trace(i + ";" + j + " : image.at : " + image.at(j,i).A + ", " + image.at(j,i).Ab + ", " + image.at(j,i).R + ", " + image.at(j,i).Rb + ", " + image.at(j,i).G + ", " + image.at(j,i).Gb + ", " + image.at(j,i).B + ", " + image.at(j,i).Bb);

				if(image.at(j,i) == Color.fromBytes(0,0,0))
				{
					array.push(Tile_type.DEFAULT);
				} 
				else if(image.at(j,i) == Color.fromBytes(255,255,255))
				{
					array.push(Tile_type.WALL);
				}
				else if(image.at(j,i) == Color.fromBytes(255,0,0))
				{
					array.push(Tile_type.WATER);
				}
			}
			map.push(array);
		}
	}`

The problem is that the color returned by Image.at doesn't seem right so my if-else statement doesn't work. Here's what the trace returns:
`
Tilemap.hx:48: 0;0 : image.at : 0, 0, 0, 0, 0, 0, 0.9882352941176471, 252
Tilemap.hx:48: 0;1 : image.at : 0, 0, 0, 0, 0, 0, 0, 0
Tilemap.hx:48: 0;2 : image.at : 0, 0, 0, 0, 0, 0, 1, 255
`

The first color should be perfect red, the second perfect black and the third perfect white.
My image is a .png so it shouldn't be a compression problem.

Thanks!

**Comment by RobDangerous** [comment]
What target do you use? Is your image "readable" (it's not by default)?

**Comment by MrBramard** [comment]
It doesn't work with HTML5 or Krom. 
I've changed from loadEverything to loadImageFromPath with readable = true but the only difference is that the B and Bb values from the color that should be red are now 1 and 255 and that Krom don't even launch the game (Haxe compilation server stopped)

**Comment by RobDangerous** [comment]
I think Krom does not yet support readable images.
But apart from a color channel switch in the html5 target it sound like it is working now.

**Comment by MrBramard** [comment]
What do you mean by color channel switch?

**Comment by RobDangerous** [comment]
Red is blue and blue is red.

**Comment by MrBramard** [comment]
Yes it solves the problem for the red but the white is still 255,0,0 (rgb) and not 255,255,255

**Comment by RobDangerous** [comment]
I tried to reproduce this and failed, it works fine for me. Can you upload a test project?
