### ISSUE TITLE
ram consumption on text rendering

### ISSUE THREAD

**Issue by r3d9u11** [Kode/Kha#524]
Hi. This theme is a continuation of the [haxeui-kha](https://github.com/haxeui/haxeui-kha/issues/10) and just for a discussion.

I have an little sample, after rendering of a little string the consumption of resources of application will increased about x2.5 (~27mb at startup and about ~67mb after "Hello world" will be displayed):
```
package;

class KhaApplication {
	private var initialized:Bool = false;
	
	public function new () {
		kha.System.notifyOnRender(render);
		kha.Assets.loadEverything(function () { this.initialized = true; });
	}
	
	public function render (framebuffer:kha.Framebuffer): Void {
		if (this.initialized) {
			framebuffer.g2.begin(0x000000);
			
			framebuffer.g2.font = kha.Assets.fonts.arial;
			framebuffer.g2.drawString("Hello, world!", 10, 10); // here consumption of RAM will be increase up to 67mb
			
			framebuffer.g2.end();
		}
	}
}
```
I'm trying to understand why the display of simple labels leaves as many resources.

Maybe someone have any ideas on this?

Also where I can find text rendering methods (the method graphics2.Graphics.drawString has an empty body, and will be overrided for target platform)?

I'm on Linux Mint 18.1 x64
Haxe 3.4.0
Latest Kha and KodeStudio (from git)

Thanks.

**Comment by RobDangerous** [comment]
Looked into it and it's hxcpp deciding to fetch a bunch of memory during all the things which are going on while the font-atlas is created. Interestingly when you render a second text in a different font size (which generates a completely new font-atlas) there's no noticeable increase in memory consumption. This is not ideal and font rendering could be improved further (but that would make it harder to keep it up to date with stb_truetype) but it's to be expected in a garbage collected environment. There are probably some values which can be tweaked in hxcpp for your specific use-case. Alternatively have a look at Kore for tighter memory control.
The text rendering functions which are used on most systems are in kha.graphics4.Graphics2.

**Comment by r3d9u11** [comment]
@RobDangerous Thank you for answer and interest thinks. Also thanks for hint, I'll try to play with Graphics2 and will do some experiments!
