### ISSUE TITLE
Kha 2d vs Pixijs

### ISSUE THREAD

**Issue by markknol** [Kode/Kha#525]
Hi!

I was wondering how does Kha graphics2 compare to pixijs, on WebGL target?
I'm no expert, but I think this is really impressive: http://www.goodboydigital.com/pixi-js-v4-batching/ Does Kha have similar performance on WebGL ?

**Comment by RobDangerous** [comment]
Kha doesn't yet use multitexturing for this use-case (but it's planned, shader-compiler can already compile shader-variations based on multitexturing counts). Apart from that performance is similar AFAIK but the one thing everybody is missing is one big 2D graphics benchmarking suite which can test lots of different situations.

**Comment by RobDangerous** [comment]
(btw, please use the forum for questions)

**Comment by markknol** [comment]
Thanks for this explanation!

(Sorry, wasn't aware of the forums.)
