### ISSUE TITLE
D3D11 Crash and Unknown error

### ISSUE THREAD

**Issue by dmitryhryppa** [Kode/Kha#530]
Got a strange errors with D3D11. 
It's alwas print "**Unknown error**" in output console. 

After some investigations I found that error caused on this line:
https://github.com/Kode/Kore/blob/24bd154ed65ca3eb35f07eb8a53117b07903f080/Backends/Direct3D11/Sources/Kore/ProgramImpl.cpp#L240

In debug mode I got different errors on different shaders:

First type of errors:
`D3D11 ERROR: ID3D11Device::CreateInputLayout: Encoded Signature size doesn't match specified size. [ STATE_CREATION ERROR #161: CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE]`

Second type of errors:
`D3D11 ERROR: ID3D11Device::CreateInputLayout: Element[3] and Element[2] have the same Semantic (TEXCOORD 0).  All Semantics in the Input Layout must be unique.  This error is only printed on the first occurence detected. [ STATE_CREATION ERROR #160: CREATEINPUTLAYOUT_DUPLICATESEMANTIC]`

But everything works fine with OpenGL.

**Comment by dmitryhryppa** [comment]
Found why those errors happens. 

This will work:
```
out vec4 fragColor;
void main() 
{
    fragColor = vec4(1.0, 1.0, 1.0, 1.0);
}

```


This will not work and will cause errors described above:
```
void main() 
{    
    gl_FragData[0] = vec4(1.0, 1.0, 1.0, 1.0);
    gl_FragData[1] = vec4(1.0, 0.0, 0.0, 1.0);
}
```

**Comment by dmitryhryppa** [comment]
I fixed that error:
`D3D11 ERROR: ID3D11Device::CreateInputLayout: Element[3] and Element[2] have the same Semantic (TEXCOORD 0). All Semantics in the Input Layout must be unique. This error is only printed on the first occurence detected. [ STATE_CREATION ERROR #160: CREATEINPUTLAYOUT_DUPLICATESEMANTIC]`



By replacing **COLOR** with **SV_Target** here:
https://github.com/Kode/SPIRV-Cross/blob/64f77f45bc84033a7cbb78549d99db1422042c99/spirv_hlsl.cpp#L177

But thats will not work for D3D9, I guess.

**Comment by RobDangerous** [comment]
Test project please (there have been some changes to the compiler, maybe it's already fixed).

**Comment by dmitryhryppa** [comment]
No, I still have that errors. 
Will do some research and will create a test project.

**Comment by dmitryhryppa** [comment]
After last update this errors are gone. 
Don't know what's going on and what was changed in this 18 days, but issue can be closed, I think.
Thank you.

**Comment by dmitryhryppa** [comment]
Still here :(

**Comment by dmitryhryppa** [comment]
@RobDangerous, try this, please. It's a sample for Kore, but it contains current issue
https://www.dropbox.com/s/q5wmevpzoesiur6/sample.zip?dl=0

**Comment by RobDangerous** [comment]
I fixed something and it now runs but doesn't look much like in OpenGL. Problem is/was about unused attributes. Maybe more problems, that sample is huge...

**Comment by dmitryhryppa** [comment]
Thanks, Robert, for all your hard work. 
I can confirm that it runs now, but result is very strange :D
Here is how it looks like in my case:

![D3D11 Issue](http://i.imgur.com/mMdfZVC.png)

Sorry for the huge sample, please, the problem became on complex shaders only so it needs normal maps and all that weird stuff.


Also, I tried to update Kore in Kha and still got this with Kha project (with crash):
```
D3D11 ERROR: ID3D11Device::CreateInputLayout: Encoded Signature size doesn't match specified size. [ STATE_CREATION ERROR #161: CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE]
D3D11 WARNING: Process is terminating. Using simple reporting. Please call ReportLiveObjects() at runtime for standard reporting. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: Live Producer at 0x01DC790C, Refcount: 178. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x03F40070, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x03FEE120, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x03FF57F4, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x03FF5C84, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
```
So looks like I should create more complex sample with Kha :)

**Comment by RobDangerous** [comment]
Nooo... I'll fix it with the Kore sample.

**Comment by dmitryhryppa** [comment]
About:

`D3D11 ERROR: ID3D11Device::CreateInputLayout: Encoded Signature size doesn't match specified size.`

I found some interesting thing. With small meshes D3D works correctly. But with big meshes (like Sponza) it cause issue. But both mehses works fine with GL.

**Comment by dmitryhryppa** [comment]
Update. 
Can't reproduce " Encoded Signature" error again... 
But here is small sample that includes issue with rendering of 3D models. 
GL - ok,  D3D11 - not ok. 
https://www.dropbox.com/s/22s5w6rofzdhqel/d3d11_issue_sample.zip?dl=0

Please, check 17 line in Main.hx and try to switch `LOAD_SPONZA` variable from `true` to `false` for loading different models on startup. 

![Screenshot](https://i.imgur.com/p6HUbtm.png)

**Comment by dmitryhryppa** [comment]
Btw, looks like D3D9 works fine and does not contain those errors. 
But there is no option to use D3D9 if you using MRT in your code or building to windows universal app, so D3D11 is still important :)

**Comment by RobDangerous** [comment]
Didn't fix your rendering yet but the actual "Encoded Signature..." bug is fixed (Haxe/hxcpp could collect and reuse the vertex shader memory in D3D11 so it was kind of a random incident).

**Comment by RobDangerous** [comment]
I get the broken output via html5 as well...

**Comment by RobDangerous** [comment]
Uhm and also via OpenGL. Does this still render correctly for you?

**Comment by RobDangerous** [comment]
Hey, I think it's all fixed.
