### ISSUE TITLE
Default Font?

### ISSUE THREAD

**Issue by ashes999** [Kode/Kha#532]
I created a new Kha game that doesn't use text or fonts anywhere. When I build and run the HTML5 version, I get an error (stack dump shows `set_font` being called).

This means every single game must have a font (eg. TTF) file, which is loaded by assets, and assigned to the graphics object at render-time.

It would be great if there was some kind of built-in default font, even if it's really hideous. Or, if Kha failed fast (and clearly), indicating that the user needs to load and set a font.

(Flixel or HaxeFlixel uses some sort of 8-bit-ish font by default, I think).

**Comment by RobDangerous** [comment]
I don't intend to bundle a font. But Kha doesn't use fonts if you don't make it use fonts - please have a look at your call stack to see where that set_font call comes from.

**Comment by ashes999** [comment]
While writing up a stack-dump for you, I realized that I'm setting `g.font = someFont`. It's unfortunate that `someFont` here happens to be null (derp!), and yet that triggers Kha's `set_font` and `setFont` methods, which throw.

I don't know if you want to make this more "idiot-proof" by either ignoring this case (if null, do nothing) or throwing a glaring exception. Either way, I can close this, since it's not actually broken (my bad).
