### ISSUE TITLE
Shader compile issue on html5 with Mobile "Huawei P8 Lite"

### ISSUE THREAD

**Issue by wighawag** [Kode/Kha#539]
using a huawei p8 lite chrome browser I get the following error : 

```
Could not compile shader: ERROR: 0:3: 'highp' : precision is not supported in fragment shader 
```

The app use only g2 and the failing shader is the painter-image.frag.glsl that get generated to
```
#version 100
precision mediump float;
precision highp int;

uniform highp sampler2D tex;

varying highp vec2 texCoord;
varying highp vec4 color;

void main()
{
    highp vec4 texcolor = texture2D(tex, texCoord) * color;
    highp vec3 _32 = texcolor.xyz * color.w;
    texcolor = vec4(_32.x, _32.y, _32.z, texcolor.w);
    gl_FragData[0] = texcolor;
}
```

**Comment by wighawag** [comment]
I guess remove highp would work but another approach that would solve other gpu specific issues would be to catch these issues and disable webgl for built-in shader so a game that rely only on g2 can still work

**Comment by RobDangerous** [comment]
We should compile fallback shaders for old hardware.

**Comment by wighawag** [comment]
good idea, I would still catch potential fallback shader compile error if it can happen ?

**Comment by RafaelOliveira** [comment]
I'm also seeing this error in the Samsung Galaxy J3 (brazilian model). Its a entry model here. 

I found this code that detect the shader precision:
var highp = gl.getShaderPrecisionFormat(gl.FRAGMENT_SHADER, gl.HIGH_FLOAT);
var highpSupported = highp.precision != 0;
http://codeflow.org/entries/2013/feb/22/how-to-write-portable-webgl/#how-to-query-fragment-shader-precision
this way we could use a lower precision when needed.

**Comment by wighawag** [comment]
Cool, that looks like a good solution for error related to precision

**Comment by RobDangerous** [comment]
Tried to implement it, please test the latest revision (and use Windows to compile the project, have yet to compile the updated shader-compiler for Linux/macOS).

**Comment by wighawag** [comment]
Got the same error with commit df8f96d41e7f51de6bec8b850726f42ebdc9cf0f ( i use windows with ```node Kha\make.js -t html5```

**Comment by wighawag** [comment]
It throws there : https://github.com/Kode/Kha/blob/master/Backends/HTML5/kha/graphics4/PipelineState.hx#L93

**Comment by RobDangerous** [comment]
The commit is allright, but that line is empty. Can you figure out anything else? Does it actually try to load the relaxed shader? Does it still throw the same error? Sadly can't test it myself, need some help.

**Comment by wighawag** [comment]
sorry it was this line : https://github.com/Kode/Kha/blob/master/Backends/HTML5/kha/graphics4/PipelineState.hx#L74

And debugging it it take the relaxed version of the shader and fail. I can see there is stil highp in uniform and varying in the shader. could this be these ?

**Comment by RobDangerous** [comment]
There shouldn't be any highp in the relaxed shader. Do you also see that in the files in html5-resources? Did you update the submodules? If you didn't, clean your build dir after you did.
painter-image-relaxed.frag.essl looks like this for me:
```
#version 100
precision mediump float;
precision highp int;

uniform mediump sampler2D tex;

varying vec2 texCoord;
varying vec4 color;

void main()
{
    vec4 texcolor = texture2D(tex, texCoord) * color;
    vec3 _32 = texcolor.xyz * color.w;
    texcolor = vec4(_32.x, _32.y, _32.z, texcolor.w);
    gl_FragData[0] = texcolor;
}
```

**Comment by wighawag** [comment]
Sorry for giving the information piece by piece. 

here the shader source that failed :

```
#version 100
precision mediump float;
precision highp int;

uniform mediump sampler2D tex;

varying vec2 texCoord;
varying vec4 color;

void main()
{
    vec4 texcolor = texture2D(tex, texCoord) * color;
    vec3 _32 = texcolor.xyz * color.w;
    texcolor = vec4(_32.x, _32.y, _32.z, texcolor.w);
    gl_FragData[0] = texcolor;
}
```

This is exactly the same so maybe the highp int is not accepted ?

**Comment by RobDangerous** [comment]
Shouldn't make a difference as not int is actually used. What's the error message?

**Comment by wighawag** [comment]
Same as before : 

Could not compile shader: ERROR: 0:3: 'highp' : precision is not supported in fragment shader

**Comment by RobDangerous** [comment]
Crazy compiler, will remove the unused int qualifier...

**Comment by RobDangerous** [comment]
--compile support is here for android and android-native.

**Comment by RobDangerous** [comment]
Well, wrong issue.

**Comment by RobDangerous** [comment]
Please try again with the latest krafix revision (I didn't update the parent repositories, just update Kha/Kore/Tools/krafix manually).

**Comment by wighawag** [comment]
fixed!

**Comment by RobDangerous** [comment]
Wonderful. That's one pretty advanced compatibility feature.

**Comment by wighawag** [comment]
Should be mentioned on the website in some way :)
