### ISSUE TITLE
"Samsung S6 Edge+" slow and crash on webgl

### ISSUE THREAD

**Issue by wighawag** [Kode/Kha#541]
Kha g2 on g4 on "Samsung S6 Edge+" is very slow and crash the web browser 
By forcing canvas, the game runs fine

Note that the game rendering is very basic : a clear and at max 10 filled circles + 10 character font rendering.

I am not sure the best way forward here, should we create a blacklist of device if we can detect them ?
Or can we detect performance issues before hand ?

**Comment by RafaelOliveira** [comment]
Some Samsung devices have problems with wegbl. Check this thread:
https://forum.xda-developers.com/galaxy-s6-edge/help/webgl-disabled-chrome-t3080336

**Comment by wighawag** [comment]
Hi saw some report too regarding Mali GPU that the s6 edge + use

The problem here is that webgl is enabled but it is slow and crash.  

I am using only g2

**Comment by RobDangerous** [comment]
I think a blacklist is the only reasonable thing to do here. Performance tests can be unreliable and would slow down application startup. But how can we test for the device? Anything useful in the browser version string?

**Comment by wighawag** [comment]
It was mot my device and will not easily get access to all the information regarding that particular device.
I agree though that a blacklist would be ideal.

Alternatively what Kha could provide would be an callback api so the callback get called when the device is running g2 slowly ? 
It could also handle this by reloading the page for example and requesting canvas on the second load (by using local storage to store the info that the device do not really support webgl)

Some of these or all could be handled by the app itself but maybe it make sense than Kha handle at least the callback part ?

**Comment by RobDangerous** [comment]
I don't think there is a reliable and performant way to figure out if g2 runs slowly. We could measure frame times but slow frame times could as well mean that some really complex graphics are running. We would introduce functionality which is very random by nature, really don't want to do that. What would make more sense IMHO would be to create an actual test app which optionally uploads device data so we can populate the black list.

**Comment by RafaelOliveira** [comment]
The size of the generated js is very important in mobile devices, so I think a option could be a option in khafile.js to create the list in a separate file, that would be read automatically by kha if present. Or we put the list in the wiki and Kha would have a method where we can pass a list and it force the canvas if the device is present in the list.

**Comment by RobDangerous** [comment]
Ya, we can put it in an extra file and load it when init is called (luckily that's already async). But would only do that if the list actually grows to a relevant size.

**Comment by RblSb** [comment]
That phone should be dead, problem solved

**Comment by RobDangerous** [comment]
Let's hope so, at least I haven't heard of more situations like this one.
