### ISSUE TITLE
Proper fullscreen support for Windows/macOS/Linux

### ISSUE THREAD

**Issue by RobDangerous** [Kode/Kha#542]
Windows works, needs some work to also switch at runtime.
macOS, Linux...

**Comment by OvermindDL1** [comment]
By fullscreen do you mean switching the mode to fullscreen or are you wanting to just remove all the chrome of the application and make it maximized?  I've seen both methods as pretty popular, and I find the latter more generally useful.  Will both methods be available?

**Comment by sh-dave** [comment]
You already can do borderless window's on some native targets, Currently only works at startup though.

**Comment by OvermindDL1** [comment]
> You already can do borderless window's on some native targets, Currently only works at startup though.

Yeah I'm curious about runtime switching though.  :-)

**Comment by RobDangerous** [comment]
It's all working now during startup and runtime on Windows/macOS/Linux.
