### ISSUE TITLE
Can't play mp4 video

### ISSUE THREAD

**Issue by r3d9u11** [Kode/Kha#550]
Hi. I have some mp4 video file in my Assets, but when I tried to call .play() method I have exception (in Html5 debugging):

Failed to load resource: net::ERR_FILE_NOT_FOUND
Video.hx:102: Error loading file:///home/username/Desktop/video_example_kha/build/debug-html5/undefined
WebGL: INVALID_VALUE: texImage2D: no video

[Sample](https://github.com/luboslenco/video_example_kha)

Also I have a blank screen for a cpp-target.

Thanks.

**Comment by RobDangerous** [comment]
You have to provide a path to ffmpeg to transcode videos, you'll find the ffmpeg option in Kode Studio's settings. Also it's not supported on all cpp targets yet (currently only iOS and Android).

**Comment by r3d9u11** [comment]
@RobDangerous Thank you! I changed setting kha.ffmpeg in KodeStudio->User Settings and now it works fine for html5.
