### ISSUE TITLE
MRT not worked as expected, D3D

### ISSUE THREAD

**Issue by dmitryhryppa** [Kode/Kha#551]
![image](https://cloud.githubusercontent.com/assets/4466595/24707341/db80720e-1a1b-11e7-906d-f030032341d4.png)

_Sample_:
https://www.dropbox.com/s/bfddrn81zp7zzmd/d3d11_issue_MRT.zip?dl=0

**Comment by RobDangerous** [comment]
Looks like it was just the AMD driver going crazy. I think this is done.
