### ISSUE TITLE
Need help with window(s) managing system

### ISSUE THREAD

**Issue by r3d9u11** [Kode/Kha#552]
Hi. I need some help with managing of the window(s).

For example:

1) Get/Set properties of window:
   * window's title
   * window's size (native)
   * window's position (native)
   * maximize/minimize window (native)
   * make fullscreen (native)
   * set/unset borderless (native)
   * set/unset topmost (native)
2) Handle events:
   * on size changed (native)
   * on position changed (native)
   * on window maximized/minimized (native)
   * on window closed
3) Multiwindows (native?):
   * make an additional window(s) and manage it
   * move window to specific display
4) Cursor:
   * hide cursor
   * set a custom cursor

In kha-api I found a several intresting classes and methods, but I can't find more detailed information about them: 
* method [System.init](http://api.kha.technology/kha/System.html#init)
* method [System.initEx](http://api.kha.technology/kha/System.html#initEx)
* method [System.notifyOnApplicationState](http://api.kha.technology/kha/System.html#notifyOnApplicationState)
* method [System.changeResolution](http://api.kha.technology/kha/System.html#changeResolution)
* method [System.windowHeight](http://api.kha.technology/kha/System.html#windowHeight)
* method [System.windowWidth](http://api.kha.technology/kha/System.html#windowWidth)
* [SystemOptions](http://api.kha.technology/kha/SystemOptions.html)
* [Display](http://api.kha.technology/kha/Display.html)
* [Cursor](http://api.kha.technology/kha/Cursor.html)
* [WindowOptions](http://api.kha.technology/kha/WindowOptions.html)
* [WIndowModeOptions](http://api.kha.technology/kha/WindowedModeOptions.html)
* [Mode](http://api.kha.technology/kha/Mode.html)
* [Position](http://api.kha.technology/kha/Position.html)

I can only get/set size of current (main) window's by System.windowHeight, System.windowWidth, System.changeResolution (by I'm no sure, that is the correct way).

Maybe somebody have an ideas/information how to use these and how to manage needed parameters?

(an similar topic on [Kha's forum](http://forum.kode.tech/topic/159/need-help-with-properties-of-the-window))
Thanks.

**Comment by sh-dave** [comment]
For 3) you can take a look at the provided sample:
- https://github.com/Kode/Kha/tree/master/Tests/MultiWindow

To move a window to a specific display, use ```WindowOptions.targetDisplay```. WindowOptions.Mode lets you set Windowed / Borderless / Fullscreen mode. This currently only works at initialization time.

**Comment by r3d9u11** [comment]
@sh-dave Awesome! Many thanks.
Also can I set window mode "Top Most"? I can't find this or similar property.

**Comment by sh-dave** [comment]
Currently not, but pull requests are always welcome :wink:
Also, not all properties are actually implemented on all targets. I did most of the multiwindow code and only implemented what i actually needed at work (windows+opengl for development; linux for release later). So multiwindow probably won't work for like windows + directx. Also not implemented for macos at all.

**Comment by r3d9u11** [comment]
@sh-dave Well, thank you for the update. For Linux your Multiwindow system also works fine!  I opened enhancement [issue](https://github.com/Kode/Kha/issues/553) for  "Top Most" parameter.
What about window's events? Is it supported?

**Comment by sh-dave** [comment]
Sorry, never tried it as i don't have a use case for that. The app i build only creates static sized, borderless windows and never lets the user change anything.
But it might be a good idea to ask some questions in the irc (especially in the evening as more people are on), as i'm not sure how many ppl actually watch the issues here.

**Comment by primesoftware** [comment]
@r3d9u11 Are you trying to use native windows that can move anywhere or do you want to open up dialogs contained within the main Kha windows?

**Comment by r3d9u11** [comment]
@primesoftware I'm trying to use several native windows, like in [this sample](https://github.com/Kode/Kha/tree/master/Tests/MultiWindow)

**Comment by RobDangerous** [comment]
This is mostly done...
