### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by r3d9u11** [Kode/Kha#554]
Hi. Does really work Storage/StorageFile system and can save/load some user data?

**Comment by RobDangerous** [comment]
Uhm, yes. Why, couldn't you get it to work?

**Comment by r3d9u11** [comment]
@RobDangerous sorry, because I saw only a [stub for nodejs ](https://github.com/Kode/Kha/blob/master/Backends/Node/kha/Storage.hx). What targets doest it support?

In debugging for html5 I have code:
```
package;

import kha.System;
import kha.Storage;
import kha.StorageFile;

class KhaApplication {
	public function new () {
		trace(Storage.defaultFile().canAppend());
		Storage.defaultFile().appendString("asd-");
		trace(Storage.defaultFile().readString());
	}
}
```
but as result have nothing:
KhaApplication.hx:10: false
KhaApplication.hx:12: null

What am I doing wrong?
Thanks.

**Comment by RobDangerous** [comment]
It's supported on most targets. Will test your code later today, might be that reading only works on a second run via html5...

**Comment by r3d9u11** [comment]
@RobDangerous I did several restarts, but it's nothing changed: readString() returns null

**Comment by RobDangerous** [comment]
Hm. Maybe a bug then.

**Comment by RobDangerous** [comment]
Ah it's all right, append doesn't work on all targets, that's why canAppend returns false. Try this:
```
kha.Storage.defaultFile().writeString("Hello");
trace(kha.Storage.defaultFile().readString());
```

**Comment by r3d9u11** [comment]
Thanks, it's work
