### ISSUE TITLE
How to attach frame to the borders of the window?

### ISSUE THREAD

**Issue by r3d9u11** [Kode/Kha#555]
Hi. Is it possible to refresh zero-position (for Y) and canvas size after window resizing?

1. How to attach my frame to the upper border of the window. I tried to draw frame at foxed position 10,10, but Y coordinates will be changed after window be resized:
![2](https://cloud.githubusercontent.com/assets/15020827/24830041/8df86524-1c86-11e7-99d6-90d08eb622d6.gif)
Test sample: [XYPosition.zip](https://github.com/Kode/Kha/files/907536/XYPosition.zip)

2. How to attach scaled frame to the both borders of the window? I tried to draw image 300x225 to the canvas 400x300. But scaling do not do after window size has been changed:
![1](https://cloud.githubusercontent.com/assets/15020827/24830065/0fc6cc80-1c87-11e7-9932-3f4650888edf.gif)
Test sample: [WHScaling.zip](https://github.com/Kode/Kha/files/907539/WHScaling.zip)

Thanks.

**Comment by RobDangerous** [comment]
Is that Windows with a fancy skin? Do you use the D3D9 target?

**Comment by r3d9u11** [comment]
@RobDangerous no, this is a Linux Mint 18.1 x64

**Comment by r3d9u11** [comment]
@RobDangerous Also similar behavior for native target (Linux)
OpenGL version string: 3.0 Mesa 12.0.6

**Comment by RobDangerous** [comment]
Window resizing on Linux native is not yet supported but I can not reproduce your WHScaling issue using a current Kha version and html5-debugging and I can't reproduce your XYPosition issue at all using html5-debugging.

**Comment by RobDangerous** [comment]
And resize for native Linux is fixed. Please reopen if you really can provoke that behavior using html5-debug.

**Comment by r3d9u11** [comment]
@RobDangerous It's super cool! Really works now, thanks!
