### ISSUE TITLE
[Request] Create screenshots and save as file

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#556]
I'd like to save screenshots of the framebuffer in my HD. This would be useful to create videos from the files using some video editing app.

This gist creates screenshots in html5 but html5 is limited and can only shows in a new window.
https://gist.github.com/RafaelOliveira/050de54121b38b1945fb71624f258d3d

**Comment by RobDangerous** [comment]
Lubos just added a getPixels function for render-targets.

**Comment by RafaelOliveira** [comment]
I made a library, but the red colors are being saved as blue (both bmp and png). @RobDangerous do you know if this code is correct? I also tried png.tools.build32ARGB, but it generates images with the background transparent (but the background was painted black).

I adapted from this code http://stackoverflow.com/questions/14034644/save-an-array-of-pixels-to-a-file

```haxe
package;

import kha.Image;

class SaveFrames
{
	static var idx:Int;
	static var filePath:String;
	static var image:Image;

	public static function start(image:Image, startIndex:Int, filePath:String):Void
	{
		SaveFrames.image = image;
		idx = startIndex;
		SaveFrames.filePath = filePath;
	}

	public static function saveBmp():Int
	{
		#if cpp
		var handle = sys.io.File.write(filePath + idx + '.bmp', true);
		new format.bmp.Writer(handle)
		.write(format.bmp.Tools.buildFromBGRA(image.width, image.height, image.getPixels()));
		handle.close();
		#end

		idx++;
		return idx - 1;
	}

	public static function savePng():Int
	{
		#if cpp
		var handle = sys.io.File.write(filePath + idx + '.png', true);
    		new format.png.Writer(handle)
        	.write(format.png.Tools.build32BGRA(image.width, image.height, image.getPixels()));
    		handle.close();
		#end

		idx++;
		return idx - 1;
	}
}
```

**Comment by RafaelOliveira** [comment]
I made a library that works (html5 and linux) based on https://github.com/Kode/Kha/pull/440#issuecomment-276461361. It will be put on the forum when finished.

**Comment by RafaelOliveira** [comment]
I mixed things and closed the wrong issue.

**Comment by RafaelOliveira** [comment]
The function getPixels is available to save a render target, so I closing this.
