### ISSUE TITLE
shaderPipeline documentation

### ISSUE THREAD

**Issue by peteshand** [Kode/Kha#557]
I've searched high and low on the interwebs and I've not had any luck finding documentation on Kha's shaderPipeline. Does anyone have experience with this? I'm particularly interested in blendmodes and per pixel masking.

I've got something like "add" working
```
var shaderPipeline = new PipelineState();
shaderPipeline.fragmentShader = Shaders.painter_image_frag;
shaderPipeline.vertexShader = Shaders.painter_image_vert;

var structure = new VertexStructure();
shaderPipeline.inputLayout = [structure];
shaderPipeline.blendSource = BlendingFactor.SourceAlpha;
shaderPipeline.blendDestination = BlendingFactor.DestinationAlpha;
shaderPipeline.compile();

graphics.pipeline = shaderPipeline;
```

However what I would expect to result in a multiply just shows a completely black image.

**Comment by RobDangerous** [comment]
I suppose you are talking about setting a pipeline in g2, right? Take a look at kha.graphics4.Graphics2, copy then modify the corresponding code. Your sample code in particular is missing the proper inputLayout.

**Comment by peteshand** [comment]
Hey Rob

Yeah, so graphics4.Graphics2 is pretty much the only place I could find an example of the PipelineState in action. Yes I've currently just playing with 2d stuff.

code with structure is as follows:

```
shaderPipeline = new PipelineState();
shaderPipeline.fragmentShader = Shaders.painter_image_frag;
shaderPipeline.vertexShader = Shaders.painter_image_vert;

var structure = new VertexStructure();
structure.add("vertexPosition", VertexData.Float3);
structure.add("texPosition", VertexData.Float2);
structure.add("vertexColor", VertexData.Float4);
shaderPipeline.inputLayout = [structure];

map.set("none", [BlendingFactor.BlendOne, BlendingFactor.BlendZero]);
map.set("normal", [BlendingFactor.SourceAlpha, BlendingFactor.InverseSourceAlpha]);
map.set("add", [BlendingFactor.SourceAlpha, BlendingFactor.DestinationAlpha]);
map.set("multiply", [BlendingFactor.DestinationColor, BlendingFactor.InverseSourceAlpha]);
map.set("screen", [BlendingFactor.SourceAlpha, BlendingFactor.BlendOne]);
map.set("erase", [BlendingFactor.BlendZero, BlendingFactor.InverseSourceAlpha]);
map.set("mask", [BlendingFactor.BlendZero, BlendingFactor.SourceAlpha]);
map.set("below", [BlendingFactor.InverseDestinationAlpha, BlendingFactor.DestinationAlpha]);

var blendingFactors:Array<BlendingFactor> = map.get("add");

shaderPipeline.blendSource = blendingFactors[0];
shaderPipeline.blendDestination = blendingFactors[1];
shaderPipeline.compile();
```

Am I missing something obvious?

**Comment by RobDangerous** [comment]
The PipelineState is used in every 3D Kha sample. Images are already drawn using additive blending by the way (images use premultiplied alpha).

**Comment by peteshand** [comment]
cool, any idea on "multiply" blendmode?

**Comment by RobDangerous** [comment]
No idea.

**Comment by sh-dave** [comment]
You should probably google 'OpenGL blending', this will reveal a lot more help than Kha specifics.

http://gamedev.stackexchange.com/questions/17043/blend-modes-in-cocos2d-with-glblendfunc and especially the playground here: http://www.andersriggelsen.dk/glblendfunc.php .

Most of the The GL_XXX constants have an eqivalent in kha's BlendingFactor enum (GL_ONE = BlendingFactor.BlendOne, ...)

**Comment by RafaelOliveira** [comment]
Blending factors (like in painting apps) are very common in game engines, I think this could be added to Kha, a method to apply a blending factor to the pipeline.

**Comment by RobDangerous** [comment]
Anyway, closing this because there's no bug to be found. Further questions/discussions in the forum please.
