### ISSUE TITLE
[Request] HLSL for D3D

### ISSUE THREAD

**Issue by dmitryhryppa** [Kode/Kha#559]
Would be nice to have a possibility to write shaders directly in HLSL for D3D targets.

It's useful especially if your target is Windows (and even XBox) and you have big and complex shaders (or even uver-shaders) and you want to put into it some native optimizations and write it by hands.

**Comment by RobDangerous** [comment]
Could keep people from reporting bugs in the HLSL output. Maybe later.

**Comment by RobDangerous** [comment]
Oh and if you have actual sample code where that would make sense, please send it my way.
