### ISSUE TITLE
[Request] VSync option to on / off it

### ISSUE THREAD

**Issue by dmitryhryppa** [Kode/Kha#561]
Sometimes this option is useful. 
Also, it's a nice way to compare GL and D3D renders to see which one gives more FPS on the current scene.

**Comment by tienery** [comment]
It's practically an essential option in this modern age. It's an option that should be available in all games, and frameworks such as Kha should make no exception to this rule.

**Comment by RobDangerous** [comment]
I do not agree that all games should have that option, but Kha should of course where possible (some systems of this modern age disallow it). Kore has it, just have to hook it up...
