### ISSUE TITLE
HTML5 it's not applying colors when drawing white images

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kha#562]
With a image totally white, using framebuffer.g2.color = Color.Red, the image is not being drawn in red, but in white. In the Windows target the color is correct.

HTML5 on the left, Windows on the right. 
The blue rectangle is a drawing made with fillRect, this is ok.
![screenshot](https://cloud.githubusercontent.com/assets/69374/25078391/b6303a0c-2308-11e7-9ab1-5dff708f62aa.png)

Link to the project: https://www.dropbox.com/s/7mak3d1o38kzokm/HTML5Colors.zip?dl=0
```haxe
package;

import kha.Color;
import kha.Assets;
import kha.Framebuffer;
import kha.Scheduler;
import kha.System;

class Project {
	public function new() {
		Assets.loadEverything(assetsLoaded);
	}

	function assetsLoaded()
	{
		System.notifyOnRender(render);
		Scheduler.addTimeTask(update, 0, 1 / 60);
	}

	function update(): Void {
		
	}

	function render(fb: Framebuffer): Void {
		fb.g2.begin(true, Color.Black);

		// should be red, but it's white
		fb.g2.color = Color.Red;
		fb.g2.drawImage(Assets.images.polygon, 20, 20);

		fb.g2.color = Color.Blue;
		fb.g2.fillRect(300, 20, 230, 230);

		fb.g2.end();
	}
}
```

**Comment by RobDangerous** [comment]
When the canvas fallback is active image tinting is not active due to performance reasons.
But it was probably just active because of #563

**Comment by RafaelOliveira** [comment]
I updated Kha, but now everything is black, and there is no errors. nothing is being rendered.

**Comment by RobDangerous** [comment]
Just added the colors back in.

**Comment by RafaelOliveira** [comment]
:+1:
