### ISSUE TITLE
Does kha.graphics2.GraphicsExtension.fillCircle work?

### ISSUE THREAD

**Issue by hoseyjoe** [Kode/Kha#564]
Does kha.graphics2.GraphicsExtension.fillCircle work?
I am using 
kha.graphics2.GraphicsExtension.fillCircle(g2, 100, 100, 100);

kha.graphics2.GraphicsExtension.drawCircle(g2, 100, 100, 100); works fine

**Comment by RobDangerous** [comment]
Guess that's a no then.

**Comment by hoseyjoe** [comment]
maybe its an older version I had issue with.   I downloaded January release of studio and it works with that copy. IDK.
