### ISSUE TITLE
Newlines are automatically inserted after 2000 characters on a single line in a Blob

### ISSUE THREAD

**Issue by rhacking** [Kode/Kha#565]
If a line in a file (read using Blob.readUtf8String) contains more than 2000 characters, newlines are automatically inserted. 

Example
Original file: https://pastebin.com/k0cy5S1G
Result after being read by kha: https://pastebin.com/MkwbzZis

It also seems the character after every 2000th character on a line is being discarded

**Comment by RobDangerous** [comment]
Please test, hope it works.

**Comment by rhacking** [comment]
The result returned by readUtf8String is now equal to the original document (thanks!).
