### ISSUE TITLE
[Request] Expose Gamepad (hardware?) IDs

### ISSUE THREAD

**Issue by Disar** [Kode/Kha#566]
Currently it's not possible to distinguish between gamepads.
Exposing some sort of ID would allow us to implement gamepad profiles and gamepad specific button icons for our applications/games.

**Comment by RobDangerous** [comment]
Done (for html5 and Kore), but untested. Works for sure.

**Comment by Disar** [comment]
It now crashes at SystemImpl eventhough i haven't touched any gamepad code
        static function checkGamepadButton(pad: js.html.Gamepad, num: Int) {
		if (buttonspressed[num]) {
			if (pad.buttons[num].value < 0.5) {
				buttonspressed[num] = false;
			}
		}
		else {
		>>>	if (pad.buttons[num].value > 0.5) {
				buttonspressed[num] = true;
			}
		}
	}`

**Comment by Disar** [comment]
`var sysGamepads = getGamepads();
			if (sysGamepads != null) {
				for (i in 0...sysGamepads.length) {
					var pad = sysGamepads[i];
					if (pad != null) {
						checkGamepadButton(pad, 0);
						checkGamepadButton(pad, 1);
						checkGamepadButton(pad, 12);
						checkGamepadButton(pad, 13);
						checkGamepadButton(pad, 14);
						checkGamepadButton(pad, 15);

						checkGamepad(pad);
					}
				}`

I changed those 12 ~ 15 to 2 ~ 5 and it stopped complaining. But I'm not sure what your intend was with this?

**Comment by RobDangerous** [comment]
All fine now?

**Comment by Disar** [comment]
seems to be running, sent you another small fix.

**Comment by RobDangerous** [comment]
Cool Spot
