### ISSUE TITLE
[BUG] shader related compile problem

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#567]
coming back to kha, ive kept up to date with... updates. but started new project & this error popped up in KS console

```
ERROR: /usr/local/lib/kha/Sources/Shaders/painter-colored.frag.glsl:6: 'gl_FragColor' : undeclared identifier 
ERROR: /usr/local/lib/kha/Sources/Shaders/painter-colored.frag.glsl:6: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
SPIR-V is not generated for failed compile or link
```

**Comment by sh-dave** [comment]
Are you sure you're using the latest Kha, Robert comitted some changes here https://github.com/Kode/Kha/commit/bf445b754cd1aab6602339b132cf2d5d50a34893
and the shaders aren't using gl_FragColor anymore?

**Comment by RobDangerous** [comment]
What Dave said. Looks like you somehow managed to update your submodule repos but not the Kha repo itself.

**Comment by lewislepton** [comment]
im trying the updating git, but still not. gonna just try deleting then installing kha - ill let you know. but sure i have the right commands: the bottom 2 here https://github.com/Kode/Kha/wiki/Getting-Started

**Comment by lewislepton** [comment]
its what ive been using since i first installed kha thru git

**Comment by lewislepton** [comment]
aye working now.

**Comment by RobDangerous** [comment]
The commands are fine. You can always use git status and git log to see if everything is correct.

**Comment by lewislepton** [comment]
cheers ill keep that in mind
