### ISSUE TITLE
[BUG?] cant build/run project if shaders are even in project & not set

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#572]
this is something that is a bit weird. purely because just to get projects underway, you cant have any shader in projects unless you have things built first to run.

so on a blank project, just putting shaders in a folder & calling them in khafile.js, this error pops up without even trying.

these shaders work perfectly well in there projects, but on blank ones to get started in, just errors right away.

just think its a bit strange & somewhat weird. dont think its too much of a bug, but think most may think so since its saying about your shader code. i know because its a blank project thats not accessing the shader. but its like accessing an image, shouldnt have to error out if not being used

anyhow

```
Creating Kha project.
Exporting asset 1 of 2 (grid.frag.glsl).
Exporting asset 2 of 2 (shader.frag.glsl).
Compiling shader 1 of 2 (grid.frag.glsl).
ERROR: #version: ES shaders for OpenGL SPIR-V are not supported
ERROR: /Users/lepton/Developer/Kha/libraries/ll_complete/ll_shader/Assets/Shaders/grid.frag.glsl:16: 'gl_FragColor' : undeclared identifier 
ERROR: /Users/lepton/Developer/Kha/libraries/ll_complete/ll_shader/Assets/Shaders/grid.frag.glsl:16: 'scalar swizzle' : not supported with this profile: es
```

**Comment by sh-dave** [comment]
Seems like the same issue you reported a couple of days ago #567

**Comment by lewislepton** [comment]
funnily it might seem that way & i can be forgetful, but this is a new problem.
im totally up to date, but have coded shaders inside a folder id like to use. but no matter what, if a shader is in a folder but not being accessed, it errors.

**Comment by RobDangerous** [comment]
No, these shaders don't work perfectly well in their projects if you use an up to date version of Kha. The shader compiler is more strict now and requires a more up to date version of glsl (have a look at the changes done to the painter shaders - it's easy). Guess you just didn't try to compile those other project yet after you updated Kha.
And no, projects which contain broken shaders can not possibly build. Shaders are not assets, they are parts of your source code (and btw I think if you add a broken png or something like that it won't build either). One of the big reasons to use a compiler is that broken things error before you run them.

**Comment by lewislepton** [comment]
ok. good to konw about the strict complier. ill have a look see at painter shaders
my shaders were fine & werent broken. actually brought from working projects, which did build completely fine.

thanks. just wasnt sure since it didnt seem to make sense & have been wondering for a while
