### ISSUE TITLE
Graphics2 drawRect appears broken on HTML5 target

### ISSUE THREAD

**Issue by rrohrer** [Kode/Kha#581]
I'm seeing drawRect (in the most basic use case) not work on HTML5 targets in both Chrome and Firefox.

Here is the code:

    function render(framebuffer: Framebuffer): Void {
        var graphics = framebuffer.g2;

        graphics.begin(Color.Black);
        graphics.color = Color.Orange;
        graphics.drawRect(50,50,40,40, 8);
        graphics.end();
    }

This is the result in Firefox:
<img width="325" alt="screen shot 2017-05-10 at 10 30 14 pm" src="https://cloud.githubusercontent.com/assets/2242454/25934133/f586d050-35d0-11e7-8860-edb786b1568f.png">

This is the result of building the osx target:
<img width="251" alt="screen shot 2017-05-10 at 10 33 26 pm" src="https://cloud.githubusercontent.com/assets/2242454/25934141/01644eca-35d1-11e7-93c3-b833c49ecdc9.png">

I'm running head from this afternoon of the kha git repo:
`HEAD detached at 0640218`

Edit: Graphics2 fillRect also doesn't work on HTML5 but works on native.

**Comment by RobDangerous** [comment]
Everything is broken since yesterdays WebGL2 adventures, working on it...

**Comment by rrohrer** [comment]
Awesome, glad it's a known issue :)
