### ISSUE TITLE
Windows build not works

### ISSUE THREAD

**Issue by malublu** [Kode/Kha#585]
After installing this:
http://landinghub.visualstudio.com/visual-cpp-build-tools

Building with this:
`msbuild "D:\...\build\windows-build\New Project.sln" /p:Configuration=Release`
or
`msbuild "D:\...\build\windows-build\New Project.sln" /p:Configuration=Release /p:Platform=x64`

And try to start it its not running.

![grafik](https://cloud.githubusercontent.com/assets/14329224/26037515/928a539c-38f4-11e7-83a4-b33afed2f399.png)

Also the debug builds like:

msbuild "D:\...\build\windows-build\New Project.sln"

or

msbuild "D:\...\build\windows-build\New Project.sln" /p:Platform=x64

don't works.

But without error message.

Also the automatic detection not works:

```
ERROR: Cannot determine the location of the VS Common Tools folder.

Der Befehl "MSBuild.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

```

**Comment by RobDangerous** [comment]
What kind of project is that? Do you run it in the correct dir (where the assets are)?
