### ISSUE TITLE
[BUG?] are inputs gamepads still not working for macOS builds?

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#588]
this isnt much of a bug, i guess.
but more a question as to the state with gamepads on macOS. just tried with xbox one controller but not working. just wondering more if its been done or not in terms of working with builds for macOS or even any builds for platforms.

thanks

**Comment by sh-dave** [comment]
Can't test on mac as i don't have a gamepad at work, but do a build and then debug in xcode.
For starters, put a couple of breakpoints in some or all of the functions in the HID classes and step trough to figure out where it bails out:
https://github.com/Kode/Kore/tree/6da394a16354be31d94aaff2aefda6d1c2aeae58/Backends/System/macOS/Sources/Kore/Input

**Comment by RobDangerous** [comment]
Everything works on macOS - except for Xbox One pads. Also no immediate plans because those are super complicated. Sorry.

**Comment by lewislepton** [comment]
thats a damn shame indeed. & yes they are a little bit different to say the least.
i do have a driver which should 'imitate' a 360 controller. but that doesnt seem to be working.
guess il have to invest buying another 360 controller. will look to getting ps3/4. as long as they work

thanks again
