### ISSUE TITLE
Creating a Windows target with KodeStudio fails

### ISSUE THREAD

**Issue by DualLayer** [Kode/Kha#590]
In KodeStudio, when I press ctrl+b and choose Windows, the Target creation fails.
The following output is printed:

Creating Kha project.
Exporting asset 1 of 1 (circles.png).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-image.frag.glsl).
e:\Kha\Projects\Test\build\temp\painter-image.frag.hlsl(20,29): error X3000: syntax error: unexpected token ','
e:\Kha\Projects\Test\build\temp\painter-image.frag.hlsl(20,29): error X3000: syntax error: unexpected token ','

Here is a snippet of the painter-image.frag.hlsl file:

```
void frag_main()
{
    float4 texcolor = tex2D(, texCoord) * color;
    float3 _32 = texcolor.xyz * color.w;
    texcolor = float4(_32.x, _32.y, _32.z, texcolor.w);
    FragColor = texcolor;
}
```

When im using the following command line:

`node Kha/make windows -v vs2015`

the Target is created correctly and i can build it with Visual Studio 2015.

Kode Studio version: KodeStudio-win32 17.1

**Comment by RobDangerous** [comment]
Should be fixed. Note that Kode Studio still builds for Direct3D 9 while normally Kha now defaults to Direct3D 11. Will change with the next version of Kode Studio.
