### ISSUE TITLE
[BUG?] different input on different platforms - gamepad

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#594]
both sidar & myself have been looking at gamepads.
he has done the most work with his bracelet library, which makes multiple gamepads much more simpler to put in.
but we have been looking at other controllers. to make it simpler for people to use.
xbone & 360, with DS4

but on trying it on macOS, the ABXY buttons are actually in a different position compared to windows [not sure about linux]. on his machine they seem to be where they need to be [& correct from when we were testing back & forth a week or so ago], but on macOS, have shifted say 90 degrees to the left. so Y ends up being X & A is B etc

we were thinking that this may be different for other desktop/KS platforms [macOS, windows, linux] & that it may be a bug. as DS4, xbone, 360 ABXY or its equivalent are actually the same when we checked. about a week or so ago
so it wouldnt be cross platform in the end & with the tests ive done, it is different. both with xbone & 360. which are the same problem. i dont have a DS4 controller to check yet
there may be something just a miss with other platforms that is changing.

the library in question is here: https://bitbucket.org/stalei/powerbracelet

i know that xbone is not fully supported due to the annoying changes. but its output ABXY is the same as an 360 ABXY & also DS4
it still works, but its been marked as 'generic' for now

cheers.

**Comment by Disar** [comment]
Also like to add that Electron might be giving us wrong input compared when compiled to HTML5 for browser.

**Comment by RobDangerous** [comment]
So what targets are we actually talking about here? "trying it on macOS" means what exactly? Kode Studio? Krom? Native?

**Comment by lewislepton** [comment]
gah. knew i missed something.
its in kode studio

**Comment by RobDangerous** [comment]
Electron bug. Talked to Disar about it before. Should be fixed incidentally in the next version of Kode Studio as it seems to work in Chrome if I remember correctly.

**Comment by lewislepton** [comment]
ok. cool

**Comment by lewislepton** [comment]
thanks man
