### ISSUE TITLE
Flash Unhandled ErrorEvent: Context3D not available.

### ISSUE THREAD

**Issue by asdfgl3d** [Kode/Kha#595]
**OS:** `Windows 7 64-bit SP1`

**Haxe version:** `3.4.2`
**Kha version**: `1607 (github)`
**Command:** `node Kha\make flash (to create the project)`

Any implementation thing going on that I should know?
TIA.

**Comment by RobDangerous** [comment]
Nothing going on, sounds like something is wrong with your computer or your flash version. Did it work before? Is that in a webpage or in a flash debugger?

**Comment by thronecode** [comment]
What are you? F*ing omnipresent?? That was quick...

`Sounds like something is wrong with your computer or your flash version.`
Flash Player version 25. Standalone. (flashplayer_25_sa_debug if it helps you sleep at night).
What are common problems on Flash? 

`Did it work before?`
Nope, first attempt.

` Is that in a webpage or in a flash debugger?`
Debugger, but it doesn't work in a web page either.

I guess I'll just delete everything and setup up again, I'll come back with further results.

**Comment by RobDangerous** [comment]
Don't think it's a Kha specific thing. A google search for that error brings up a lot. Does other Stage3D content work?

**Comment by thronecode** [comment]
Yep, Away3D works just fine.

**Comment by RobDangerous** [comment]
Hm. The relevant line should be https://github.com/Kode/Kha/blob/master/Backends/Flash/kha/SystemImpl.hx#L58
You could try other Context3DProfiles.

**Comment by sh-dave** [comment]
Haven't used 25, but i tried a flash build of my app at work today and it works on debug flashplayer 16 + 19.

**Comment by RobDangerous** [comment]
Hm, nothing to do here I guess, but please reopen if you think otherwise and have further results.

**Comment by asdfgl3d** [comment]
Thanks, and I will come back to this later.

**Comment by sourceskyboxer** [comment]
Hello ,
But Kha is not good framework. I recommend NME, OpenFL / Lime better than Kha.
Away3D works for Openfl 5.1.3 and Away3D 5.0.2 fine.
I can not reproduce issues.
