### ISSUE TITLE
haxe.Timer not usable until Kha is initialized

### ISSUE THREAD

**Issue by wighawag** [Kode/Kha#610]
Now that haxe.Timer.stamp() use Scheduler behind the scene it does not work if used before kha is initialised.

I think haxe.Timer should work at any point

**Comment by RobDangerous** [comment]
stamp() looks like it should still work in any situation (the other Timer functions - not so much - but then again, up to now they didn't work at all on native targets). What targets did you test?

**Comment by wighawag** [comment]
It was html5

**Comment by RobDangerous** [comment]
And what happened exactly?

**Comment by wighawag** [comment]
it crash because performance is null 

performance is only initialised here : https://github.com/Kode/Kha/blob/master/Backends/HTML5/kha/SystemImpl.hx#L217

**Comment by RobDangerous** [comment]
ok, no more performance problems in Kha. performance is null in all other frameworks.

**Comment by wighawag** [comment]
:D

You have typo though : ```window.Data```

**Comment by RobDangerous** [comment]
Not any more.
