### ISSUE TITLE
Library adding dependencies

### ISSUE THREAD

**Issue by MuzikarM** [Kode/Kha#612]
So basically I'm trying to make a library dependent on hscript and I think it would be great if the end user of any library using kha could just add that library in their khafile.js and the dependencies of libraries would add automatically.

**Comment by sh-dave** [comment]
You should be able to just add it in the ```dependencies``` field of the libraries haxelib.json.

Lib2/haxelib.json:
```json
...
  "dependencies": {
    "Lib1": ""
  }
...
```

This should pick up Lib1 locally from /Libraries or haxelib.

**Comment by sh-dave** [comment]
Is the haxelib.json solution sufficient enough, or do you still need it handled via khamake?

**Comment by RobDangerous** [comment]
Please reopen if it isn't sufficient.
