### ISSUE TITLE
arrow keys don't seem to work on linux

### ISSUE THREAD

**Issue by 0xFireball** [Kode/Kha#614]
I compiled a Kha project for Linux, and everything is working fine except the arrow keys, which don't seem to be triggering any keydown event. Alphabetical keys seem to be working fine

**Comment by RobDangerous** [comment]
I can not reproduce that. https://github.com/Kha-Samples/BlocksFromHeaven works fine for me on Linux, can you test that one?

**Comment by 0xFireball** [comment]
All right, so I tested it again with Kha git, and it's working with that. In the version of Kha bundled with Kode Studio, the arrow keys worked on the HTML5 runner, but not on Linux.

Looks like the issue is no longer present then.

Thanks.
