### ISSUE TITLE
MultiWindow examples fail

### ISSUE THREAD

**Issue by zjnue** [Kode/Kha#618]
Hi. None of these examples currently seem to work:

 - https://github.com/Kode/Kha/tree/master/Tests/MultiWindow
 - https://github.com/armory3d/zui/tree/master/examples/MultipleWindows
 - https://github.com/r3d9u11/haxe-basics/tree/master/9_AdditionalLibraries/9.3_GraphicMediaEngines/9.3.2_Kha/9.3.2.1_Application/9.3.2.1.3_Multiwindow

**Comment by sh-dave** [comment]
Some :smiling_imp: person renamed Mode to WindowMode in commit https://github.com/Kode/Kha/commit/221259fa92dd31dd24821abe9c2d229fd0280c90 it seems.
Just ```import kha.WindowMode``` in your main and use ```WindowMode.BorderlessWindow``` (or whatever) to test until the examples are fixed.

**Comment by zjnue** [comment]
Hi, sadly that's not the real issue. I've made the small code fixes to get things compiling again. The problem is that windows only flash up for a split second before crashing.
Please try this command: node Kha/make windows --run

**Comment by sh-dave** [comment]
This won't work, i implemented the multiwindow stuff only for the opengl backend on windows, but it defaults to directx9 or 11 i think.

Try this ```node Kha/make windows --graphics opengl --run```.

**Comment by zjnue** [comment]
Aha! Very good to know, thanks 👍
