### ISSUE TITLE
iOS app crashing

### ISSUE THREAD

**Issue by dmitryhryppa** [Kode/Kha#630]
Hey,

I found that iOS app crashing on that line:
https://github.com/Kode/Kore/blob/master/Backends/System/iOS/Sources/Kore/GLView.mm#L215

To reproduce it, you need to minimize app and then maximize it again. 
And it happens only on real devices but not on simulators.

**Comment by Joncom** [comment]
@dmitryhryppa, is this still an issue? I've not noticed it...

**Comment by dmitryhryppa** [comment]
Probably not, because the code in that class was changed. The old one was with the comment about the crash. From Jun 2017:
```objc
- (void)end {
	glBindRenderbufferOES(GL_RENDERBUFFER_OES, colorRenderbuffer);
	[context presentRenderbuffer:GL_RENDERBUFFER_OES]; // crash at end
}
```

So I think it can be closed by now.
