### ISSUE TITLE
Error compiling with custom shaders

### ISSUE THREAD

**Issue by whuop** [Kode/Kha#633]
I've been having trouble compiling my project with custom shaders, and there is no error indicating what went wrong.

The output i get is:
```
Using Kha from d:\KodeStudio\resources\app\extensions\kha\Kha
Creating Kha project.
Compiling shader 1 of 2 (simple_frag.glsl).
Usage: krafix profile in out tempdir system
Launch canceled.
```

Minimal project with reproduced error: 
[https://github.com/whuop/KhaShaderTest](url)

I'm using KodeStudio and the version of Kha that comes with it:
![image](https://user-images.githubusercontent.com/1681274/28823282-162fb420-76bd-11e7-95f9-f2f3c435787d.png)

**Comment by RobDangerous** [comment]
Does this still happen with Kode Studio 17.9?

**Comment by RobDangerous** [comment]
Oh, no response :(
