### ISSUE TITLE
shader compilation problem when using --to option

### ISSUE THREAD

**Issue by romamik** [Kode/Kha#638]
Steps to reproduce: 
1) call `kha --init`
2) add shaders to the project 
`addShaders("Shaders")` in khafile,
put some shader in Shaders folder
3) build with `kha html5 --to ..\build\html5`

For me this gives: `Error: ENOENT: no such file or directory, rename 'c:\projects\ttt\html5\html5-resources\outline.frag.essl.temp' -> 'c:\projects\ttt\html5\html5-resources\outline.frag.essl' at Object.fs.renameSync (fs.js:771:18)`

PS Windows 10, latest kha from git

**Comment by romamik** [comment]
I've made a little investigation and found possible reason:
Here is part of the krafix output for path not starting with `..`:
```
#file:build\html5\html5-resources\outline.vert.essl.temp
#file:build\html5\html5-resources\outline-relaxed.vert.essl.temp
#file:build\html5\html5-resources\outline-webgl2.vert.essl.temp
```
And here is the same part for path starting with `..`:
```
#file:..\build\html5\html5-resources\outline.vert.essl.temp
#file:-relaxed..\build\html5\html5-resources\outline.vert.essl.temp
#file:-webgl2..\build\html5\html5-resources\outline.vert.essl.temp
```
In the first case it actually creates 3 files with these names. 
But in the second case it creates only one file `..\build\html5\html5-resources\outline.vert.essl.temp` (I think it overwrites it 3 times...) 
And in `ShaderCompiler.ts` `compiledShader.files` is an array of 3 same filenames. It tries to rename ".essl.temp" files to ".essl" and for first element of the array it works ok but for second it fails because file is already renamed.

I see two possible solutions:
1) Fix krafix so that it works with relative paths starting with `..`. I did not look at krafix code and I'm not sure I really want to do that.
2) Invoke krafix with absolute url as parameter. That was easy and it worked: https://github.com/Kode/khamake/pull/108

**Comment by RobDangerous** [comment]
I like the easy fix. Thanks.

**Comment by romamik** [comment]
Oops, I've found that these changes break things. No krafix does not generate "-webgl2" version at all. And at runtime it's required to run... 
Currently no idea why this can happen.

**Comment by romamik** [comment]
My bad: https://github.com/Kode/khamake/pull/109

**Comment by RobDangerous** [comment]
Thanks again.
