### ISSUE TITLE
android-native build 

### ISSUE THREAD

**Issue by romamik** [Kode/Kha#640]
Blank Kha project is not compiling with Android Studio. Errors:

    Kha\Kore\Backends\Graphics4\OpenGL\Sources\Kore\TextureImpl.cpp:358:2: error: use of undeclared identifier 'glTexImage3D'
    Kha\Kore\Backends\Graphics4\OpenGL\Sources\Kore\TextureImpl.cpp:365:33: error: use of undeclared identifier 'GL_TEXTURE_WRAP_R'

**Comment by luboslenco** [comment]
Can you test https://github.com/Kode/Kore/pull/206?

**Comment by romamik** [comment]
Yes, it's working with these changes.
