### ISSUE TITLE
ToCharArray() function

### ISSUE THREAD

**Issue by tienery** [Kode/Kha#641]
I think that now we have the `drawCharacters` function inside of `kha.graphics2.Graphics`, it would be useful to have a convenient `toCharArray` function that would be useful in an extension class somewhere in Kha, but I'm not sure -- if I were to make the change myself -- where to put it.

I looked at the `SuperString` class, but that looks like a C++-specific thing, so it doesn't seem feasible to place such a function there. Nevertheless, here is the code for the function:

```haxe
package;

class StringExtension
{
    
    public static function toCharArray(s:String):Array<Int>
    {
        var results = new Array<Int>();
        for (i in 0...s.length)
            results.push(s.charCodeAt(i));
        return results;
    }

}

```

Then to use it, you just need to do:

```haxe
package;

using StringExtension;

class Main
{

    public static function main()
    {
       var chars = "This is some text".toCharArray();
       ....


    ....
    buffer.g2.drawCharacters(chars, 0, chars.length, 12, 12);
    ....
}
```

**Comment by RobDangerous** [comment]
Can't think of any better place to put it either, so it's in like that. Thanks!
