### ISSUE TITLE
Image.createRenderTarget color difference

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#652]
A copy of the translucent image from Image.createRenderTarget has a different color tint.
Code: https://gist.github.com/RblSb/1b6f8da91bc04ca1e801e92482a666e0
Image: http://i.imgur.com/uIn8hqP.png
Results (flash/html5-canvas):
![default](https://user-images.githubusercontent.com/8753432/29999532-4decb0be-9055-11e7-8fca-e376ad38fb3f.png)
Results (html5-webgl):
![default](https://user-images.githubusercontent.com/8753432/29999533-58073a2e-9055-11e7-8c3b-b8fa55614845.png)

**Comment by RobDangerous** [comment]
Aha. The bug seems to be in flash. Kha uses premultiplied alpha which is lost when you render an image to a render target so blending has to be changed to alpha/1-alpha then. Don't yet know why it works in flash like that...
canvas is a bit restricted when it comes to blending sadly.

**Comment by RblSb** [comment]
At the moment I'm using the current pipeline to save the correct colors in render targets (thanks @dmitryhryppa!)
```haxe
#if kha_g4
import kha.Shaders;
import kha.graphics4.BlendingFactor;
import kha.graphics4.PipelineState;
import kha.graphics4.VertexData;
import kha.graphics4.VertexStructure;
...
_struct = new VertexStructure();
_struct.add("vertexPosition", VertexData.Float3);
_struct.add("texPosition", VertexData.Float2);
_struct.add("vertexColor", VertexData.Float4);

_pipeline = new PipelineState();
_pipeline.inputLayout = [_struct];
_pipeline.vertexShader = Shaders.painter_image_vert;
_pipeline.fragmentShader = Shaders.painter_image_frag;
_pipeline.blendSource = BlendingFactor.BlendOne;
_pipeline.blendDestination = BlendingFactor.BlendZero;
_pipeline.alphaBlendSource = BlendingFactor.BlendOne;
_pipeline.alphaBlendDestination = BlendingFactor.BlendZero;
_pipeline.compile();
...
g.pipeline = _pipeline;
#end
```

**Comment by riseremi** [comment]
Any progress on this?

**Comment by RobDangerous** [comment]
No, flash target is very low priority for me nowadays.

**Comment by RblSb** [comment]
@RobDangerous, but I think that the behavior of flash about the colors in renderTargets is correct. It would be nice if all g4 targets also used such a blending mode to save translucent image colors.

**Comment by RobDangerous** [comment]
I agree that g2 should blend images and render targets the same way - but please create a separate issue for that because flash/everything else blending differently is a separate topic.

**Comment by RobDangerous** [comment]
So this specific issue can sadly not be fixed because Flash does not support separate blending modes (that said, fixing the other issue will at least make the standard blending equivalent I think).
