### ISSUE TITLE
drawSubImage with float x/y

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#654]
Code: https://gist.github.com/RblSb/5f410dbe15ab492690a6abf8bf5fb3e6
```haxe
g.drawSubImage(
img, 10.5, 10.5,
0, 0, 100, 100
);
```
Result on html5-webgl:
![default](https://user-images.githubusercontent.com/8753432/30198888-dcf13f9c-9478-11e7-8297-63e684ce2ee1.png)
Itself img on the right. I think this is a bug (blue strip of 1px)?

**Comment by wighawag** [comment]
https://gist.github.com/RblSb/5f410dbe15ab492690a6abf8bf5fb3e6#file-main-hx-L25

should not this line be : ```g.fillRect(0, 100,100, 200);``` ?

**Comment by RblSb** [comment]
@wighawag fillRect is (x, y, width, height), not a (x, y, x2, y2) :)

**Comment by wighawag** [comment]
ah yes, sorry

**Comment by RobDangerous** [comment]
This happens when imageScaleQuality is set to high. It's normal bilinear filtering behavior. You start at half a pixel so the last pixel filters into the next pixel - it's not a blue strip, it's a mix of red and blue.

**Comment by RblSb** [comment]
@RobDangerous I get this problem with imageScaleQuality = Low, then this is a bug?

**Comment by RobDangerous** [comment]
Can not reproduce, no blue line in Electron for me. What browser?

**Comment by RblSb** [comment]
@RobDangerous latest Firefox/Chrome and Kode Studio Electron, same for my friend. Also, imageScaleQuality is Low by default?

**Comment by RobDangerous** [comment]
Yes, it's low by default. And I can't reproduce your problem on any of those browsers. Here's the project I'm testing: http://kodegarden.org/#cd70aec5416bf1d6e478d7a48758f6b039ea358b

**Comment by RobDangerous** [comment]
Hey, I can reproduce that on my Mac. Nothing we can do about it though, avoid edge cases like that.
