### ISSUE TITLE
Status on VR

### ISSUE THREAD

**Issue by primesoftware** [Kode/Kha#658]
Just curious what the status of the VR target is..... I heard Khronos is coming out with OpenXR for HMDs but its not ready yet. Where does Kha stand with current implementations of VR?

**Comment by RobDangerous** [comment]
Kha has WebVR and Kore has SteamVR, Rift and a pull request for HoloLens - but we need to update the Kha/Kore VR interface.

PS: There's a forum for questions at http://forum.kode.tech
