### ISSUE TITLE
TextField...

### ISSUE THREAD

**Issue by cjmxp** [Kode/Kha#666]
Whether or not you can add TextField, the three party GUI library is not that easy to use

**Comment by tienery** [comment]
I've just uploaded my TextBox project which was going to be closed source until I made any effort to create a feature-rich GUI based on my engine, Twinspire, but seeings as how you seem so desperate for one, here: https://github.com/tienery/KhaTextBox

**Comment by RobDangerous** [comment]
Thanks tienery, super cool!

**Comment by cjmxp** [comment]
Thanks
