### ISSUE TITLE
.SWF files do not display in HTML file

### ISSUE THREAD

**Issue by VeronMin** [Kode/Kha#668]
When I create an SWF file with: node Kha/make flash -  the flash layer can display the file, but
using SWFObject in the HTML file it does not show the display.  I use SWFObject in HTML
files to display SWF files compiled with Haxe in HaxeDevelop.  Is this broken in Kha?  Also
using: node Kha/make html5 produces an html file which only displays a black rectangle.

**Comment by sh-dave** [comment]
Flash: I think you have to set 'wmode = direct' or something as Kha only uses Stage3d.
Html5: Depending on the browser, you actually have to serve the build/html5 folder, as the browser isn't allowed to access local files. So try to run a ```node Kha/make html5 --server``` and then connect to the port shown in the console.

**Comment by RobDangerous** [comment]
All done here, right?
