### ISSUE TITLE
Is it possible to add external libraries to hxcs?

### ISSUE THREAD

**Issue by qntf** [Kode/Kha#669]
I am trying to add some custom C# libraries to my program, and see this described here:
https://github.com/HaxeFoundation/HaxeManual/wiki/Haxe-C%23

With hxcs you can pass in `-net-lib library.dll` to allow using an external .NET library.

Is this possible with Kha/khamake?

**Comment by tienery** [comment]
See this on the wiki page: https://github.com/Kode/Kha/wiki/khafile.js

Or, to put it simply, add the following line into `khafile.js`:

```
project.addParameter('-net-lib library.dll');
```

You may want to add some conditionals to separate C#-specific builds from generic ones.

Like say:

```
let c_sharp_build = false;
let project = new Project("New Project");
if (c_sharp_build)
{
    project.addParameter('-net-lib library.dll');
}
// other project building stuff
```

**Comment by qntf** [comment]
Thanks!
