### ISSUE TITLE
Cannot build for Windows x86 - "Project file not found"

### ISSUE THREAD

**Issue by prabab** [Kode/Kha#671]
The image is pretty self explanatory. MSBuild says that project file doesn't exist, even if it's clearly there. What am I doing wrong?
![image](https://user-images.githubusercontent.com/5394904/31692137-e1cccb46-b398-11e7-83d1-b95bb57f3324.png)
I don't have any special characters in the path to the project folder.
I'm using Windows 10, if that's any help.

Update 1: I've tried manually changing the build.bat to include the full path to file and after that the project compiled, however it still doesn't work in the end - as soon as I launch the EXE file, it turns off.
Update 2: After copying resource files from the /windows folder to the newly created /Release folder - the game works! But I'm not very fond of these extra steps and if possible would've preferred to avoid them in the first place.

**Comment by sh-dave** [comment]
Try to run the cmdline manually and see if that changes anything.
In your project folder run:

```shell
node Kha/make windows --run
```

This should build the project files, compile, and run the project.
As an alternative just open the generated sln file in MSVC.

**Comment by prabab** [comment]
So, this is what happens:
![image](https://user-images.githubusercontent.com/5394904/31714813-a9fd038e-b401-11e7-9c6b-18868d8488fa.png)
I've installed Haxe and Kha following the Lewis Lepton's tutorials. I'm not that good at Node, but it seems like there's something I still need to do to have everything working properly?

After compiling the project from .sln, the result is pretty much the same as when I modified .bat to contain full path to the project, meaning that there's tons of unnecessary weird files left in the /Release folder and all assets still need to be copied in there manually. Or is this the expected behaviour?

**Comment by sh-dave** [comment]
- you don't need to install haxe at all, it's already included in Kha/Tools/haxe
- for the posted cmdline to work you have to have Kha in your project folder or adjust the 'Kha/make' path accordingly, say ```node c:/SomeDirectory/Kha/make windows --run```
- depending on what MSVC you're using, you might also need to add a ```--visualstudio vs2013``` parameter (i think the default is vs2017 nowadays?)
- if you run your app from inside MSVC (or from cmdline with --run) you shouldn't need to copy anything

**Comment by prabab** [comment]
Through cmd, after navigating to project's folder and entering **Kha/make windows --run**, I get the same error as before: "Project file does not exist".
![image](https://user-images.githubusercontent.com/5394904/31718067-cafcba9a-b40e-11e7-9717-95a9ca1d08cb.png)

As for the vs2013, I get a "--compile not yet implemented on this platform" error.

**Comment by RobDangerous** [comment]
Can you open and compile the vcxproj in Visual Studio?

**Comment by sh-dave** [comment]
No, you shouldn't have to install vs2013, it was just an example (i overlooked that it actually says vs2017 in the screenhost in your opening post).

It seems you run a (i think) polish windows?, so do you maybe have "strange characters" in your path especially in the blacked out parts (something with accents/ticks like ```Ù``` or some such) that might be a problem?

Also your projects seems to be on drive D:\ and your Kha on C:\, maybe that causes path problems as well. You could try to put them both on the same drive for testing.

**Comment by prabab** [comment]
@RobDangerous 
![image](https://user-images.githubusercontent.com/5394904/31718747-4825f200-b411-11e7-9f5d-cac26567cba9.png)
This is what VS told me after opening the vcxproj.

So, I did this "retarget solution" thing and the app builds and it did compile. But I encountered the same issue as before:
* Tons of OBJ files in Release folder (is this intended?)
* Assets need to be copied manually to the build folder, which is not a huge issue as for now, but since there's not much documentation on this subject there's no way for me to find out where exactly should files go when I'm involved in more robust projects.

@sh-dave 
No unusual characters in the path, not even spaces as for now. To get a clean state I've uninstalled Haxe (since you mentioned Kode Editor is self sufficient) and moved Kode to the same drive as project... But I think I might have... broken something? Not exactly sure what's going on here.
![image](https://user-images.githubusercontent.com/5394904/31719582-384e8470-b414-11e7-82e2-6bcc55072757.png)

So, to reiterate, here's what happens with every approach I tried:
* F1 -> Compile Kha project: "Project file does not exist", does not compile
* Kha/make windows: "Project file does not exist", does not compile
* Editing .bat to include full project path: Compiles, no assets, tons of OBJ files
* Compiling through VS .sln = Compiles, no assets, tons of OBJ files
* Compiling through VS .vcxproj = Compiles, no assets, tons of OBJ files

**Comment by sh-dave** [comment]
Can you run the project in VS (via F5), because the working directory should point to ```/build/windows``` (where the exported assets are located)? Check with:
1) rightclick on your project -> properties
2) in the dialog go to 'Configuration Properties' -> Debugging
3) check the 'Working Directory' path. It should point to an absolute path to your project/build/windows

![image](https://user-images.githubusercontent.com/13007175/31720940-42d70b2a-b418-11e7-9c4d-8ffe30263aaf.png)

Yes, ton's of obj files for c++ builds is normal. You basically get a cpp file for every single haxe class.

**Comment by prabab** [comment]
@sh-dave 
* I've removed the /build directory (Old path to Kha was still in .vcxproj)
* Triggered F1 -> Compile -> Windows in Kode Studio
* Three new directories were created and filled with files - _/build/windows, /build/windows-resources, /build/windows-build_
* Kode Studio output once again said that compilation failed because project file does not exist.
* I've opened the .vcxproj from _/build/windows-build_ in VS2017.
* Working directory seems to be ok: ![image](https://user-images.githubusercontent.com/5394904/31721986-21cb5276-b41b-11e7-8987-8255b8151b49.png)
* Run F5 to build the project, got a message that project is outdated, built it any way.
![image](https://user-images.githubusercontent.com/5394904/31722747-3270f386-b41d-11e7-8aa1-1a33c96034b4.png)
* The project compiled successfully, but into _/windows-build/Debug_ directory instead of _/windows_. Working directory is set to _/windows_ in all compilation targets.
* The created _/windows-build/Debug_ directory doest not contain assets.

**Comment by RobDangerous** [comment]
With the exception of the "project file does not exist" thing that's all as it should be. Kha is designed to be minimally invasive to native development in Visual Studio, Xcode,...
The whole object files chaos, exe in Debug/Release,... all of that is standard Visual Studio behavior. Assets are exported to build/windows - to ship something grab the exe from build/windows-build/Release and copy it to build/windows. During development you should usually use the exe from build/windows-build/Debug.

**Comment by prabab** [comment]
@RobDangerous Thank you, that's a relief. It's good to know that I can still build projects despite of this weird issue, even if it needs some additional steps to go through with it.
What else might be causing the problem with VS saying that project file doesn't exist?
* Kode Studio and project are on the same drive.
* There are no special characters or spaces in the path.

**Comment by Jarrio** [comment]
After I reinstalled windows I am also experiencing this issue. I am running `Windows 10 | x64 | UK | English`. Same setup as before, the only thing that has really changed in my setup is the new windows update that was released maybe around a week or two ago?

My project file exists, the path is correct and contains no special characters or spaces. But prior to the reinstall everything worked fine. I am also unable to compile the project at all for cpp windows

**Comment by RobDangerous** [comment]
Same question, can you open and compile the vcxproj in Visual Studio?

**Comment by Yanrishatum** [comment]
Pretty much same log as with Jarrio, except VS17 prompt version is 15.4.5 and different Kha path (`E:\HaxeToolkit\kha`).  
Same thing both for manual `kha -t windows --compile` command and via Kode F1 -> Compile Kha Project -> Windows or Windows Universal.  
Opening .sln file and compiling manually do work.  
Win10x64

**Comment by RobDangerous** [comment]
Sadly I can't reproduce at all. Tried the fanciest paths to no avail. The build process creates a build.bat file in build/windows-build and just calls that. Does that file work when you run it manually? Do the contents look ok? For me it looks like
```
@call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
@MSBuild.exe "Blocks.vcxproj" /m /p:Configuration=Release,Platform=Win32
```

**Comment by Yanrishatum** [comment]
No it doesn't. As I said - in my case (and I'm pretty sure in all other cases of "not found" in this issue) first line with call of `vcvars32.bat` changes current directory, resulting in second line failing. And if I edit it to go back to proper directory, compilation fails with whooping 366 errors, probably because my CMD doesn't have all environmental variables set as it expects. And if I try to compile it via calling kha - it regenerates build.bat and removes directory fix.

**Comment by RobDangerous** [comment]
Ah, I missed your current dir comment. That shouldn't happen. And your system prints a lambda on both lines instead of the @ (which in batch files just means don't print this line). That's weird though because @ is ASCII. I'll removed it for now, maybe it helps.

**Comment by Yanrishatum** [comment]
It shows lambdas because I use Cmder for primary console host :) But same thing happens in just plain CMD:
<details><summary>cmd.exe log</summary><p>

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Yanrishatum>cd C:\_work\2017\khatest\build\windows-build

C:\_work\2017\khatest\build\windows-build>build.bat
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.5
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: Khatest.vcxproj

C:\Users\Yanrishatum\source>
```
</p></details>

Removing `@` does not solve the problem. It seems that is a bug in VS where some versions of vacvars by some reason change current directory. [Source](https://developercommunity.visualstudio.com/content/problem/134471/vcvarsallbat-changes-current-directory.html)

**Comment by RobDangerous** [comment]
Aha. OK, that's fixed then. Thanks a lot for the help. @Jarrio and @prabab please re-check.

**Comment by RobDangerous** [comment]
Please reopen if you still run into issues.
