### ISSUE TITLE
Outdated XNA backend

### ISSUE THREAD

**Issue by 0xFireball** [Kode/Kha#677]
Looks like the XNA backend is out of date:
<https://github.com/Kode/Kha/tree/master/Backends/XNA/kha/xna>

Are there plans to continue supporting this platform?

If I may make a suggestion, since XNA is now dead, MonoGame is a current implementation of the XNA APIs. Maybe this could be a MonoGame/C# backend instead.

But the latest MonoGame is now using SDL2 anyway, so it might be unnecessary to target another abstraction layer.

I'm not sure, but I think that SDL2 is comparable to Kore?

**Comment by dmitryhryppa** [comment]
What is a point to maintain XNA/MonoGame backend? IMHO, but it's a waste of time nowadays. 
Currently Kha has official consoles support... :)
Would be better to focus on D3D11, D3D12 targets :P

**Comment by RobDangerous** [comment]
Yes. I thought about MonoGame support but now that we have proper console support I think I'll just remove the backend. And yes, SDL2 is comparable to Kore - but it doesn't do graphics, which is the interesting part.

**Comment by 0xFireball** [comment]
Yeah, that makes sense. I was just curious.
Thanks!
