### ISSUE TITLE
Vertex & Fragment shader errors when compiling for windows & iOS

### ISSUE THREAD

**Issue by FuzzyWuzzie** [Kode/Kha#678]
(I think this also affects iOS, but I will check again later when I have access to my OSX box again)

When trying to compile the generated windows project, using [Kha @ 8842de7](https://github.com/Kode/Kha/tree/8842de72a7b1004cebb71d1ca1f8de689a06b0d9), I get the following errors:

| Severity | Code | Description | Project | File | Line | Suppression State |
|-|-|-|-|-|-|-|
| Error | C2664 | `Kore::Graphics4::Shader::Shader(Kore::Graphics4::Shader &&)`: cannot convert argument 1 from `unsigned char *` to `const char *` | ... | ...\build\windows-build\sources\src\kha\graphics4\vertexshader.cpp | 48 | 
| Error | C2039 | `get_length`: is not a member of `kha::internal::BytesBlob_obj` | ... | ...\build\windows-build\sources\src\kha\graphics4\fragmentshader.cpp | 48 | 
| Error | C2664 | `Kore::Graphics4::Shader::Shader(Kore::Graphics4::Shader &&)`: cannot convert argument 1 from `unsigned char *` to `const char *` | ... | ...\build\windows-build\sources\src\kha\graphics4\fragmentshader.cpp | 48 | 
| Error | C2039 | `get_length`: is not a member of `kha::internal::BytesBlob_obj` | ... | ...\build\windows-build\sources\src\kha\graphics4\vertexshader.cpp | 48 | 

Android and HTML5 targets seem unaffected.

**Comment by FuzzyWuzzie** [comment]
Same error for iOS:

```
.../build/ios-build/Sources/src/kha/graphics4/FragmentShader.cpp:48:89: No member named 'get_length' in 'kha::internal::BytesBlob_obj'
```

**Comment by sh-dave** [comment]
get_length() is a DCE error iirc, so try to build without DCE.

**Comment by FuzzyWuzzie** [comment]
Ahh, that kind of makes sense. Sucks that DCE gets rid of critical functionality though. There must be a way to force Haxe to not cut it?

**Comment by sh-dave** [comment]
A couple of classes still need an @:keep to not be considered by DCE
