### ISSUE TITLE
[Feature req] Gamepad input on Linux (Krom and native C++)

### ISSUE THREAD

**Issue by guzzard** [Kode/Kha#680]
Please add gamepad/joystick support for native c++ and Krom on Linux.

**Comment by guzzard** [comment]
Hi @RobDangerous, I have been working on Linux gamepad input ..It's working now and I'm currently testing, cleaning up etc and will try to send a pull request in a couple of days, which you can review and give feedback on.

**Comment by RobDangerous** [comment]
Cool Spot

**Comment by guzzard** [comment]
Pull req: https://github.com/Kode/Kore/pull/232

**Comment by guzzard** [comment]
Renaming this issue into a feature req instead.. :-)

**Comment by guzzard** [comment]
Initial implementation done! https://github.com/Kode/Kore/pull/237, https://github.com/Kode/Kore/pull/238
