### ISSUE TITLE
Disable WebVR??

### ISSUE THREAD

**Issue by FuzzyWuzzie** [Kode/Kha#696]
Every time I load an HTML5 build with the latest firefox, it starts up SteamVR and becomes a big pain in the butt all because Kha is setting up WebVR when I don't want it to. Is there any way to disable VR?

**Comment by RobDangerous** [comment]
No way, Kha's WebVR support will haunt you forever.

**Comment by sh-dave** [comment]
Just to make sure everyone is on the same page, you have to use

`node kha/make html5 --vr webvr`

to enable it now.
