### ISSUE TITLE
[MINOR BUG?] shader crashes once fixed

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#697]
this is a minor thing ive noticed since learning shaders.
whilst debugging is fine, i can find what i need, but say if a shader does not work due to a bug. i can fix it, but then on running again, it crashes the running application.

pointing right to `PipelineState.hx` on line 87. now the shader does work, its just seems that there is this overloading or whatever it could be.
i know the shader works, since this happens. so have to then try again, then it works perfectly as it should.

its just the weird crash prior to the working shader running after its had a crash before due to an actual error that was fixed

latest public release of KS with latest git committed kha

this is a screenshot of where it takes me when i first run the now working shader after fixing the bugs
<img width="877" alt="screen shot 2017-11-21 at 12 53 09" src="https://user-images.githubusercontent.com/11299322/33073682-90773a72-cebb-11e7-8962-3da6a0a6087b.png">

**Comment by RobDangerous** [comment]
What the exception message?

**Comment by lewislepton** [comment]
just tried again, but i cant find a message in any of the console/error windows to see if there is one. all that pops up is the screenshot from before & a crash

**Comment by RobDangerous** [comment]
You can see the exception message in the variables panel in the debug panel to your left.

**Comment by lewislepton** [comment]
ah, oh yeah. here it is in screenshot form as i cant seem to copy the text
<img width="1419" alt="screen shot 2017-11-21 at 18 10 46" src="https://user-images.githubusercontent.com/11299322/33089096-85b60164-cee7-11e7-8656-e9fdecc2ce54.png">

**Comment by gmisail64** [comment]
i opened a brand new project and i got this too. i don't know if @lewislepton found the solution or if it is a bug on my side. kode studio wasn't doing this to me before, so i am pretty lost as to why the error is occurring.

**Comment by lewislepton** [comment]
i mean. it does work once you run it again. its this weird thing where once fixed, it crashes, then try again. its fine.
im sure that this is on the list of being looked at. but really, there is a lot of other things to do in terms of kha/kode studio etc

lets just hope its something simple

**Comment by RobDangerous** [comment]
Everything is being looked at (unless I close it).

**Comment by gmisail64** [comment]
mine breaks every time i run it, something must be up with my versions of haxe or kha

**Comment by lewislepton** [comment]
in kha, it runs its own version of haxe. i do need to do an update video of some things to clear stuff up

**Comment by gmisail64** [comment]
oh, in that case im kind of stumped. it was working the last time i used it before i used godot for a little bit. it must be kha cursing me for leaving it

**Comment by gmisail64** [comment]
the workflow works fine with the latest kha version in the git workflow when exporting to html5. must be a kode studio issue.

**Comment by gmisail64** [comment]
nevermind, it was an issue with my node.js version. my node version was not compatible with the current version of khamake.

**Comment by RobDangerous** [comment]
Hey, I fixed it, was some shader-compile-info-caching thing.
