### ISSUE TITLE
html5 black canvas if compiled on phone

### ISSUE THREAD

**Issue by CoruNethron** [Kode/Kha#698]
Tested such weird scenario to compile from android phone.
Environment:
nexus5 / Android 6.0.1 / Kali nethunter chroot
nodeJs 6.12.0 (also tested with nodeJs 9.2.0)

To reproduce:
git clone https://github.com/Kha-Samples/Shader --recursive
cd Shader
node Kha/make html5
cp ./build/html5/* /sdcard/

#then navigate to sd card with file manager and open index.html

Tested with chrome mobile (WebGL 2.0 enabled) and firefox mobile
Also tested with chrome under Win7

Always black khanvas, instead of red triangle.

Same scenario under Windows behaves well, but compiled kha.js differs.

**Comment by RobDangerous** [comment]
Why does the compiled kha.js differ? Also generally you should not open index.html directly because then browser security things can kick in, load it from a webserver instead.

**Comment by Disar** [comment]
For a quick server you can use 

`node Kha/make --server`

Then simply connect to your local address. Should work, if not you'd have to add some port fowarding in your router.

**Comment by CoruNethron** [comment]
Tested with local server on port 8080, the result is same - black canvas.
I'll check - how exactly kha.js differs, compared to build under Windows and report soon.

**Comment by CoruNethron** [comment]
Log, taken with "diff -u":
[kha.log](https://github.com/Kode/Kha/files/1502142/kha.log)

Most attracting changes looks like:
```
 -	kha_Shaders.shader_frag = new kha_graphics4_FragmentShader(blobs,["shader.frag.essl"]);
 +	kha_Shaders.shader_vert = new kha_graphics4_VertexShader(blobs,["shader.vert.essl","shader-relaxed.vert.essl","shader-webgl2.vert.essl"]);
```

or

```
 -	kha_Shaders.shader_vert = new kha_graphics4_VertexShader(blobs1,["shader.vert.essl"]);
 +	kha_Shaders.shader_frag = new kha_graphics4_FragmentShader(blobs1,["shader.frag.essl","shader-relaxed.frag.essl","shader-webgl2.frag.essl"]);
```

Where long array generated on Desktop and short array generated on mobile.
Also, Base64 shaders differ, but it's likely consequence of highlighted differences.

**Comment by CoruNethron** [comment]
Found way to resolve the issue in my case:

```
cd ~
git clone https://github.com/Kha-Samples/Shader --recursive
git clone https://github.com/ktxsoftware/koremake
git clone https://github.com/Kode/krafix --recursive
cd ~/krafix
node ~/koremake/koremake.js --compile
cp ~/krafix/krafix ~/Shader/Kha/Kore/Tools/krafix/krafix-linuxarm
cd ~/Shader
node Kha/make html5
```

Now all works fine with both "open index.html directly" and "node Kha/make.js --server" ways.
Both Firefox mobile and Chrome mobile renders a nice red triangle.

Please close the issue as soon, as you wish.

**Comment by RobDangerous** [comment]
Oh, now I understand it (read your last messages out of context in GitHub's mails and was just confused). The linuxarm build of krafix is not up to date, that's all there is to it. Will close the issue once I updated it...

**Comment by RobDangerous** [comment]
Hey, I updated it at some point.
