### ISSUE TITLE
video support

### ISSUE THREAD

**Issue by saveriocastellano** [Kode/Kha#7]
Hello, 

I'm trying to embed a video in my kha application, I have added the video asset to the project.kha but the video does not seem to be considered (it does not end up being in the build directory that gets generated together with the other assets).

Also, in Video.hx I don't see anything to position and size the video, are videos currently displayed in overlay at a fixed position and original size?

**Comment by RobDangerous** [comment]
Video support is now pretty nifty with hardware accelerated decode everywhere but on Linux.
