### ISSUE TITLE
4 bytes for color in vertex data?

### ISSUE THREAD

**Issue by romamik** [Kode/Kha#700]
http://forum.kode.tech/topic/186/4-bytes-for-color-in-vertex-data

Color is 4 bytes, but we are using 4 floats in vertex data for color, which is 16 bytes.
In opengl we can specify GL_BYTE in glVertexAttribPointer and vec4 in shader and it will interpret our 4 bytes as 4 floats.
Is something like this possible in kha?

For just one color it's ok, but I want to pass color matrix to shader and using 12 (or even 20 if it should affect alpha) floats per vertex for that feels too expensive.

**Comment by romamik** [comment]
PS you mention Kore in forum, but what about html5?

**Comment by RobDangerous** [comment]
Fixed.
