### ISSUE TITLE
Unable to debug "Unknown Exception"

### ISSUE THREAD

**Issue by CoruNethron** [Kode/Kha#702]
Compiled simple project with zui Library from https://github.com/armory3d/zui
`node Kha/make windows -v vs2015`

Then compiled project within VS2015.

When running Debug or Release configuration (any of Win32 or x64), attached to debugger - all fine and works like expected.
But if I run executable, then I get a message box, stating "Unknown Exception".

I tried to comment "#ifndef _DEBUG" within Kha\Kore\Backends\System\Windows\Sources\Kore\System.cpp WinMain() , so I expect to catch the same message box when debugger is attached. But it still runs normal, without any exceptions, when debugger is attached.

Please, give me a hint, if you have an idea - how to catch - where this exception comes from.

**Comment by RobDangerous** [comment]
Copy the .exe to build/windows and run it from there.

**Comment by CoruNethron** [comment]
That do the trick. Thank you, @RobDangerous 
I've tried to copy whole "Assets" folder into the folder, containing *.exe

**Comment by RobDangerous** [comment]
The build/windows folder plus the exe file is also generally what you can ship. It's the usual Visual Studio workflow, I generally try to keep close to the original workflow for any given target system.

**Comment by CoruNethron** [comment]
Not sure to open new issue, but I have one more trouble with the same symptoms.

Created simple ndll, like this:
tstar.cpp:
```
#define IMPLEMENT_API

#include <hx/CFFI.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>

extern "C" {
	value Sum(value x, value y) {
		return alloc_int( val_int( x ) + val_int( y ) );
	}
	value Sub(value x, value y) {
		return alloc_int( val_int( x ) - val_int( y ) );
	}
	value Mul(value x, value y) {
		return alloc_int( val_int( x ) * val_int( y ) );
	}
	value Div(value x, value y) {
		return alloc_int( val_int( x ) / val_int( y ) );
	}
}
DEFINE_PRIM(Sum, 2);
DEFINE_PRIM(Sub, 2);
DEFINE_PRIM(Mul, 2);
DEFINE_PRIM(Div, 2);
```

Compiled it with: `g++ ./tstar.cpp -shared -o ./bin/tstar.ndll -I../../hxcpp/include`

And get `tstar.ndll`

Created com/corunethron/Ar.hx:
```
package com.corunethron;

class Ar {
    public static var Sum:Int->Int->Int = cpp.Lib.load("tstar", "Sum", 2);
    public static var Sub:Int->Int->Int = cpp.Lib.load("tstar", "Sub", 2);
    public static var Mul:Int->Int->Int = cpp.Lib.load("tstar", "Mul", 2);
    public static var Div:Int->Int->Int = cpp.Lib.load("tstar", "Div", 2);
}
```

Finally added into Main.hx:
```
import com.corunethron.Ar;
//...
if( ui.button("Button") ){
    trace(Ar.Sum(2, 3));
    trace(Ar.Sub(2, 3));
    trace(Ar.Mul(2, 3));
    trace(Ar.Div(2, 3));
}
//...
```

And got the message box, stating "Unknown Exception" again, once Button is clicked.

I've tryed to add tstar.ndll into Assets folder and / or into build/windows folder along with compiled *.exe
Also now Exception comes with debugger attached as well. It says:
`Exception thrown at 0x76F1C54F in HydGraph.exe: Microsoft C++ exception: Dynamic at memory location 0x0032FB60.`

Just to clarify - I don't need to outsource arithmetical operations into c++, it's just for test. I need ndll to perform communication with COM port, using Modbus interface.

It's likely, that I just doing something wrong, maybe just need some compile flag for haxe to load that *.ndll ? Also, likely, that this issue is not related to Kha.

**Comment by RobDangerous** [comment]
I can't really help here because I know nothing about ndlls, but you can instruct Visual Studio to break when an exception is thrown. We also have a forum for questions at forum.kode.tech

**Comment by sh-dave** [comment]
To use c++ you don't actually need ndll's (i think, b/c i don't know anything about them either). See here for alternatives:

* https://github.com/luboslenco/kha_callcpp
* https://github.com/luboslenco/kha_calldll
* https://github.com/luboslenco/kha_cppexterns

**Comment by CoruNethron** [comment]
@sh-dave , thank you, this is a huge field for experiments.

Right now I tested kha_cppexterns. It works for simple arithmetics test. And it looks much more organic, than ndll way. There is no explicit type conversions. And seems, that I can continue to debug UI within Kode / html5 until I don't touch c++ functionality. 

I think, that i'll return to forum.kode.tech, once I have little bit more time to compare all four ways, but now it seems to satisfy my needs.

Thank you for help, guys.
