### ISSUE TITLE
update haxe?

### ISSUE THREAD

**Issue by romamik** [Kode/Kha#706]
haxe supplied with kha is 3.4.2, while current version is 3.4.4. 
I've ran into bug in haxe that is fixed in 3.4.4 and is present in 3.4.2. 

Isn't it a good idea to update haxe to recent version?

I've tried it myself. I just replaced haxe binary with 3.4.4 downloaded from official site and it worked ok for windows and linux-64. So it looks it does not break anything. 

PS I've found that just replacing binaries is not enough. When building android-native on linux khamake builds the project, but there is error message during the build (`/bin/sh: 1: haxelib: not found`) and returns non zero exit code.

**Comment by dmitryhryppa** [comment]
Btw, there was some option for custom Haxe location.
Try `Kha/make --haxe PATH`

**Comment by RobDangerous** [comment]
On 3.4.4 now.
