### ISSUE TITLE
 Is it possible to solve the problem of localisation 

### ISSUE THREAD

**Issue by cjmxp** [Kode/Kha#709]
Whether the problem of localization can be solved first, the problem of Chinese chaotic code is very serious at present, and the font is also a very troublesome problem.

**Comment by RobDangerous** [comment]
Is this about that other issue which is still open? There is no solution in sight for Chinese fonts taking up a lot of space, that is a fundamental problem of bitmap fonts. What is the chaotic code thing about?

**Comment by cjmxp** [comment]
#606  The title of the form is in Mac, and the Linux should also be messed up.

**Comment by RobDangerous** [comment]
ok, I take notice that this is urgent for you but I will close this issue because we don't need two of the same.

**Comment by cjmxp** [comment]
@RobDangerous Thank you very much.
