### ISSUE TITLE
Dynamic font rendering

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#710]
With a larger font size or/and a range of characters (for example, hieroglyphs), caching a font in a bitmap can take a very long time (especially mobile devices with large dpi). Also caching occurs for each font size separately.

To draw short texts, maybe you can use the algorithm:
- recalculation of all code letters in the text into an int array
- Sorting an array in ascending order
- use this array as fontGlyphs
- Caching this text to an image
- Repeat for each text

But for long descriptions (for example, descriptions of objects in RPG) this will also be slow. So, dynamic text rendering will be very useful. Any ideas how this can be implemented?

**Comment by RobDangerous** [comment]
Sorry but I don't want to do that. Kha does not know beforehand how much text you will render so I would either have to add weird mechanisms to guess when it would maybe make sense or alternatively make the api weird and complex. I want to bring back the font pre-baking that Kha previously had though.
