### ISSUE TITLE
WebGL Image.isOpaque() and at() not working for huge sizes

### ISSUE THREAD

**Issue by koonsolo** [Kode/Kha#721]
For the HTML5 backend, Image.isOpaque() and Image.at() is not working for images bigger than 2048x2048.

To reproduce:

1. Load an image that is larger than 2048x2048
2. Query a pixel in this image with Image.at(), which falls outside of this range (but still inside the loaded image size)
3. The color value of this pixel is always 0.

Reason:

The class that handles this for HTML5 is WebGLImage. At init(), it creates a context of size 2048x2048, which will be used to retrieve pixel data (in createImageData()). Because of this, everything that falls outside of this range will receive a 0 value.

Proposed solution:

Since 4096x4096 textures are supported on almost all WebGL devices (99.9%, see http://webglstats.com/webgl/parameter/MAX_TEXTURE_SIZE), I propose to make this the default instead of 2048x2048.

Besides that, when an Image is queried with a bigger size than the initialized context, and exception should be thrown to notify the programmer that incomplete results will be returned. It's a hard bug to track down (believe me! ;))

Maybe this arbitrary size could be configured somehow, or reinitialized at runtime when bigger images are requested.

**Comment by koonsolo** [comment]
For reference and "proof", I changed the context size to 4096x4096 in my build, and then it worked. So I'm pretty sure that is the problem :).

**Comment by RobDangerous** [comment]
ok, I'll make it 4k by default (it's totally hip (because Amigas supported 4k colors)) and increase it automatically when a bigger image requires it.

**Comment by RobDangerous** [comment]
Please test because I did not.
