### ISSUE TITLE
framebuffer.g2.end() causes 'cannot cast' exception for debugger in Khode

### ISSUE THREAD

**Issue by Triangle345** [Kode/Kha#722]
I have a simple test program which draws a few rectangles. Nothing special. I'm creating a backbuffer and using Scaler to write it. However; when debugging (F5) in Khode it always  hits an exception:

```
@:ifFeature("typed_cast") private static function __cast(o : Dynamic, t : Dynamic) {
    if (__instanceof(o, t)) return o;
<-- always hits exception here -->    else throw "Cannot cast " +Std.string(o) + " to " +Std.string(t);
```

The local variables for o and t are:
o: Kha_CanvasImage
t: function(width,height,format,...)

The call stack is as follows:
js_Boot.__cast
setTexture
drawBuffer
end
MyRenderFunction

It seems as this is occurring on end().

```
framebuffer.g2.begin();
Scaler.scale(backbuffer, framebuffer, System.screenRotation);
framebuffer.g2.end();
```

Is my Kha setup properly or is my  code doing something that is causing this. I'm having trouble figuring out if this is a bug on my end or not.

**Comment by RobDangerous** [comment]
I think it's your code but I can't tell for sure. CanvasImage, how did that happen?

**Comment by Triangle345** [comment]
I mean it is debugging on HTML. I'm not doing anything special this is just a simple render of a line and rectangle.

I even commented out the rendering code all together. It currently only writes to the frame buffer, i'm not drawing anything to my back buffer

my init code for kha looks like the following. As you see, nothing special. All standard procedure:

```
public function new(options:SystemOptions)
	{
			
			System.init(options, init);

			backbuffer = Image.createRenderTarget(options.width-1,options.height-1);
    		graphics = backbuffer.g2;
	}

	private function init()
	{
		Assets.loadEverything(function () {
		///we also put in a renderer which talks to our 'Shapes' class render function
		System.notifyOnRender(renderAll);
		Scheduler.addTimeTask(updateAll, 0, 1 / 60);
		});
	}
```

**Comment by RobDangerous** [comment]
Doesn't look quite so standard to me. You create the backbuffer before the init callback is called, that might be the problem.

**Comment by Triangle345** [comment]
Ah thank you very much, i see where i went wrong. The init call took some time for kha so it created my back buffer first. I fixed it by putting the back buffer creation into the same thread as system init like so:

Thanks for the extremely timely advice.

Fixed:

```
	public function new(options:SystemOptions)
	{
			this.options = options;

			System.init(options, init);
	}

	private function init()
	{
		Assets.loadEverything(function () {

		backbuffer = Image.createRenderTarget(options.width,options.height);
    	        graphics = backbuffer.g2;

		///we also put in a renderer which talks to our 'Shapes' class render function
		System.notifyOnRender(renderAll);
		Scheduler.addTimeTask(updateAll, 0, 1 / 60);
		});
	}
```

**Comment by RobDangerous** [comment]
Cool (there's no extra thread here though, it's merely async so this is also not about init taking some time - you can read up about the difference in the internetz).
