### ISSUE TITLE
[REQUEST] ability to rename exported kha.js & khanvas within khafile.js

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#730]
this is something ive been thinking of more & more lately.
but when exporting things such as a html project, it only exports things as `kha.js`, with also inside the `index.html` it has the canvas id as `khanvas` & the script source as `kha.js`

i do think this is good, BUT, it would be nice if there was an ability from the `khafile.js`,  to rename & give a certain the html `id` & script `source` on an export.

ive recently been playing with shaders & working on a gallery type thing & i have gotten multiple shaders to work from using kha & exporting the project to html.
but the problem, is that renaming things, whilst not a huge problem, just takes up time.

how i worked it was renaming the js file to whatever i wanted. then going into the exported js file & changing this `kha_CompilerDefines.canvas_id = "khanvas";` by changing the `khanvas` to whatever, lets say `changedJSFile`. its normally at line`25536`.
then lastly in the html i would call up the canvas id with this `<canvas id="changedJSFile" width="470" height="305"></canvas>` & obviously calling the js with something like this `<script src="assets/js/shader/changedJSFile.js"></script>`

it has worked, very well
<img width="1539" alt="screen shot 2018-01-15 at 20 45 00" src="https://user-images.githubusercontent.com/11299322/34961053-633f4306-fa35-11e7-8028-32cbee5cccbf.png">

these are all moving as well & works incredibly fast. but sadly are not resizing with the webpage, but ill figure that out somehow.
but yeah, a way to rename things on an export would be really useful & a great option for folks. especially if you plan to use more than 1 html/js file per page or whatever

**Comment by lewislepton** [comment]
![large gif 1534x368](https://user-images.githubusercontent.com/11299322/34961458-166d189e-fa37-11e7-9b9d-780cf007f3c2.gif)

**Comment by RblSb** [comment]
Do I understand you correctly?
https://github.com/Kode/Kha/wiki/khafile.js#set-specific-options-for-the-html5-target

**Comment by lewislepton** [comment]
well oh welly wellness. when the hell did that get put in the wiki?
thats awesome.

well... ill shut up then & go eat my words ;)
