### ISSUE TITLE
Network issues

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#731]
I checked the BlockArena demo after the merger #398, there appeared the clients out of sync, which is especially noticeable if you keep each client in the tab, and not in a separate browser window. Before the merge, when switching between tabs, the motion occurred at the correct coordinates.
Also in both commits, there is no possibility to control the client's left/right movement, replicated coordinates changed on the client are not synchronized with the server. Color flip/flop works correctly.

**Comment by RblSb** [comment]
@RobDangerous, it also breaks the run of the flash target with [this lib](https://github.com/fponticelli/edge) (without using the Network class or something. I can not explain it. Need a demo?).
```
Error #1014: Class kha.network::Network could not be found.
at kha::Scheduler$/executeFrame()
at kha::SystemImpl$/update()
```

**Comment by RobDangerous** [comment]
There is no network implementation for flash. Also don't plan to add one (unless someone sends a pull request). Apart from that, networking currently heavy in development...

**Comment by RblSb** [comment]
Closed in favor of https://github.com/Kode/Kha/issues/793

**Comment by sh-dave** [comment]
Oh, didn't see this issue or i would have added here. Networking doesn't work in flash, but you can still compile and run it when you run full DCE `project.addParameter('-dce full');`, this will strip it out if it's unused.
