### ISSUE TITLE
VSync option is not worked with OpenGL [windows]

### ISSUE THREAD

**Issue by dmitryhryppa** [Kode/Kha#732]
VSync option is not worked with OpenGL [windows]
But I'm sure it worked some time ago.

**Comment by RobDangerous** [comment]
Oh, I didn't change a thing. It's the wglSwapIntervalEXT thing in OpenGL.cpp. Any driver updates or maybe changes to the driver settings?

**Comment by dmitryhryppa** [comment]
Hm, maybe regular Windows updates broke something in my driver...
Will try to update driver directly.

**Comment by dmitryhryppa** [comment]
After driver update it start to work again.  ¯ \ _ (ツ) _ / ¯
