### ISSUE TITLE
Web page scrolls on pressing cursor keys in HTML5 game

### ISSUE THREAD

**Issue by koonsolo** [Kode/Kha#733]
When pressing any navigation key in a HTML5 game, the web page will scroll along. Remark that this is not only for the cursor keys, but also for any other browser navigation. Page up/down, spacebar, .... In Firefox, backspace will navigate history to the previous page, etc.

As I see it, there are 2 possible solutions:

1. Disallow any browser keys and shortcuts (including for example ctrl-t for opening a new tab)
2. Disallow any key that was handled by the game. So it's up to the game to decide if it handled a certain key, and if not it's passed on to the browser.

Remark that the above only disallows keys when the game canvas has focus. When it does not, key events are not passed on it and so navigation works as expected.

The implementation of this functionality can be found in Backends/HTML5/kha/SystemImpl.hx. It contains 3 functions that react to javascript key events: keyDown(), keyUp(), keyPress().

keyDown() contains a call to event.stopPropagation(), but remark that this will not stop the browser from reacting to keys. only event.preventDefault() will make sure the browser does not handle the key.

At first, adding event.preventDefault() to keyDown() might seem like a good solution (keyUp() already has it), but unfortunately this will prevent keyPress() to be triggered, and that one handles kha text input with keyboard.sendPressEvent(char).

Only doing event.preventDefault() for non character keys is not possible because of spacebar.

I would think handling character keys in keyDown(), and always doing event.preventDefault() would fix it. Kha would then ignore keyPress(). But I don't know how keys on mobile (coming from the virtual keyboard) are handled.

**Comment by RobDangerous** [comment]
We need keyPress, we don't get proper text input otherwise (keyDown can't handle more complex non-English text input which can require more than one key per character).

**Comment by koonsolo** [comment]
Tested this some more, and seems putting a event.preventDefault() at keyPress() does the trick. But I know we need to be careful with this, on different browsers and different platforms.

**Comment by RblSb** [comment]
I do not think that preventDefault in keypress breaks something, it does not prevent to receive press events in kha. But for some people there will be a minus lock to the hotkeys of the browser, so if we want to add this feature to Kha, it's worth making it optional, for example, in khafile targetOptions or in System.SystemOptions.
At the moment, you can use this snippet:
https://github.com/Kode/Kha/wiki/HTML5#block-browser-hotkeys
@koonsolo its Firefox bug, but it fixed in Kha

**Comment by koonsolo** [comment]
@RblSb Adding preventDefault() in keyDown() prevents keyPress() to get called (in Chrome at least), and so you will receive no text input from kha. So although that snipped indeed blocks all browser behavior, it also blocks kha text input.

In my opinion, the most versatile solution is to have a user return value on handling key presses. If you return true, the app handled it and so no underlying browser or system functionality is called. When returning false, it can propagate up to browser or system.

In that case, always returning false would give the current behavior, and always returning true would block everything. On app level, you can decide that or anything in between for specific keys.

I don't know if this is a HTML5 only problem. What do you want a desktop game to do when you press the windows button, or alt-F4 or whatever?

**Comment by RobDangerous** [comment]
Special system yadayada always goes to the system in Kha, but for browsers it's more complicated because the apps usually don't run in their own window (there is no and can not be any key up/down problem with other targets).

**Comment by koonsolo** [comment]
@RobDangerous So to be consistent, HTML5 target should also capture everything and not pass anything to the browser :). I like this because it only works when the game canvas has focus anyway.

I thought some more about a possible solution (at least for me), and I think I'm going to handle it like this:

1. Add preventDefault() in keyPress().
2. In keyDown(), for any key that will not get sent to keyPress(), do a preventDefault().

Now how to best check that last part I still need to figure out.
