### ISSUE TITLE
unable to log in to kha forum

### ISSUE THREAD

**Issue by jakelewis3d** [Kode/Kha#752]
I am unable to login at http://forum.kode.tech/login
after a lengthy wait this message is displayed: 
"Failed login attempt, please try again.
Something went wrong."

It may be that my password has become scrambled, but I see no "forgotten your password" button either.

Nobody has posted on the forum for nearly a month, so I suspect I'm not the only one having issues logging in.

Regards, Jake

**Comment by RobDangerous** [comment]
Indeed, there's something amiss. Thanks, will fix it ASAP...

**Comment by RobDangerous** [comment]
Fixed. This was difficult.

**Comment by jakelewis3d** [comment]
Thanks, working now
