### ISSUE TITLE
g4.clear() is not bound by g4.viewport()

### ISSUE THREAD

**Issue by jakelewis3d** [Kode/Kha#753]
g4.clear() seems to clear the entire framebuffer rather than just the area defined by g4.viewport().
I can see that this might be the intended functionality, but is there a way to restrict clearing the screen to just a rectangle / viewport?

**Comment by luboslenco** [comment]
Does `g4.scissor()` work?

**Comment by RblSb** [comment]
+1 for `clearRect(x, y, w, h)` :)

**Comment by RobDangerous** [comment]
Do 3D APIs work that way? Have to check.

**Comment by luboslenco** [comment]
Yes, from https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glClear.xml:
`The pixel ownership test, the scissor test, dithering, and the buffer writemasks affect the operation of glClear. The scissor box bounds the cleared region.`

**Comment by RobDangerous** [comment]
I put some scissors in the garden, you can now take care of your bonsai trees.

**Comment by luboslenco** [comment]
Bonsai tree is grateful, looking sharp again:
http://kodegarden.org/#177720764e073d071578dd82c7e9db02ccc8ea60

**Comment by jakelewis3d** [comment]
Working well, thank you.

**Comment by RobDangerous** [comment]
I suppose this is fixed - if it isn't please reopen and tell use about which target this was actually about.
