### ISSUE TITLE
Update Pi support

### ISSUE THREAD

**Issue by RobDangerous** [Kode/Kha#755]
Get everything up to date, make sure the makefile and --compile works, recompile all the tools.

**Comment by RobDangerous** [comment]
Oh no, I forgot to take a look at --compile. But it's all updated and works fine via Code::Blocks.

**Comment by RobDangerous** [comment]
Added --compile without testing it. Works for sure (and if it doesn't somebody please re-open this issue).

**Comment by postite** [comment]
hello and thx but still not compilling ....
i have :
    /usr/bin/ld: cannot find -lGLESv2
    /usr/bin/ld: cannot find -lEGL
    /usr/bin/ld: cannot find -lbcm_host
    collect2: error: ld returned 1 exit status
    makefile:6: recipe for target 'Empty' failed
    make: *** [Empty] Error 1
    Compilation failed.

maybe related to this https://raspberrypi.stackexchange.com/questions/77619/where-is-legl-lglesv2
they say those lib where renammed in raspbian stretch.
and in fact they are in my /opt/vc/lib

**Comment by RobDangerous** [comment]
Didn't run into that although I did a dist-upgrade. Please change it at https://github.com/Kode/Kore/blob/master/korefile.js#L312 and send a pull request.

**Comment by gepatto** [comment]
on Raspbian Stretch the _EGL_, _GLESv2_ and _bcm_host_ libraries are in _/opt/vc/lib_ and they are called _libbrcmEGL_, _libbrcmGLESv2_ and _libbcm_host_.
On Raspbian Jessie that is NOT up to date they are called _libEGL_ and _libGLESv2_ and _libbcm_host_.
On Raspbian Jessie that has all updates you have BOTH names 
( the files are the same, I guess this was for the transition to Stretch )

Normally I need an LDFLAG to compile.
`-L/opt/vc/lib`

Seems right now it's only looking in /usr/lib/arm-linux-gnueabihf/ 
Not sure how to do this in Kore just yet.
