### ISSUE TITLE
Chinese title display chaotic code on the Mac osx platform。

### ISSUE THREAD

**Issue by cjmxp** [Kode/Kha#756]
Chinese title display chaotic code on the Mac osx platform。

![image](https://raw.githubusercontent.com/cjmxp/images/master/title-osx.png)

```
import kha.System;
class Main {
	public static function main() {
		System.init({title: "中文", width: 1024, height: 768}, function () {
			new Project();
		});
	}
}
```

**Comment by RobDangerous** [comment]
Are you sure you are using the latest code? I thought I fixed that in December.

**Comment by cjmxp** [comment]
What I'm using is Kode Studio 17.9.1

**Comment by RobDangerous** [comment]
The integrated Kha in Kode Studio is quite old (because the last Kode Studio release was a while back), see https://github.com/Kode/Kha/wiki/Getting-Started for how to get the git version of Kha and set the khaPath in Kode Studio to use it.
