### ISSUE TITLE
Triangles not drawn mobile html5

### ISSUE THREAD

**Issue by juakob** [Kode/Kha#765]
![screenshot_2018-03-04-13-51-45](https://user-images.githubusercontent.com/3499218/36948638-8c6c137e-1fbc-11e8-891b-2c459dc8f33d.png)
In some android devices some triangles are not drawn 
tested devices: Amazon fire 10 HD chrome, firefox and Silk
Example: http://kodegarden.org/run/cdd3093b1a60256d39eec3a06f32adbaa08e6e5a/sysop

Still happens without the depth buffer, does not happened when build to native

**Comment by luboslenco** [comment]
Maybe related to https://github.com/Kode/krafix/issues/51#issuecomment-364594887.

**Comment by juakob** [comment]
thanks luboslenco it looks like its related, looks like if I manually change the precision of the position to highp the problem dosent happend. 
I have tested other 2d proyects and they work fine, so I think it might be related also to the scale and how numbers are rounded up. I have an animated uv water, and in this device the water jumps from one position to another instead of transitioning from one position to the other.

**Comment by RobDangerous** [comment]
Very interesting. Making high precision a high priority...

**Comment by RobDangerous** [comment]
I think this is fixed.
