### ISSUE TITLE
[webgl] Render targets ignore anti-aliasing

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#766]
Meh, couldn't fix it.
Sample: https://gist.github.com/RblSb/19d84dbf4e0929f3164c1e483e8c799c

**Comment by nanjizal** [comment]
seems that drawing larger onto a canvas and then back to scale for normal gives better results, test concept on my jigsaw experiment.

**Comment by RobDangerous** [comment]
Of course it does. Also it's way slow.

**Comment by RblSb** [comment]
Fixed in #1082 #1083
