### ISSUE TITLE
[BUG?] videos in textures are flipped

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#777]
this is something im trying to solve. but its weird that a video is flipped when put into a texture.

supplied a project with the video

[VIDEOTEXTURE.zip](https://github.com/Kode/Kha/files/1835420/VIDEOTEXTURE.zip)

**Comment by RobDangerous** [comment]
I think you reported that before. That's via html5, right?

**Comment by lewislepton** [comment]
aye I did say about this before. not sure if I actually posted an issue.

yep, its using the KS html debug

**Comment by RobDangerous** [comment]
Your sample is broken, you suddenly draw into a texture without calling begin first. That said, render targets being flipped is normal, you have to check http://api.kha.tech/kha/graphics4/Graphics.html#renderTargetsInvertedY

**Comment by lewislepton** [comment]
ah cool. thanks for that. I had a feeling flipping was normal as I think OpenGL does that, cant remember.

cheers man

**Comment by RobDangerous** [comment]
Exactly, yes. Maybe I'll find some shader compiler trick to circumvent that but for now that has to be handled manually.
