### ISSUE TITLE
Wiki documentation links are broken

### ISSUE THREAD

**Issue by sh-dave** [Kode/Kha#781]
They're pointing to `http://api.kha.ktxsoftware.com` and that just gives a `Cannot GET /`
Both in the TOC and the page itself `https://github.com/Kode/Kha/wiki`.

**Comment by RobDangerous** [comment]
Fixed. I think you can also edit the Wiki by the way.

**Comment by sh-dave** [comment]
Yeah already did a couple of times, didn't know where to point the links at though.
