### ISSUE TITLE
Haxe class names can conflict with C standard includes (prev. Cannot compile windows target)

### ISSUE THREAD

**Issue by MadIcecream** [Kode/Kha#783]
But html5 is ok.

The compiler error message is:
```
//Math.cpp
#if defined(HX_WINDOWS) || defined(__SNC__)
   unsigned int t = clock();        <- clock is undefined.

//StdLibs.cpp
   return (double)clock() / ( (double)CLOCKS_PER_SEC);        <-CLOCKS_PER_SEC is undefined.
```

**Comment by RobDangerous** [comment]
How do you compile? What Visual Studio version do you use?

**Comment by MadIcecream** [comment]
I compile it like all other visual-studio cpp projects, I open the solution and right click then build it.
I use vs2017 community.

And, an empty kha project doesn’t have this problem, if you would like, I can upload my project tomorrow

**Comment by RobDangerous** [comment]
Ah, yes, please.

**Comment by MadIcecream** [comment]
Hi, this is my project
[McCorgi.zip](https://github.com/Kode/Kha/files/1854563/McCorgi.zip)

**Comment by RobDangerous** [comment]
ok, you can fix this by renaming your Time class, it confuses the C++ compiler because it gets included in StdLibs.cpp instead of the standard time.h. There's an option for the Haxe compiler to avoid that but it caused other troubles, have to investigate that again...

**Comment by RobDangerous** [comment]
Properly fixed now.
