### ISSUE TITLE
[Feature Request] Threading/Workers on Krom

### ISSUE THREAD

**Issue by Jarrio** [Kode/Kha#788]

**Comment by N8n5h** [comment]
Any update on this? I think getting workers on Krom might help this issue on the Armory engine https://github.com/armory3d/armory/issues/243 to allow using some functions of https://github.com/vincent/recast.js that require workers.

**Comment by RobDangerous** [comment]
No "any updates on this" comments please, they demotivate me. Send money or ice cream instead.

**Comment by N8n5h** [comment]
Oh sorry, I didn't mean it like that, I wanted to make a little bump on this feature request and also get some status on the issue, not familiar with Krom internal, so I was looking for some insight in the issue too.

**Comment by RobDangerous** [comment]
There is no status, haven't yet looked into it at all.

**Comment by N8n5h** [comment]
@RobDangerous if I wanted to get my hands dirty to help with this one, where should I start reading?
I'm a newcomer to kha/krom

**Comment by RobDangerous** [comment]
Start at https://github.com/microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview

**Comment by RobDangerous** [comment]
You can look up the actual standards documents for WebWorkers - or just google it and look at the API, it's quite simple and it's the same everywhere. Using Kinc threads would of course make sense.
