### ISSUE TITLE
[Feature Request] 64 bit arrays

### ISSUE THREAD

**Issue by ImmanuelSamuel** [Kode/Kha#789]
I would love to see some 64 bit array support for 64 bit coordinate systems.

**Comment by RobDangerous** [comment]
Hm, what does that mean? Standard Float is 64 bits and you can create arrays with it. You can't pass that to the GPU but that's not our fault, consumer GPUs have poor or no 64 bit support.

**Comment by ImmanuelSamuel** [comment]
OK. I get it now. Thanks for the explanation.
