### ISSUE TITLE
Khafile option to disable assets postprocessing

### ISSUE THREAD

**Issue by dmitryhryppa** [Kode/Kha#791]
Here is an image: https://www.dropbox.com/s/4faxapuk4isjv1b/background.jpg?dl=0
The original image size is 64kb (and it is already compressed). 
After Kha's assets compression it is becaming 1.8mb. 

In some cases it may be useful to disable this behaviour.

**Comment by juakob** [comment]
The main objective of that pass is not to compress but to make the file faster to load into the GPU memory.
You can remove the file extension and load the data as a blob and uncompress the JPG/PNG at runtime. I did that with pngs, but now I just use kha default process

**Comment by RobDangerous** [comment]
Already talked to Dmitry about it and while I think using jpegs is especially silly (in RAM the image blows up to 2 Megs in any case and there's no way around it) the final decision should be up to the individual developer.
