### ISSUE TITLE
OpenGL error with official example

### ISSUE THREAD

**Issue by trsh** [Kode/Kha#794]
https://github.com/Kha-Samples/ComputeShader

GL Error 1280 e:\projects\haxe\kha\kore\backends\graphics4\opengl\sources\kore\computeimpl.cpp 430

GC: GTX 750 Ti, newest nvidia drivers, win 10 up to date, latest Kha

For compiling VS 2017 and make command `node ../Kha/make -g opengl`

**Comment by trsh** [comment]
@RobDangerous :(

**Comment by RobDangerous** [comment]
Don't cry.

**Comment by trsh** [comment]
OK :D

**Comment by RobDangerous** [comment]
So, I was wrong, this actually works fine for me. WIth the latest update it also works via D3D11. GTX 1080, latest drivers, Win10.
In that armory issue you mention that you actually see the fancy red graphics. I didn't know that, that's still the case?

**Comment by trsh** [comment]
Debugging Shader obj.

![khash](https://user-images.githubusercontent.com/3727523/38484132-34575566-3bde-11e8-8344-103f83d646bd.png)

```
#version 330
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif
#extension GL_ARB_compute_shader : require
#extension GL_ARB_shader_image_load_store : require
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

uniform float roll;
uniform writeonly image2D destTex;

void main()
{
    ivec2 storePos = ivec2(gl_GlobalInvocationID.xy);
    float localCoef = length(vec2(ivec2(gl_LocalInvocationID.xy) - ivec2(8)) / vec2(8.0));
    float globalCoef = sin((float(gl_WorkGroupID.x + gl_WorkGroupID.y) * 0.100000001490116119384765625) + roll) * 0.5;
    imageStore(destTex, storePos, vec4(1.0 - (globalCoef * localCoef), 0.0, 0.0, 1.0));
}
```

**Comment by trsh** [comment]
Id did this

glCheckErrors2();
	glUseProgram(shader->_programid);
	glCheckErrors2();

And seems error is before glUseProgram

**Comment by trsh** [comment]
```
bool convRstr = glewIsSupported("GL_NV_conservative_raster");

	if (convRstr) {
		if (pipeline->conservativeRasterization) {
			glEnable(0x9346); // 
		}
		else {
			glDisable(0x9346);
		}
	}
```

this kind of solves the issue.

What I don't understand is why the below `glCheckErrors();` doesn't spit out GL error, but it's buffered until next render.

**Comment by trsh** [comment]
http://feedback.wildfiregames.com/report/opengl/feature/GL_NV_conservative_raster

**Comment by RobDangerous** [comment]
GL drivers don't do stuff immediately. It all makes sense but as expected is completely unrelated to compute shaders.

**Comment by trsh** [comment]
@RobDangerous thanks! I think this was good cooperation :)

**Comment by FuzzyWuzzie** [comment]
Fixed by adding a check for if the extension string is null in the if body:

```c
if (extension != NULL && strcmp(extension, "GL_NV_conservative_raster") == 0)
```

Will add a pull request shortly

**Comment by RobDangerous** [comment]
Fixed.

**Comment by FuzzyWuzzie** [comment]
I didn't even have time to pull the fork!

**Comment by RobDangerous** [comment]
Trying to beat the world record for the fastest bug fix.
