### ISSUE TITLE
Window management

### ISSUE THREAD

**Issue by ImmanuelSamuel** [Kode/Kha#796]
I am trying to write a program that shows up every hour for a few seconds and hides away. Right now I am calling System.Shutdown but that exits the program. Any way to hide window? Also Timer doesnt work in the following code which is probably my issue?

KhaApplication.hx
```
package;

import haxe.ui.Toolkit;
import haxe.ui.components.Button;
import haxe.ui.core.Component;
import haxe.ui.core.Screen;
import haxe.ui.macros.ComponentMacros;
import kha.Assets;
import kha.Framebuffer;
import kha.Scheduler;
import kha.System;

class KhaApplication {
    private var _main:Component;

    public function new() {
        Assets.loadEverything(onAssetsLoaded);
    }

    function onAssetsLoaded() {
        Toolkit.init();
        _main = ComponentMacros.buildComponent("../assets/ui/main.xml");
        Screen.instance.addComponent(_main);

        var button:Button = _main.findComponent("testButton2", null, true);
        button.onClick = function(e) {
            button.text = "Set from code!";
        }

        System.notifyOnRender(render);
        Scheduler.addTimeTask(update, 1, 1 / 60);
    }

    function update(): Void {
      System.requestShutdown();
    }

    function render(framebuffer:Framebuffer): Void {
        var g = framebuffer.g2;
        g.begin(true, 0xFFFFFF);
        Screen.instance.renderTo(g);
        g.end();
    }
}
```

Main.hx
```
package;

import kha.System;
import haxe.Timer;

class Main {
  public static function main() {

    System.init({title: "HaxeUIApp", width: 800, height: 600}, function () {
      new KhaApplication();
    });

    Timer.delay( function () {
      trace( "PTLJ! delayed" );
    }, 1000);
  }
}

```

**Comment by sh-dave** [comment]
I think haxe.Time is rewired inside Kha to use kha.Scheduler internally. So try to call it in the callback for System.init(). It might not work if Kha isn't initialized yet. Also, using kha.Scheduler.addTimeTask(someFunc(), 1.0) will do the same thing, execute the callback once, after 1s initial delay.

I don't think Kha has an API to hide windows yet.

**Comment by ImmanuelSamuel** [comment]
Yes haxe.Timer works inside System.Init thanks. However I am unable to open window again.
```
package;

import kha.System;
import haxe.Timer;

class Main {
  public static function main() {

    System.init({title: "HaxeUIApp", width: 800, height: 600}, function () {

          Timer.delay( function () {
            trace( "PTLJ! delayed" );
          }, 1000);

      new KhaApplication()
    });

    trace( "PTLJ!" );

    System.init({title: "HaxeUIApp", width: 800, height: 600}, function () {
      new KhaApplication();
    });
  }
}
```

**Comment by ImmanuelSamuel** [comment]
Also as you said it didnt compile.
```
Using Kha from /home/j/Downloads/test/multiWindow/Kha
Creating Kha project.
Compiling shader 1 of 8 (painter-colored.frag.glsl).
internal/child_process.js:330
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at Object.exports.spawn (child_process.js:500:9)
    at fs.stat (/home/j/Downloads/test/multiWindow/Kha/Tools/khamake/out/ShaderCompiler.js:292:55)
    at FSReqWrap.oncomplete (fs.js:171:5)
```

**Comment by sh-dave** [comment]
I'll see if i can fix the example, it's only old shaders i think.

But that won't help with the actual issue. Question is, do you actually need to do this inside the app itself? One thing you could try is to use the [windows task scheduler](https://en.wikipedia.org/wiki/Windows_Task_Scheduler) or a cron job if you're on linux. Then you could just use it like now. Use a job to open the app and just close it via System.requestShutdown().

**Comment by ImmanuelSamuel** [comment]
Hmm i see so it seems I have to then just go the traditional route of c++ qt.

**Comment by ImmanuelSamuel** [comment]
Yep I did recursive clone
![image](https://user-images.githubusercontent.com/7865018/38561642-88d14c1e-3ca6-11e8-9540-41da68fad8ba.png)

**Comment by Jarrio** [comment]
It is possible to create a scheduled via the command line. On Windows, you'd use the command `SchTasks` which you can access via `Sys.command` in Haxe as a temporary solution

**Comment by ImmanuelSamuel** [comment]
After learning about hashlink I am considering using that. It has an sdl library however no tutorials. I am able run some basic code but cant figure out how to use the libraries. Thank you for taking the time to respond to my questions amidst your schedules. I really appreciate it!

**Comment by RobDangerous** [comment]
Closing this. Hiding windows is now supported but still, Kha is not made for idling in the background.
