### ISSUE TITLE
Image and drawRect not rendering all the pixels

### ISSUE THREAD

**Issue by MangelMaxime** [Kode/Kha#80]
I am trying to draw a rectangle in an image of the same width. Here is the code :

``` haxe
this.texture = Image.createRenderTarget(this.width, this.height);
```

``` haxe
    override public function refresh()
    {
        var g : Graphics = this.texture.g2;
        g.begin();

        g.clear(Color.fromValue(0x00000000));

        g.color = this.color;
        // TODO : (0) Remove the hack to draw from (0,0) when Robert fix the bug
        g.drawRect(0, 0, this.get_width(), this.get_height());

        g.end();
    }
```

Here is the result :
![imagerect1](https://cloud.githubusercontent.com/assets/4760796/8205824/5ea1c7b6-14f4-11e5-9077-7757fad54d89.PNG)

I tried with this code too :

``` haxe
    override public function refresh()
    {
        var g : Graphics = this.texture.g2;
        g.begin();

        g.clear(Color.fromValue(0x00000000));

        g.color = this.color;
        // TODO : (0) Remove the hack to draw from (0,0) when Robert fix the bug
        g.drawRect(1, 1, this.get_width(), this.get_height());

        g.end();
    }
```

Here is the result :
![imagerect2](http://i.imgur.com/04sf0nf.png)

In both sample, there a pixel missing in the image rendered.

I have testing it on html5 target.

**Comment by MangelMaxime** [comment]
This bug is present using `node Kha\make.js -t windows -v vs2010 -g opengl` to compile the project too.

**Comment by RobDangerous** [comment]
I thought long and hard about it and decided that this behavior is correct. drawRect draws rects where width/height is based on the centers of the surrounding lines. Line thickness by default is 1 so the lines start at -0.5, -0.5 when you call drawRect(0, 0, w, h) - without antialiasing you then get the behavior you described. g2 works with floats everywhere so I think this makes sense and we should avoid introducing any pixel-snapping behavior which would lead to strange effects in other situations which then are very hard to avoid. For your specific situation g.drawRect(0.5, 0.5, width - 0.5, height - 0.5) does the job.
