### ISSUE TITLE
Json Parsing inconsistant with normal Haxe.

### ISSUE THREAD

**Issue by nanjizal** [Kode/Kha#803]
Json parsing in haxe is documented here:
https://haxe.org/manual/std-Json-parsing.html

KodeGarden test:
http://kodegarden.org/#7a6c341a0e6545c897ee3cb2354cd4af2b5279b3

Within Kha this approach fails.
``` haxe
package;
import kha.Framebuffer;
import kha.Scheduler;
import kha.System;
import kha.Font;
import kha.Assets;
import haxe.Json;

typedef MyData = {
  var name:String;
  var tags:Array<String>;
}
class Main {
    static var data: MyData;
    static var font: Font;
	static function render(framebuffer: Framebuffer): Void {
        var g2 = framebuffer.g2;
        g2.font = font;
        g2.fontSize = 20;
        g2.color = 0xFFFFFF00; // yellow
        g2.begin( true );
        g2.drawString( data.name + ' ' + data.tags[0], 100, 100 );
        g2.end();
        System.removeRenderListener( render );
    }
    static function onLoaded(){
        trace('loaded all');
        var str = Assets.blobs.data_json.toString();
        font = Assets.fonts.Arimo_Regular;
        data = haxe.Json.parse( str );  // errors here!
        System.notifyOnRender(function (framebuffer) { render(framebuffer); });
    }
    public static function main() {
	System.init({title: "Kode Project", width: 800, height: 600}, function() {
            trace( 'start' );
            Assets.loadEverything( onLoaded );
	});
    }
}
```

Lewis was having an issue mentioned it on twitter so thought I would create a demo use case but I couldn't as it seems not to work same as Haxe?   This definitely seems like a bug so have raised an issue, although perhaps it's a limitation due to the way Kha uses json internally or node ness related.

**Comment by RobDangerous** [comment]
data.json does not contain valid json. Fixed it for you: http://kodegarden.org/#c24f0967f90785a0fd0aaa3341789485873983b4
Haxe uses native Json parsers when available so behavior can be different when you put in bogus data but this is not specific to Kha at all. Please read error messages.
