### ISSUE TITLE
image drawn on transparent frame buffer opaque and same as background.

### ISSUE THREAD

**Issue by nanjizal** [Kode/Kha#806]
http://kodegarden.org/#b9bb1f28c793018bcbced5bc109bd32a33b304e6
It would be more intuitive for users if the default when drawing an image before anything else to framebuffer - was always for it to be drawn with color assumed white unless they specify color on the frame buffer before.  At the moment it's very easy to want to composite an image and then when drawing to the framebuffer it just does not appear.  While it may seem logical from a GL point of view, it's quite common to want to use an image as a background and not obvious that you must always set the color property first.
My original problem was drawing the back2future background to an image 7800 triangles and then animating 1380 triangles on top.  I am not sure if there are other combinations that are strange but if Kha can default first image drawn so that it's normally visible then that would be good?
Unsure if this an issue but I think it has stung me quite a few times so would be nice if considered as I am sure others will slip up on it as well.

**Comment by nanjizal** [comment]
The original code was a bit different, without the g.color = Color.White; I end up having to add the firstTime code to get the image to appear, so it's kind of weird till you realize it's just a color setting aspect. 
``` haxe
var firstTime = true;
    function render( framebuffer: Framebuffer ): Void {
        var g = framebuffer.g2;
        //if( firstTime ){
            g.begin( 0xFF181818 );
            g.color = Color.White;
            g.drawImage( background, 0, 0 );
            g.end();
           // firstTime = false;
        //} else {
            g.begin( false, Color.Transparent );
            renderTriangles( g );
            g.end();
            //}
    }
```

**Comment by RobDangerous** [comment]
Too much text, that's the gist of it?

**Comment by nanjizal** [comment]
**Color of graphics should be set to white for all cases when begin is called.**

Details:

It's easy to draw an image that is not visible due to how begin/end default the color property.
http://kodegarden.org/#b9bb1f28c793018bcbced5bc109bd32a33b304e6
Because render loops are often **repeated** if the image is the only aspect rendered it sometimes visible but not if additional other draws are added this can lead to very unpredictable results that are confusing because why would drawing a triangle on top stop the image rendering?

For instance in this demo if I just draw the background ( image ) it appears, but when also draw the digits it disappears! 
https://nanjizal.github.io/TrilateralBazaar/segmentTest/build/html5/
The key is to make sure I set the color before drawing the image.
https://github.com/nanjizal/TrilateralBazaar/blob/master/segmentTest/src/Main.hx#L279 

**The issue as I understand it is that color does not default to white for the image first draw command in a begin end.**  

While you can argue that is as per design it's incredibly easy to get wrong and not intuitive for users that are used to Canvas etc.. and only want to use 2D Kha, Also by adding a white default there will be less cases where multiple render loops render differently from a single render loop.

This feature of Kha has caught me out many times, I was complaining that my polypainter was not working right, and numerous other occasions it comes from not realizing that **sometimes** I must set color on **g** before drawing the first image other times it won't matter. 

The problem is that strange reordering of functionality can lead to the image being drawn, be defaulting it the system is predictable, I was doing stuff like drawing in update loop and stuff suddenly worked. 
 Perhaps color on image and framebuffer are also linked in render loop. My thoughts are that reset color to white on begin is very valid way to avoid strange render order confusion.  The problem is that at the moment you can easily write code that is unpredictable, image renders in second loop but not first.

I guess now I have a good understanding I won't be caught out but others will.

**Comment by RobDangerous** [comment]
Found the discussion in the chatlog. Dave is right about that, behavior is equivalent to all the other g2 properties so I'll keep it like that.
