### ISSUE TITLE
[webgl] invalid framebuffer operation

### ISSUE THREAD

**Issue by gmisail** [Kode/Kha#807]
- macOS 10.13.3
- Node - v9.4.0
- Haxe - v3.4.4
- Kha - latest git version
- Kode Studio 17.1

I am having issues drawing to the screen using a backbuffer. Although the program does not crash, I do get errors concerning the WebGL framebuffer. 

```
SystemImpl.hx:348: Could not initialize WebGL 2, falling back to WebGL.
WebGLImage.hx:226: WebGL error: Framebuffer incomplete
Graphics.hx:137: WebGL error: Invalid framebuffer operation
[.Offscreen-For-WebGL-0x7ff9bc03ce00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[.Offscreen-For-WebGL-0x7ff9bc03ce00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[.Offscreen-For-WebGL-0x7ff9bc03ce00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
Graphics.hx:137: WebGL error: Invalid framebuffer operation
[.Offscreen-For-WebGL-0x7ff9bc03ce00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[.Offscreen-For-WebGL-0x7ff9bc03ce00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[.Offscreen-For-WebGL-0x7ff9bc03ce00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```
First of all, I am not sure if not falling back to WebGL 2 is causing these issues. If so, then I am confused as to why WebGL 2 is not supported. 

I am trying to render a basic rectangle; no images or text.

```
class Renderer
{
	private var canvas : Image;

	public function new()
	{

	}

	public function start(display : Display) : Void
	{
		
		canvas = Image.createRenderTarget(display.RENDERER_WIDTH, display.RENDERER_HEIGHT);

		System.notifyOnRender(render);
	}

	private function render(framebuffer : Framebuffer) : Void
	{
		canvas.g2.begin();
		canvas.g2.color = kha.Color.Cyan;
		canvas.g2.drawRect(0, 0, 16, 16);
		canvas.g2.end();

		framebuffer.g2.begin();
		Scaler.scale(canvas, framebuffer, System.screenRotation);
		framebuffer.g2.end();
	}
}
```

**Comment by RblSb** [comment]
Did you remember to call start()?

**Comment by RobDangerous** [comment]
WebGL 2 is not supported because you're still on Kode Studio 17.1.
I tried to reproduce your problem using your code but all seems to work fine: http://kodegarden.org/#737ec55d058e011611ca783599ce72b0fdaabba8
Please provide a complete sample project.

**Comment by RobDangerous** [comment]
Sounds like the shader compiler gets passed bogus data. Peak into the shader.sources array please (you should find it somewhere in the variables pane).

**Comment by gmisail** [comment]
I have one entry in the array:

```
"#version 100
uniform mat4 projectionMatrix;
attribute vec3 vertexPosition;
varying vec2 texCoord;
attribute vec2 texPosition;
varying vec4 color;
attribute vec4 vertexColor;
void main(){ 
    gl_Position = projectionMatrix * vec4(vertexPosition, 1.0);
    texCoord = texPosition;    color = vertexColor;
}"
```

![screen shot 2018-04-17 at 9 30 44 am](https://user-images.githubusercontent.com/8661089/38872762-09114af2-4222-11e8-923c-e323a6f70c7e.png)

**Comment by RobDangerous** [comment]
That's not right, the webgl2 shader is missing. Are you sure your Kha is completely up to date, including all submodules? What does git status print in your Kha dir?

**Comment by gmisail** [comment]
All good! My sub-modules must have not been up-to-date, because everything worked after I re-downloaded Kha and set the modules to their latest versions.

**Comment by RobDangerous** [comment]
Cool Spot.
