### ISSUE TITLE
Make script crashes when compiling Kha project

### ISSUE THREAD

**Issue by AndrewBelt** [Kode/Kha#814]
Hello. I am unable to compile an empty Kha project with Arch Linux, Node v10.0.0, and Kha  2765735.

Initializing the Kha project is fine.
```
~/src/empty ❯ node ../Kha/make --init
Initializing Kha project.

If you want to use the git version of Kha, execute "git init" and "git submodule add https://github.com/ktxsoftware/Kha.git".
```

But it fails immediately when building.
```
~/src/empty ❯ node ../Kha/make
node[8059]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [node]
 2: 0x563647ad29db [node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [node]
 5: 0x563647ce7ba7 [node]
 6: 0x563647ce833c [node]
 7: 0x712dcc0427d
zsh: abort (core dumped)  node ../Kha/make
```

The Kha v17.1 tag seems to work, however.

**Comment by sh-dave** [comment]
Can you build the test projects included in Kha?

```shell
cd Kha/Tests/Empty
node ../../make
```

**Comment by sh-dave** [comment]
Also reading the error you get and this one [here](https://github.com/nodejs/node/issues/20285) it might be a nodejs issue. Can you downgrade to 9.x and try that?

**Comment by AndrewBelt** [comment]
Same error for the Empty project (since they're identical files I think) with Node v10.

Confirmed that Node v9.11.1 works fine.

**Comment by RobDangerous** [comment]
ok, updating the dependencies fixes that but introduces other problems. I'm on it...

**Comment by RobDangerous** [comment]
Fixed.
