### ISSUE TITLE
Android build hiccups

### ISSUE THREAD

**Issue by AndrewBelt** [Kode/Kha#815]
I'll document my process of compiling for Android with Kha master 2f4956a on Arch Linux.

When running `node ../Kha/make html5 android --compile`, the script fails at

https://github.com/Kode/khamake/blob/3570a09d9beadc008b5c5de7b1b15ecd6297143c/src/main.ts#L614

because the value of `options.to` is "build/android/New Project" instead of "build/android/New-Project", which is the folder it actually creates.

Furthermore, it tries to run `bash gradlew assemble` which doesn't work because 1) it should be `./gradlew` and 2) the file doesn't have execute permissions.

A workaround is to make sure you have [Gradle](https://gradle.org/) installed and run

	cd build/android/New-Project
	gradle assemble

It seems to specifically require Android Platform 25.

Make sure you set your `ANDROID_HOME` and `ANDROID_NDK_HOME` environment variables to your `android-sdk` and `android-ndk` folders, that the folders are writable by your user (since the build system writes to them for some reason), and that all licenses are accepted (`sdkmanager --licenses`).

At this point, the `Empty` project fails with

```
> Task :app:mergeDebugResources FAILED
/home/vortico/src/js/atlas/haxe/empty/build/android/New-Project/app/src/main/res/mipmap-hdpi/ic_launcher.png.temp: Error: The file name must end with .xml or .png
/home/vortico/src/js/atlas/haxe/empty/build/android/New-Project/app/src/main/res/mipmap-xhdpi/ic_launcher.png.temp: Error: The file name must end with .xml or .png
/home/vortico/src/js/atlas/haxe/empty/build/android/New-Project/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png.temp: Error: The file name must end with .xml or .png
/home/vortico/src/js/atlas/haxe/empty/build/android/New-Project/app/src/main/res/mipmap-mdpi/ic_launcher.png.temp: Error: The file name must end with .xml or .png
/home/vortico/src/js/atlas/haxe/empty/build/android/New-Project/app/src/main/res/mipmap-xxhdpi/ic_launcher.png.temp: Error: The file name must end with .xml or .png

FAILURE: Build failed with an exception.
```

After renaming each file, two .apk files are generated in `build/android/New-Project/app/build/outputs/apk`!
I don't know where these icons came from, but they will be used as the app icon.

The unsigned release version doesn't install on my phone, because I guess I haven't disabled certificate checking for apps, and the debug version installs ~~but crashes upon launch~~ (resolved, had accidentally added a bad line of Haxe to the "Empty" project.)

The ~300 KB APK size (~1.2 MB unpacked) is *fantastic* compared to similar libraries.
Here's a screenshot of the app on my homescreen.
![screenshot_20180509-143927](https://user-images.githubusercontent.com/338179/39833351-cb13182a-5397-11e8-92e9-27e9a5576565.png)

Hopefully this helps someone.

**Comment by sh-dave** [comment]
Thanks for the informations, i think it's quite a while ago since someone tried to do a non native android build (at least that i heard of).

`node ../Kha/make html5 android --compile` khamake only supports 1 target per call so i think you should remove the `html5`, i'm not sure if specifying 2 targets might affect anything in a bad way.

For the gradle script, just `chmod +x gradlew` it and put up a PR please 👼 

Instead of the env vars, you can also create a `local.properties` file in `./build/android/PROJECT_NAME` with `sdk.dir=e:\\dev\\android-sdk` (or your linux equivalent). `ANDROID_NDK_HOME` or `ndk.dir` should only be required for the `android-native` target, not the java one.

To use a custom icon, just drop an icon.png into your projects root folder. Khamake should pick that one up and use it to create the different variants.

To debug you should be able to just open the generated folder in android-studio.

**Comment by AndrewBelt** [comment]
>`html5 android`

Whoops, that was a typo, and apparently the script ignored the `html5` build anyway.

Thanks for the information. First, I'd like to ask if I'm missing some documentation/docstrings that would have answered this.

If not, there's a good chance that I'll want to overhaul this GitHub's wiki to push the documentation along, time allowing. I'm a strong believer that every project should focus on building a "hello world" example, especially one with as many target architectures, programming languages, build systems involved as this one. I think it's even more important than documentation about the API itself, because most people can get by with a dox-generated documentation, *provided* they can get all their desired targets running in reasonable effort. (If I really got carried away, I'd offer an overhaul of the website.)

**Comment by sh-dave** [comment]
No, i don't think so. Most of what i wrote comes from experience. I usually think, wait, i should add that to the wiki somewhere, but than that evil boss person at work suddenly appears out of nowhere and want's some new build finished yesterday! So you're actually more than welcome to update the wiki with whatever information you feel is missing. Also just opening issues like that is great to document missing/outofdate issues in the build system or target.

**Comment by RblSb** [comment]
Android target has been removed in favor of android-native target, so there is probably nothing to do.
Reasons: https://github.com/Kode/Kha/issues/1424#issuecomment-1186277565
Straightforward info about android-native setup is here:
https://github.com/Kode/Kha/wiki/Android-%28native%29
