### ISSUE TITLE
Keyboard input events being dispatched for both keyUp and keyDown in sequence.

### ISSUE THREAD

**Issue by skylerparr** [Kode/Kha#820]
Pulled master today (https://github.com/Kode/Kha/commit/479cbe03bde1a08eab7e07d9a658edef0dc6b803) and the keyboard events on Linux (maybe others?) are dispatching the keyUp Event even though the key hasn't stopped being pressed.

How to reproduce:
```
    public function new() {
        kha.input.Keyboard.get(0).notify(onKeyDown, onKeyUp, onKeyPress);
    }

    public function onKeyDown(key: kha.input.KeyCode):Void {
        trace(key);
    }

    public function onKeyUp(key:kha.input.KeyCode):Void {
        trace(key);
    }
```

When holding down the `d` key. The console prints like this:
```
@ input.kha.KhaKeyboardInputSourceListener.onKeyDown
  36 68
@ input.kha.KhaKeyboardInputSourceListener.onKeyUp
  44 68
@ input.kha.KhaKeyboardInputSourceListener.onKeyDown
  36 68
@ input.kha.KhaKeyboardInputSourceListener.onKeyUp
  44 68
@ input.kha.KhaKeyboardInputSourceListener.onKeyDown
  36 68
@ input.kha.KhaKeyboardInputSourceListener.onKeyUp
  44 68
```

I would not expect the onKeyUp to not be called until the key is actually depressed.

**Comment by luboslenco** [comment]
Keys also get stuck when pressing them madly FPS-style.

**Comment by vivichrist** [comment]
is this still an issue?

**Comment by RobDangerous** [comment]
I don't understand your fancy slang - what's up with 17.04?
Should still be an issue, I didn't do anything about it.

**Comment by skylerparr** [comment]
@RobDangerous not sure the distribution version is related. I think @vivichrist is say that he help with testing for Ubuntu 18.04, but is unable to test for ubuntu 17.04. I can definitely help with testing for Linux Mint. Also, is there any other debugging I can provide?

**Comment by vivichrist** [comment]
I can't reproduce this bug on Ubuntu 18.04

**Comment by RobDangerous** [comment]
Oh, interesting. @skylerparr You see it on current Mint, right?

**Comment by vivichrist** [comment]
A solution could be to just turn off key repeat "xset r off" via command line and then restore key repeat once the code has quit "xset r on" if it was set "on" to begin with. Perhaps there is a X11 or kernel C/C++ call that does a similar thing. This kind of setting may be different for the various destro's of Linux.... Well it could also be personal preference.

**Comment by RobDangerous** [comment]
Not a good solution. On Windows Kha prevents keyrepeat completely, I'll figure something out to do that on Linux as well.

**Comment by vivichrist** [comment]
for this bug turning on/off key repeat has no effect but I haven't tried changing the repeat rate (on Ubuntu 18.04)
