### ISSUE TITLE
Font doesn't load even if asset(myfont.ttf) is in /Assets

### ISSUE THREAD

**Issue by mundusnine** [Kode/Kha#821]
Lewis Lepton pushed this issue : https://github.com/haxeui/haxeui-kha/issues/16 
But I believe it is a kha issue.

On my end, I started a project with kha and everytime I try to use the font by doing Assets.fonts.myfontname I get a null value. When debugging I realised that kravur seems to detect the asset because it has the field and when gettting the names array and tracing the names I get the correct name for the font in question. But when getting the field the value is null. I tried two different fonts( [bold_type.zip](https://github.com/Kode/Kha/files/2054706/bold_type.zip) and [Aclonica-Regular.zip](https://github.com/Kode/Kha/files/2054708/Aclonica-Regular.zip)) Both did not work so I guess it isn't a font issue. 

I got the latest kha version on git as of this date. The Haxe compiler is 3.7.1. and I am using KodeStudio OS is Windows 10.

**Comment by RobDangerous** [comment]
Did you load your assets? See https://github.com/Kode/Kha/wiki/Managing-Your-Assets#loading-your-assets

**Comment by mundusnine** [comment]
Hi Rob, 

That solves it. Sorry for the false alarm just started learning and I missed this necessity of loading assets( I thought that since the field was detected to the name of the asset in question, my issue caused by a loading error). Will modify the docs on fonts loading for future users.

Thank you and good day,
