### ISSUE TITLE
kha.audio1.Audio.play broken if extensions are declared via khafile

### ISSUE THREAD

**Issue by Nazariglez** [Kode/Kha#822]
This is a weird bug, because is created by the name of the asset. If the khafile use something like `{dir}/{name}{ext}` and tries to load and play a wav `mysound_wav` fails: ``` this.data``` for AudioChannel is null. 

```
project.addAssets('assets/**', {nameBaseDir: 'assets', destination: 'assets/{dir}/{name}', name: '{dir}/{name}{ext}'});
```  

If the `{ext}` is removed, the audio is played as usual.

**Comment by Nazariglez** [comment]
Seems something related to the loadSound (by name), check this -> http://kodegarden.org/#5506f98cceb6100de94a25f05121312f5f09497d. 

Use mouse click left to load everything and play the sound. Refresh and click right to load just the sound and try to play it. Check the browser's console.

**Comment by Nazariglez** [comment]
My fault, i thought all the loaders do the same, thanks i'll do!

**Comment by RobDangerous** [comment]
Audio is a bit special because you can also use uncompressed audio directly (via Audio.stream).
