### ISSUE TITLE
[BUG?] can not access static field fontGlyphs from a class instance

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#823]
this is regarding the latest changes with the static on the GraphicsExtension - pops up right away when in KS using the git version of kha

<img width="1530" alt="screen shot 2018-06-08 at 12 11 45" src="https://user-images.githubusercontent.com/11299322/41155375-943c9278-6b15-11e8-81e5-66e87f5801f4.png">

**Comment by sh-dave** [comment]
As it's static now, just change it to `Graphics.fontGlyphs` instead of `g2.fontGlyphs` and put up a PR.

**Comment by lewislepton** [comment]
I was just about to change it. but just checking your change first

**Comment by lewislepton** [comment]
it did work, but needed to change the drawAlignedCharacters as well which I have done & pushed for review

**Comment by lewislepton** [comment]
thanks @sh-dave again for putting up with my 'what the fuck is going on' thoughts ;)

**Comment by sh-dave** [comment]
No problem. I guess you can close this now as #824 is merged?

**Comment by lewislepton** [comment]
BOOM
