### ISSUE TITLE
Kha crashes compiling under macOS 10.13.3

### ISSUE THREAD

**Issue by gmisail** [Kode/Kha#830]
I am compiling under the latest version of Mac, Node, & Kha. When compiling to macOS (first of all, I need to use `node Kha/make` because Kode Studio is acting up) my code compiles fine but throws a SIGABRT exception.

My full error message is below.

```
Assertion failed: (false), function Sound, file /usr/local/Kha/Kore/Sources/Kore/Audio1/Sound.cpp, line 170.
```

Here is an image of Xcode. 

![screen shot 2018-06-19 at 5 34 16 pm](https://user-images.githubusercontent.com/8661089/41625528-192dbf46-73e7-11e8-9808-1c1f8f325b5d.png)

Maybe there is an issue with my C++ compiler? All help is appreciated.

**Comment by RobDangerous** [comment]
You can see what's going on right there in the source code - it tries to read some wav file but you put in some fancy file which uses neither 16 bit nor 8 bit samples. Probably a 24 bit file, just convert it down before you feed it to Kha.
But let's keep this bug open, we should add a proper error message and maybe also convert such files in khamake.

**Comment by gmisail** [comment]
I guess my confusion came from how it works fine under HTML5 but not macOS. It makes more sense to me now, though.

**Comment by RobDangerous** [comment]
For html5 everything is converted to mp3 and ogg because some browsers can't handle wav files, that's why that works fine.

**Comment by gmisail** [comment]
There we go, my audio file was 32 bit. Works fine after converting it to 16 bit.
