### ISSUE TITLE
Xinerama issue on linux

### ISSUE THREAD

**Issue by varomix** [Kode/Kha#832]
Hi
downloaded and compiled the Blocks from Heaven example, everything compiles correctly but it doesn't run, complains about XInerama extension, I tested enabling Xinerama and it works but I can't use my linux setup like that, I remember it used to work before without Xinerama active
here's the error

```
Xinerama extension is not installed

Initializing Haxe libraries

Starting Kore

No display attached?
```

One thing that is different is that I have 2 GPUs and the second one is just for computing so there's nothing connected, maybe is trying to use the wrong GPU, I understand this setup is not common but I think it should just use the display GPU.

thanks

**Comment by sh-dave** [comment]
https://github.com/Kode/Kore/pull/273

**Comment by RobDangerous** [comment]
Aha!
