### ISSUE TITLE
Complementary functionality to Assets.loadEverything()

### ISSUE THREAD

**Issue by xolit** [Kode/Kha#834]
Hello,
there does not seem to be a way to call a function when the window is closed and the program terminates. We assumed this was possible with 
System.notifyOnApplicationState();
though it turned out the given shutdownListener is never called.
Tested with the HTML5 debug option in Kodestudio.

**Comment by RobDangerous** [comment]
Working on window management stuff right now, will call you back soon.
But don't expect it to work via HTML5 debug, closing a window is not really a concept which makes sense in HTML5.

**Comment by RobDangerous** [comment]
Should now work wherever it makes sense.
