### ISSUE TITLE
Krom's cutCopyPaste

### ISSUE THREAD

**Issue by ustance** [Kode/Kha#847]
Krom do nothing with `System.notifyOnCutCopyPaste`

Tested on this version, using built-in Krom:
![Kode Studio](https://i.imgur.com/WfdoiLL.png)

Here is a simple test. It works in html5-debug, but not in Krom 
![Test](https://i.imgur.com/O26c7l8.png)

**Comment by RobDangerous** [comment]
That's on Windows, right?

**Comment by ustance** [comment]
Yep, Windows 10, x64.
