### ISSUE TITLE
[Feature] Modding API for Kha incl. Krom and C++ Targets

### ISSUE THREAD

**Issue by zicklag** [Kode/Kha#849]
I am building my first game with Armory and Kha and it is high priority for my team to have the game moddable. It would be great if Kha had a `kha.modding` package that could be implemented by the different backends just like other APIs. The API would provide a standardized way to compile and load mods regardless of the backend.

For my game I need to have modding implemented for at least the Krom, C++, and console backends. I am looking into different ways that this could be implemented and am very open to input. I have somewhat ambitious goals for the modding solution, if it is possible to achieve:

1. Mods should be able to be written in Haxe and built by Kha just like the game is.
1. Mods should be able to contain assets along with code
1. Mods should ( *hopefully* :crossed_fingers: ) be able to access the full Kha API and potentially other APIs specific to the game, such as Iron and Armory.

I was successfully able to build a Haxe mod in an [armory example](https://github.com/armory3d/armory/issues/748#issuecomment-407954128) that had full access to the Kha API for the Krom target, but that is a simple thing because it is easy to dynamically load Javascript. When it comes to C++ it is a whole other story.

## C++ Modding

There are a number of challenges with the above strategy for C++ mods, specifically binding the whole Kha API. I'm not sure if it is completely impractical or not, but here are a couple strategies that I've considered.

### Mods are compiled to .so/.dll shared libraries

If the Haxe mods were compiled to C++ libraries they would get full access to the Kha/game API, but they would also get full access to the gamer's system. This is undesirable because of the threat that downloading a mod for the game could represent to your computer. A possible remedy for this issue is running the game in a Sandboxed environment such as [Firejail](https://github.com/netblue30/firejail) for Linux or maybe [ksm](https://github.com/asamy/ksm), but I don't know much about this subject.

There is also the disadvantage with shared modules being platform and compiler specific which is an inconvenience to the gamers for building and installing mods.

### Mods are compiled to Javascript and V8 is embedded into the game

It might be possible to embed V8 into the game and, somewhat similar to Krom, use it to execute the code for mods and expose the Kha/game APIs to the Javascript mods. So instead of running the entire game as Javascript as is done with Krom, you run most of the game in C++ and run only the mods in Javascript. This would be safer from a security standpoint ( I think ) than using shared libraries because you are only binding game libraries and you could specifically **not** bind any system manipulating functions.

The difficult part of this method is binding Javascript automatically to the whole game API. I have never done anything with V8 so I don't know the difficulty that this would present; my only note is that Haxe macros might provide a good way to automate the binding process without needing a change to much of Kha itself.

## Game consoles

I don't know what the options for dynamically loading code are on game consoles, not that I want users to be able to put mods on the console, but core mods that come with the game need to be able to work on consoles. I am assuming that this is very similar to handling mods in C++.

## Feedback

I would really like to get some feedback on these ideas. I would love to see modding built seamlessly into Kha, but I don't know a whole lot about most of this stuff. I am currently researching different options and trying to make stuff work so any thoughts, help, or guidance is appreciated.

**Comment by zicklag** [comment]
REALLY! That would make this *sooooo* much easier that I thought it would be. :relieved: I was assuming that the C++ target would have a performance advantage over Krom. It Krom is comming to consoles, then that would mostly be all I need.

> I have no idea what a kha.modding API would be supposed to do though.

The idea for a `kha.modding` API would be that it would give you an API to load mods for different platforms ( and I don't know how Khamake works exactly but you would need to be able to build mods for different platforms as well ). For example for Web/Krom targets you would build and load Javascript mods, for the C# target you build and load .dll's, and for the Java target you would build and load JARs.

If Krom can pretty much run everywhere than it may not be that important, though.

**Comment by RobDangerous** [comment]
About security - when you load in JavaScript you can provide functions for whatever or you can avoid doing it to make things more secure. JS is prototype based so everything is just a piece of data you can or can not pass to some other piece of JS.
Currently I would prefer not to add anything like that to khamake. Maybe after somebody made a working prototype of that kinda thing first.

**Comment by RobDangerous** [comment]
Okidoki, I'm closing the issue, feel free to open new issues when you run into more concrete problems with it.
