### ISSUE TITLE
AudioChannels are not advancing without registered `audioCallback`

### ISSUE THREAD

**Issue by sh-dave** [Kode/Kha#854]
To handle muting all sound and music when our app goes into the background, i use `kha.audio2.Audio.audioCallback = null;` This seems to work at first, but exhibits a problem.

Every sound that is played during this `mute period` doesn't advance it's internal state, but will only do it once i set `kha.audio2.Audio.audioCallback` back to it's default mix function.

**Comment by RobDangerous** [comment]
Hm, I didn't consider audioCallback = null to be more than a hack to silence the computer during development, for actual production use we should do something else (like setting the volume to zero and doing an early return in the mixer when there's nothing to mix).

**Comment by sh-dave** [comment]
But it seemed such an easy fix **\*sigh\***
