### ISSUE TITLE
How would you start Krom from the command line?

### ISSUE THREAD

**Issue by tienery** [Kode/Kha#857]
Hello, I know this is more of a question than an issue, but I would like to know how you would use the command line to open a Krom window as if you had built it and launched from Kode Studio?

Is there a way to do this?

**Comment by RobDangerous** [comment]
We have a forum at http://forum.kode.tech for questions. But, yes, it's in the Krom readme at the very end. The shadersdir parameter is optional, only used for runtime shader replacement.
