### ISSUE TITLE
GamePad (XBOne) Broken ?

### ISSUE THREAD

**Issue by rafaelvasco** [Kode/Kha#858]
Just tested game pad (XBox One) axis event on Krom and HTML5 targets on Win10x64, and it appears that the returned axis values are all wrong. Is XOne Controller not supported ?

**Comment by RobDangerous** [comment]
More details please, what does "all wrong" mean exactly?

**Comment by rafaelvasco** [comment]
OK. First , thank you for such a wonderful framework. 

They're not exactly wrong but...
I believe the axis values should go from -1.0 to 1.0 ? If I move , for example, the left analog stick all the way to the left the axis value should be -1.0 but it behaves erratically, like reaching only -0.3, or -0.8 then -0.5 etc. Same thing for the other directions. The other thing is that I probably I misunderstood the game pad axis event. Does it only get triggered when you move the stick ? In my test , for example, the sprite started moving left whan I started moving the stick to the left, but when I reached the far left It stopped. I was wondering what was happening. If that's the case it's just a matter of logic adjusting then.

**Comment by RobDangerous** [comment]
It does indeed only trigger on change. But I just tested this via HTML5 (in Kode Studio) and Kore (same backend code as used by Krom), also in x64 Win10 and and also using an Xbox One pad and it goes right to -1 and 1. Are you sure your gamepad is all right? Did you maybe test the wrong axis? All axis events are send to the same callback it can easily get confusing.

**Comment by rafaelvasco** [comment]
Maybe. Going to try it again and report back. Thanks.

**Comment by rafaelvasco** [comment]
Gave a try again. Worked ok. Guess it was a driver problem before. I'm closing. Thanks.
