### ISSUE TITLE
[BUG] error when building simple project in Xcode - missing SystemImpl

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#870]
I was looking at the other error I said via IRC - but this ran onto the scene when I just made a new & relatively blank project
this complains about SystemImpl not being in the project

builds & runs fine is HTML5/kode studio

[BLANKERS.zip](https://github.com/Kode/Kha/files/2348427/BLANKERS.zip)

**Comment by RobDangerous** [comment]
Can not reproduce that problem. What's the exact error message? Did you try a clean build?

**Comment by lewislepton** [comment]
really weird. after a clean out & trying again, it works. so im now just trying with my other project
