### ISSUE TITLE
[BUG] crash on iOS with simple project via connected iOS device

### ISSUE THREAD

**Issue by lewislepton** [Kode/Kha#879]
this problem has popped up even with a simple iOS project - drawing a rectangle on screen.

project
[khaTests.zip](https://github.com/Kode/Kha/files/2407775/khaTests.zip)

what the console prints when crashing
```
2018-09-22 13:28:31.975346+0100 New Project[2448:669447] [DYMTLInitPlatform] platform initialization successful
2018-09-22 13:28:32.059926+0100 New Project[2448:669354] Metal GPU Frame Capture Enabled
2018-09-22 13:28:32.060782+0100 New Project[2448:669354] Metal API Validation Enabled
Initializing Haxe libraries
Starting Kore
could not find vertex attribute vertexPosition
2018-09-22 13:28:32.082695+0100 New Project[2448:669354] -[MTLVertexAttributeDescriptorArrayInternal objectAtIndexedSubscript:], line 352: error 'vertex attribute index (4294967295) must be < 31.'
-[MTLVertexAttributeDescriptorArrayInternal objectAtIndexedSubscript:]:352: failed assertion `vertex attribute index (4294967295) must be < 31.'
(lldb) 
```

**Comment by lewislepton** [comment]
xcode version is 9.4.1 
kha version - latest git repo

**Comment by RobDangerous** [comment]
Hmm, maybe the cable is broken, when I connect to my PC it connects/disconnects at about 1 Hz. Oh and it's that system with the very special cable of course.

**Comment by lewislepton** [comment]
ill have a look-see. I have not updated my Mac & cant update my iPad since its the iPad gen 4 - but ill see what I can doe will need a wee bit of help as well maybe.
but ill do it, since im the one that bitches the most about it ;)

**Comment by RobDangerous** [comment]
Aaaah. iPad 4 doesn't support Metal. Try -g opengl (but I probably broke that).

**Comment by RobDangerous** [comment]
(also ordered a new cable by the way, should be here tomorrow)

**Comment by lewislepton** [comment]
goddamit - I really need a new iPad then - but that does suck. but also cool youre getting a new cable.
so will deving on iPad be a problem, or I guess the OpenGL work around may work?

but odd though that I had it working before. but then again, it may just be that broken OpenGL you said about

**Comment by RobDangerous** [comment]
Well, we recently made Metal the default. But yes, OpenGL should still work.

**Comment by lewislepton** [comment]
ok cool

**Comment by RobDangerous** [comment]
The new cable fixed everything.

**Comment by lewislepton** [comment]
awesome
