### ISSUE TITLE
Problem with hxcpp.h not found  - I already installed haxe but kha from github doesn't work like Armory too

### ISSUE THREAD

**Issue by deleteaccount1234567890** [Kode/Kha#894]
Hello everyone, I have problem I am disappointed because stupid error shows - Since I have success now I don't understand why does it not work?

I am using Ubuntu 18.04 - node.js is installed and build-deps are installed.
```
In file included from ../Sources/src/ImGuiDemo.cpp:14:0:
../../../Libraries/linc_imgui/linc/linc_imgui.h:3:10: fatal error: ./hxcpp.h: No such file or directory
 #include <hxcpp.h>
          ^~~~~~~~~
compilation terminated.
makefile:14: recipe for target 'imguidemo.o' failed
make: *** [imguidemo.o] Error 1
Compilation failed.
```
I have installed haxe's libs is ~/haxelib/hxcpp
But why does Kore/Kha doesn't know where is my haxelib installed. How do I fix?

Help-wanted!

**Comment by RobDangerous** [comment]
I have no idea what you are doing but I don't think it has anything to do with what you should be doing which is either calling `node Kha/make --compile` to compile directly or calling `node Kha/make` and then using the build files created in the build/linux-build subdirectory. A haxelib hxcpp can not be used with Kha, hxcpp.h should be in Kha/Backends/Kore/khacpp/include.

**Comment by deleteaccount1234567890** [comment]
Okay thanks I will try... I hope it works...

**Comment by sh-dave** [comment]
Hm, you shouldn't have to adjust any paths, generated haxe generated cpp code seems to work just fine in native builds, and that includes `hxcpp` the same way. Maybe @dmitryhryppa or @CoruNethron know more, as they contributed to the Kha sample code for `linc_imgui`.

As for the flickering, can you upload your sample code somewhere instead of us having to guess what might wrong?

**Comment by RobDangerous** [comment]
When you have to set an absolute path to hxcpp.h like that something is very wrong.

**Comment by CoruNethron** [comment]
Probably related to #792 , also take a look into linc_imgui/test/kha/khafile.js, there is comment on relative path, used to avoid circular dependencies.
I'm unable to test and debug right now, sorry.
