### ISSUE TITLE
Crash when run IOS app

### ISSUE THREAD

**Issue by OlegAntipov** [Kode/Kha#918]
Hi,
after updating kha sources, I can't run IOS app project, I get this message in log and the application crashes:
"Assertion failed: (mtlFunction), function Shader, file /Users/OlegAntipov/Downloads/Kha/Kha/Kore/Backends/Graphics5/Metal/Sources/Kore/Shader5Impl.mm, line 48."

**Comment by RobDangerous** [comment]
Don't know why that happens, can you upload a project I can use to reproduce that?

**Comment by OlegAntipov** [comment]
I tried on empty kha template project, and got same error :(

2018-11-30 13:56:41.828 New Project[15729:2920852] Metal GPU Frame Capture Enabled
2018-11-30 13:56:41.834 New Project[15729:2920852] Metal API Validation Enabled
Initializing Haxe libraries
Starting Kore
Assertion failed: (mtlFunction), function Shader, file /Users/OlegAntipov/Downloads/Kha/Kha/Kore/Backends/Graphics5/Metal/Sources/Kore/Shader5Impl.mm, line 48.
(lldb) 

MacOS High Sierra 10.13.5
XCode 9.4.1

**Comment by OlegAntipov** [comment]
I tried on empty kha template project, and got same error :(

2018-11-30 13:56:41.828 New Project[15729:2920852] Metal GPU Frame Capture Enabled
2018-11-30 13:56:41.834 New Project[15729:2920852] Metal API Validation Enabled
Initializing Haxe libraries
Starting Kore
Assertion failed: (mtlFunction), function Shader, file /Users/OlegAntipov/Downloads/Kha/Kha/Kore/Backends/Graphics5/Metal/Sources/Kore/Shader5Impl.mm, line 48.
(lldb) 

MacOS High Sierra 10.13.5
XCode 9.4.1

**Comment by RobDangerous** [comment]
Oh, wow, it's a Mini 1. That one doesn't support Metal. Also doesn't run 64 bit applications so it's not really suitable for testing apps for the store. But you can use `--graphics opengl` to run Kha.

**Comment by OlegAntipov** [comment]
Ok, thanks!
