### ISSUE TITLE
Raw png image aliasing

### ISSUE THREAD

**Issue by JeriXNet** [Kode/Kha#92]
When I add my image to project.kha all looks allright:
![2015-06-29_202123](https://cloud.githubusercontent.com/assets/7815518/8414155/a28357fc-1e9e-11e5-8172-8ca09edba099.jpg)
But when I use it directly so it's not processed with kraffiti it looks like this:
![2015-06-29_202223](https://cloud.githubusercontent.com/assets/7815518/8414182/d0c13986-1e9e-11e5-8ac6-5d22bfe3c932.jpg)
And here is original image:
![sock](https://cloud.githubusercontent.com/assets/7815518/8414202/f1caea14-1e9e-11e5-9758-6ad0e77d8b4d.png)
Why this happening? How can I use my images directly so them borders looks smooth?

**Comment by RobDangerous** [comment]
Kha normally uses images with premultiplied alpha. For native targets kraffiti preprocesses images accordingly to speed up loading times. In other targets it's done at runtime. Is this from a native target?

**Comment by JeriXNet** [comment]
Yes, native on windows, in GL and DX

**Comment by JeriXNet** [comment]
Is there a way to use images with alpha in separated channel?

**Comment by RobDangerous** [comment]
Yes, works fine when you use kraffiti. But here's my plan: I'll change the file extension for kraffiti processed files and at runtime add premultiplied alpha for plain pngs.

**Comment by JeriXNet** [comment]
I just can't get it:
By default kaffiti premultiplies rgb with alpha?
Then what's goes to alpha and how it rendered?

**Comment by RobDangerous** [comment]
See here for example https://developer.nvidia.com/content/alpha-blending-pre-or-not-pre and http://home.comcast.net/~tom_forsyth/blog.wiki.html#[[Premultiplied%20alpha]]
Premultiplied alpha is used in practically all graphics processing nowadays, it solves a lot of problems which normally show up when working with alpha-channels.

**Comment by JeriXNet** [comment]
Oh, thanks for pointing me!

**Comment by JeriXNet** [comment]
Now I get it! Thanks again :)
About your plan:
I think it should be parameterized if ext images needs alpha to be premultiplied at loading or not. Because someone might want to have his own blend func and etc.
BTW
I can't find any filtering-mipmapping settings for images?
And what about vsync settings? It seems it always only on or off depending on target but it might be very handy to disable it during dev time

**Comment by RobDangerous** [comment]
Kha now expects pngs to not contain premultiplied alpha (and uses custom k files with premultiplied alpha on native targets). Mipmapping settings are also available nowadays. vsync not so much.
