### ISSUE TITLE
[FR] add support to change mouse cursor

### ISSUE THREAD

**Issue by trsh** [Kode/Kha#932]
Unix

https://stackoverflow.com/questions/3583746/c-change-the-cursor-in-an-x-window
https://tronche.com/gui/x/xlib/pixmap-and-cursor/cursor.html

App simulated cursor (fallow mouse) will always lag with the FPS and can mislead the actual position.

**Comment by RobDangerous** [comment]
Sorry but "app simulated cursors" make more sense to me because they don't get ahead of the rest of the rendered image.
