### ISSUE TITLE
Red and blue color channels are swapped when using graphics1 in Krom.

### ISSUE THREAD

**Issue by bent95** [Kode/Kha#940]
The red and blue color channels are swapped when using graphics1 in Krom. Code that demonstrates the problem:
```
    static function render(frames: Array<Framebuffer>): Void {

        frames[0].g1.begin();
        for (x in 0...frames[0].width){
            for (y in 0...frames[0].height){
                frames[0].g1.setPixel(x,y,Color.Red);
            }
        }
        frames[0].g1.end();
    }
```
This should fill the screen with red pixels, but instead fills it with blue pixels when debugging with Krom. The code works as expected with the HTML5 and Windows targets. This is only a problem with graphics1, similar code using graphics2 does display the correct color.

**Comment by RblSb** [comment]
I think it's because g1 uses RGB colors, while kha.Color stores the ARGB palette.

**Comment by bent95** [comment]
But why does it only happen when debugging in Krom, and not when debugging in HTML5 or running a Windows build?

**Comment by RobDangerous** [comment]
What target system are we talking about?

**Comment by bent95** [comment]
I’m using the latest version of Kode studio running on a 64-bit Windows 7 computer.

**Comment by potatoelixir** [comment]
I know this thread is quite old but... There is already a conditional compilation if/else that swaps `Color`'s  R and B values on HTML5, shouldn't this be as simple as extending that to Krom? I'll submit a PR, please somebody review.
