### ISSUE TITLE
android-native: "Compilation failed" does not throw error code

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#943]
Instead it returns code 0, as if everything was successful, when it definitely wasn't.

This means, for example, that continuous integration scripts will continue to run as if the compilation was a success, when it wasn't.

![screen shot 2019-01-02 at 2 14 53 pm](https://user-images.githubusercontent.com/1667179/50583426-b58ac100-0e9b-11e9-8974-9980871c7802.png)

In Discord chat, Robert said, "It normally does [throw an error code]. Just not for Android it seems. Should be easy to fix - go ahead, give it a try."

**Comment by Joncom** [comment]
It seems Kha is correctly throwing error code 1 after all.

For some reason in Gitlab CI, if you setup a single command like `cd some/folder && node Kha/make android-native --compile && cd -` and the make fails, the non-zero exit will not be caught, and the next command in the Gitlab CI script will run. However, if you break it up, and run the commands separately like `cd some/folder`, then `node Kha/make android-native --compile`, and then `cd -`, Gitlab will actually stop after the failed compile. Very strange that this is necessary.

**Comment by RblSb** [comment]
I thought this issue was about the fact that compilation in android-native continues even if haxe compiler fails.

**Comment by Joncom** [comment]
Nah. I thought koremake was failing to provide a non-zero exit code because
Gitlab Continious Integration (CI) scripts are suppose to stop running when
any command returns non-zero. Seems like a Gitlab bug or something.
