### ISSUE TITLE
koremake: Cannot use custom "icon.png" if following documentation

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#945]
According to the documentation (https://github.com/Kode/Kha/wiki/khafile.js#add-a-custom-icon), it should be possible to drop an icon.png into the root of the project, and have it be used when compiling for Android/iOS/etc.

I tried following those instructions:

```bash
$ ls
Assets		Kha		Sources		build		icon.png	khafile.js	korefile.js
```

However, building with, for example, `node Kha/make android-native --debug --compile` produces an APK with the default icon, not my custom one.

Moving "icon.png" into the "build" folder fixes the problem.

So either the documentation is wrong, or koremake is looking in the wrong folder, so one of them should be corrected.

Seems like perhaps the documented way (of having icon.png in the root, not the "build" folder) is better, because the "build" folder is supposed to be completely ignored (via ".gitignore") anyway, right?

**Comment by RobDangerous** [comment]
Oh, that sounds like a new bug, it really should be directly in the project folder and that used to work. Will have a look.

**Comment by luboslenco** [comment]
Maybe https://github.com/Kode/khamake/commit/b8c082c1e6e6af8692e179203c99a843ed5f7f1c?

**Comment by RobDangerous** [comment]
Yes.

**Comment by RobDangerous** [comment]
Fixed.

**Comment by Joncom** [comment]
Confirmed (iOS target)
