### ISSUE TITLE
kha.graphics2.GraphicsExtension.drawCircle() Has Gaps In It

### ISSUE THREAD

**Issue by M00nR4bb1t** [Kode/Kha#946]
I wanted to draw beautiful circles, so I implemented my own GraphicsExtender class.
```haxe
static public function drawCircle(g:Graphics, x:Float, y:Float, radius:Float, vertices:Int=48, strength:Float = 1.0):Void {
	for (i in 0...vertices) {
		g.drawLine(x + radius*Math.cos(2/vertices*Math.PI*i), y + radius*-Math.sin(2/vertices*Math.PI*i), x + radius*Math.cos(2/vertices*Math.PI*(i+1)), y + radius*-Math.sin(2/vertices*Math.PI*(i+1)), strength);
	}
}

static public function fillCircle(g:Graphics, x:Float, y:Float, radius:Float, vertices:Int=48):Void {
	for (i in 0...vertices) {
		g.fillTriangle(x + radius*Math.cos(2/vertices*Math.PI*i), y + radius*-Math.sin(2/vertices*Math.PI*i), x + radius*Math.cos(2/vertices*Math.PI*(i+1)), y + radius*-Math.sin(2/vertices*Math.PI*(i+1)), x, y);
	}
}
```
But then the circle (or, more accurately, ring) produced by my `drawCircle()` was ugly. when the stroke was thick enough (around a few dozen pixels or thicker), it had noticable gaps. So I looked through the docs looking for a way to change the line cap shape. I realized I just wasted my time and that there was already a Graphics extension class-the `kha.graphics2.GraphicsExtension`.

However, that had the exact same problem. Now, is there a way to solve this without stupidly increasing the number of `vertices` as in my example or `segments` as in `kha.graphics2.GraphicsExtension`?

**Comment by RobDangerous** [comment]
Sure, just adjust your algorithm to the line strength, both your algorithm and the one in GraphicsExtension fail to do that. drawLine applies thickness from the center outwards, to avoid gaps you'll have to consider the outer border of the lines aka move the lines thickness/2 closer to the center of the circle.

**Comment by RobDangerous** [comment]
Or alternatively (which would be the better version) make the lines a bit longer - I think that's a bit harder to do though.
