### ISSUE TITLE
iOS broken rendering

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#947]
My game is running great on HTML5 and Android. It's been a long time since I tested on iOS, but it seems the build on that platform is broken. It's throwing an exception every time I call `graphics2.begin(false);` at the beginning of my render loop.

![screen shot 2019-01-06 at 6 49 00 pm](https://user-images.githubusercontent.com/1667179/50735656-13454300-11e5-11e9-9077-0b70da4127bf.png)

**Comment by RobDangerous** [comment]
Are your begin/end calls in order?

**Comment by Joncom** [comment]
Most certainly.

**Comment by RobDangerous** [comment]
Kha samples also not working?

**Comment by Joncom** [comment]
The following code sample should reproduce the issue on your end:

```haxe
package;

class Main {
  public static function main() {
    kha.System.start({}, init);
  }

  private static function init(window) {
    kha.Assets.loadEverything(function() {
      var image : kha.Image = kha.Assets.images.custom_04b03;
      var copy : kha.Image = kha.Image.createRenderTarget(image.width, image.height);
      copy.g2.begin(true, kha.Color.Transparent);
      copy.g2.drawImage(image, 0, 0);
      copy.g2.end();
    });
  }
}
```

![custom_04b03](https://user-images.githubusercontent.com/1667179/50834013-88e81500-1385-11e9-9c04-77e4d742c8c4.png)

Clone-able from this branch too: https://github.com/Joncom/Empty/tree/ISSUE_947

**Comment by sh-dave** [comment]
But you aren't rendering anything? Call begin/end on the framebuffer at least once per frame.

**Comment by RobDangerous** [comment]
I guess that's the root of the problem. Should nonetheless work though and I'll take care of it - meanwhile listen to Dave's advice.

**Comment by Joncom** [comment]
Dave, of course I’m drawing to the framebuffer every frame. This was just a
minimal sample that still reproduces the error.

**Comment by Joncom** [comment]
@sh-dave, I've refined the sample such that it will still crash, even when rendering to the main framebuffer every frame as you suggest.

```haxe
package;

class Main {
    public static function main() {
        kha.System.start({}, function init(window) {
            kha.Assets.loadEverything(function() {
                var image:kha.Image = kha.Assets.images.pixelmix_hd_4x;

                var copy:kha.Image = kha.Image.createRenderTarget(image.width, image.height);
                copy.g2.begin(true, kha.Color.Transparent);
                copy.g2.drawImage(image, 0, 0);
                copy.g2.end();

                copy.g2.begin(false);
                copy.g2.end();

                kha.System.notifyOnFrames(function render(framebuffers:Array<kha.Framebuffer>):Void {
                    var framebuffer = framebuffers[0];
                    framebuffer.g2.begin();
                    framebuffer.g2.end();
                });
            });
        });
    }
}
```

Clone here: https://github.com/Joncom/Empty/tree/ISSUE_947

In my game engine, I'm just trying to do some simple image composition/manipulation to off-screen render-targets, but this bug is causing the whole render system to grind to a halt.

**Comment by sh-dave** [comment]
Yep, that crashes for me now as well.

**Comment by Joncom** [comment]
Yay, thanks to @sh-dave's recommendation in IRC chat, I figured out how to get my game to actually render on iOS, by using OpenGL, not Metal. `node Kha/make ios --graphics opengl`

**Comment by Joncom** [comment]
However, using OpenGL seems like a poor solution, in part because Metal appears to be up to 2x faster.

@RobDangerous, have you had a chance to confirm this runtime error on your end? https://github.com/Kode/Kha/issues/947#issuecomment-453077098

**Comment by RobDangerous** [comment]
Of course it is a poor solution, it's officially deprecated on macOS and iOS, drivers are poorly optimized and the feature-set is from 10 years ago. And no, didn't boot my Mac yet but it looks like an easy to fix issue, so don't worry too much about it.
