### ISSUE TITLE
iOS: Xcode Recompiles Everything Between Each “node Kha/make ios”

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#948]
This means that changing a single line in my game will require the entire Haxe and Kha libraries, as well as my entire game to be recompiled (all the cpp files) in Xcode. It’s a really slow workflow to troubleshoot bugs or just make any changes at all. Seems like “android-native” doesn’t suffer this issue.

**Comment by juakob** [comment]
Did you try using kha/make ios -noproject to avoid creating the project files again when you change something?

**Comment by Joncom** [comment]
Didn't know about that flag before.
However, yup, I've tried it now.
Sadly it doesn't improve the issue at all.

**Comment by Joncom** [comment]
Just speculating here... Maybe Xcode considers a file "modified" if replaced even if the code within the file has not changed, and that flags the file for recompilation?

**Comment by RobDangerous** [comment]
Maybe but it didn't used to be like that. Please try to just call Haxe and see whether that behaves the same:
`cd build`
`../Kha/Tools/haxe-osx project-osx.hxml`

**Comment by Joncom** [comment]
Before I start, Xcode has already compiled my project, so subsequent runs
are instant (no recompile).

Then I close the Xcode project.

Then from the “build” folder, I run “../Kha/Tools/haxe/haxe-osx
project-ios.hxml”. Runs ok, no errors.

Then I open the project again in Xcode and hit the play button. It runs
instantly (no recompile).

Did this just debunk my above speculative theory?

**Comment by RobDangerous** [comment]
It appears so. No idea why that behaves different to using the -noproject switch though.

**Comment by RobDangerous** [comment]
Ah, sorry. Single letter options are all one -, multi-letter options are --. There's also --help.
But let's keep this open and fix the original issue, too.

**Comment by RblSb** [comment]
Judging by the large diff, all the problems are due to the generation of new ids in files through the call of `getBuildId()` function https://github.com/Kode/koremake/blob/master/src/Exporters/XCodeExporter.ts#L316 and etc.

Original function: https://github.com/Kode/koremake/blob/master/src/Exporters/XCodeExporter.ts#L17

I think that reading old identifiers, if the project file already exists, can be a solution.

**Comment by Joncom** [comment]
> But let's keep this open and fix the original issue, too.

@RobDangerous, what is the original issue?

> Judging by the large diff...

@RblSb, what files are you observing a large diff on?

I don't know about you guys, but my problem of "Xcode recompiling everything between builds" went away after I learned I could use `--noproject`.

Or are you guys suggesting that `--noproject` shouldn't be necessary in the first place?

**Comment by RobDangerous** [comment]
Exactly that, --noproject shouldn't be necessary to reduce build times.

**Comment by RblSb** [comment]
Oh, it's about `Kha/make osx`, but I don't think it matters.
@Joncom its about recompilation without `--noproject`, large diff inside `project.pbxproj` with new file ids.

**Comment by RblSb** [comment]
Hm, i think `--noproject` doesn't work well, you need to regenerate project file if project source files added or removed?

Seems complicated it this case. Probably we have to separate static `pbxproj` stuff from dynamic, that can be changed after project regeneration (kha/kore/project source files), and do something like:
```ts
writeXCodeProj(project: Project, from: string, to: string, platform: string) {
	const xprojPath = path.resolve(to, project.getName() + '.xcodeproj', 'project.pbxproj');
	if (fs.existsSync(xprojPath)) {
		regenXCodeProj(project, from, to, platform);
		return;
	}
	<func code from> https://github.com/Kode/koremake/blob/master/src/Exporters/XCodeExporter.ts#L245
}
```
Inside `regenXCodeProj` compare files from (temp) `prev-build` Sources folder and from `build` Sources to see if we need to change the id or add/remove source file from project file. But I hope there's a better way to do that. Ideas?

**Comment by RobDangerous** [comment]
Of course --noproject doesn't work well. Just regenerating the project when new files are added is also not good enough because that would also trigger a full rebuild. I'll need to write down those ids, no way around it.

**Comment by RblSb** [comment]
There at least problem with compilation when you remove all project code and try to compile empty main function. Probably k__make doesn't removes old source files and you get errors of bad file references (with haxe's dce at least). Need to check that in other exporters and probably do map of files to remove.

**Comment by RobDangerous** [comment]
It's like that for every target. Ideally we'd just delete the cpp files dir but that messes up incremental compilation so we'd sadly have to do something complicated to make that perfect.
