### ISSUE TITLE
Keyboard API : keyCode

### ISSUE THREAD

**Issue by wighawag** [Kode/Kha#95]
Thought to add  an issue regarding a keyboard api that deal with keyCode only (instead of the char based one) as discussed here : http://forum.ktxsoftware.com/topic/13/about-kha-keyboard-api
Thanks

**Comment by ratalaika** [comment]
As a workarround the keyCode I recommend you to check this:
https://github.com/ratalaika/KhaSpiller/blob/master/Libs/spiller/SpiGame.hx

	/**
	 * Internal event handler for Kha keyboard events.
	 */
	public function onKeyUp(key:Key, char:String):Void
	{
		var keyCode:Int = getKeyCode(key, char);
		if(keyCode == -1)
			return;

		keyUpInternal(keyCode);
	}

With something like that I overcome that problem you can check my repo all the needed info is there :)

**Comment by wighawag** [comment]
I did something similar 
did not use 
```
if(keyCode == -1)
keyCode = char.toUpperCase().charCodeAt(0);
```
though, so thanks for that :)

The annoying thing about that is the unecessary overhead  (already Kha transform keyCode into char) we transformed it back again.
This is not critical but it would be better if we could get direct access via Kha

**Comment by RobDangerous** [comment]
Direct access is now available.
