### ISSUE TITLE
iOS: AppStore upload error: "Your binary is not optimized for iPhone 5"

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#960]
![screenshot](https://user-images.githubusercontent.com/1667179/51423532-4da2dd00-1bf4-11e9-9c34-e794c5e1b21c.png)

**Comment by Joncom** [comment]
This can be resolved with the following patch:

```diff
diff --git a/Kha/Kore/Backends/System/iOS/Sources/Kore/ios.plist b/Kha/Kore/Backends/System/iOS/Sources/Kore/ios.plist
index 4cb77811..73b87da8 100644
--- a/Kha/Kore/Backends/System/iOS/Sources/Kore/ios.plist
+++ b/Kha/Kore/Backends/System/iOS/Sources/Kore/ios.plist
@@ -45,5 +45,18 @@
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
        </array>
+       <key>UILaunchImages</key>
+       <array>
+               <dict>
+                       <key>UILaunchImageMinimumOSVersion</key>
+                       <string>7.0</string>
+                       <key>UILaunchImageName</key>
+                       <string>Default-568h</string>
+                       <key>UILaunchImageOrientation</key>
+                       <string>Portrait</string>
+                       <key>UILaunchImageSize</key>
+                       <string>{320, 568}</string>
+               </dict>
+       </array>
 </dict>
 </plist>
```

And adding two files to the root of the Xcode project:

- Default-568h.png
- Default-568h@2x.png

The first file should be 320x568. And the second file should be twice that resolution.

**Comment by Joncom** [comment]
However, I'm not sure how to integrate the adding of these two images into the `node Kha/make ios` process. @RobDangerous, any chance you could offer a hint or two about where to get started with that?

**Comment by RobDangerous** [comment]
Of course. That kinda stuff happens around https://github.com/Kode/koremake/blob/master/src/Exporters/XCodeExporter.ts#L188 and has to be expanded regularly because Apple keeps adding more icon and start image sizes. Think we also should add a separate khamake option for startup images, that's nowadays a thing at least on iOS, Windows Universal and consoles.

**Comment by Joncom** [comment]
Wondering if this is unnecessary now that we have "LaunchScreen.storyboard". Will investigate...

**Comment by Joncom** [comment]
Seems AppStore uploads work without this fix, in the presence of "LaunchScreen.storyboard". My guess is that storyboards are the "modern" way to define the launch visuals.
