### ISSUE TITLE
HTML5: Right-Click / Context Menu Disabled By Default

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#965]
Excerpt from Discord 2018-11-29:

> **Joncom:** I can understand why it's useful to disable the context menu, particularly if the right click is assigned to some in-program action, however, if not, it's nice to be able to right click on the canvas and do stuff, like save the current image
> ...
> **Joncom:** Seems Kha disabled it for me
> **Robert:** Didn't even know it's disabled.
> **Joncom:** It should be enabled by default
> **Robert:** Probably slipped in via some pull request.
> **Robert:** I agree.

**Comment by RblSb** [comment]
disableContextMenu in System.start or another way?

**Comment by RblSb** [comment]
Can fix it after @RobDangerous design decision.
I suggest `disableContextMenu` in `System.start` with public `System` field, or khafile option (fit better, but static).
I feel we should have some place for platform-specific options in runtime, if we can change them dynamically, for example browser hotkey blocking (full/current version without f-keys/none).
