### ISSUE TITLE
iOS: Poor Performance

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#974]
Not sure how to approach this issue just yet, but these numbers are a lot lower than I was expecting.

**OpenGL:**
![opengl-cropped](https://user-images.githubusercontent.com/1667179/51737476-43cf1d00-20bf-11e9-8f57-aa4e4ec76e5b.png)

**Metal:**
![metal-cropped](https://user-images.githubusercontent.com/1667179/51737479-46ca0d80-20bf-11e9-9f08-4b0016921e75.png)

**Comment by RobDangerous** [comment]
We can't do anything here without some actual code to test.

**Comment by sh-dave** [comment]
Are these 636 drawcalls on a mobile phone?

**Comment by Joncom** [comment]
@sh-dave, this is iOS, so yes, it's an iPhone. Specifically though, an iPhone 5S.

**Comment by RobDangerous** [comment]
Ah, an old phone. Looks okish then for 636 draw calls.

**Comment by Joncom** [comment]
> Looks okish then for 636 draw calls.

Except that it runs at a solid 60 FPS in iOS Chrome and Safari...

![chrome](https://user-images.githubusercontent.com/1667179/51739327-c954cc00-20c3-11e9-930c-0252829afbdb.png)

**Comment by Joncom** [comment]
Native is supposed to be faster than HTML5, right?

**Comment by RobDangerous** [comment]
Nope, HTML5 is faster than native in a lot of cases - not draw calls though so that doesn't seem to be the issue after all. Garbage collection is one thing that's much faster in HTML5, but that's likely an issue in your code. Please use a profiler and/or provide sample code.

**Comment by Joncom** [comment]
Thanks @sh-dave for pointing out in the IRC, I was using iOS "debug builds", so the performance is actually better when I test "release" builds.

OpenGL = 45 FPS
Metal = 55 FPS

So HTML5 is still performing better than native, but at least it's not as bad as I thought.

**Comment by RobDangerous** [comment]
So, nothing to do here from our side it seems.

**Comment by RblSb** [comment]
If you are using separate images for small sprites, you should merge them into an atlas, it can be very helpful for gpu. To quickly compare performance with it, I suggest generating it in runtime. There is my simple generator example:

<details><summary>Spoiler</summary>

```haxe
package;

import kha.Image;
import kha.graphics2.Graphics;
import kha.Assets;

typedef IRect = {
	x:Int, y:Int,
	w:Int, h:Int
}

class Atlas {

	static final maxSize = 1024 * 2;
	public static var atlas:Image;
	static var keys:Array<String>;
	static var map:Map<String, Int>;
	static var offsX:Array<Int>;
	static var offsY:Array<Int>;
	static var sizesW:Array<Int>;
	static var sizesH:Array<Int>;

	public static function init():Void {
		initImagesMap();
		keys.sort(function(a, b) {
			final img:Image = Reflect.field(Assets.images, a);
			final img2:Image = Reflect.field(Assets.images, b);
			final size = img.height;
			final size2 = img2.height;
			if (size > size2) return -1;
			else if (size < size2) return 1;
			return 0;
		});
		map = [
			for (i in 0...keys.length) keys[i] => i
		];

		offsX = [];
		offsY = [];
		sizesW = [];
		sizesH = [];
		atlas = Image.createRenderTarget(maxSize, maxSize);

		final g = atlas.g2;
		var x = 0;
		var y = 0;
		var blockW = 0;
		var blockY = 0;
		var lineY = y;
		var lineH = 0;
		g.begin(true, 0x0);
		for (i in 0...keys.length) {
			final img:Image = Reflect.field(Assets.images, keys[i]);
			g.drawImage(img, x, y);
			offsX.push(x);
			offsY.push(y);
			sizesW.push(img.width);
			sizesH.push(img.height);
			if (i == keys.length - 1) break;
			final next:Image = Reflect.field(Assets.images, keys[i + 1]);

			if (lineH < img.height) lineH = img.height;
			if (blockW < img.width) blockW = img.width;
			blockY += img.height;

			if (blockY + next.height < lineH) { // down
				y += next.height;
				blockY += next.height;
				if (blockW < next.width) blockW = next.width;
			} else { // left and up
				x += blockW;
				y = lineY;
				blockW = next.width;
				blockY = 0;
			}

			if (x + next.width >= maxSize) {
				lineY += lineH;
				x = 0;
				y = lineY;
				blockW = next.width;
				blockY = 0;
				lineH = 0;
			}
			x++;
			y++;
		}
		g.end();
	}

	static inline function initImagesMap() {
		keys = [];
		final fields = Reflect.fields(Assets.images);
		var i = 0;
		for (field in fields) {
			// skip image data files
			if (~/(Name|Description|names)$/.match(field)) continue;
			// skip any images you want
			if (~/(walls|spikes|mines|powerups)$/.match(field)) continue;
			keys.push(field);
			i++;
		}
	}

	public static function drawAtlas(g:Graphics, x:Float, y:Float):Void {
		g.drawImage(atlas, x, y);
	}

	public static function drawImage(g:Graphics, img:String, x:Float, y:Float):Void {
		final id = map[img];
		g.drawSubImage(atlas, x, y,
			offsX[id], offsY[id], sizesW[id], sizesH[id]
		);
	}

	public static function drawSubImage(
		g:Graphics, img:String, x:Float, y:Float,
		sx:Float, sy:Float, sw:Float, sh:Float
	):Void {
		final id = map[img];
		g.drawSubImage(
			atlas, x, y,
			offsX[id] + sx, offsY[id] + sy,
			sw, sh
		);
	}

	public static function drawScaledImage(
		g:Graphics, img:String, x:Float, y:Float, w:Float, h:Float
	):Void {
		final id = map[img];
		g.drawScaledSubImage(
			atlas,
			offsX[id], offsY[id], sizesW[id], sizesH[id],
			x, y, w, h
		);
	}

}
```
</details>

Call `Atlas.init()` after loading the assets and replace calls like `g.drawSubImage(img, ...)` to `Atlas.drawSubImage(g, 'img_name', ...)`.

**Comment by RobDangerous** [comment]
But... that helps with html5 much more than with native backends.

**Comment by RblSb** [comment]
It helps me to get 60 fps instead of 45 on android native for 6 years old phone. Don't know about fps on html5 for version with separate images.

**Comment by RobDangerous** [comment]
I didn't say it doesn't help on native mobile targets. And it will probably help with this project. But it very likely has a much bigger performance problem than draw calls - because draw calls are slowest in html5 yet it is his fastest target. Also debug/release mode does not effect draw calls. But unless we see some code or some profiling data all we can do is guessing games... and those are silly so let's stop that.

**Comment by Joncom** [comment]
[Kha Bunnymark](https://github.com/dmitryhryppa/frameworks_test/tree/master/bunnymark/kha) on my iPhone 5S suggests that 1000+ draws per frame at 60 FPS should be possible:

![photo](https://user-images.githubusercontent.com/1667179/52430577-0051c580-2b39-11e9-8734-b1f4e3f22c6c.jpg)

**Comment by RblSb** [comment]
Bunnymark draws same texture many times. Have you checked the profiler? If yes, and the problem is in draw calls, do you use texture atlas?

**Comment by RobDangerous** [comment]
Ya, bunnymark does one draw call per 1500 bunnies, you're phone is clearly a draw call monster.
As said earlier, please send profile data or code. Anything else makes zero sense.

**Comment by Joncom** [comment]
Yes, I will do some profiling. By the way, what do you mean 1 draw call per
1500 bunnies?

**Comment by juakob** [comment]
He means that you render all the bunnies using one GPU call . All the 1500 bunnies are render/draw at the same time in parallel.  If you are drawing stuff that uses the same shader, texture and setting you can draw them in parallel. This is call batching. Thats why @RblSb is asking you if you use a texture atlas
