### ISSUE TITLE
iOS and MacOS are both blurry compared to other targets

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#977]
From 11/30/2018 Discord chat:

> **Joncom:** Is Kha intended to execute/work the same on all platforms?
> **Joncom:** Just noticing an Image scaled to fit the framebuffer in HTML5 target looks crisp (like nearest neighbor), whereas the same looks blurry on MacOS target
> **NotBilly:** I don't believe this is anything kha or haxe can control, as far as I understood it. It's one API to unify the various targets/platforms
> **Not Billy:** I could totally be wrong though
> **Robert:** Sorry, you're wrong. Some things are undefined but that one is just a bug. Metal is still set to a bilinear filter on all textures I think.
> **NotBilly:** No need to be sorry :p
> **Joncom:** Robert, should I create an issue for it on Github?
> **Robert:** Yes, please.

**Comment by tyrondis** [comment]
@RobDangerous I would love to see this fixed. Any pointers for someone who might be willing to send a PR? :)

**Comment by RobDangerous** [comment]
Have a look at  for example https://github.com/Kode/Kinc/blob/master/Backends/Graphics5/Direct3D12/Sources/kinc/backend/graphics5/texture.cpp#L19 - D3D12 and Vulkan have to tackle the same problem. But don't worry about it too much, I want to look into the most urgent Metal issues myself in two weeks.

**Comment by RobDangerous** [comment]
Fixed.
