### ISSUE TITLE
The use of audioCallback and playSound/Music

### ISSUE THREAD

**Issue by gen111** [Kode/Kha#98]
Hi.

Am I right to assume that I can't use playSound/playMusic when directly accessing to the audio buffer using Audio.audioCallback like tech.ktxsoftware.com/wwx-new-part-3-the-slides/ and need to make my own original mixer function that handles them?

**Comment by RobDangerous** [comment]
That is correct. Am I right to assume this is just a question and not an actual issue or would you like me to add a method to the mixer to optionally forward mixed audio?

**Comment by gen111** [comment]
Ah sorry, it's not really an issue. Just wanted to  clarify it because I am too used to AS3's sampledataevent and thought there might be a way to work around this without starting to attempt to  make such methods myselfe :o  It would be great if you cloud add such a method though!

**Comment by RobDangerous** [comment]
Will do that then.

**Comment by gen111** [comment]
Great, thank you!

**Comment by RobDangerous** [comment]
When you set audioCallback you can now forward sample requests to audio2.Audio1.mix, then do your own thing on top.
