### ISSUE TITLE
iOS crashes if there is too many assets in the "Assets" folder

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#985]

**Comment by Joncom** [comment]
Will post example momentarily...

**Comment by Joncom** [comment]
Adding a bunch of images (1024 seems to be enough) to an empty project and then running on iOS will result in the app crashing.

![screen shot 2019-02-08 at 8 22 00 pm](https://user-images.githubusercontent.com/1667179/52481076-19fa1800-2be0-11e9-81ac-f9ba2b4002b7.png)

Clone here to replicate the issue on your end:
https://github.com/Joncom/Empty/commits/KHA_ISSUE_985

**Comment by sh-dave** [comment]
If you're loading them manually (ie. use `Assets.loadXXXFromPath()` instead of `Assets.loadEverything()` or `Assets.loadXXX()`), you can most likely prevent that by adding `notinlist` in your `khafile.js` (`project.addAssets("assets/**", { notinlist: true });`)

**Comment by Joncom** [comment]
@sh-dave, this crash occurs in the official "Empty" project which, I believe, loads everything via `Assets.loadEverything()`. Is that a problem?

**Comment by sh-dave** [comment]
Oh wait i misread, i thought the build failed (That happened to me some time ago on MSVC b/c of too many assets).

**Comment by sh-dave** [comment]
Dunno how much overhead each png incurs, but maybe it's just out of memory?

**Comment by Joncom** [comment]
@RobDangerous would know better about graphics, but I suspect it's not running out of memory because we can quickly do some math:

```
var image_count = 1024;
var image_width = 64; // Image width is actually smaller than this
var image_height = 64; // Image height is actually smaller than this
var bytes_per_pixel = 4; // Assuming 32-bit image, RGBA
var total_bytes = image_count * image_width * image_height * bytes_per_pixel;
var total_kilobytes = total_bytes / 1024;
var total_megabytes = total_kilobytes / 1024;
console.log("Uncompressed images should consume " + total_megabytes + " MB in memory.");
```

This prints:

> Uncompressed images should consume 16 MB in memory.

**Comment by sh-dave** [comment]
Set a breakpoint in `ImageList_obj.cpp / __alloc` and try to see how much it want's to allocate (if that's the source of the error, can't tell from screenshot for certain). Maybe it want's to allocate a giant block for the list that's kept in the Assets class.

**Comment by Joncom** [comment]
![screen shot 2019-02-08 at 10 42 16 pm](https://user-images.githubusercontent.com/1667179/52488709-03a98780-2bf3-11e9-923d-efafb4548b56.png)

That seems to be where the crash occurs. The original error is thrown before things progress beyond that  `__alloc` call.

**Comment by RobDangerous** [comment]
That's an out of memory. There can be overhead for textures and whatnot. Anyways, works as intended, don't load so much stuff all at once.

**Comment by RobDangerous** [comment]
Oh and there's a mechanism to work without the Assets list. Dave can tell you all about it I think. You should use that, a static list of names isn't really useful with large amounts of assets like that anyway.

**Comment by Joncom** [comment]
@RobDangerous, you said "that's an out of memory error". Assuming that's why you closed this issue, I'm re-opening it because I really don't think it's running out of memory. If I delete 24 of the images (so there's 1000 now, instead of 1024), the app runs fine, and it appears to be using hardly any memory at all (25 MB, not every remotely close to the 500+ MB needed to exhaust the memory on my iPhone 5S).

![screen shot 2019-02-09 at 7 22 58 pm](https://user-images.githubusercontent.com/1667179/52520822-a9670000-2ca0-11e9-8221-72ad594fe656.png)

**Comment by Joncom** [comment]
Wait a minute, there's no button for me to re-open this issue? :-\

**Comment by RobDangerous** [comment]
Of course not. Out of memory not only happens when you're actually out of memory, it also happens when you allocate too much at once. Dave posted the answer to your problem in his very first response. Nothing left to do here.
