### ISSUE TITLE
kha.Color.White should be 0xFFFFFFFF but instead compiles to -1

### ISSUE THREAD

**Issue by Joncom** [Kode/Kha#990]

**Comment by Joncom** [comment]
Steps to reproduce:

- Clone Empty project
- `trace(kha.Color.White);`
- `node Kha/make html5`
- Observe `-1` printed to console

For convenience, you could just clone this one:
https://github.com/Joncom/Empty/commits/KHA_ISSUE_990

Expected `4294967295` to be printed to console instead, because that's what the value is [defined](https://github.com/Kode/Kha/blob/a30360aeda5b2697b234a24c961fed264190e7d7/Sources/kha/Color.hx#L9) as in Kha.

**Comment by RobDangerous** [comment]
Apparently Haxe is completely broken 
https://try.haxe.org/#0CE97 😱
(please read up on how signed 32 bit integers work)

**Comment by Joncom** [comment]
But as a result, doesn't this make Kha kind of broken too? For example, I do `kha.Color.at` on a white pixel, and it returns the value -1. Therefore the value is not reliable. `color.Rb != 255` even though it should be. Is this not a legitimate issue?

**Comment by RobDangerous** [comment]
No, it isn't. Just give
```
var color = kha.Color.White;
trace(color.Rb);
```
a try. And as I said read up on how integers work.
