### ISSUE TITLE
Warning: Sampler tex not found.

### ISSUE THREAD

**Issue by RblSb** [Kode/Kha#995]
`kha/graphics4/PipelineState.hx:111: Warning: Sampler tex not found.`
![](https://i.imgur.com/XGDqMZc.png)
textures array is empty on call moment, see https://github.com/Kode/Kha/commit/4891d9eb59e858f586e058bf84fa74f65c7e1ffc
Build Empty for html5 to reproduce.

**Comment by RobDangerous** [comment]
It's nothing to worry about but I'll have to silence the warning somehow (it's a very useful warning in other situations though).
